### ISSUE TITLE
Submit form and wait before getting the response

### ISSUE THREAD

**Issue by woodsbox** [chrome-php/headless-chromium-php#10]
Hello,

With the help of gsouf I now have the following script:

`$content = $page
    ->evaluate(
        '(() => {
            document.querySelector('#username').value = 'username';
            document.querySelector('#password').value = 'password';
            document.querySelector('#loginform').submit();
        })()'
    )
    ->getReturnValue();`

Only when doing this the return value is empty.

**Comment by gsouf** [comment]
@woodsbox That's normal, ```getReturnValue``` will wait for the script to execute and return the value returned by the script. When the script returned the new page is not loaded yet, you will have to add a new instruction for that. 

As I said that's not implemented in the library yet, so I need to give further test instead of giving you a wrong answer. If you have a little patience I will check for this tomorrow in the morning (UTC+2)

**Comment by woodsbox** [comment]
@gsouf I'm sorry I thought you ment open a new ticket, of course I have time to wait!! thanks already so much for your help!

**Comment by gsouf** [comment]
Hi @woodsbox 

I added a method (``waitForPageReload``) to the page evaluation that lets you wait for the page to reload when javascript has been evaluated in the page. See the example here: https://github.com/chrome-php/headless-chromium-php/blob/master/examples/form-submit.php

**Comment by gsouf** [comment]
@woodsbox nont that you will have to update to version 0.1.3

**Comment by woodsbox** [comment]
@gsouf  maybe stupid question but how to update?

**Comment by gsouf** [comment]
@woodsbox you should use [composer update](https://getcomposer.org/doc/03-cli.md#update)

**Comment by woodsbox** [comment]
@gsouf Perfect!!!

Only wanted to let you know this works:
document.querySelector("#myinput").value = "hello";

This doesn't:
document.querySelector('#myinput').value = "hello";

The ' couses a 500 internal error.

**Comment by gsouf** [comment]
@woodsbox that's great. Yes the reason is probably that quotes are conflicting with php string quotes.
