### ISSUE TITLE
How get complate html?

### ISSUE THREAD

**Issue by KrosCW** [chrome-php/headless-chromium-php#100]
How to get a ready page html, for example, facebook? getting weird shit.

**Comment by pashkasan** [comment]
require __DIR__ . '/../vendor/autoload.php';

use HeadlessChromium\BrowserFactory;
use HeadlessChromium\Cookies\Cookie;

// open browser
$factory = new BrowserFactory();
$browser = $factory->createBrowser();

// navigate to a page with a form
$page = $browser->createPage();

    $page->setCookies([
        Cookie::create('locale', 'en_US', [
            'domain' => '.facebook.com',
            'expires' => time() + 23600 
        ])
    ])->await();


$page->navigate('https://www.facebook.com')->waitForNavigation();
$cookies = $page->getCookies();
$page_html = $page->evaluate('document.documentElement.innerHTML')->getReturnValue();


file_put_contents('1.html', $page_html);
file_put_contents('1.cookies', print_r($cookies, true));
