### ISSUE TITLE
headerTemplate and footerTemplate

### ISSUE THREAD

**Issue by daemon-byte** [chrome-php/headless-chromium-php#101]
Hi,

Is it possible to set these using the master version of this code? I tried this but it didn't seem to work. 

```
        $options = [
            'headerTemplate' => 'holy headers batman',
            'footerTemplate' => 'footer bam',
            'displayHeaderFooter' => true,
        ];
        $pdf = $page->pdf($options);
```

**Comment by Vimalsumanthran** [comment]
got any solution??

**Comment by Vimalsumanthran** [comment]
Which One?

**Comment by Vimalsumanthran** [comment]
I have tried Spiritix/php-chrome-html2pdf,similar issue is happening.. :-(

**Comment by jonrmitchell** [comment]
I had a similar issue, in the end I had to do 2 things:

1. Give the page margins (I had set them to 0)
2. Give the header/footer template a font-size: `'footerTemplate' => '<div style="font-size:10px">footer bam</div>',`

I'm sure you've moved on, but hopefully this helps someone else, so they don't have to try to pivot to a whole different system based on puppeteer like I did, only to realize that the same issue exists (you need margins and styles there too!)

**Comment by GrahamCampbell** [comment]
Yes, that is supported by this package. @jonrmitchell has answered this. :)
