### ISSUE TITLE
mkdir: cannot create directory '/.local': Permission denied

### ISSUE THREAD

**Issue by sterichards** [chrome-php/headless-chromium-php#106]
I am running Chrome on Ubuntu via Docker. I get the following error message:

`Chrome process stopped before startup completed. Additional info: mkdir: cannot create directory '/.local': Permission denied\ntouch: cannot touch '/.local/share/applications/mimeapps.list': No such file or directory\nFailed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted\nFailed to generate minidump.Illegal instruction`

My code:

`
$browserFactory = new BrowserFactory('google-chrome-stable');

$browser = $browserFactory->createBrowser([
    'headless'        => true,
    'debugLogger'     => 'php://stdout',
    'userDataDir' => '/var/www/html'
]);

$page = $browser->createPage();

$page->navigate('https://something.com')->waitForNavigation();

$page->screenshot()->saveToFile('/var/www/html/web/image1.png');

$browser->close();
`

I have tried setting the userDataDir to /tmp, /var/www/html and any other directory that is writable. But the error suggests that /.local is attempting to be written to, hence the permission denied.

I have checked all the potential arguments for createBrowser() but none seem to help me. I don't know why /.local is the selected write directory nor can I see how to configure it

**Comment by lhpalacio** [comment]
@sterichards Did you try noSandbox option? I think should fix it.

**Comment by alecszaharia** [comment]
Make sure you have enough space on disk. It was gone after I freed some space.
