### ISSUE TITLE
How to get info from Iframe?

### ISSUE THREAD

**Issue by Glebsky** [chrome-php/headless-chromium-php#117]
Can not get any info from iframe.
In puppeteer it some kind like those.
`const frame = await page.frames().find(f => f.name() === 'tito-iframe');`

i tried `document.querySelector('iframe').contentWindow.document.childNodes["0"]`

but it says Blocked a frame with origin from accessing a cross-origin frame.

How to solve this?

**Comment by momala454** [comment]
what happens if you try to use the chrome api to get the iframe ?

https://vanilla.aslushnikov.com/?DOM.querySelector

**Comment by sunnyday80** [comment]
is the iframe source in same domain as main document?
if so - its code working for me

$page->evaluate('document.querySelector("iframe#bba-classic-cont").contentDocument.body.querySelector("iframe#bba-data.bba-frame").contentDocument.body.querySelector("#sValue").value = "06363008"');
