### ISSUE TITLE
Home directories outside of /home are not currently supported.

### ISSUE THREAD

**Issue by TigranGevorgyan** [chrome-php/headless-chromium-php#118]
Hi everybody.
I have installed chromium on my ubuntu device via this command "sudo apt install chromium-browser".
Everything is ok, when I using package on my localhost, but when I setup project on ubuntu server, and when called this code:
      $browserFactory = new BrowserFactory('chromium-browser');
      $browserFactory->createBrowser();   //<------
I receive this error message "Chrome process stopped before startup completed. Additional info: Sorry, home directories outside of /home are not currently supported. ↵See https://forum.snapcraft.io/t/11209 for details.".
Can somebody help me?

**Comment by gsouf** [comment]
Hi @TigranGevorgyan this appears to be related to your server provider. It seems silly that they don't support writing to tmp directory.

To workaround you could provide your own temp directory with the option `userDataDir`. Just put it in your home directory and you should be ok. Just remember that this folder should be unique and might (will) be deleted when you close the browser.
