### ISSUE TITLE
Persistent browser not working

### ISSUE THREAD

**Issue by alex-rsk** [chrome-php/headless-chromium-php#119]
Hello.
I tried to make browser persistent, as in example /src/persistent-browser.php, but it doesn' works.
Every time I start the script, browser is initializing from scratch, connect to socket always failed.

````
$socketFile = '/tmp/debug/chrome-php-demo-socket1';
$browser = null;
if (file_exists($socketFile)) {
    $socket =  file_get_contents($socketFile);
    try {
        $browser = \HeadlessChromium\BrowserFactory::connectToBrowser($socket, [
            'debugLogger' => 'php://stdout'
        ]);
    } catch (\HeadlessChromium\Exception\BrowserConnectionFailed $e) {
        echo 'browser was closed<BR>';
    }
}
if (!$browser) {
    $factory = new \HeadlessChromium\BrowserFactory('/usr/bin/google-chrome');
    $browser = $factory->createBrowser([
        'headless' => false,
        'userDataDir' => '/tmp/debug/users/test',
        'debugLogger'  => 'php://stdout',
        'keepAlive' => true
    ]);
    file_put_contents($socketFile, $browser->getSocketUri());
}

$page = $browser->createPage();
$page->navigate('http://example.com')->waitForNavigation();
````

The socket file is present:
````
stat /tmp/debug/chrome-php-demo-socket1

  Файл: /tmp/debug/chrome-php-demo-socket1
  Размер: 74            Блоков: 8          Блок В/В: 4096   обычный файл
Устройство: fd00h/64768d        Inode: 9703982     Ссылки: 1
Доступ: (0664/-rw-rw-r--)  Uid: ( 1000/ alexrsk)   Gid: ( 1000/ alexrsk)
Доступ: 2019-11-19 13:24:10.623808675 +0300
Модифицирован: 2019-11-19 13:24:10.087813580 +0300
Изменён: 2019-11-19 13:24:10.087813580 +0300
 Создан: -
````
... And, anyway, while connecting, it's fails:
````
[2019-11-19 13:24:09] DEBUG Browser Factory: connecting using ws://127.0.0.1:41051/devtools/browser/aeb4d701-0677-44c0-a005-18933018ce04
[2019-11-19 13:24:09] DEBUG socket(1): connecting
[2019-11-19 13:24:09] DEBUG socket(1): ✗ could not connect
browser was closed<BR>[2019-11-19 13:24:09] DEBUG Factory: chrome version: Google Chrome 78.0.3904.97
[2019-11-19 13:24:09] DEBUG process: initializing
````

The exceptions occurs /vendor/wrench/wrench/lib/Wrench/Client.php
And it says : 
````
Could not connect to socket: Connection refused (111)
````
Any ideas, please?

**Comment by YogSotot** [comment]
After delving into, It seems, it's just doesn't finding the websocket port.
Because after executing that script, the browser instance exiting.
So, how to prevent exiting from browser instance in that example?

**Comment by YogSotot** [comment]
Well, I figured it out.
The library appoints random port number, and it doesn't work.
When you define port manually, it works!
E.g.
` $browser = $factory->createBrowser([
        'headless' => false,
        'noSandbox' => true,
        'headless' => true,
        /*'userDataDir' => '/tmp/debug/users/test',
        'debugLogger'  => 'php://stdout',*/
        'keepAlive' => true,
        'customOptions' => 
            [
                '--remote-debugging-port' => 9223
            ]
        ]);
`

**Comment by rseyferth** [comment]
Not quite working for me, I think it should be:
```php
'customFlags' => [ '--remote-debugging-port=9223' ]
```

**Comment by crislin2046** [comment]
@YogSotot you might want to check out this project: [control Headless Chrome from Node.JS and use it like a regular browser](https://github.com/dosycorp/BrowserView)

**Comment by gsouf** [comment]
Hello, I think this has been fixed with https://github.com/chrome-php/headless-chromium-php/issues/135
Apologize for delays.
Please feel free to re-open if this occurs again

**Comment by gregsparrow** [comment]
I also have an issue with a persistent browser, but for me, it's a little bit different. Initially, the browser starts successfully, and then the PDF is generated successfully. However, the next time I try to connect to the existing browser, it connects but does not progress beyond this point in the code: `chrome-php/chrome/src/Browser.php:84`

```
Browser Factory: connecting using ws://127.0.0.1:39777/devtools/browser/4497c4c8-529c-4f27-aeca-2405b55ce148
socket(1): connecting
socket(1): ✓ connected
socket(1): → sending data:{"id":1,"method":"Target.setDiscoverTargets","params":{"discover":true}}
socket(1): ← receiving data:{"id":1,"result":{}}
```
