### ISSUE TITLE
Not working when adding flag --v

### ISSUE THREAD

**Issue by momala454** [chrome-php/headless-chromium-php#121]
When adding on the customFlags parameters the option  "--v", the script doesn't seems to work properly and timeout

**Comment by gsouf** [comment]
Hi @momala454  can you explain what `--v` is made for? Can you provide code sample of how you are using it please?

**Comment by momala454** [comment]
i was having random problems with and wanted to debug it, so i added the --v parameter to chrome

just add --v to the customflags and any script will be broken

**Comment by gsouf** [comment]
so you want to enable chrome logging? Can you describe the use case that requires this flag to be passed?

**Comment by momala454** [comment]
i had random (and rare) timeout of chrome, even if i wait 1 minute, chrome is not responding to my request
i didn't get rid of the issues, i just catch the timeout and restart from the beginning the process

**Comment by momala454** [comment]
this kind of errors
HeadlessChromium\Exception\OperationTimedOut: Operation timed out (45sec)
 at HeadlessChromium.Utils.tryWithTimeout(Utils.php:65)
 at HeadlessChromium.Communication.ResponseReader.waitForResponse(ResponseReader.php:103)
 at HeadlessChromium.PageUtils.PageEvaluation.waitForResponse(PageEvaluation.php:69)
 at HeadlessChromium.PageUtils.PageEvaluation.getReturnValue(PageEvaluation.php:101)

**Comment by gsouf** [comment]
@momala454 do you think you would be able to provide a minimal reproducible test case?

**Comment by momala454** [comment]
Sorry it looks like it's not crashing anymore, maybe it was a bug with chrome (now fixed)

**Comment by gsouf** [comment]
I'm glad to hear it, feel free to re-open if it occurs again
