### ISSUE TITLE
Response from chrome remote interface did not provide a valid message id

### ISSUE THREAD

**Issue by byhaskell** [chrome-php/headless-chromium-php#122]
```15:35:51 ERROR     [console] Error thrown while running command "cron '/var/www/mister-register.com/public'". Message: "Response from chrome remote interface did not provide a valid message id" ["exception" => HeadlessChromium\Exception\CommunicationException\InvalidResponse^ { …},"command" => "cron '/var/www/mister-register.com/public'","message" => "Response from chrome remote interface did not provide a valid message id"]

In Connection.php line 354:

  Response from chrome remote interface did not provide a valid message id
```

When performing the third time ```$page->evaluate``` such an error is caused. At the same time, there is always an element on the page. What is the problem?

**Comment by gsouf** [comment]
Hi @byhaskell 

apologize for the delays. Can you please provide a minimal reproducible case?

**Comment by byhaskell** [comment]
@gsouf Hello. Unfortunately, too much time has passed to recall and display everything again.

**Comment by gsouf** [comment]
@byhaskell thanks for your answer, I'm closing this one then. Feel free to re-open if required
