### ISSUE TITLE
Chrome process stopped before startup completed.

### ISSUE THREAD

**Issue by monoulou** [chrome-php/headless-chromium-php#125]
Please, i have a problem to use this bundle on my server prod (Linux Debian). First, I installed google-chrome-stable on my system.

Even if on my Windows local version, everythings works fine, please show below my code:

On windows:
'''$browserFactory = new BrowserFactory(C:\Progra~2\Google\Chrome\Application\chrome.exe);
  $browser = $browserFactory->createBrowser([
                'headless'        => false,         // disable headless mode
                'customFlags' => ['--print-to-pdf='.$destination],
                'connectionDelay' => 0.8,  // add 0.8 second of delay between each instruction sent to chrome,
                'debugLogger'     => 'php://stdout', // will enable verbose mode
                'windowSize' => [800, 600],
                'keepAlive' => false,
            ]);'''
====> OK

On linux:
'''$browserFactory = new BrowserFactory(google-chrome);
  $browser = $browserFactory->createBrowser([
                'headless'        => false,         // disable headless mode
                'customFlags' => ['--print-to-pdf='.$destination],
                'connectionDelay' => 0.8,  // add 0.8 second of delay between each instruction sent to chrome,
                'debugLogger'     => 'php://stdout', // will enable verbose mode
                'windowSize' => [800, 600],
                'keepAlive' => false,
            ]);'''
====> KO, This code cannot create browser and get : Chrome process stopped before startup completed.

Stack trace:

'''RuntimeException:
Chrome process stopped before startup completed.

  at vendor/chrome-php/chrome/src/Browser/BrowserProcess.php:386
  at HeadlessChromium\Browser\BrowserProcess->HeadlessChromium\Browser\{closure}(object(Process))
     (vendor/chrome-php/chrome/src/Utils.php:51)
  at HeadlessChromium\Utils::tryWithTimeout(30000000, object(Generator))
     (vendor/chrome-php/chrome/src/Browser/BrowserProcess.php:421)
  at HeadlessChromium\Browser\BrowserProcess->waitForStartup(object(Process), 30000000)
     (vendor/chrome-php/chrome/src/Browser/BrowserProcess.php:128)
  at HeadlessChromium\Browser\BrowserProcess->start('google-chrome', array('headless' => false, 'customFlags' => array('--print-to-pdf=/home/yaggo/Downloads'), 'connectionDelay' => 0.80000000000000004, 'debugLogger' => 'php://stdout', 'windowSize' => array(800, 600), 'keepAlive' => false, 'userDataDir' => '/tmp/chromium-php-udxx6u'))
     (vendor/chrome-php/chrome/src/BrowserFactory.php:78)
  at HeadlessChromium\BrowserFactory->createBrowser(array('headless' => false, 'customFlags' => array('--print-to-pdf=/home/yaggo/Downloads'), 'connectionDelay' => 0.80000000000000004, 'debugLogger' => 'php://stdout', 'windowSize' => array(800, 600), 'keepAlive' => false))
     (src/AppBundle/Controller/ResumeController.php:499)
  at AppBundle\Controller\ResumeController->headlessIntuitionAction('https://************.fr/document/view/12391694/19140623/doc.doc')
     (src/AppBundle/Controller/ResumeController.php:335)
  at AppBundle\Controller\ResumeController->getResumeContentFromUrl('http://********.fr/document/view/12391694/19140623/doc.doc', 912754, 'convert')
     (src/AppBundle/Controller/ResumeController.php:163)
  at AppBundle\Controller\ResumeController->visualisationAction(object(Resume))
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:151)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:68)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:200)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (web/app_dev.php:28)'''

Please, Please, i am facing this problem since 24h... Any idea or solution?? Thank you!!

**Comment by crislin2046** [comment]
@monoulou you might want to check out this project: [control Headless Chrome from Node.JS and use it like a regular browser](https://github.com/dosycorp/BrowserView)

**Comment by gsouf** [comment]
I think it's because you have disabled headless mode. Please pass option `headless` to `true:

```
$browser = $browserFactory->createBrowser([
    'headless' => true,
```

**Comment by monoulou** [comment]
Thank you for your reply but I also tried by setting headless to true. It
doesn't work like on my dev project on windows. Maybe I have to set
something like http-proxy on my production server to able to open a browser
with php?

Le lun. 23 déc. 2019 à 21:01, Soufiane Ghzal <notifications@github.com> a
écrit :

**Comment by gsouf** [comment]
FYI you will never be able to use `"headless" => false` on a server, so just get rid of that first. Then try to pass option `noSandbox` to true. Finally if it's not working install chrome as per this thread and try launching it manually in headless mode: https://gist.github.com/ipepe/94389528e2263486e53645fa0e65578b

**Comment by monoulou** [comment]
Hello!
When I set headless and noSandBox to true...nothing is happening, I can just see a new browser openning but navigate function not working?? Any idea, please ??

``try {
            $browserFactory = new BrowserFactory($chromeBinary);
            //start headless chrome
            $browser = $browserFactory->createBrowser([
                'connectionDelay' => 0.8,           // add 0.8 second of delay between each instruction sent to chrome,
                'debugLogger'     => 'php://stdout', // will enable verbose mode
                'windowSize' => [800, 600],
                'keepAlive' => false,
                'noSandbox' => true
            ]);
            $script =
                '   //Remplir le formulaire de connexion et click sur le boutton;
                    document.querySelector("input[name=login]").value = "********";
                    document.querySelector("input[name=password]").value = "**********";

                    click_event = new CustomEvent("click");
                    btn = document.querySelector(".greenbutton");
                    btn.dispatchEvent(click_event);
                ';
            $page = $browser->createPage();
            $page->addPreScript($script, ['onLoad' => true]);
            $page->navigate($url)->waitForNavigation();// Here, if i try to evaluate to get page content, it doesn't work...
}
``
Thank you!!!

**Comment by gsouf** [comment]
@monoulou have you made any progress on that one?

**Comment by gsouf** [comment]
Closing, feel free to re-open
