### ISSUE TITLE
 Does not run on windows.

### ISSUE THREAD

**Issue by rvazheninr** [chrome-php/headless-chromium-php#126]
Trying to run headless chromium.  I use Windows 7, Open Server. 
include_once('/./vendor/autoload.php');
use HeadlessChromium\BrowserFactory;
 $browserFactory = new BrowserFactory();

Gives an error message: 
Fatal error: in D:\OpenServer\domains\september\vendor\chrome-php\chrome\src\Browser\BrowserProcess.php on line 386

If i use;
$browser = $browserFactory->createBrowser([ 'debugLogger' => 'php://stdout', 'sendSyncDefaultTimeout' => 60000, ]);

In this case, the message;
Fatal error: in D:\OpenServer\domains\september\vendor\chrome-php\chrome\src\BrowserFactory.php on line 102
Please tell me what I'm doing wrong?

**Comment by menriquez** [comment]
i am running it fine on win10...it looks like your `include_once('/./vendor/autoload.php');` is malformed...

**Comment by rvazheninr** [comment]
Installed on Windows 10. The result is almost the same as on Windows 7.

Fatal error: Uncaught RuntimeException: Chrome process stopped before startup completed. Additional info: 'chrome' is not recognized as an internal or external command, operable program or batch file. in D:\OpenServer535\OSPanel\vendor\chrome-php\chrome\src\Browser\BrowserProcess.php:386 Stack trace: #0 D:\OpenServer535\OSPanel\vendor\chrome-php\chrome\src\Utils.php(51): HeadlessChromium\Browser\BrowserProcess->HeadlessChromium\Browser\{closure}(Object(Symfony\Component\Process\Process)) #1 D:\OpenServer535\OSPanel\vendor\chrome-php\chrome\src\Browser\BrowserProcess.php(421): HeadlessChromium\Utils::tryWithTimeout(30000000, Object(Generator)) #2 D:\OpenServer535\OSPanel\vendor\chrome-php\chrome\src\Browser\BrowserProcess.php(128): HeadlessChromium\Browser\BrowserProcess->waitForStartup(Object(Symfony\Component\Process\Process), 30000000) #3 D:\OpenServer535\OSPanel\vendor\chrome-php\chrome\src\BrowserFactory.php(78): HeadlessChromium\Browser\BrowserProcess->start('chrome', Array) #4 D:\OpenServer535\OSPanel\domains\septe in D:\OpenServer535\OSPanel\vendor\chrome-php\chrome\src\Browser\BrowserProcess.php on line 386

I do not know what to do.

**Comment by menriquez** [comment]
ill ask once again...did you check the line `include_once('/./vendor/autoload.php'); ` ?? that is malformed syntax and WILL NOT INCLUDE the `vendor/autoload.php` classes that your software will need to run successfully.

i will not spoonfeed you the correct syntax as it is trivial to look it up and fix it yourself, and it will be a good learning experience for you.

**Comment by TKompernass** [comment]
I had the same issue and I fixed it with giving the absolute path from the chrome installation to the browser factory.
`$browserFactory = new BrowserFactory('C:\Program Files (x86)\Google\Chrome\Application\chrome.exe');`

**Comment by gsouf** [comment]
It will use the env variable `CHROME_PATH` by default, if not specified then it fallbacks to 'chrome'. I suspect some windows install not to have the `CHROME_PATH` set.

In that case response from @TKompernass is the right way to go.

As for composer @menriquez is right

**Comment by rcoenen** [comment]
Still it does not work...

Fatal error: Uncaught Symfony\Component\Process\Exception\ProcessTimedOutException: The process ""C:/Program Files/chrome-win/chrome.exe" --version" exceeded the timeout of 60 seconds. in C:\wamp64\www\myproject\vendor\symfony\process\Process.php on line 1213
