### ISSUE TITLE
how to use --no-sandbox parameter?

### ISSUE THREAD

**Issue by fuxifex** [chrome-php/headless-chromium-php#127]
here's my code:

```
$path = "/usr/lib64/chromium-browser/headless_shell"; // was installed by my server admin
$browserFactory = new BrowserFactory($path);

```
i'm getting the following error:

`No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox. `

the problem: when changing the path variable into:
$path = "/usr/lib64/chromium-browser/headless_shell --no-sandbox";

i'm getting this error:
No such file or directory in [ .. path ..]

any ideas how to solve this?
thanks

**Comment by haris1024** [comment]
$browser = $factory->createBrowser(['headless' => true, 'noSandbox' => true]);
