### ISSUE TITLE
mouse->click() not clicking...

### ISSUE THREAD

**Issue by menriquez** [chrome-php/headless-chromium-php#128]
ok...so I am trying to build a website crawler that finds every link on a website not by scanning <a> tags and loading href's (which missing all JS-based hrefs and links), but _by actually clicking every link on the page, recursively._

when i found this project and did some quick testing, i thought i finally found the right library...but, alas, after spending 4 hours today carefully checking and testing my work, i've concluded that `mouse->click()` just don't work.  here is my code

```
   // load jquery
	$page->addScriptTag([
		                    'url' => 'https://code.jquery.com/jquery-3.3.1.min.js'
	                    ])->waitForResponse();
	
	// get the raw number of links on the page and store there link info
	$links['href'] = $page->evaluate("$('a').map( function() {
		return $(this).attr('href');
	}).get();")->getReturnValue();

	// how many?
	$links['count'] = count($links['href']);

	// get the link text so we can keep track...
	$links['text'] = $page->evaluate("$('a').map( function() {
		return $(this).text();
		}).get();")->getReturnValue();

	$links['pos'] = $page->evaluate("$('a').map( function() { 
	    return $(this).position();
	}).get();")->getReturnValue();

	$x = intval($links['pos'][0]['left']+5);
	$y = intval($links['pos'][0]['top']+5);

	// this should click the link and load a new page...
	$page->mouse()
		->move($x,$y)                             
		->click();

	// times out everytime
	$page->waitForReload();

```

i've tested and retested everypart of my code...i found a snippet that shows the xy coords on the page im parsing and the return xy values of my jquery calls are spot on...my `$x` and `$y` are right on the link...the `click()` is where the problem lies...its not doing anything it feels like!

does anyone have any sample code with a working `click()` so i can see what im doing wrong?

**Comment by haris1024** [comment]
use offset() instead of  position()

**Comment by menriquez** [comment]
thxs for the reply...so yeah I tried that too (remember I said I 100% verified for hours that the x,y coords were right on the button?).  I am sure that my `click()` hit x,y coords that were solidly over the link text.

in this case, clicking on the link text would create a popup window (the link text linked to a js `window.open()` call that just popped up a simple window with some basic text in it...

I sure would love if I could figure this out as I have all the code ready to go and such and if I could just get the `click()` to work I would be very happy.   I am in the process of creating a example webpage to test and make sure its not any bugs in my code and will post the results here...

**Comment by gsouf** [comment]
Hi @menriquez 

In the unit tests there is an example with `getBoundingClientRect` 

https://github.com/chrome-php/headless-chromium-php/blob/master/test/suites/MouseApiTest.php#L53

You said you would like to have the click ready to work. Can you please give some example of what you would expect?

**Comment by gsouf** [comment]
I'm closing it, please feel free to re-open if you wish to provide more details
