### ISSUE TITLE
JS does not run

### ISSUE THREAD

**Issue by BeekeeperVS** [chrome-php/headless-chromium-php#129]
$browserFactory = new BrowserFactory('C:\Program Files (x86)\Google\Chrome\Application\chrome.exe');

        $browser = $browserFactory->createBrowser([
            'headless' => true,
        ]);

        $page = $browser->createPage();

        $page->navigate($url)->waitForNavigation();

        $page_html = $page->evaluate('document.documentElement.innerHTML')->getReturnValue();

        file_put_contents('1.html', $page_html);
### 
does not run js. Body empty. What's the mistake?

**Comment by gsouf** [comment]
Hello @BeekeeperVS can you provide an url that fails with your script?

**Comment by gsouf** [comment]
I'm closing it, feel free to re-open if you come back to this thread
