### ISSUE TITLE
Background colors only rendered in PDF on certain pages / sites

### ISSUE THREAD

**Issue by gillarf** [chrome-php/headless-chromium-php#130]
Background color rendering in PDFs only seems to work on certain webpages.

For the following code, if I change $url to https://www.hovec.co.uk/ then it does not render any background colors or images, and yet it works for the BBC site.

```
$browserFactory = new BrowserFactory("/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome"); //thats my local Chrome

    $browser = $browserFactory->createBrowser([
      'windowSize' => [794, 1122]
    ]);

    $url='https://www.bbc.co.uk/';
    //$url='https://www.hovec.co.uk/';

    // creates a new page and navigate to $url
    $page = $browser->createPage();
    $page->navigate($url)->waitForNavigation();
    $page->pdf(['printBackground'=>true, 'marginTop' => 0.0, 'marginBottom' => 0.0, 'marginLeft' => 0.0, 'marginRight' => 0.0])->saveToFile($filepath);
    $browser->close();
```

Any help with this would be much appreciated!

**Comment by gsouf** [comment]
@gillarf I'm not sure we can do much about it, this is the expected behavior of chrome unfortunately. It won't save background color when printing (that is equivalent to doing pdf).
Even when using chrome as an human it's always a challenge to keep backgorund colors.

**Comment by Courtney818** [comment]
style="-webkit-print-color-adjust:exact;"
