### ISSUE TITLE
How to crawl a web_page, which is login protected ?

### ISSUE THREAD

**Issue by NishantSoni** [chrome-php/headless-chromium-php#134]
I need to crawl a web page which is a login protected. 

I have username & password, but form on login_page is submitted via javascript, and it saves some cookies to the browser & then redirected to home_page(which need to be crawled) after successful login.
How to submit login form ?
How to save cookies ?
How to call home_page with these cookies ?

Please suggest some solution to achieve this via this package.

**Comment by gsouf** [comment]
Hi @NishantSoni you can use javascript to perform those operations.

You can find a example here: https://github.com/chrome-php/headless-chromium-php/blob/master/examples/form-submit.php
