### ISSUE TITLE
keepAlive not working

### ISSUE THREAD

**Issue by Munger** [chrome-php/headless-chromium-php#135]
I'm using the code from persistent-browser.php in a singleton class in Laravel as follows:

class MyClass
{
    private static $browser;

    public function Init() {

        $socketFile = '/tmp/chrome-php-demo-socket';

        if ( file_exists( $socketFile ) ) {
            $socket =  file_get_contents($socketFile);
        
            try {
                self::$browser = BrowserFactory::connectToBrowser( $socket, [
                    'debugLogger' => 'php://stdout'
                ]);
            } catch (BrowserConnectionFailed $e) {
                // The browser was probably closed
                // Keep $browser null and start it again below
                self::$browser = null;
            }
        }

        if ( !self::$browser ) {
            $factory = new BrowserFactory();
            self::$browser = $factory->createBrowser([
                'keepAlive'       => true,
                'enableImages'    => false,
                'headless'        => false,
                'connectionDelay' => 0.8, 
                'debugLogger'     => 'php://stdout',
                'customFlags'   => [ '--remote-debugging-port' => 9223 ]
            ]);

            file_put_contents($socketFile, self::$browser->getSocketUri());
        }
    }
}

As soon as Init() completes, the browser process is torn down and  Chrome exits. Suggestions?

**Comment by gsouf** [comment]
Hi @Munger 
I think this was working with symfony 2 and stopped to work as of symfony 3. I'm going to see what is doable

**Comment by ttk** [comment]
@gsouf Looks like you found my [comment](https://github.com/symfony/symfony/issues/7237#issuecomment-583181010).  The funny thing is that I posted that comment/solution because of this exact bug in this project.  I patched my local headless-chromium-php branch a couple of weeks ago, but didn't get around to submitting a pull request.

**Comment by gsouf** [comment]
@ttk this is funny indeed! 

@Munger  You can find a patch in this tag: `dev-v0.9.x-dev`. Might release soon
