### ISSUE TITLE
OperationTimedOut after 16 pages are loaded

### ISSUE THREAD

**Issue by BenMorel** [chrome-php/headless-chromium-php#139]
I'm re-using a `Page` to navigate several URLs:

```php
foreach ($urls as $url) {
    $page->navigate($url)->waitForNavigation();
    ...
}
```

The first 16 URLs are loaded alright, but the 17th always ends up with an `OperationTimedOut` exception:

> Operation timed out (30sec)

I tried to close the `Page` and create a new one, but got the same timeouts. The only solution is to close the `Browser` and create a new one after 16 pages are visited.

**Comment by gsouf** [comment]
Hello @BenMorel 

can you please provide a minimal reproducible code that I can run on my machine. You could just setup an array of urls and loop on it. So that it's quick to setup and I'm sure that we are testing the same thing

**Comment by BenMorel** [comment]
Can't reproduce it today. Will reopen if I can reproduce it!
