### ISSUE TITLE
Add a form to a page and submit

### ISSUE THREAD

**Issue by woodsbox** [chrome-php/headless-chromium-php#14]
`$evaluation = $page->evaluate(
'(() => {
        document.body.innerHTML += "<form id=\""dynForm\"" action=\""http://example.com/\"" method=\""post\""></form>";
        document.querySelector("#dynForm").submit();
    })()'
 );
`

is this the inccorect way to add it to the page?
document.body.innerHTML += "<

Using the chrome console it works.

**Comment by gsouf** [comment]
You should consider using ``createElement `` and ``appendChild``. Example: https://stackoverflow.com/questions/13001830/creating-and-submitting-a-form-with-javascript
