### ISSUE TITLE
Wrench / Implode Bug

### ISSUE THREAD

**Issue by michelvermeulen** [chrome-php/headless-chromium-php#140]
Hey,

Wrench has a deprecated implode method (using pieces before glue) that has been fixed in 3.0.

Any way you can update the dependency, it doesn't work with PHP 7.4 as is (and I have to manually edit the source file on my server for now).

Thanks!

**Comment by momala454** [comment]
hello

a fix : https://github.com/chrome-php/headless-chromium-php/issues/114

**Comment by haiderali97** [comment]
What i did was fork the repository and update the dependency in composer.json

**Comment by michelvermeulen** [comment]
@momala454 Works great thanks!

**Comment by momala454** [comment]
the issue should be reopened until it's fixed without manual changes in the library
