### ISSUE TITLE
Can only do read actions in javascript

### ISSUE THREAD

**Issue by Entretoize** [chrome-php/headless-chromium-php#143]
I'm trying to read a specific page on a website, there's some actions that work like signing in:

```
$eval = $page->evaluate('
						document.querySelector(\'input[name="US_LOGIN"]\').value="mylogin";
						document.querySelector(\'input[name="US_PWD"]\').value="mypassword";
						document.querySelector(\'#connexion_submit\').click();
						');
$eval->waitForPageReload();
```

And I can read anything after that:

`$html = $page->evaluate('document.documentElement.innerHTML')->getReturnValue();`

But I can't seem to do any "active" action:
```
$page->evaluate('document.querySelector("#inter-date").innerHTML=""'); //does nothing

$page->evaluate('var event = new CustomEvent("click");');
$page->evaluate('document.querySelector("span[class*=\'iconRight\']").dispatchEvent(event);'); //does nothing

$eval = $page->evaluate('document.querySelector("span[class*=\'iconRight\']").click();'); //does nothing

sleep(10); //tried more
$html = $page->evaluate('document.documentElement.innerHTML')->getReturnValue();
print $html; //nothing changed
```

How can I find the issue ? No way to see javascript console ?

**Comment by alex-rsk** [comment]
I advice to wrap all consequential instructions to function, and then evaluate it. 
try to check, do these elements exists in page, when you calling script
For example:
``
(() =>  {
    
        var loginForm = () => 
        {
            var login_field = document.querySelector('input[name="login"]');
            var password_field = document.querySelector('input[name="password"]') 
            var button = document.querySelector('button[name="submit"]');
            email_field.value =  "monty";   
            password_field.value  = "somepass";
            button.click();            
            return {"status" : "success", "message" : "logged in"};
        };
        return loginForm();        
})();

**Comment by Entretoize** [comment]
It doesn't help, in fact I I separated the lines to test if it was better.

**Comment by alex-rsk** [comment]
Just noticed that you trying to perform a click.
In new versions of chrome, any programmatically created event marked as "untrusted", so browser in majority of cases won't react on it.
It is due to security issues..
The workaround is, to send mouse and KB events through chrome-php messages. See examples with Mouse class in the library.
