### ISSUE TITLE
How to use proxy with tthe script

### ISSUE THREAD

**Issue by deb4it** [chrome-php/headless-chromium-php#145]
Hi @gsouf 
How May I use proxy in this library.
For example 
"user:pass@ip:port"

Could you please give me an example. Thanks in advance.

**Comment by alex-rsk** [comment]
Headless chrome accepts parameter --proxy-server
So you need to pass that parameter in customFlags parameter to the library.
``
$customFlags = [
...,
'--proxy-server= ' . $proxy 
];
But, headless chrome **does not** accept proxies with credentials.
It means, that you need either proxy without authorization or make proxy forwarding to some localhost port and access it without password.
``

**Comment by gsouf** [comment]
@deb4it I'm closing. Feel free to reopen if you think something is not working
