### ISSUE TITLE
Proxy doesn't work

### ISSUE THREAD

**Issue by raykudo** [chrome-php/headless-chromium-php#146]
I use squid as a proxy server installed on AWS Lightsail.
However, my code below doesn't work even though sending HTTP requests through Guzzle works completely fine via proxy.

```
$uri = 'https://www.github.com';
chrome with proxy
$innerHTML = null;
$browserFactory = new BrowserFactory('google-chrome');
$browser = $browserFactory->createBrowser([
    'headless' => true,
    'noSandbox' => true,
    'startupTimeout' => 180,
    'customFlags' => ['--proxy-server="http://proxyip:myproxyport"'],
]);
$page = $browser->createPage();
$page->navigate($uri)->waitForNavigation(Page::LOAD, 180000);
$innerHTML = $page->evaluate('document.documentElement.innerHTML')->getReturnValue();
$url = $page->evaluate('document.location.href')->getReturnValue();
\Log::info($url);
$browser->close();
return $innerHTML;
```
Http request fails with this. I can't see any log on squid. Probably Chrome failed to launch for some reason.

```
[debugged $url]
local.INFO: chrome-error://chromewebdata/  
```

```
[guzzle]
$client = new \GuzzleHttp\Client();
$result = $client->request('GET', $uri, [
  'proxy' => 'http://proxyip:myproxyport'
]);
$statuscode = $result->getStatusCode();
return $statuscode; 
```

This works perfectly fine. Also, I can see the log ```/var/log/squid/access.log```

Am I missing something? Are there any restrictions like I can't use proxy with ```headless = true```?

**Comment by gsouf** [comment]
Hi @raykudo sure.
Just so you know, you can close issues that you openned by yourself


(duplicate is #147)
