### ISSUE TITLE
Proxy doesn't work

### ISSUE THREAD

**Issue by raykudo** [chrome-php/headless-chromium-php#147]
version: "chrome-php/chrome": "^0.8.1",

I use squid as a proxy server installed on AWS Lightsail.
However, my code below doesn't work even though sending HTTP requests through Guzzle works completely fine via proxy.

```
$uri = 'https://www.github.com';
chrome with proxy
$innerHTML = null;
$browserFactory = new BrowserFactory('google-chrome');
$browser = $browserFactory->createBrowser([
    'headless' => true,
    'noSandbox' => true,
    'startupTimeout' => 180,
    'customFlags' => ['--proxy-server="https=proxyip:myproxyport"'],
]);
$page = $browser->createPage();
$page->navigate($uri)->waitForNavigation(Page::LOAD, 180000);
$innerHTML = $page->evaluate('document.documentElement.innerHTML')->getReturnValue();
$url = $page->evaluate('document.location.href')->getReturnValue();
\Log::info($url);
$browser->close();
return $innerHTML;
```
Http request fails with this. I can't see any log on squid. Probably Chrome failed to launch for some reason.

```
[debugged $url]
local.INFO: chrome-error://chromewebdata/  
```

```
[guzzle]
$client = new \GuzzleHttp\Client();
$result = $client->request('GET', $uri, [
  'proxy' => 'http://proxyip:myproxyport'
]);
$statuscode = $result->getStatusCode();
return $statuscode; 
```

This works perfectly fine. Also, I can see the log ```/var/log/squid/access.log```

In addition, I could send http/https requests through my browser via proxy.

Am I missing something? Are there any restrictions like I can't use proxy with ```headless = true```?

**Comment by raykudo** [comment]
It worked well without double quote syntax somehow

```
'customFlags' => ['--proxy-server="http=proxyip:myproxyport"']
```

change it to 

```
'customFlags' => ['--proxy-server=https=myip:myipport]
```

**Comment by mexdex1** [comment]
I got the problem, that when I set a proxyserver via customFlags, I only receive blank pages.

**Comment by raykudo** [comment]
@mexdex1 What’s the URL you’re navigating? It helps if you paste your code here.

**Comment by mexdex1** [comment]
@raykudo 
This is my code:

`use HeadlessChromium\BrowserFactory;

$browserFactory = new BrowserFactory('chromium-browser');

$browser = $browserFactory->createBrowser([
    'headless' => true,
    'noSandbox' => true,
    'startupTimeout' => 180,
	'customFlags' => ['--proxy-server=http://user:pass@ip:port'],
	'debugLogger'     => 'log.txt'
]);

$page = $browser->createPage();
$page->navigate('https://google.de')->waitForNavigation();

$page->pdf(['printBackground'=>false])->saveToFile('screen.pdf');

$browser->close();`

This will lead to a blank pdf. Removing the proxyserver gives me a screenshot with content.
I tried different proxyservers (socks/https) and also double quotations and so on.
I also tried http urls. Same problem here.
I can't figure out whats the problem here.

**Comment by raykudo** [comment]
@mexdex1 

check [this](https://superuser.com/questions/902620/google-chrome-proxy-settings-with-username-and-password) out

> Proxy auto-configuration files do not support hard-coded usernames and passwords. 
There's good reasoning behind this too, since providing support for hard-coded credentials would open up significant security holes, as anybody would be able to easily view the required credentials to access the proxy.
