### ISSUE TITLE
Close the javascript alert box coming on page load.

### ISSUE THREAD

**Issue by ramanoj** [chrome-php/headless-chromium-php#148]
Hello Sir,
            I'm scrapping the data from the page but there is coming the alert box on page load.
So can you suggest me how can i close the javascript alert box.

thanks
Manoj

**Comment by haris1024** [comment]
see this https://github.com/chrome-php/headless-chromium-php/issues/123

**Comment by ramanoj** [comment]
Hello Haris I have checked but this is not working.
[Archive.zip](https://github.com/chrome-php/headless-chromium-php/files/4434345/Archive.zip)

**Comment by haris1024** [comment]
of course it is not working for you because in my case i need to auto close confirm box. you should modify the code to suite your need. i have test your example and it is working. replace window.confirm with window.alert

**Comment by ramanoj** [comment]
Hello Haris,
                Thanks for your reply but i did check just now your suggestion but not working. below is new code.
$script = '
var acceptConfirm=window.alert;
window.alert=function(){
window.alert=acceptConfirm;
return true;
};
';
$page->addPreScript($script);

Thanks
Manoj

**Comment by ramanoj** [comment]
Hello Haris,
Thanks for your reply but i did check just now your suggestion but not working. below is new code.
$script = '
var acceptConfirm=window.alert;
window.alert=function(){
window.alert=acceptConfirm;
return true;
};
';
$page->addPreScript($script);

Thanks
Manoj

**Comment by haris1024** [comment]
i do not know what is wrong with your code but  this is my complete code

<?php
require 'vendor/autoload.php';
use HeadlessChromium\BrowserFactory;
$factory = new BrowserFactory("C:\Users\haris\AppData\Local\Chromium\Application\chrome.exe");
$browser = $factory->createBrowser(['headless' => false]);
$page = $browser->createPage();
$width = 1280;
$height = 768;
$script = 'window.alert=function(){};';
$page->addPreScript($script);
$page->setViewport($width, $height)->await();
$page->navigate('http://localhost/questions2.php')->waitForNavigation();
sleep(5);
$browser->close();
?>

**Comment by ramanoj** [comment]
Hello Haris,
                  Now working Thanks for your help.
Thanks
Manoj
