### ISSUE TITLE
How to pass headers while requesting a page?

### ISSUE THREAD

**Issue by deb4it** [chrome-php/headless-chromium-php#152]
Hi @gsouf 
How to send a bunch of headers while requesting a page
The headers look like this

Host: www.facebook.com
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:75.0) Gecko/20100101 Firefox/75.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Cookie: fr=1cgp1s7fdwer3Zi3Xzodb28.AWV61UO1R0j4tN6xEtqLTOIwfkosdfsdffsdf; sb=_WS-XRCyLCWb5sdfds; datr=_WS-XQuzXUltyL5Wyj3lS8Tf; wd=1366x285; locale=en_GB; xs=33%3AzF10yXAQT1Iasg%3A2%3A1587247927%3A-1%3A-1; spin=r.1002011557_b.trunk_t.1587247928_s.1_v.2_; presence=EDvF3EtimdsfdsfeF1587305570EuserFA21B25738637668A2EstateFDutF1587305570255CEchF_7bCC; act=15872755dsad63853%2F0
Upgrade-Insecure-Requests: 1
Cache-Control: max-age=0

**Comment by alex-rsk** [comment]
1. User agent you can set up in the library params on startup.
2.  Cookies you can set up, using setCookie method of the library.
3. "Connection: keep-alive" and other stuff should be sent automatically when you are logging into FB. But if you insist on writing them, dig towards request interception [in the Chrome DevTools protocol documentation.](https://chromedevtools.github.io/devtools-protocol/tot/Fetch)

**Comment by deb4it** [comment]
Hi @alex-rsk 
I'm in a big trouble setting the cookies. If I call the setCookies method the execution does not go to the next line. The script terminates. could you please check the following code. For example i'm just passing one cookie. 
<?php
	require_once "vendor/autoload.php";
	use HeadlessChromium\BrowserFactory;

    $browserFactory = new BrowserFactory('chromium-browser');
    $browser = $browserFactory->createBrowser([
                'customFlags' => [],
                'windowSize'  => [1920, 2000],
                'debugLogger' => 'php://stdout' // will enable verbose mode
    ]);

    // creates a new page and navigate to an url
    $page = $browser->createPage();
    $page->setUserAgent('Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:75.0) Gecko/20100101 Firefox/75.0');
    $page->setCookies([
        Cookie::create('fr', '1zcEuOSFTYDVlyoQT.AWU_8QezCaA3XSMcEvMCS3Rud7E.BenVni.MA.F6d.0.0.Benajt.AWVlhbWf', [
            'domain' => 'facebook.com',
            'expires' => time() + 3600 // expires in 1 day
        ])
	]);
    echo "<br>It comes here";
	$page->navigate('https://www.facebook.com/')->waitForNavigation();
    $page->screenshot()->saveToFile('/var/www/html/chrome-php/facebook_'.time ().'.png');
    $browser->close();
    exit;

**Comment by deb4it** [comment]
Hi @alex-rsk 
I'm in a big trouble setting the cookies. If I call the setCookies method the execution does not go to the next line. The script terminates. could you please check the following code. For example i'm just passing one cookie.
#


	require_once "vendor/autoload.php";
	use HeadlessChromium\BrowserFactory;

    $browserFactory = new BrowserFactory('chromium-browser');
    $browser = $browserFactory->createBrowser([
                'customFlags' => [],
                'windowSize'  => [1920, 2000],
                'debugLogger' => 'php://stdout' // will enable verbose mode
    ]);

    // creates a new page and navigate to an url
    $page = $browser->createPage();
    $page->setUserAgent('Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:75.0) Gecko/20100101 Firefox/75.0');
    $page->setCookies([
        Cookie::create('fr', '1zcEuOSFTYDVlyoQT.AWU_8QezCaA3XSMcEvMCS3Rud7E.BenVni.MA.F6d.0.0.Benajt.AWVlhbWf', [
            'domain' => 'facebook.com',
            'expires' => time() + 3600 // expires in 1 day
        ])
	]);
    echo "<br>It comes here";
	$page->navigate('https://www.facebook.com/')->waitForNavigation();
    $page->screenshot()->saveToFile('/var/www/html/chrome-php/facebook_'.time ().'.png');
    $browser->close();
    exit;

**Comment by CyberPunkCodes** [comment]
After some digging, I was able to set them on the page instance. It would seem more logical to set them in the browser factory, but I wasn't able to get it to work. My concern with setting them on the page instance, is that subsequent requests would lose the headers. It could work just fine, just something I thought about and haven't tested.

This is how I got it to work:

```php
$page = $browser->createPage();

$page->getSession()->sendMessageSync(new Message('Network.setExtraHTTPHeaders', [
    'headers' => [
        'Accept-Encoding' => 'identity',
        'Accept-Language' => 'en-US,en;q=0.9',
    ]
]));

$page->navigate($url);
```
