### ISSUE TITLE
Cookies not enabled, how to enable it, I need to login into fb using headless-chromium-php

### ISSUE THREAD

**Issue by deb4it** [chrome-php/headless-chromium-php#153]
Hi @gsouf 
I need to login into facebook. I'm using your library to do that. But after submitting the login form
i see the following response as in the attached screen shot.
![image](https://user-images.githubusercontent.com/10611035/79730969-7217c880-8313-11ea-8b4d-fe9c83c84f38.png)
Could you please help me about how to enable cookies  headless-chrome through your script

Many thanks!!!

**Comment by pashkasan** [comment]
Hi, 
cookies enabled by default
but you can try to set custom userDataDir  see Options https://github.com/chrome-php/headless-chromium-php#options

**Comment by kpaha** [comment]
I had this issue also. For compatibility headless and headfull need to disable '--password-store' option together with set 'userDataDir'. Now I have next config: 
`[
'passwordStore' => false,
 'userDataDir' => '/path/to/data'
]`
