### ISSUE TITLE
Unable to launch a new process. How do you kill the browser process?

### ISSUE THREAD

**Issue by seitymoe** [chrome-php/headless-chromium-php#154]
I run chrome-php to crawl a website in a queue. After a while it gives me`Unable to launch a new process. ` error and will not be able to launch chrome again until I restart the server. 
It used to run for at least 24 hours, but recently it stops in an hour.
What could be the problem? How can I resolve this?

error
```
Unable to launch a new process. {"exception":"[object] (Symfony\\Component\\Process\\Exception\\RuntimeException(code: 0): Unable to launch a new process. at /var/www/laravel/vendor/symfony/process/Process.php:342)
[stacktrace]
#0 /var/www/laravel/vendor/chrome-php/chrome/src/Browser/BrowserProcess.php(124): Symfony\\Component\\Process\\Process->start()
#1 /var/www/laravel/vendor/chrome-php/chrome/src/BrowserFactory.php(78): HeadlessChromium\\Browser\\BrowserProcess->start('chromium-browse...', Array)
#2 /var/www/laravel/app/Helper/PageScanner.php(82): HeadlessChromium\\BrowserFactory->createBrowser(Array)
#3 /var/www/laravel/app/Helper/DataRetriever.php(41): App\\Helper\\PageScanner->__construct()
#4 /var/www/laravel/app/Jobs/Retrieve30DaysData.php(89): App\\Helper\\DataRetriever->__construct(Object(App\\User), 'dtbhpv4z')
#5 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Redis/Limiters/ConcurrencyLimiter.php(75): App\\Jobs\\Retrieve30DaysData->App\\Jobs\\{closure}()
#6 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Redis/Limiters/ConcurrencyLimiterBuilder.php(113): Illuminate\\Redis\\Limiters\\ConcurrencyLimiter->block(3, Object(Closure))
#7 /var/www/laravel/app/Jobs/Retrieve30DaysData.php(114): Illuminate\\Redis\\Limiters\\ConcurrencyLimiterBuilder->then(Object(Closure), Object(Closure))
#8 [internal function]: App\\Jobs\\Retrieve30DaysData->handle()
```
```
 public function __construct($url = null)
    {
        Log::debug('PageScanner constructor.');
      
        if ($url) {
            $this->url = $url;
        }
        $this->cookie_dir = storage_path('app/admin/YAfiles/Cookie/');

        if (Storage::exists('admin/YAfiles/chrome_php_socket')) {
            $socket_uri = Storage::get('admin/YAfiles/chrome_php_socket');

            try {
                $this->chrome_client = \HeadlessChromium\BrowserFactory::connectToBrowser($socket_uri, [
                    'debugLogger' => 'php://stdout'
                ]);
            } catch (\HeadlessChromium\Exception\BrowserConnectionFailed $e) {
                // The browser was probably closed
                // Keep $browser null and start it again bellow
            }
        }

        if (!$this->chrome_client) {
            Log::debug('the browser does not exist. creating.');
            $factory = new BrowserFactory('chromium-browser');
            $this->chrome_client = $factory->createBrowser([
                'keepAlive' => true,
                'userDataDir' => $this->cookie_dir,
                'noSandbox' => true,
                'userAgent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.50 Safari/537.36',
            ]);
            $socket_uri = $this->chrome_client->getSocketUri();
            Log::debug('Chrome-browser created. Socket-URI:'.$socket_uri);
            Storage::put('admin/YAfiles/chrome_php_socket', $socket_uri);
        }else{
            Log::debug('browser already exists');
        }
        $this->chrome_page = $this->chrome_client->createPage();

        if (Storage::exists('admin/YAfiles/saved_Cookie')) {
            Log::debug('Saved Cookie found.');
            $cookie = json_decode(Storage::get('admin/YAfiles/saved_Cookie'));
            //Log::debug($cookie);
            $this->chrome_page->setCookies($cookie)->await();
        }
 public function __destruct()
    {

        Log::debug('destructing chrome page.');
        $this->saveCookies();
        $this->chrome_page->close();
    }

    }
```

**Comment by seitymoe** [comment]
I manually killed the browser process, and it started working again.
So I want to kill the process from php when I get this error. 
How can I find the process id for the chrome browser? and kill it?

**Comment by pashkasan** [comment]
if  keepalive option set, you need to use  connectToBrowser method

sample
if socket exists 

            $this->chrome_client = BrowserFactory::connectToBrowser($socket, [
                'sendSyncDefaultTimeout' => 30000,
                'ignoreHTTPSErrors' => true,
            ]);

else

$this->chrome_client = $factory->createBrowser([
                'keepAlive' => true,
                'userDataDir' => $this->cookie_dir,
                'noSandbox' => true,
                'userAgent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.50 Safari/537.36',
            ]);

**Comment by seitymoe** [comment]
@pashkasan thank you for your answer. Yes I use connectToBrowser method.
but sometimes the browser is closed, in that case I create a new browser.

**Comment by alex-rsk** [comment]
You can obtain browser's process id (PID), where the library creates new browser process.
`
       // setup chrome process
        $process = new Process($args);
        $this->process = $process;
        $process->getPid()`
`

**Comment by seitymoe** [comment]
@alex-rsk 
Thank you for your answer.
To do that, I'll have to edit chrome-php code itself, won't I?
I couldn't find any method which returns the pid or the Process instance....
As a workaround, I restart laravel queue whenever chrome failed to start, so that the chrome's parent php process gets killed, so does chrome.
So far it's working for 4 days.
I couldn't think of any other way...

**Comment by alex-rsk** [comment]
If you about legitimacy of modifications,  check the license of this code.
If you talk about technical issues, you need to slightly modify the code. What's wrong with it?

**Comment by seitymoe** [comment]
ah,I see in that way, I don't have to modify the original code. I'll try. thank you!
