### ISSUE TITLE
headerTemplate and footerTemplate not visible if defined

### ISSUE THREAD

**Issue by rnick** [chrome-php/headless-chromium-php#155]
Hi, i want to create header and footer, but if i define them, they are not displayed. If i enable them, the default header and footer are displayed.

this displays no footer
`$options = [
    'footerTemplate' => '<div class="pageNumber">pagenumber</div>',
    'displayHeaderFooter' => true,
];`

this displays default footer
`$options = [
    'displayHeaderFooter' => true,
];`

ralf

--
Chromium 79.0.3945.130
chrome-php/chrome: 0.8.1
PHP 7.3.11-0ubuntu0.19.10.4

**Comment by Cryde** [comment]
It work but you have to add some stuff : https://github.com/chrome-php/chrome/issues/101#issuecomment-727223984
