### ISSUE TITLE
Upload a file through file input like pupperteer uploadFile function

### ISSUE THREAD

**Issue by Entretoize** [chrome-php/headless-chromium-php#161]
I need to upload a file through a html file input but I don't find the equivalent of the puppeteer function.
In Puppeteer the code is:

```
    await page.waitForSelector('input[type=file]');
    await page.evaluate(() => document.querySelector('input[type=file]').click());

    const inputUploadHandle = await page.$('input[type=file]');
    inputUploadHandle.uploadFile('/var/www/myfile.ext');

    await page.waitForSelector('input[type="submit"]');
    await page.evaluate(() => document.querySelector('input[type="submit"]').click());

```

Does it exist ?

**Comment by peter279k** [comment]
It seems that this PHP package doesn't have customized function about uploading file.

You can use the `evaluate` method to execute uploading file JavaScript and you can look at more details on [examples/form-submit.php](https://github.com/chrome-php/headless-chromium-php/tree/master/examples)

**Comment by Entretoize** [comment]
You can't select a file in javascript, it would be a security issue.

**Comment by austinginder** [comment]
I'm not sure if there is a more straightforward way to do this, however it is possible to have [Javascript create the file object](https://thewebdev.info/2021/04/25/how-to-create-a-file-object-in-javascript/) and then attach that to the file input field. I did the same thing to attach a zip file to an upload field on a WordPress site. PHP can take in the raw file contains with base64 which is passed to JS. If the file is huge then you might run into issues however this works great for small files. Here is a full working example.

```php
$plugin_zip    = "/home/austin/Downloads/wordpress-plugin.zip";
$plugin_base64 = base64_encode( file_get_contents( $plugin_zip ) );

$page->navigate('/wp-admin/plugin-install.php')->waitForNavigation();

$evaluation    = $page->evaluate(
  '(() => {
        plugin_base64 = "' . $plugin_base64 . '"
        parts = Uint8Array.from(atob( plugin_base64 ), c => c.charCodeAt(0))
        blob = new Blob( [parts], {type: "application/zip" } )
        file = new File( [blob], "wordpress-plugin.zip", {
            type: "application/zip"
        })
        list = new DataTransfer()
        list.items.add( file )
        document.querySelector("#pluginzip").files = list.files
        document.querySelector(".wp-upload-form").submit()
      })()'
  );
$evaluation->waitForPageReload();
```
For reference here is the HTML of the form.

```html
<form method="post" enctype="multipart/form-data" class="wp-upload-form" action="/wp-admin/update.php?action=upload-plugin">
  <label class="screen-reader-text" for="pluginzip">Plugin zip file</label>
  <input type="file" id="pluginzip" name="pluginzip" accept=".zip">
  <input type="submit" name="install-plugin-submit" id="install-plugin-submit" class="button" value="Install Now" disabled="">
</form>
```

**Comment by enricodias** [comment]
Blobs will be limited to 500mb in size. Wouldn't just typing the file path in the input field be enough to make this work?

**Comment by austinginder** [comment]
Well if you have a working example, please share. File uploads work differently. I don't think a completely Javascript solution will work. Only the browser can access the file system. I don't know how to control the file upload selection using Chrome PHP.

**Comment by enricodias** [comment]
I didn't mean using javascript. You can use the keyboard and mouse to input commands as a real user, with full control. Try clicking on the input field paste the file path.

**Comment by austinginder** [comment]
Even as a real user I have no idea how to accomplish that on native HTML file upload field. I know I can drag and drop files onto input file fields however clicking on a file input fields displays the file selection dialog, which isn't something Chrome PHP is aware of. Also even if I do manage to tab over to a file field in Chrome, typing or pasting on it doesn't seen to do anything. It's also not something you can right click and paste.

**Comment by enricodias** [comment]
Try using the method `sendFile()` introduced recently in #259.

```php
$element = $page->dom()->querySelector('#myfile');
$element->sendFile($file);
```
