### ISSUE TITLE
Why --hide-scrollbars ?

### ISSUE THREAD

**Issue by momala454** [chrome-php/headless-chromium-php#164]
This settings render headless detectable as every browser have scrollbars, and this settings is causing the render width to be 100% of the screenwidth

and we can't remove this parameter unless we modify the code from this library

**Comment by alex-rsk** [comment]
Observing current headless detection solutions, i haven't met absence of scrollbars as criteria, for a while.
These settings are possible for using by regular users as well.. Unless you turn off the screen, these suppositions are very vague criterias.

**Comment by momala454** [comment]
you are sure chrome have an option to remove scrollbar ?

**Comment by momala454** [comment]
"Observing current headless detection solutions"
so you've reversed all of the obfuscated code ? like on tiktok by example which is strongly obfuscated

**Comment by alex-rsk** [comment]
> you are sure chrome have an option to remove scrollbar ?

I do. Try to google, "how to remove scrollbars" in chrome and you'll find few solutions.

**Comment by momala454** [comment]
installing an extension or having to modify the css of the website aren't really what i consider "possible by regular user".
Almost no one will do that

**Comment by alex-rsk** [comment]
> and you doesn't finding headless detection by using scrollbar doesn't means it is not or will never be used.

> so you've reversed all of the obfuscated code ? like on tiktok by example which is strongly obfuscated

These tricks before obfuscating are pretty readable, and they are rather well-known. Maybe,  there will be  something new in future, but it won't be scrollbars, I'm assured.

Nevertheless,  if you still not assured, just turn it off in your working copy.   Is this problem worthy of long discussion, ?

**Comment by momala454** [comment]
this means if this library is every updated again, i will have to remember to modify my local copy each time i get an update, that is not ideal at all. Having the possibility to modify the default parameters would be great

**Comment by alex-rsk** [comment]
Installing an extension... is something almost no one will do?
You underestimate people who got annoyed of something in chrome.
Anyway, I meant neither an extension nor css, I meant a chrome flag to disable scrollbars,  which was acceptable in older versions of Chrome.

**Comment by alex-rsk** [comment]
>Having the possibility to modify the default parameters would be great

Please, feel free to subclass a needed class and modify them.  It's open source.

**Comment by momala454** [comment]
why would anyone remove scrollbars, i don't see any use for it. The vast majority of people will not install plugins, or just adblock.
Having no scrollbar is a way to detect "something strange". If you have other strange things (like proxy ip), even if legit users could use the chrome flag to remove the scrollbar, it could be a good reason for a security system to ask for captcha or advanced protections or something.
Why are you so sure scrollbar will never be used to detect unusual users ?

**Comment by alex-rsk** [comment]
>Why are you so sure scrollbar will never be used to detect unusual users ?
Because some browsers don't have scrollbars at all, like mobile browsers (if the scale isn't increased).
I can't imagine that someone will be so paranoidal, that he will block all mobile browser for the sake of preventing web scraping or whatever.

**Comment by momala454** [comment]
i am talking about when you send an user agent of windows. Of course when you send an user agent of a mobile device, things are different, but this doesn't means that when the device is considered on windows that the verification of the scrollbar size couldn't be done

**Comment by alex-rsk** [comment]
Okay, you can browse webpages in windows, linux, macos in responsive mode, then you consider to block users?
Too vague.

**Comment by momala454** [comment]
beside developers, who will use the responsive mode ?
and i am not talking about blocking, but you could ask a captcha or reduce the number of allowed queries before having captcha if you don't have scrollbars

**Comment by momala454** [comment]
or just allow to remove flags that are added automatically on getArgsFromOptions

**Comment by momala454** [comment]
hi @GrahamCampbell , did you closed because you have a solution to remove default flags ?

**Comment by enricodias** [comment]
I think scrollbars are hidden by default because they don't add relevant information for tests and don't look good in screenshots.

With the current code, scrollbars will be visible if you disable the headless mode:

https://github.com/chrome-php/headless-chromium-php/blob/5f873efbb04059591a6aa540209a09c7de9aad36/src/Browser/BrowserProcess.php#L311-L317

But there are other valid reasons for controlling the flags. If you need to run the browser with any extension for example, you'll probably need to disable the headless mode, enable extensions and run the browser in a virtual display.

Allowing a more granular control over the flags would certainly make this lib more versatile. I can try to make a PR on that.
