### ISSUE TITLE
How to save html to a file?

### ISSUE THREAD

**Issue by rvazheninr** [chrome-php/headless-chromium-php#165]
Tell me. How to get and save the html of a page to a file after executing javascripts?

**Comment by peter279k** [comment]
Try to consider following script:

```PHP
<?php

require __DIR__ . '/../vendor/autoload.php';

use HeadlessChromium\BrowserFactory;

// open browser
$factory = new BrowserFactory('your-google-chrome-binary');
$browser = $factory->createBrowser();

// navigate to a page with a form
$page = $browser->createPage();
$page->navigate('file://' . __DIR__ . '/html/form.html')->waitForNavigation();

// put 'hello' in the input and submit the form
$evaluation = $page->evaluate(
'(() => {
        document.querySelector("#myinput").value = "hello";
        document.querySelector("#myform").submit();
    })()'
);

// wait for the page to be reloaded
$evaluation->waitForPageReload();

// Fetch the page content after executing/evaluating JavaScript codes
$value = $page->evaluate('document.documentElement.outerHTML')->getReturnValue();

// You can use save this $value vale as a HTML file
var_dump($value);

```

**Comment by rvazheninr** [comment]
I need to get the html of the whole page. The script you specified gives only one found item.

**Comment by peter279k** [comment]
Is the `$value` not a whole HTML page?

This script I've tried and I will get the whole page with affected field for JavaScript.

**Comment by peter279k** [comment]
Ok. I get your question. I think you've to evaluate all possible JavaScript and functions manually before getting whole HTML page contents.

**Comment by peter279k** [comment]
After try executing many cases, it cannot fetch whole page with all loaded JS functions executing.

Maybe it's the limited for `google-chrome` command with `headless` mode.

**Comment by rvazheninr** [comment]
Yes you are right. Thanks for the help!
