### ISSUE TITLE
Use chrome/chromium specifying path on Linux

### ISSUE THREAD

**Issue by Laurianti** [chrome-php/headless-chromium-php#168]
Hello, I tested the library on linux Windows (chrome or chromium executables), and it works perfectly, but I have problem on Linux.
I don't have control on Linux server, I have to copy manually chrome/chromium "portable" e use the executable, but I don't understand how specify the path.
Can you suggest me where download chrome/chromium and how to use them? Thank you

**Comment by alex-rsk** [comment]
Usually chrome placed in /user/bin/google-chrome.
But if you copied it manually, you have to know, where it is!
And I'd say, that configuring something without access to console is helluva difficult, and actually waste of time.

**Comment by Laurianti** [comment]
What is the executable?

**Comment by Laurianti** [comment]
![error_chrome_not_found](https://user-images.githubusercontent.com/20415513/88976502-73667300-d2bc-11ea-9ea3-a562667cadcf.JPG)

**Comment by shahreahang** [comment]
I have same problem.
did you solved it ?

**Comment by Laurianti** [comment]
I couldn't solve it, for now I'm using it on Windows. These days I will try again and I will tell you.

**Comment by Laurianti** [comment]
I tried to create a Docker image, and partially now it succeded.
I know I made a bad Dockerfile, but for now my goal is to have a working case.

Currently I can get it to work with headless: true (https://github.com/Laurianti/docker-php-helloworld).

With headless: false I get this error:

`Fatal error: Uncaught RuntimeException: Chrome process stopped before startup completed. Additional info: Fontconfig warning: "/etc/fonts/fonts.conf", line 100: unknown element "blank" [114:114:1122/171901.976313:ERROR:browser_main_loop.cc(1434)] Unable to open X display. in /var/www/html/vendor/chrome-php/chrome/src/Browser/BrowserProcess.php:379 Stack trace: #0 /var/www/html/vendor/chrome-php/chrome/src/Utils.php(51): HeadlessChromium\Browser\BrowserProcess->HeadlessChromium\Browser\{closure}(Object(Symfony\Component\Process\Process)) #1 /var/www/html/vendor/chrome-php/chrome/src/Browser/BrowserProcess.php(414): HeadlessChromium\Utils::tryWithTimeout(30000000, Object(Generator)) #2 /var/www/html/vendor/chrome-php/chrome/src/Browser/BrowserProcess.php(128): HeadlessChromium\Browser\BrowserProcess->waitForStartup(Object(Symfony\Component\Process\Process), 30000000) #3 /var/www/html/vendor/chrome-php/chrome/src/BrowserFactory.php(78): HeadlessChromium\Browser\BrowserProcess->start('/usr/bin/google...', Array) #4 /var/www/h in /var/www/html/vendor/chrome-php/chrome/src/Browser/BrowserProcess.php on line 379`
