### ISSUE TITLE
Wrench Dependancy Notice in Composer

### ISSUE THREAD

**Issue by iamashishk** [chrome-php/headless-chromium-php#169]
Deprecation Notice: Class Wrench\Tests\Protocol\HybiPayloadTest located [path] does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0.
and i looked into Issue request in wrench [here](https://github.com/varspool/Wrench/issues/133) it was written that it will be fixed in v3 which is in beta. any idea what we can do and what effect can this have on your library

**Comment by GrahamCampbell** [comment]
You can ignore this issue.

**Comment by GrahamCampbell** [comment]
The upstream package seems abounded so I am going to create our own version: https://github.com/chrome-php/wrench.

**Comment by iamashishk** [comment]
i just updated the chrome-php to 0.10.0 but its still using wrench/wrench

**Comment by enricodias** [comment]
@iamashishk `chrome-php/wrench` was implemented in version 1.0, not released yet.

**Comment by iamashishk** [comment]
any deadline about its release?

**Comment by enricodias** [comment]
That's up to Graham, but you can force your composer to load the version `1.0.x-dev` in the meantime.

**Comment by GrahamCampbell** [comment]
Not sure. It'll likely require PHP 7.4 or 8.0. To make things go faster, you can fund my work at https://github.com/sponsors/GrahamCampbell. :)
