### ISSUE TITLE
how to get the file that is downloaded when pressing a button

### ISSUE THREAD

**Issue by woodsbox** [chrome-php/headless-chromium-php#17]
So the situation:
First I need to login onto a page
Then go to the download page
Fill in some information 
Press a button

The button trigger's some jQuery on the page that does a post json to other page that downloads the file.

I manage to login go to the download page and press the button but any idea how to fetch the file of the jQuery json call when pressing the button?

**Comment by gsouf** [comment]
I never tryed so I have no idea for the moment. I guess that it goes in the download directory configured in chrome if automatic download is enabled.

**Comment by woodsbox** [comment]
Oeh, so there is a download directory, my next question then will be do you know the download dir?

**Comment by woodsbox** [comment]
So I'm almost there, when executing this script from the console in chrome it works:
Only chrome-php doesn't execute or wait on: xhr.onreadystatechange any tips?

`$page->evaluate(
'(() => {
	xhr = new XMLHttpRequest();
	var url = "url";
	xhr.open("POST", url, true);
	xhr.setRequestHeader("Content-type", "application/json");
	xhr.onreadystatechange = function () { 
    		if (xhr.readyState == 4 && xhr.status == 200) {
    		    		document.querySelector("#input").value = xhr.responseText;
    		}
	}
	var data = JSON.stringify({"var1":"2"});
	xhr.send(data);
    })()'
 );
`

**Comment by woodsbox** [comment]
By changing: xhr.open("POST", url, true); to xhr.open("POST", url, false); it works!
