### ISSUE TITLE
Get content of page after ajax request

### ISSUE THREAD

**Issue by ugozhaev** [chrome-php/headless-chromium-php#172]
Good day.
```php
$evaluation = $page->evaluate(
    '(() => {
        document.querySelectorAll("table a")[11].click();
    })()'
);
```
This code activates a function that runs Ajax. I see rendered content, but $page not changes. It contains only html before request. How to get all new html?

**Comment by thanhtoan1196** [comment]
any updates?

**Comment by enricodias** [comment]
Both the `Page::getHtml()` and `Page::dom()` should be able to get the current html. Note that after the click, you may need to wait until the page actually gets updated.

**Comment by jupitern** [comment]
Hi,
I have the same issue. after a click in a next page button that updates dom with ajax request the live bellow sill contain previous page dom:
$html = $this->page->dom()->getHTML();
I added a sleep(5) but not event that resolves the question.
