### ISSUE TITLE
For PHP 7.4 the 'wrench/wrench' version need to be upgraded. 

### ISSUE THREAD

**Issue by wasuint** [chrome-php/headless-chromium-php#174]
Version 0.8.1 of chrome-php/chrome uses library `"wrench/wrench": "^2.0"`

This library version uses a depricated `implode()`
`PHP 7.4: Deprecated: implode(): Passing glue string after array is deprecated.`
see https://github.com/varspool/Wrench/blob/master/lib/Protocol/Protocol.php

Can the version of `wrench/wrench` be upgraded to a higher version, please?

**Comment by GrahamCampbell** [comment]
This issue is not present in `v2.0.11`.
