### ISSUE TITLE
Fonts not loading on screen capture

### ISSUE THREAD

**Issue by reiven93** [chrome-php/headless-chromium-php#175]
Tryed with google-chrome and chromium-browser packages on Ubuntu 16 and neither load fonts right.

This is the init configuration I've chosen
`$browserFactory = new BrowserFactory('chromium-browser');
$browser = $browserFactory->createBrowser([
'windowSize' => [$style->formato->width, $style->formato->height],
'enableImages' => true,
'ignoreCertificateErrors' => true,
'customFlags' => ['--font-render-hinting=max'] // medium, none, slight are not working too
]);`
Fonts like Comic Sans and chrome/firefox supported are not loading, instead it loads the default one. HTML to capture is working fine, it loads the fonts.

**Comment by blkhawk** [comment]
I have the same issue but I think I know why it is happening for me - the server instance simply doesn't have the fonts. 
That means chromium cannot use them.

**Comment by GrahamCampbell** [comment]
Try upgrading to 0.9.* and removing the custom flags.
