### ISSUE TITLE
Can't send special key press like enter, del...

### ISSUE THREAD

**Issue by Entretoize** [chrome-php/headless-chromium-php#176]
I'm sending "normal" key with that code:

```
$page->getSession()->sendMessageSync(new HeadlessChromium\Communication\Message('Input.dispatchKeyEvent', [
					'type' => 'char',
					'text' => $char,
					]));
```

And it works but if I try to send the enter (return) key like that:

```
$page->getSession()->sendMessageSync(new HeadlessChromium\Communication\Message('Input.dispatchKeyEvent', [
					'type' => 'char',
					'text' => '\r',
					]));
```

It just print "\r" in the input field.

I tried that:
```

					$code=sprintf("U+%04d",13);
					
					//print "<br>vkey ".$code;
					$page->getSession()->sendMessageSync(new HeadlessChromium\Communication\Message('Input.dispatchKeyEvent', [
					'keyIdentifier' => $code,
					'type' => 'rawKeyDown', 
					'text' => '\r',
					]));
```

But that does nothing.

**Comment by alex-rsk** [comment]
$params = [
            "type" => "rawKeyDown",
            "windowsVirtualKeyCode" => 13,
            "unmodifiedText" => "\r",
            "text" => "\r"
        ];

**Comment by Entretoize** [comment]
That still doesn't work :-(

**Comment by Entretoize** [comment]
Anything I can check ?

**Comment by alex-rsk** [comment]
> Anything I can check ?

`$params = [
            "type" => "rawKeyDown",
            "windowsVirtualKeyCode" => 13,
            "unmodifiedText" => "\r",
            "text" => "\r"
        ];
        $message        = new Message('Input.dispatchKeyEvent', $params);
        $response       = $this->page->getSession()->sendMessageSync($message, 5000);
        $params['type'] = 'char';
        $message        = new Message('Input.dispatchKeyEvent', $params);
        $response       = $this->page->getSession()->sendMessageSync($message, 5000);
        $params['type'] = 'keyUp';
        $message        = new Message('Input.dispatchKeyEvent', $params);
        $response       = $this->page->getSession()->sendMessageSync($message, 5000);`

**Comment by Entretoize** [comment]
That works, thank you  !

**Comment by alex-rsk** [comment]
You're welcome.)
