### ISSUE TITLE
Interact with Dev Tools?

### ISSUE THREAD

**Issue by agentmarine** [chrome-php/headless-chromium-php#18]
Trying to access the websockets, using a page, so i've got the browser, created the page, and started setting up a websocket Uri, but every time i try and do any thing it just says the connection is closed, and I'm thinking its not connecting to the websocket at all..

 ```
$webSocketUri = 'ws://127.0.0.1:9222/devtools/browser';
            $connection = new Connection($webSocketUri);
            $connection->connect();
            Log::info(dd($connection));
```
```
HeadlessChromium\Communication\Connection {#645
  #strict: true
  #delay: null
  -lastMessageSentTime: null
  #wsClient: HeadlessChromium\Communication\Socket\Wrench {#700
    #client: Wrench\Client {#746
      #uri: "ws://127.0.0.1:9222/devtools/browser/"
      #origin: "http://127.0.0.1"
      #socket: Wrench\Socket\ClientSocket {#748
        #scheme: "tcp"
        #host: "127.0.0.1"
        #port: 9222
        #socket: false
        #context: null
        #connected: false
        #name: null
        #options: array:5 [
          "protocol" => Wrench\Protocol\Rfc6455Protocol {#749}
          "timeout_socket" => 5
          "timeout_connect" => 2
          "ssl_verify_peer" => false
          "ssl_allow_self_signed" => true
        ]
        #protocol: Wrench\Protocol\Rfc6455Protocol {#749}
      }
      #headers: []
      #connected: false
      #payloadHandler: Wrench\Payload\PayloadHandler {#750
        #callback: array:2 [
          0 => Wrench\Client {#746}
          1 => "onData"
        ]
        #payload: null
        #options: array:4 [
          "protocol" => Wrench\Protocol\Rfc6455Protocol {#747}
          "socket_class" => "Wrench\Socket\ClientSocket"
          "on_data_callback" => null
          "socket_options" => []
        ]
        #protocol: Wrench\Protocol\Rfc6455Protocol {#747}
      }
      #received: []
      #options: array:4 [
        "protocol" => Wrench\Protocol\Rfc6455Protocol {#747}
        "socket_class" => "Wrench\Socket\ClientSocket"
        "on_data_callback" => null
        "socket_options" => []
      ]
      #protocol: Wrench\Protocol\Rfc6455Protocol {#747}
    }
    #socketId: 2
    #logger: Psr\Log\NullLogger {#690}
  }
  #responseBuffer: []
  #sendSyncDefaultTimeout: 3000
  #sessions: []
  #listeners: []
  #onceListeners: []
  #logger: Psr\Log\NullLogger {#690}
}
```

**Comment by agentmarine** [comment]
So I've been able to interact with chrome dev tools using a tool built into chrome and ran chrome from cli, now im replicating that using your examples and im running into this issue when trying to connect.

`[2018-05-11 15:00:21] local.ERROR: No accept header receieved on handshake response {"exception":"[object] (Wrench\\Exception\\HandshakeException(code: 500): No accept header receieved on handshake response at /Users/dansmacbook/projects/project-scrapper/vendor/wrench/wrench/lib/Wrench/Protocol/Protocol.php:417)`

any thoughts that might be causing this?

**Comment by agentmarine** [comment]
I have actually managed to resolve this, and ended up pulling the connection out of the original objects that were being used.

```
$response = $page->getSession ()->sendMessageSync ( new Message( 'Page.navigate', [ "url" => $url ] ) );
```

**Comment by gsouf** [comment]
Hi @agentmarine 

Sorry for the delay. Yes that's the right way to send messages to an existing page. Be aware that you might have weird behavior by manipulating pages like this and if you have, I encourage you to open an issue so that we can fix it for general usage. 

Finally, if you find yourself in a situation where you use a lot of time the same methods, then  you can also open an issue and we can create a wrapper to simplify the tasks.
