### ISSUE TITLE
Fatal error: Uncaught RuntimeException: Chrome process stopped before startup completed. 

### ISSUE THREAD

**Issue by shahreahang** [chrome-php/headless-chromium-php#181]
Hello,

I'm getting this error :
`
Fatal error: Uncaught RuntimeException: Chrome process stopped before startup completed. Additional info: 'chrome' is not recognized as an internal or external command, operable program or batch file. in C:\xampp\htdocs\chrome-head\vendor\chrome-php\chrome\src\Browser\BrowserProcess.php:379 `

How can i set manual path for chrome browser ?

**Comment by mrgentledolphin** [comment]
$browserFactory = new BrowserFactory('chromium-browser'); // or any chrome version you prefer

**Comment by Djaps27** [comment]
@shahreahang Did you solved problem? I am issuing same thing.

**Comment by enricodias** [comment]
If the command ```chrome``` doesn't work on your machine, you will need to enter the complete path of the chrome binary when creating an instance of ```BrowserFactory```.

If your chrome is in ```/usr/bin/google-chrome``` for example, you need to call ```new BrowserFactory('/usr/bin/google-chrome');```.

In windows the path is probably something like ```C:\Program Files (x86)\Google\Chrome\Application\chrome.exe```.

**Comment by GrahamCampbell** [comment]
Or you can set the environment variable  `CHROME_PATH`, like in the README: https://github.com/chrome-php/headless-chromium-php#using-different-chrome-executable.
