### ISSUE TITLE
Cache busting; cached css resources

### ISSUE THREAD

**Issue by attisan** [chrome-php/headless-chromium-php#187]
While working on PDFs styles I'm getting desperate forcing the chrome to reload or pick up changes. Is there a way to definitely force the cache to be cleared or ignored, like it would be when pressing Control+Shift+R or Shift+F5?

I tried doing 

```
$page = $browser->createPage();
$page->getSession()->sendMessage(new Message('Network.clearBrowserCache'));
```

and

```
$page = $browser->createPage();
$page->getSession()->sendMessage(new Message('Network.setCacheDisabled', ['cacheDisabled' => TRUE]));
```

before but neither worked / had no effect.

**Comment by enricodias** [comment]
I just tested and it seems that ```Network.setCacheDisabled``` is working:

```
$page->navigate('https://refreshyourcache.com/en/cache-test/')->waitForNavigation();
$page->getSession()->sendMessage(new Message('Network.setCacheDisabled', ['cacheDisabled' => TRUE]));
$page->navigate('https://refreshyourcache.com/en/cache-test/')->waitForNavigation();
```

> ![file](https://user-images.githubusercontent.com/32619307/102828308-25651f80-43c3-11eb-8742-f853f6e4b9a8.jpg)

Could you share a more specific example where it doesn't work?
