### ISSUE TITLE
undefined getHtml method

### ISSUE THREAD

**Issue by shivaprasad87** [chrome-php/headless-chromium-php#188]
I need to get the HTML code from a URL, But when I used getHtml() method It's throwing below error
![Screenshot from 2021-01-27 12-15-59](https://user-images.githubusercontent.com/38426537/105953610-75f22b80-6099-11eb-9722-08c1328399df.png)

Fatal error: Uncaught Error: Call to undefined method HeadlessChromium\Page::getHtml()

**Comment by GrahamCampbell** [comment]
This is because that method is not in released code yet. You will need to use `^0.10@dev` to install a version of this package that has that method. Note that there may still be breaking changes made to the 0.10.x line before the release of 0.10.0, in line with semver.

**Comment by shivaprasad87** [comment]
thanks
