### ISSUE TITLE
What are your plans?

### ISSUE THREAD

**Issue by StasToken** [chrome-php/headless-chromium-php#19]
When do you plan to add support for the following features?

1. Possibility to install cookies
2. The ability to read cookies
3. Install user agent 
4. Working through a proxy server?

**Comment by agentmarine** [comment]
I'll just note here, you can read cookies already by evaluating Document.Cookie,  you can also set cookies via Javascript.

**Comment by gsouf** [comment]
Hi @StasToken 

Sorry for the delay, jsut returning from holidays.

All that features can be implemented, I will try to work on those as of the next week.
