### ISSUE TITLE
No easy way to check connection status & status checks don't work correctly

### ISSUE THREAD

**Issue by IMN-MichaelL** [chrome-php/headless-chromium-php#195]
This is a two fold issue. I'm working on a project where a persistent chrome browser is being used for multiple processes. After some issues, I am adding logic to my project to attempt to detect if the connection has been lost. The first issue is that there is no easy way to do this other than using getConnection() on the browser object. From there it seems there are two functions that one can use. isConnected() is the obvious first choice but regardless of the state of the chrome process it always returns true leading me to believe it caches the state or at the very least doesn't do a fresh check. The next option is connect() but that always returns false, this could be due to it thinking the connection is already established. My tests were all conducted right after creating a fresh browser instance then using sleeps to allow me to kill chrome processes before creating a new page.

This finding explains the fact that I never see any BrowserConnectionFailed exceptions, instead I get operation timed out when trying to create a page.

Below are places that are effected by these functions not working correctly:
https://github.com/chrome-php/headless-chromium-php/blob/423d8e60bd1c2612ddc72502891f26f600bca707/src/BrowserFactory.php#L139

https://github.com/chrome-php/headless-chromium-php/blob/423d8e60bd1c2612ddc72502891f26f600bca707/src/BrowserFactory.php#L145

Version in composer: chrome-php/chrome                 0.10.x-dev 423d8e6

**Comment by enricodias** [comment]
This package uses [wrench/wrench](https://github.com/varspool/Wrench) to handle the socket connection. The connection status is updated only after trying to send and receive data from the socket. Have you tried sending any dummy action just to ping the browser before checking the connection?

**Comment by IMN-MichaelL** [comment]
My current solution to the issue of checking the connection status is to establish a connection to the browser instance using the socket info and fsockopen along with feof. It would of preferable if this library would correctly check the connection status.

The problem of course with the connection status being cached is that many places check that status before attempting various tasks. In the event of that connection status being wrong, timeout exceptions are thrown as opposed to connection exceptions. I understand that another library is used for the connection but many places in this library relies upon this false information.
