### ISSUE TITLE
Timeout on Windows?

### ISSUE THREAD

**Issue by rcoenen** [chrome-php/headless-chromium-php#196]
Windows 10 / 64 bit
PHP 7.4.9 (cli) (built: Aug  4 2020 11:51:50) ( NTS Visual C++ 2017 x64 )
Chrome Version 88.0.4324.150 (Official Build) (64-bit)

I have tried this with Chrome/Chrmium/Canary. Same result:
Truned off headless to observe what's happening/

my PHP script opens chrome(/Chromium/Canary) and it's empty
When I close the browser, and immediately opens a new browser but now it says "Chrome I being controlled by test automation software"

Regardless of whether I close the browser or not it always ends with:

( ! ) Fatal error: Uncaught Symfony\Component\Process\Exception\ProcessTimedOutException: The process ""C:/Program Files/chrome-win/chrome.exe" --version" exceeded the timeout of 60 seconds. in C:\wamp64\www\myproject\vendor\symfony\process\Process.php on line 1213

**Comment by enricodias** [comment]
Regardless of the message displayed on chrome, the timeout is expected in this situation. Closing and opening the browser will cut its connection with the php script. The script will try to communicate with the old browser instance and won't get a response since it doesn't exists.
