### ISSUE TITLE
Page navigation timeout is not parametrized

### ISSUE THREAD

**Issue by vertexvaar** [chrome-php/headless-chromium-php#20]
Hello there :wave: 

thank you for this cool package in advance, i'm using it to access information from sites which do not offer APIs and it is a very helpful tool.

On of the things i require to be able is to set the timeout when calling `\HeadlessChromium\Page::navigate`.
Currently there is no parameter, therefor `\HeadlessChromium\Communication\Connection::$sendSyncDefaultTimeout` will be used which can't be set and is hardcoded to 3 seconds. When downloading files from some pages the download might take longer than 3 seconds (because the file is big/needs to be generated by the server first) and `$page->navigate($downloadUrl);` will throw an exception.

I will provide a non-breaking pull request shortly and i'd be glad if you could merge it into your awesome lib :slightly_smiling_face:

**Comment by vertexvaar** [comment]
Hi @gsouf 

i'm passing the timeout to 
`Session::sendMessageSync` which passes it to `SessionResponseReader::waitForResponse` and is used instead of the default timout defined in Connection::$sendSyncDefaultTimeout
Please see https://github.com/chrome-php/headless-chromium-php/blob/7c227270f76d8605b585e212f4954e5c7e428afd/src/Communication/Session.php#L78
for the exact location where the provided timout will override the default value.

Prior to the change there is no possibility to define a timout for `$page->navigate()`, because it is neither parametrized nor configurable in the session.

I am currently running the app with my changes and it solves the problem :slightly_smiling_face:

**Comment by gsouf** [comment]
Hi @vertexvaar 

Ok, so if it fix I will provide a different way to fix it. The reason is that it makes it complexe to have to deal with timeout in both of ``navigate`` and ``waitForNavigation`` methods.

**Comment by gsouf** [comment]
As of version ``0.2.0`` the timeout passed in ``$page->navigate($url)->waitForResponse($timeout)`` is global.

@vertexvaar feel free to give a feedback in case it does not fix your issue.
