### ISSUE TITLE
Fatal error</b>:  Uncaught TypeError: implode(): Argument #2 ($array) must be of type ?array, string given in C:\xampp\htdocs\chrome\vendor\wrench\wrench\lib\Wrench\Protocol\Protocol.php:316

### ISSUE THREAD

**Issue by yellowmoon01** [chrome-php/headless-chromium-php#200]
> require __DIR__ . '/vendor/autoload.php';
>use HeadlessChromium\BrowserFactory;
>$browserFactory = new BrowserFactory('C:\Program Files\Google\Chrome\Application\chrome.exe');
>$browser = $browserFactory->createBrowser();
>try {
>$page = $browser->createPage();
>$page->navigate('https://www.google.com')->waitForNavigation();
>$pageTitle = $page->evaluate('document.title')->getReturnValue();
>$page->screenshot()->saveToFile('/foo/bar.png');
>$page->pdf(['printBackground' => false])->saveToFile('/foo/bar.pdf');
>} finally {
>$browser->close();
>}
>echo $pageTitle;

  | <br />
  | <b>Fatal error</b>:  Uncaught TypeError: implode(): Argument #2 ($array) must be of type ?array, string given in C:\xampp\htdocs\chrome\vendor\wrench\wrench\lib\Wrench\Protocol\Protocol.php:316
  | Stack trace:
  | #0 C:\xampp\htdocs\chrome\vendor\wrench\wrench\lib\Wrench\Protocol\Protocol.php(316): implode(Array, '\r\n')
  | #1 C:\xampp\htdocs\chrome\vendor\wrench\wrench\lib\Wrench\Client.php(233): Wrench\Protocol\Protocol-&gt;getRequestHandshake('ws://127.0.0.1:...', 'zJe3bqeiMHxgsyt...', 'http://127.0.0....', Array)
  | #2 C:\xampp\htdocs\chrome\vendor\chrome-php\chrome\src\Communication\Socket\Wrench.php(97): Wrench\Client-&gt;connect()
  | #3 C:\xampp\htdocs\chrome\vendor\chrome-php\chrome\src\Communication\Connection.php(156): HeadlessChromium\Communication\Socket\Wrench-&gt;connect()
  | #4 C:\xampp\htdocs\chrome\vendor\chrome-php\chrome\src\Browser\BrowserProcess.php(144): HeadlessChromium\Communication\Connection-&gt;connect()
  | #5 C:\xampp\htdocs\chrome\vendor\chrome-php\chrome\src\BrowserFactory.php(73): HeadlessChromium\Browser\BrowserProcess-&gt;start('C:\\Program File...', Array)
  | #6 C:\xampp\htdocs\chrome\index.php(9): HeadlessChromium\BrowserFactory-&gt;createBrowser()
  | #7 {main}
  | thrown in <b>C:\xampp\htdocs\chrome\vendor\wrench\wrench\lib\Wrench\Protocol\Protocol.php</b> on line <b>316</b><br />
  |

**Comment by enricodias** [comment]
I'm assuming you are using php8. The Wrench version currently used by this lib (v2.0.1) uses the old signature in the `implode()` function, passing the separator after the array, which was deprecated in php7.4 and no longer supported in php8.

This issue was fixed by the vendor in [this PR](https://github.com/varspool/Wrench/pull/124) and released in version v3.0.0-rc1. I ran the tests using this release candidate but 2 tests failed.

I recommend using php7.4 until we fix this.

**Comment by GrahamCampbell** [comment]
This will be fixed in the v1.0.0 release of this package. We're switching to an in-house version of wrench. https://github.com/chrome-php/wrench with all these issues fixed and full PHP 8 support. :)

**Comment by divinity76** [comment]
seems if people are missing php-socket, composer will install wrench\wrench instead of chrome-php\wrench and run into this issue even in 2024

**Comment by timint** [comment]
*Bump*

Just installed, and got:

`Fatal error: Uncaught TypeError: implode(): Argument #2 ($array) must be of type ?array, string given in ~\vendor\wrench\wrench\lib\Wrench\Protocol\Protocol.php:316`

How can I get around it? I have php_sockets enabled.

**Comment by divinity76** [comment]
@timint try running `composer require "chrome-php/chrome:>=1.11"`  , what do you get?

**Comment by timint** [comment]
Sorry I moved on to a single run command instead:

```
    $command = implode(' ', [
      escapeshellarg('..\\chrome-win\\chrome.exe'),
      '--headless=old',
      '--incognito',
      '--disable-gpu',
      '--print-to-pdf='. escapeshellarg($file),
      '--no-pdf-header-footer',
      '--remote-allow-origins=*',
      escapeshellarg($url),
    ]);

    exec($command, $output, $result);
```
