### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Symfony\Component\Process\Process'

### ISSUE THREAD

**Issue by flameblue59** [chrome-php/headless-chromium-php#205]
Hi, I am using your native code from the library. However, it went in error.

`Fatal error: Uncaught Error: Class 'Symfony\Component\Process\Process' not found in /opt/lampp/htdocs/vendor/chrome-php/chrome/src/Browser/BrowserProcess.php:123 Stack trace: #0 /opt/lampp/htdocs/vendor/chrome-php/chrome/src/BrowserFactory.php(73): HeadlessChromium\Browser\BrowserProcess->start('chrome', Array) #1 /opt/lampp/htdocs/curl.php(37): HeadlessChromium\BrowserFactory->createBrowser() #2 {main} thrown in /opt/lampp/htdocs/vendor/chrome-php/chrome/src/Browser/BrowserProcess.php on line 123`

Here is the code

```
use HeadlessChromium\BrowserFactory;
require_once($_SERVER["DOCUMENT_ROOT"].'/vendor/autoload.php');

$browserFactory = new BrowserFactory();

// starts headless chrome
$browser = $browserFactory->createBrowser();

try {
    // creates a new page and navigate to an url
    $page = $browser->createPage();
    $page->navigate('https://google.com')->waitForNavigation();

    // get page title
    $pageTitle = $page->evaluate('document.title')->getReturnValue();

    // screenshot - Say "Cheese"! 😄
    $page->screenshot()->saveToFile('/foo/bar.png');

    // pdf
    $page->pdf(['printBackground' => false])->saveToFile('/foo/bar.pdf');
} finally {
    // bye
    $browser->close();
}
```

Where is the problem anyway?

**Comment by maximgrynykha** [comment]
@flameblue59 I fixed this issue. You got this one because you'll not pass the path to Chrome.exe to work with this library. Try to change code one of the next ways
```php 
$browserFactory = new BrowserFactory('C:\Program Files\Google\Chrome\Application\chrome.exe'); 

// OR (it depends on your environment)

$browserFactory = new BrowserFactory('C:\Program Files (x86)\Google\\Chrome\Application\chrome.exe')
```

**Comment by enricodias** [comment]
This doesn't seem to be an error with the chrome path, but with a missing class.

@flameblue59 did you install the dependencies correctly using composer?

**Comment by maximgrynykha** [comment]
@enricodias actually ````BrowserFactory```` cannot run browser instance on Windows without passing the right path to Chrome.exe. I may assume that $_SERVER["CHROME_PATH"] works well on a Linux environment but with [Windows 10 x64 | OpenServer | PHP 7.4] it not works at all. 

P.S. 

It is my $_SERVER

```shell
Array
(
    [HTTP_HOST] => chromium
    [HTTP_USER_AGENT] => Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0
    [HTTP_ACCEPT] => text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
    [HTTP_ACCEPT_LANGUAGE] => ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3
    [HTTP_ACCEPT_ENCODING] => gzip, deflate
    [HTTP_CONNECTION] => keep-alive
    [HTTP_COOKIE] => notice_behavior=none
    [HTTP_UPGRADE_INSECURE_REQUESTS] => 1
    [HTTP_CACHE_CONTROL] => max-age=0
    [PATH] => c:\openserver\modules\php\PHP_7.4\ext;c:\openserver\modules\php\PHP_7.4\pear;c:\openserver\modules\php\PHP_7.4\pear\bin;c:\openserver\modules\php\PHP_7.4;c:\openserver\modules\wget\bin;c:\openserver\modules\database\MariaDB-10.3\bin;c:\openserver\modules\http\Apache_2.4-PHP_7.0-7.1\bin;c:\openserver\modules\http\Apache_2.4-PHP_7.0-7.1;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\system32\Wbem;C:\WINDOWS\SysWOW64
    [SystemRoot] => C:\WINDOWS
    [COMSPEC] => C:\WINDOWS\system32\cmd.exe
    [PATHEXT] => .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
    [WINDIR] => C:\WINDOWS
    [SERVER_SIGNATURE] => 
    [SERVER_SOFTWARE] => Apache
    [SERVER_NAME] => chromium
    [SERVER_ADDR] => 127.0.0.1
    [SERVER_PORT] => 80
    [REMOTE_ADDR] => 127.0.0.1
    [DOCUMENT_ROOT] => C:/OpenServer/domains/chromium
    [REQUEST_SCHEME] => http
    [CONTEXT_PREFIX] => 
    [CONTEXT_DOCUMENT_ROOT] => C:/OpenServer/domains/chromium
    [SERVER_ADMIN] => [no address given]
    [SCRIPT_FILENAME] => C:/OpenServer/domains/chromium/index.php
    [REMOTE_PORT] => 55585
    [GATEWAY_INTERFACE] => CGI/1.1
    [SERVER_PROTOCOL] => HTTP/1.1
    [REQUEST_METHOD] => GET
    [QUERY_STRING] => 
    [REQUEST_URI] => /
    [SCRIPT_NAME] => /index.php
    [PHP_SELF] => /index.php
    [REQUEST_TIME_FLOAT] => 1621424077.871
    [REQUEST_TIME] => 1621424077
    [argv] => Array
        (
        )

    [argc] => 0
)
```

**Comment by maximgrynykha** [comment]
We might bundle this library with chrome.exe (*as a driver) and deliver it like an earlier had made it by the team of [Symfony Panther](https://github.com/symfony/panther) but it hard to say whether it will need to update Chrome.exe too often. 

P.S.

[Symphony Panther](https://github.com/symfony/panther) refused of delivering the browser drivers in a bundle with the library

**Comment by enricodias** [comment]
@ismaxim I know it cannot run without the proper path, I'm just saying that the problem in this issue doesn't seem to be related to the binary path.
