### ISSUE TITLE
Ubuntu Runtime error | Chrome process stopped before startup completed. Additional info: sh: 1: exec: /opt/google/chrome: Permission denied

### ISSUE THREAD

**Issue by sjnlabs2013** [chrome-php/headless-chromium-php#209]
Type: RuntimeException
Message: Chrome process stopped before startup completed. Additional info: sh: 1: exec: /opt/google/chrome: Permission denied

PHP 7.2.34 | Ubuntu 20.04.2 LTS

getting this error
$browserFactory = new BrowserFactory("/opt/google/chrome");

i tried 
"google-chrome"
"/usr/bin/google-chrome"
"/opt/google/chrome/chrome"

**Comment by enricodias** [comment]
Your php process doesn't have the necessary permissions to execute chrome. Check the user executing the php script or the permissions of the `/opt/google/chrome` file.

**Comment by sjnlabs2013** [comment]
php is running as daemon
google chrome is located in /opt/google/chrome but user and group are root :(
theres a .config folder in the home dir
how to do this

**Comment by enricodias** [comment]
This may be related to your issue: https://superuser.com/questions/505870/installing-software-to-usr-opt-needs-permission-to-run-the-software

**Comment by sjnlabs2013** [comment]
:( still didnt work i am using xampp the php is runnign as daemon, i cant change it to my logged in username because the application doesnt work. 
i installed chromium (https://medium.com/smarter-world/how-to-easily-use-chrome-without-installing-it-43929b83e9e1)

**Comment by sjnlabs2013** [comment]
$browserFactory = new BrowserFactory('/usr/bin/google-chrome'):
permission error no longer comes

getting an new error
symbol lookup error: /lib/x86_64-linux-gnu/libcairo.so.2: undefined symbol: FT_Get_Var_Design_Coordinates
