### ISSUE TITLE
Maintainer's Requirement

### ISSUE THREAD

**Issue by josiahking** [chrome-php/headless-chromium-php#210]
What is the requirement to become a maintainer.

**Comment by GrahamCampbell** [comment]
To have been contributing to the repo for a few months, and to have some kind of other open-source presence, so we can be sure of the security of the repo. You're more than welcome to contribute to the repo by fixing issues and reviewing PRs, without having push access to the repo. :)

**Comment by GrahamCampbell** [comment]
If you'd like to chat about the repo, hit me up at `hello at gjcampbell dot co dot uk`.

**Comment by josiahking** [comment]
Alright thanks Graham.
