### ISSUE TITLE
Why I cannot to set timeout on $page->waitForNavigation without any events? 

### ISSUE THREAD

**Issue by ShamanHead** [chrome-php/headless-chromium-php#211]
I have a problem with one page. This page returns that she is loaded, but it's not, and as result I have half of the Page.
That's occurs when I use any of events, such as Page::LOAD and other.

**Comment by enricodias** [comment]
You can set a timeout, but this method requires an event:

https://github.com/chrome-php/headless-chromium-php/blob/423d8e60bd1c2612ddc72502891f26f600bca707/src/PageUtils/PageNavigation.php#L123

Note that a page can load some of its content dynamically with javascript even after the load events.

If you want to just wait a certain time regardless of the events fired, you can use `sleep()` directly in you application.

**Comment by ShamanHead** [comment]
Okay, thank you, I'll try.
