### ISSUE TITLE
Uncaught Error: Call to undefined method HeadlessChromium\Page::getHtml()

### ISSUE THREAD

**Issue by Fluoo** [chrome-php/headless-chromium-php#215]
Hello,

i can take sscreenshot, it works but the function getHtml() doesn't work.

I use chrome-php v0.9.0 and chromium-browser (90.0.4430.72-0ubuntu0.16.04.1)

use HeadlessChromium\BrowserFactory;

$browserFactory = new BrowserFactory('chromium-browser');

// starts headless chrome
$browser = $browserFactory->createBrowser();

try {
    // creates a new page and navigate to an url
    $page = $browser->createPage();
    $page->navigate('https://www.limprimeriegenerale.com')->waitForNavigation();

	$test = $page->getHtml();
	
	echo $test;
} finally {
    // bye
    $browser->close();
}

Regards

**Comment by GrahamCampbell** [comment]
This method doesn't exist in the 0.9.x series.

**Comment by GrahamCampbell** [comment]
See https://github.com/chrome-php/headless-chromium-php/issues/188.
