### ISSUE TITLE
Set window size and viewport size

### ISSUE THREAD

**Issue by stekida** [chrome-php/headless-chromium-php#22]
Hi,

would it be possible to set width (and height or height = fullpage, ...) für die screenshot() function?

best regards
stefan

**Comment by gsouf** [comment]
Hi @stekida 

Does the ["Choose an area" section](https://github.com/chrome-php/headless-chromium-php#make-a-screenshot) helps you to achieve your goal?

**Comment by stekida** [comment]
As I understood the documentation, the area() function allows me to select only one area from the screenshot. But if the screenshot is already too small (All screenshots i can take are only 800px wide), the area() function does not help.

crome headless has a parameter to setthe width of the browser (viewportWidth, viewportHeight), I would expect that I can specify these parameters in the screenshot() function.

**Comment by gsouf** [comment]
Your actual is to grow the width of the widow?

**Comment by stekida** [comment]
yes,

here you find an article with exmaples on how to set the width of the browser

https://medium.com/@dschnr/using-headless-chrome-as-an-automated-screenshot-tool-4b07dffba79a

the same option would be helpfull for the screenshot() function

**Comment by gsouf** [comment]
@stekida 

I will add a way to set the width of the window.

**Comment by stekida** [comment]
@gsouf 

That's great. Tell me if you need a tester :-)

**Comment by gsouf** [comment]
Hi @stekida 
I just release version 0.2.1 that adds ability to set window's width and height + changing the viewport size:

Setting window size at browser creation will set the size for all the pages:

```php
    use \HeadlessChromium\BrowserFactory;
  
    $browserFactory = new BrowserFactory();
    $browser = $browserFactory->createBrowser([
        'windowSize' => [1920, 1080]
    ]);
```

For individual pages you can use chrome's device emulation to change the viewport size without affecting the size of the window:

```php
    $page->setViewportSize(800, 300)
        // "await" will wait for chrome to be resized
       ->await();
```

If you have any issue or question concerning the viewport, you can reopen the issue. If you have any other issues with screenshot or other feature of the library, please feel free to open a new issue.

Thanks for contributing to the library
