### ISSUE TITLE
Use "flatten" mode 

### ISSUE THREAD

**Issue by momala454** [chrome-php/headless-chromium-php#220]
The "non flatten" mode is deprecated and we should switch to flattened :
See here : 
https://vanilla.aslushnikov.com/?Target.attachToTarget

With this mode, requests are sent directly to the target instead of using "Target.sendMessageToTarget"

**Comment by momala454** [comment]
Hello @GrahamCampbell , do you think it's a possible upgrade ? The non flatten may stop working at any time and it looks like without flatten, some things are not possible to do.

**Comment by GrahamCampbell** [comment]
Yes, I think we could do that.

**Comment by momala454** [comment]
Hello, do you plan to implement it soon ?
thanks

**Comment by GrahamCampbell** [comment]
Not personally, no. I'd review a PR to do this, though.

**Comment by momala454** [comment]
i'm working on a pr, don't close
