### ISSUE TITLE
Click on HTML element

### ISSUE THREAD

**Issue by nathnat** [chrome-php/headless-chromium-php#225]
Hello world!
I want to developp maybe a new feature for this wonderful project.
I was thinking that maybe 70% of the time we use this library form fill and submit form. 
I was thinking at a functionality to directly click on a html element in php.
Maybe something like `$page->click('.my-selector');`!
We can add this functionnality with a lot of function like :
- form submit `$page->submitForm('.my-selector');`
- fill input `$page->fillInput('.my-selector', 'some text');`*
- etc.

And maybe with a new object like that `$page->formHandler->fillInput('.my-selector');`

And maybe after do a whole html support with node, etc.

Thanks for reading this!
(and sorry for my bad english)

**Comment by FelipeAzambuja** [comment]
i install and use jquery for form handle

**Comment by enricodias** [comment]
This can be done with javascript directly, but it wouldn't look like a normal user behavior. It could even select inputs that are hidden behind other elements and not supposed to be selected by the user.

I was thinking about implementing a mechanism to find the coordinates of the html elements and use the actual mouse to click in that position.

**Comment by nathnat** [comment]
Yeah that's a really good idea! Maybe get the coordinates in javascript the click ?

**Comment by enricodias** [comment]
I don't know of any other way of getting the coordinates without javascript. It's also unlikely that a real user would click in the exact edge of an element every time, so it would be nice if we add a little variation to it.

**Comment by nathnat** [comment]
Yes your right but you also have to get the width and the height then.

**Comment by enricodias** [comment]
Implemented in #239
