### ISSUE TITLE
Implode Error line 316 | Copied code directly from example

### ISSUE THREAD

**Issue by zackattack1029** [chrome-php/headless-chromium-php#226]
Fatal error: Uncaught TypeError: implode(): Argument #2 ($array) must be of type ?array, string given in C:\xampp\htdocs\html\kw2\vendor\wrench\wrench\lib\Wrench\Protocol\Protocol.php:316 Stack trace: #0 C:\xampp\htdocs\html\kw2\vendor\wrench\wrench\lib\Wrench\Protocol\Protocol.php(316): implode(Array, '\r\n') #1 C:\xampp\htdocs\html\kw2\vendor\wrench\wrench\lib\Wrench\Client.php(233): Wrench\Protocol\Protocol->getRequestHandshake('ws://127.0.0.1:...', 'sXANwRWYFCFEciw...', 'http://127.0.0....', Array) #2 C:\xampp\htdocs\html\kw2\vendor\chrome-php\chrome\src\Communication\Socket\Wrench.php(99): Wrench\Client->connect() #3 C:\xampp\htdocs\html\kw2\vendor\chrome-php\chrome\src\Communication\Connection.php(163): HeadlessChromium\Communication\Socket\Wrench->connect() #4 C:\xampp\htdocs\html\kw2\vendor\chrome-php\chrome\src\Browser\BrowserProcess.php(146): HeadlessChromium\Communication\Connection->connect() #5 C:\xampp\htdocs\html\kw2\vendor\chrome-php\chrome\src\BrowserFactory.php(71): HeadlessChromium\Browser\BrowserProcess->start('C:\\Program File...', Array) #6 C:\xampp\htdocs\html\kw2\src\dompdf.php(70): HeadlessChromium\BrowserFactory->createBrowser() #7 {main} thrown in C:\xampp\htdocs\html\kw2\vendor\wrench\wrench\lib\Wrench\Protocol\Protocol.php on line 316

use HeadlessChromium\BrowserFactory;

_______________________

Windows 10
PHP Version 8.0.0

```
$browserFactory = new BrowserFactory();
$browser = $browserFactory->createBrowser();

try {
    // creates a new page and navigate to an url
    $page = $browser->createPage();
    $page->navigate('https://google.com')->waitForNavigation();

    // get page title
    $pageTitle = $page->evaluate('document.title')->getReturnValue();

    // screenshot - Say "Cheese"! 😄
    $page->screenshot()->saveToFile('/foo/bar.png');

    // pdf
    $page->pdf(['printBackground' => false])->saveToFile('bar.pdf');
} finally {
    // bye
    $browser->close();
}
```

**Comment by enricodias** [comment]
See #200
