### ISSUE TITLE
Send Key-Combinations like CTRL+ALT+A

### ISSUE THREAD

**Issue by kadrim** [chrome-php/headless-chromium-php#231]
Hi there,

i tried many with with sending messages (without using the Keyboard-API) but i still don't know how to send Keystroke-Combinations like CTRL+ALT+A.

Any hints?

Best regards

**Comment by enricodias** [comment]
That's something we should support in the keyboard api. Have you tried to send each key with a `typeRawKey()` sequentially? This method just sends a key down event, not the key up.

**Comment by kadrim** [comment]
yep, did try that.

Background: i want to open menus within google-sheets using the keyboard, like "CTRL+f" to open the file-menu.

Currently my only workaround is to use the mouse-api but that i think this should be possible via keyboard.

**Comment by enricodias** [comment]
Maybe the key up event is being triggered automatically, then. I think we need to send multiple key down events before any key up. I'll try to take a look at this in the weekend.

**Comment by enricodias** [comment]
It ended up taking me 2 weekends to do it. Check if #236 solves your issue.

**Comment by kadrim** [comment]
Thanks alot for your effort!

The patch works flawlessly! Now i can automate my google-sheet downloads without relying on the mouse =)
