### ISSUE TITLE
Make it really persistent

### ISSUE THREAD

**Issue by Entretoize** [chrome-php/headless-chromium-php#233]
As reported in several threads, chrome process is kill by the symfony Process class, can you just add the code as suggested by ttk [here](https://github.com/symfony/symfony/issues/7237#issuecomment-583181010) ?

**Comment by GrahamCampbell** [comment]
The code suggested there looks like a bad idea. Something like https://github.com/laravel/octane/pull/182 is probably the better approach. Please feel free to send a PR, and I'll take a look.

**Comment by GrahamCampbell** [comment]
This is already supported. You should use the `keepAlive` option: https://github.com/chrome-php/chrome#options.

As of v0.11.0, we no longer check the chrome binary version, so issues with duplicate processes should be now resolved.
