### ISSUE TITLE
Socket is not connected

### ISSUE THREAD

**Issue by JailsonS** [chrome-php/headless-chromium-php#235]
Hello, 

I am using PHP 7.4.16 with this lib to iterate urls but I am getting the following error:

PHP Fatal error:  Uncaught Wrench\Exception\SocketException: Socket is not connected in C:\Dev\php\web-scrapping\vendor\wrench\wrench\lib\Wrench\Socket\Socket.php:248

`
try {

    $toBeChecked = [];
    foreach($links as $link) {
    
        $page = $browser->createPage();
        $page->navigate($link)->waitForNavigation();
    
        $c = $page->evaluate("document.querySelectorAll('p').length")->getReturnValue();
    
        for($i = 0; $i < $c; $i++) {
            $txt = $page->evaluate("document.querySelectorAll('p')[$i].textContent")->getReturnValue();
            $toBeChecked[$link] = $txt;
        }
    }
    
    print_r($toBeChecked);

} finally {
    // bye
    $browser->close();
}

`

Could someone help me ?

**Comment by enricodias** [comment]
Are you using the new [0.11](https://github.com/chrome-php/chrome/releases/tag/v0.11.0) version? It uses a fork of Wrench that solved some issues.

**Comment by GrahamCampbell** [comment]
0.11 does not actually use the fork. Version 1.0 will, when it is ready.

**Comment by enricodias** [comment]
Oh, my bad, then. I though it was already implemented in 0.11.
