### ISSUE TITLE
Fatal error: Uncaught RuntimeException: Chrome process stopped before startup completed. Additional info: sh: line 0: exec: google-chrome: not found in

### ISSUE THREAD

**Issue by pedropankaj** [chrome-php/headless-chromium-php#237]
Fatal error: Uncaught RuntimeException: Chrome process stopped before startup completed. Additional info: sh: line 0: exec: google-chrome: not found in

i already installed the google chrome in cpanel but gives me error. please help

**Comment by GrahamCampbell** [comment]
This happens when the chrome binary is not the one we expected. See https://github.com/chrome-php/chrome#using-different-chrome-executable.
