### ISSUE TITLE
Some questions about your project

### ISSUE THREAD

**Issue by StasToken** [chrome-php/headless-chromium-php#24]
1. can I set cookies for any domain? - if so how?
2. Install user agent? - if so how? 
3. Does the current stable version support working via proxy? - if so how? 
4. Getting cookies that have been set by the site? - if so how?

**Comment by gsouf** [comment]
Hi @StasToken you already asked for those question on #19 

None of those features are implemented yet but they are all planed. I cannot give you a date for them to be released.

**Comment by StasToken** [comment]
sorry, I think it's already been earned....
