### ISSUE TITLE
PHP Fatal error:  Uncaught HeadlessChromium\Exception\OperationTimedOut: Operation timed out (30sec) in vendor/chrome-php/chrome/src/Utils.php:71

### ISSUE THREAD

**Issue by Fluoo** [chrome-php/headless-chromium-php#242]
Hello,

I have randomly this error : 

PHP Fatal error:  Uncaught HeadlessChromium\Exception\OperationTimedOut: Operation timed out (30sec) in vendor/chrome-php/chrome/src/Utils.php:71
Stack trace:
#0 vendor/chrome-php/chrome/src/Page.php(387): HeadlessChromium\Utils::tryWithTimeout()
#1test.php(2217): HeadlessChromium\Page->waitForReload()

chrome-php v0.11.0
PHP Version 7.4.21
Chromium 92.0.4515.107 snap

Regards

**Comment by GrahamCampbell** [comment]
I don't understand what this report is asking for us to do? It's saying that your chrome browser didn't reload the page within 30 seconds. This isn't a bug in this code.

**Comment by Fluoo** [comment]
If I understand correctly the problem : 
An exception is thrown by  chrome/src/Utils.php line 71
But the exception isn't catched because you haven't a try in chrome/src/Page.php line 387
And this generate a fatal error in php.

So I think that if you change line 387 to something like that : 
```
try
{
	Utils::tryWithTimeout($timeout * 1000, $this->waitForReloadGenerator($eventName, $loaderId));
}
catch(OperationTimedOut $e)
{
	throw $e;
}
```

**Comment by GrahamCampbell** [comment]
No, that code won't fix it. The fatal error is because **you** didn't catch it. Us catching and re-throwing is the same as not catching it.

**Comment by ShamanHead** [comment]
This problem arise because chrome can't get in time your request. If you use proxies, check it before integrate with chrome. If dont, reopen browser once in certain time. It might help you with your problem.
