### ISSUE TITLE
Is it possible to reproduce something like Venom/Sulla with chrome-php?

### ISSUE THREAD

**Issue by Eskelsen** [chrome-php/headless-chromium-php#244]
They are essentially javascript library for Whatsapp. I have never found anything similar in another language.

Venom:
https://github.com/orkestral/venom

Sulla:
https://github.com/danielcardeenas/sulla

**Comment by enricodias** [comment]
Those libraries interact with Whatsapp using its web interface. You can do something similar with php using chrome-php. It would be like a human interacting with the browser.

**Comment by GrahamCampbell** [comment]
Note that such libraries cannot be used for anything other than personal use, without violating the terms of service of whatsapp. They have a separate API for businesses to use.
