### ISSUE TITLE
How to avoid detection from navigator.webdriver

### ISSUE THREAD

**Issue by foremtehan** [chrome-php/headless-chromium-php#246]
Hello there, Looks like the [navigator.webdriver](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/webdriver) can easily detect chrome drivers, is it possible to set it to false ? there are a [discussion](https://stackoverflow.com/questions/53039551) in stackoverflaw for python but dont know how to aplly those things in your repo

**Comment by foremtehan** [comment]
nevermind i just used the `cusotmFlag` and add those args on that thread

**Comment by steamboatid** [comment]
now,
it's detected by https://bot.sannysoft.com/
