### ISSUE TITLE
[Feature Request] Ignore SSL certificate errors

### ISSUE THREAD

**Issue by ejunker** [chrome-php/headless-chromium-php#249]
When working with a local development environment that may have a self-signed certificate it can be helpful to have a way to ignore SSL certificate errors. Adding a method would be helpful or maybe it is something that just needs to be documented in the README.

```php
$page->getSession()->sendMessageSync(new Message('Security.enable'));
$page->getSession()->sendMessageSync(new Message('Security.setIgnoreCertificateErrors', ['ignore' => true]));
```

**Comment by GrahamCampbell** [comment]
What's the use case for ignoring certificate errors?

**Comment by ejunker** [comment]
My local dev environment has self-signed SSL certs and I have some HTML with images loaded over HTTPS from my dev environment. The images were not loading until I ignored SSL errors.

**Comment by foremtehan** [comment]
did you tried:

```php
$browser = $browserFactory->createBrowser([
                'customFlags' => ['--ignore-certificate-errors'],
            ]);
```

?

**Comment by ejunker** [comment]
I'm fine with closing this issue if you don't think it is a common need. It is something that I ran into and thought other users might also run into the same issue. At least the issue will be here and people can refer to it if needed.

**Comment by ejunker** [comment]
@foremtehan thanks, that also worked for me

**Comment by wlius-support3** [comment]
There is also a method already called: `ignoreCertificateErrors`

It is mentioned in the README
