### ISSUE TITLE
waitForPageReload: Error Executing Test. The operation has timed out

### ISSUE THREAD

**Issue by woodsbox** [chrome-php/headless-chromium-php#25]
Hi,

Since a few days I have a problem with a form that I submit. I now get the error:
Error Executing Test. The operation has timed out

Strange thing before it was working!

$evaluation = $page->evaluate(
'(() => {
	document.querySelector("#username").value = "'.USERNAME.'";
        document.querySelector("#password").value = "'.PASSWORD.'";
        document.querySelector("#submitButton").click();
    })()'
 );

// wait for the page to be reloaded
$evaluation->waitForPageReload();

Any tips or idea's?

**Comment by woodsbox** [comment]
I see the element on my screen, when I inspect it in the HTML I also see it. But when I do: document.documentElement.innerHTML it's not there so chrome can't access it.

**Comment by woodsbox** [comment]
Maybe it has something to do with Shadow..?

**Comment by gsouf** [comment]
My guess is that the problem is related to your page and query selector and not with the library itself
