### ISSUE TITLE
How to work in one Tab ?

### ISSUE THREAD

**Issue by foremtehan** [chrome-php/headless-chromium-php#250]
I tried this example to work in one instanse of browser:

https://github.com/chrome-php/chrome/blob/1.0/examples/persistent-browser.php

but the problem is it opens new tab every time script executed, is it possible to work in one tab ? it stores a lot of memory

**Comment by GrahamCampbell** [comment]
If you only call createPage one, I think this will do what you want?

**Comment by foremtehan** [comment]
Yeah i call the `createPage` once, But for the next execution (i mean execute the script with cronjob) it opens another tab on the same browser

**Comment by GrahamCampbell** [comment]
The persistent browser requires you to keep your PHP instance alive.

**Comment by GrahamCampbell** [comment]
What’s happening here is a new process is being started.

**Comment by codes-begin** [comment]
Hi, Anyone got solutions to this. I want to work in one tab only. My code is creating a new tab everytime. below is my code
        $socketFile = 'tmp';
        $browser = null;
        if (file_exists($socketFile)) {
            $socket = \file_get_contents($socketFile);
            try {
                $browser = \HeadlessChromium\BrowserFactory::connectToBrowser($socket, [
                    'debugLogger' => 'php://stdout',
                ]);
            } catch (\HeadlessChromium\Exception\BrowserConnectionFailed $e) {
                echo "No browser";
            }
        }

        if (!$browser) {
            $factory = new \HeadlessChromium\BrowserFactory();
            $browser = $factory->createBrowser([
                'headless' => false,
                'keepAlive' => true,
            ]);
            file_put_contents($socketFile, $browser->getSocketUri());
        }
        $page = $browser->createPage();
