### ISSUE TITLE
mouse bug

### ISSUE THREAD

**Issue by shawn996** [chrome-php/headless-chromium-php#251]
in mouse.php,line 182-183,width and height is wrong,The correct code is：
        $distanceX = $this->getMaximumDistance($distanceX, $visibleArea['pageX'], $scollableArea['width']);
        $distanceY = $this->getMaximumDistance($distanceY, $visibleArea['pageY'], $scollableArea['height']);

**Comment by enricodias** [comment]
I'll check that latter today.

**Comment by GrahamCampbell** [comment]
Fixed in 0.11.2 and 1.0.1. :)
