### ISSUE TITLE
URL bar is selected when window pops up.

### ISSUE THREAD

**Issue by codes-begin** [chrome-php/headless-chromium-php#254]
When new window pops up, url bar is selected and cursor is at url bar. I would like to place the cursor in captcha box, which I am able to do but when I type it starts typing in url bar. How to change it?

**Comment by enricodias** [comment]
Are you clicking on the input field? Just moving the mouse to it won't work. You need to select the input.

**Comment by codes-begin** [comment]
I am selecting the input but url bar is also selected along with it.
