### ISSUE TITLE
Proxy problem

### ISSUE THREAD

**Issue by t3mnikov** [chrome-php/headless-chromium-php#256]
Hi all!
I use Ubuntu 20.04 / Debian 10 and Tor.
After install Tor I try this:

```
...
$browser = $browserFactory->createBrowser([
    'headless' => true,
    'customFlags' => ["--proxy-server=socks://127.0.0.1:9050", '--timeout 60000'],
    'enableImages' => false,
]);
...
```

After some requests to test domain I`v get an error:

`
Operation timed out (2sec)
`

Why am I getting this error?

**Comment by t3mnikov** [comment]
2 second may be here:
`
ResponseReader::waitForResponse($timeout)
`

But I dont know how to increase this value

**Comment by t3mnikov** [comment]
Tor installed like here:
```
# apt install tor torsocks
```

**Comment by GrahamCampbell** [comment]
This sounds like a question for some forums. I’d like to keep the issue tracker free to track library bugs. :)
