### ISSUE TITLE
auto load file doesn't exist

### ISSUE THREAD

**Issue by mohammad-mahdi-hodayan** [chrome-php/headless-chromium-php#260]
require __DIR__.'/../vendor/autoload.php';

in example folder , but this file and many more files do not exist

**Comment by enricodias** [comment]
You need to install the dependencies using `composer install`.

If you are using this package in your project, you should install it using `composer require chrome-php/chrome`

**Comment by sasanmoradidev** [comment]
@mohammad-mahdi-3341 lotfan ba man tamas begir, ssn.moradi@gmail.com
