### ISSUE TITLE
Uncaught RuntimeException: Chrome process stopped before startup completed.

### ISSUE THREAD

**Issue by proconsult-ti** [chrome-php/headless-chromium-php#261]
I tried to solve this problem but I can't find a solution. I'm getting this issue but without any further information. I activated the suggested debug options but it doesn't make any difference since the error happens in the first line of code.

Error:
Fatal error: Uncaught RuntimeException: Chrome process stopped before startup completed. in D:\manual1\_dev\Assistec\vendor\chrome-php\chrome\src\Browser\BrowserProcess.php:400 Stack trace: #0 D:\manual1\_dev\Assistec\vendor\chrome-php\chrome\src\Utils.php(57): HeadlessChromium\Browser\BrowserProcess->HeadlessChromium\Browser\{closure}(Object(Symfony\Component\Process\Process)) #1 D:\manual1\_dev\Assistec\vendor\chrome-php\chrome\src\Browser\BrowserProcess.php(437): HeadlessChromium\Utils::tryWithTimeout(30000000, Object(Generator)) #2 D:\manual1\_dev\Assistec\vendor\chrome-php\chrome\src\Browser\BrowserProcess.php(139): HeadlessChromium\Browser\BrowserProcess->waitForStartup(Object(Symfony\Component\Process\Process), 30000000) #3 D:\manual1\_dev\Assistec\vendor\chrome-php\chrome\src\BrowserFactory.php(67): HeadlessChromium\Browser\BrowserProcess->start('C:\\Program File...', Array) #4 D:\manual1\_dev\Assistec\services\TicketDownloadService.php(278): HeadlessChromium\BrowserFactory->createBrowser(Array) #5 D:\manual1\_dev in D:\manual1\_dev\Assistec\vendor\chrome-php\chrome\src\Browser\BrowserProcess.php on line 400

**Comment by enricodias** [comment]
If you remove the headless option in the options, can you see the chrome window appear during the execution? And can you paste the debug output here?

The debug info isn't displayed in a page, it's sent to the terminal.

**Comment by proconsult-ti** [comment]
About the debug information it is simply not being generated. I'm using Monolog and in the version of my local machine, the logs are generated normally, but in this version that is giving an error, nothing is generated... apparently it doesn't even reach the "browserFactory->createBrowser(['debugLogger' => monologInstance] )".

About the headless option I'll check it tomorrow as it's a machine that I don't have direct access to, but I'm afraid it will fall into the same problem as the debug.

My code:
```php
$log = new Logger("chrome_php");
$logPath = __DIR__ . "/../logs/chrome_php.log";
$log->pushHandler(new StreamHandler($logPath));

$browserFactory = new BrowserFactory(); // seems to stop here
$browser = $browserFactory->createBrowser([
    'headless' => false,
    'debugLogger' => $log
]);
try {
    $page = $browser->createPage();
    $pdfOptions = [ 'printBackground' => true ];
    // stuff
    $page->navigate($url)->waitForNavigation(Page::DOM_CONTENT_LOADED);
    $page->pdf($pdfOptions)->saveToFile($output);
} catch (Exception $e) {
    $response['error'] = "Exception on Chrome-php: " . $e->getMessage();
} finally {
    $browser->close();
}
```

**Comment by proconsult-ti** [comment]
Here is the generated log:
[2021-09-28T08:12:10.717276-03:00] chrome_php.DEBUG: process: initializing [] []
[2021-09-28T08:12:10.730863-03:00] chrome_php.DEBUG: process: using directory: C:\Windows\Temp\chr5A3C.tmp [] []
[2021-09-28T08:12:10.738759-03:00] chrome_php.DEBUG: process: starting process: "C:\Program Files\Google\Chrome\Application\chrome.exe" --remote-debugging-port=0 --disable-background-networking --disable-background-timer-throttling --disable-client-side-phishing-detection --disable-default-apps --disable-extensions --disable-hang-monitor --disable-popup-blocking --disable-prompt-on-repost --disable-sync --disable-translate --metrics-recording-only --no-first-run --safebrowsing-disable-auto-update --enable-automation --password-store=basic --use-mock-keychain --headless --disable-gpu --font-render-hinting=none --hide-scrollbars --mute-audio --user-data-dir=C:\Windows\Temp\chr5A3C.tmp [] []
[2021-09-28T08:12:10.755276-03:00] chrome_php.DEBUG: process: waiting for 30 seconds for startup [] []
[2021-09-28T08:12:10.776049-03:00] chrome_php.DEBUG: process: ✗ chrome process stopped [] []
[2021-09-28T08:12:10.785035-03:00] chrome_php.DEBUG: process: killing chrome [] []
[2021-09-28T08:12:10.785091-03:00] chrome_php.DEBUG: process: cleaning temporary resources:C:\Windows\Temp\chr5A3C.tmp [] []

I tried using the connectionDelay and noSandbox options, but they did the same thing. The browser also doesn't seem to be opening with headless as false.
I think I will have to switch to MPDF.

**Comment by enricodias** [comment]
Your chrome is just stopping shortly after starting.

What happens if you try to execute `C:\Program Files\Google\Chrome\Application\chrome.exe" --remote-debugging-port=0 --disable-background-networking --disable-background-timer-throttling --disable-client-side-phishing-detection --disable-default-apps --disable-extensions --disable-hang-monitor --disable-popup-blocking --disable-prompt-on-repost --disable-sync --disable-translate --metrics-recording-only --no-first-run --safebrowsing-disable-auto-update --enable-automation --password-store=basic --use-mock-keychain --disable-gpu --font-render-hinting=none --hide-scrollbars --mute-audio --user-data-dir=C:\Windows\Temp\chr5A3C.tmp` manually? (I removed the `--headless` option.

**Comment by proconsult-ti** [comment]
Running your command opens chrome normally.
At this point I don't know if this has something with the PHP script running on a Windows server with IIS and for some reason it's being blocked

**Comment by proconsult-ti** [comment]
Unfortunately I couldn't make it work through chrome-php and decided to make a separate script via command line with chrome. Thanks for trying to help
