### ISSUE TITLE
Message could not be sent. Reason: the connection is closed.

### ISSUE THREAD

**Issue by chuoke** [chrome-php/headless-chromium-php#262]
See detail of the error [https://flareapp.io/share/47qGRjEm#F51](https://flareapp.io/share/47qGRjEm#F51)

the error shows me:
` Message could not be sent. Reason: the connection is closed. `

But through the output of the logger, I found that it was still running.

**Comment by enricodias** [comment]
I see that you are trying to inject a custom `Connection` to the `Browser` and the very first `sendMessageSync` is failing. The issue is the connection.

The `the connection is closed` reason only happens if `wsClient->isConnected()` returns false.

**Comment by chuoke** [comment]
I added judgment `$connection->isConnected()` before inject. The error was gone, but some unknown error caused the program to terminate, and I found that the browser continued to execute the command.

Maybe I make something wrong.
