### ISSUE TITLE
Wait for 'download completed' missing

### ISSUE THREAD

**Issue by CWBudde** [chrome-php/headless-chromium-php#264]
At the moment, there is no callback or blocking function or whatsoever to wait until a download is complete.  At least
```
...->waitForNavigation();
```
seems to timeout as there is no real navigation at all. The download is triggered as a background process.

I'm not sure whether this can be solved by the headless chrome process at all (see #258), but it would be quite useful.

**Comment by octoper** [comment]
Have you tried calling?
```
...->waitForNavigation('networkidle2');
```

**Comment by ResetButton** [comment]
> Have you tried calling?
> 
> ```
> ...->waitForNavigation('networkidle2');
> ```

not working without networkidle, networkidle2, networkidle0

**Comment by nocodelab** [comment]
Hello guys? Did anyone succeeded intercepting the event of download completed?
I am experiencing the same issue. File is downloaded correctly but the script goes timeout.
