### ISSUE TITLE
How open OS browser (windows) ?

### ISSUE THREAD

**Issue by foremtehan** [chrome-php/headless-chromium-php#266]
I want to open my own browser in window:

```php
$browserFactory = new BrowserFactory("C:\Program Files (x86)\Google\Chrome\Application\chrome.exe");

$browser = $browserFactory->createBrowser([
    'headless' => false,
]);
```

The problem is, it opens new raw browser not my existing browser all of my extension will gone.

**Comment by enricodias** [comment]
The browser is the same, but an empty new profile is used if you don't specify any.

https://github.com/chrome-php/chrome/blob/ce6ceb5cb556cdbc1792b5d30e1506ab7c6a406a/src/BrowserFactory.php#L48
