### ISSUE TITLE
Download file as Resource ?

### ISSUE THREAD

**Issue by foremtehan** [chrome-php/headless-chromium-php#267]
I want to download file similar to `file_put_contents` in php.

```php
$page->evaluate('document.querySelector("#downloadButton").click()')->getReturnValue();
```

The problem is, it downloads the file but nothings will return, I want to know the downloaded filename etc....

Is it possible to download the file as resource and save it via php ?

**Comment by enricodias** [comment]
The browser won't return a php resource, but it should be possible to detect when a download starts and get its url and the requested headers. That way it would be possible to request the file again using the native php functions.

**Comment by j-applese3d** [comment]
My suggestion is to set the download directory using `Browser.setDownloadBehavior`
Then after clicking the download button, check the directory you set for the downloaded file.

Ex:
1. Add this function to \HeadlessChromium\Page :  *(You can probably call all these methods without modifying the class, so that's probably a better idea)*
```php
public function setDownloadBehavior(string $path = '/tmp/download.from.chrome')
{
    $this->assertNotClosed();

    $currentLoaderId = $this->frameManager->getMainFrame()->getLatestLoaderId();
    $reader = $this->getSession()->sendMessage(
        new Message(
            'Browser.setDownloadBehavior',
            [
                'behavior' => 'allow',
                'downloadPath' => $path,
                'eventsEnabled' => false,
            ]
        )
    );
    return new PageEvaluation($reader, $currentLoaderId, $this);
}
```
2. Use it
```php
$dir = tempnam('/tmp', 'headless-download');
$page->setDownloadBehavior($dir);
$page->evaluate('document.querySelector("#downloadButton").click()')->getReturnValue();
// check the directory for any files
$files = glob($dir . '/*');
// do something with the downloaded files. read into a resource, move, etc.
```

**Comment by enricodias** [comment]
@j-applese3d This workaround would only work if you really need the entire file stored locally and can wait for the download to finish. If you need the resource to, for example, read and relay the data to a user in real time, you can't. Fetching a partial file would not be possible either.
