### ISSUE TITLE
How to get console logs ?

### ISSUE THREAD

**Issue by Entretoize** [chrome-php/headless-chromium-php#268]
I have an issue with a website that seems not to load xhr request properly but I can't see any error, maybe there's something on the javscript console but is there a way to see it ?

**Comment by enricodias** [comment]
The logger outputs the logs directly in the terminal when the debug is enabled. You can also start the browser without the `headless` flag and inspect its console manually using the gui,

**Comment by j-applese3d** [comment]
Use the `debugLogger` option when calling `BrowserFactor->createBrowswer()`
Ex:
```php
$myPsr3Logger = new Psr3Logger(); // needs to implement this interface: https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-3-logger-interface.md
$browserFactory = new \HeadlessChromium\BrowserFactory('google-chrome');
$browser = $browserFactory->createBrowser(['debugLogger' => $myPsr3Logger]);
// ...
```

It'll be quite verbose if you output everything, but you should find any console exceptions / errors in there.

**Comment by Entretoize** [comment]
Enricodias I don't know how to run my script from a terminal and interact with the browser or I'm missing something, also I never achieved to make it work without the headless flag.

j-applses3d I don't understand how to implement that interface, also I'm not sure it can work as this is a varaible passed to the browserfactory and my script is ran several times with the save keepalive session, then I would need to log even between script calls.

**Comment by enricodias** [comment]
You can set the `headless` flag as `false` in the options: https://github.com/chrome-php/chrome/blob/a564e1e92d414a412c9f1b63957559290bd21fc0/src/BrowserFactory.php#L40

The logger can be any psr3 logger. You can use one that writes the logs to a file, for example.
