### ISSUE TITLE
Mouse element position aways the last

### ISSUE THREAD

**Issue by danilocolasso** [chrome-php/headless-chromium-php#270]
When selecting an element `->find('some-query-selector', 2)`, the 2nd param `$position` is always being replaced by `\max(0, (\count($elementList) - 1));`.

Mouse.php:273

**Comment by enricodias** [comment]
It is indeed. The intention was to limit the `$position` to the number of elements found. I'll fix it and update the tests to cover this case.

**Comment by danilocolasso** [comment]
Can you please release a minor version?
