### ISSUE TITLE
Multiple instances of the chrome browser?

### ISSUE THREAD

**Issue by AndriusCTR** [chrome-php/headless-chromium-php#273]
Is it possible to run multiple instances (not tabs) of headless chrome browser at the same time? 

Ubuntu Server

**Comment by enricodias** [comment]
It is, as far as I know. Did you have any problems spawning 2 different processes?

**Comment by AndriusCTR** [comment]
I had some issues with other library because port was closed on second and other tries, so had to do some random port assigning. Wonder if it's different here or not. Thanks.
