### ISSUE TITLE
Print to PDF - specify pages?

### ISSUE THREAD

**Issue by AndriusCTR** [chrome-php/headless-chromium-php#275]
Is there a way to specify which pdf pages should be created? E.g. if I only want to print first page (so that pdf file would have first page only), how can I do that?

Chrome supports 'pageRanges' option, but not sure if that's implemented here? Tried that, but it didn't work

https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-printToPDF

**Comment by enricodias** [comment]
`pageRanges` is really not implemented in the `Page::pdf()` method. I'll do a rework on this method and implement some missing options, including this one.

**Comment by AndriusCTR** [comment]
Thanks. I think this is one of the more important/common options (the same way people quite often use page ranges when printing to pdf with regular Chrome on their computers)

**Comment by GrahamCampbell** [comment]
What page range(s) were you specifically hoping for?

**Comment by AndriusCTR** [comment]
> What page range(s) were you specifically hoping for?

"if I only want to print first page (so that pdf file would have first page only), how can I do that?"

**Comment by enricodias** [comment]
Implemented in #283
