### ISSUE TITLE
Move JavaScript snippets in code from simple single quoted string to Nowdoc

### ISSUE THREAD

**Issue by octoper** [chrome-php/headless-chromium-php#277]
It would be nice to that all the strings that contain JavaScript in the project to use Nowdoc syntax instead of a simple single quoted string, this will become useful for some IDE like PhpStorm that will see this snippet as JavaScript and it will highlight it correctly and also it will have some auto-completion.

Example: 
This (found here: [chrome/src/Page.php](https://github.com/chrome-php/chrome/blob/31bc5e66864814372732788d14a66fe9f2e2712f/src/Page.php?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L287-L299))

```php
$scriptFunction = 'async function(src) {
const script = document.createElement("script");
script.type = "text/javascript";
script.src = src;

const promise = new Promise((res, rej) => {
    script.onload = res;
    script.onerror = rej;
});

document.head.appendChild(script);
    await promise;
}';
```
will become 

```php
$scriptFunction = <<<'JS'
(async function(src) {
   const script = document.createElement("script");
   script.type = "text/javascript";
   script.src = src;
   document.querySelector()

   const promise = new Promise((res, rej) => {
       script.onload = res;
       script.onerror = rej;
   });

   document.head.appendChild(script);
   document.head
   await promise;
})
JS;
```

**Comment by maximgrynykha** [comment]
I can do that at future releases just after the current changes for documentation will be approved.
