### ISSUE TITLE
The script can run via CLI but cant run via browser

### ISSUE THREAD

**Issue by ghost** [chrome-php/headless-chromium-php#279]
I facing this problem when I setup the script in Apache and run the script via browser. Although my script can run nicely in cli. 

Anyone know the reason may cause chrome-php can run in cli but fail calling via browser. 

This is the error return when run via browser (Uncaught RuntimeException: Chrome process stopped before startup completed).

**Comment by enricodias** [comment]
How are apache executing the php? Does it have the same permissions as executing via cli and uses the same php.ini?

**Comment by ghost** [comment]
I think my issues same with https://github.com/chrome-php/chrome/issues/261, maybe some reason it's being blocked by Windows server with IIS
