### ISSUE TITLE
Different behavior with headless and headful

### ISSUE THREAD

**Issue by danilocolasso** [chrome-php/headless-chromium-php#280]
Should it happen?
Like, I'm just filling in a field and clicking on submit. But it only work with headful mode :thinking:
Maybe because it have XHR and I kinda "wait" a div appear?

**Comment by enricodias** [comment]
It shouldn't have a difference apart from headful mode being slower. What exactly happens when it doesn't work? Is there any js script in the page that creates the content you are interacting with?

**Comment by danilocolasso** [comment]
No, the js that creates the content runs after my script.
I'm just clicking on the input, filling it with the keyboard emulator and clicking a button.
But aparently it's not happening with headless (debugged getting the html), only headfull.

**Comment by enricodias** [comment]
Maybe there is an `onchange` event on the field that changes something and the headless mode runs too fast for it?
