### ISSUE TITLE
Intermitent delay when using a sleep between navigation and screenshots

### ISSUE THREAD

**Issue by maxiwheat** [chrome-php/headless-chromium-php#281]
php 7.4.25
Google Chrome 95.0.4638.69

I had a hard time finding what was causing a delay when taking screenshots in my script and what I endind up was a combinaison of sleep, setViewport()->await and screenshot saving. Here is a sample script to reproduce the issue:

```
use HeadlessChromium\BrowserFactory;

$browserFactory = new BrowserFactory('google-chrome');

$browser = $browserFactory->createBrowser();
$page = $browser->createPage();

for ($i=0;$i<100;$i++) {
    $page->setViewport(1024, 768)->await();

    $start = microtime(true);
    // Have chrome switch page on each navigation
    if (($i %2) == 0) {
        $page->navigate('https://google.com')->waitForNavigation(Page::LOAD, 10000);
    } else {
        $page->navigate('https://google.ca')->waitForNavigation(Page::LOAD, 10000);
    }

    $elapsed = microtime(true) - $start;
    echo "Navigate took $elapsed seconds\n";

    $screenshot = $page->screenshot([
        'format'  => 'jpeg',  // default to 'png' - possible values: 'png', 'jpeg',
        'quality' => 85, // only if format is 'jpeg' - default 100
        'captureBeyondViewport' => true
    ]);

    $screenshot->saveToFile('/tmp/dummy.png');

    sleep(5);
}
```

Sample output:

> Navigate took 1.4717750549316 seconds
> **Navigate took 5.5982089042664 seconds**
> Navigate took 0.43044400215149 seconds
> Navigate took 0.38882303237915 seconds
> Navigate took 0.37495589256287 seconds
> **Navigate took 5.3471350669861 seconds**
> **Navigate took 5.4216139316559 seconds**
> Navigate took 0.37632298469543 seconds
> **Navigate took 5.4116699695587 seconds**
> Navigate took 0.35712695121765 seconds
> **Navigate took 5.4241268634796 seconds**

If I remove `->await()` or `sleep(5);` from the script, tada! everything is fast (< 0.5 second)

It also looks like the delay is somewhat related to the sleep time, if I lower the sleep to 3 seconds, the navigate delay is also closer to 3 seconds. If I increase it to 7 seconds, then every navigate takes ~5.5 seconds.

I also tried lowering sendSyncDefaultTimeout with `$browser = $browserFactory->createBrowser(['sendSyncDefaultTimeout' => 500]);` but that does not change a thing.

Note that this is a sample script to reproduce the issue, I know I could skip `->await()` if the size is always the same, but that seems strange to me that this is causing such a delay.

**Comment by maxiwheat** [comment]
Nobody able to reproduce/help on this one?

**Comment by enricodias** [comment]
I didn't find the cause yet, but it's probably related to how `Utils::tryWithTimeout()` count the time between sleeps. It may also be related to some tests failing due to timeouts intermittently.

I don't think that calling `\microtime()` is a reliable way to determine how much time has passed because it relies on the server's clock. `\hrtime()` would be better.

**Comment by enricodias** [comment]
`\microtime()` wasn't the cause of this issue, but I'm still replacing it with `\hrtime()` in #318.

I couldn't find what was causing those delays. Apparently if you stop communicating with chrome it sleeps for a few seconds.
