### ISSUE TITLE
In CONTRIBUTING.md link for showing current test coverage returns 404

### ISSUE THREAD

**Issue by mosharaf13** [chrome-php/headless-chromium-php#284]
Under tests section if you click on [You can see the current coverage at code climate](https://codeclimate.com/github/gsouf/headless-chromium-php/coverage), the redirect returns 404.

**Comment by enricodias** [comment]
@GrahamCampbell are we going to keep tracking the coverage or should I remove it from the `CONTRIBUTING.md`?
