### ISSUE TITLE
Getting different HTML Outputs for same URL 

### ISSUE THREAD

**Issue by devinyasas** [chrome-php/headless-chromium-php#285]
Correct me if I'm wrong. Quite new to this. Currently I'm trying to get `src` value from a webpage inside `class= 'Product-headImage'` Tried to get `innerHTML` but it returned null! So I tried to get `outerHTML` and it works once then after refresh it get another different output. here's my code, Please let me know if there're any shortcuts. Thanks in advance!

```
$user_agents = [
        'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.1.13) Gecko/20080311 Firefox/2.0.0.13',
        'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36',
        'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0',
        'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36',
        'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36',
        'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.71 Safari/537.36',
        'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11) AppleWebKit/601.1.56 (KHTML, like Gecko) Version/9.0 Safari/601.1.56',
        'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36',
        'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/601.2.7 (KHTML, like Gecko) Version/9.0.1 Safari/601.2.7',
        'Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko',
        'Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; AS; rv:11.0) like Gecko',
        'Mozilla/5.0 (compatible, MSIE 11, Windows NT 6.3; Trident/7.0; rv:11.0) like Gecko',
        'Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; Trident/5.0)',
    ];


$browserFactory = new HeadlessChromium\BrowserFactory('/usr/bin/google-chrome');
$random_array_key = array_rand($user_agents);
$user_agent = $user_agents[$random_array_key];
$browser = $browserFactory->createBrowser([
'windowSize' => [1920, 780],
'enableImages' => false,
'userAgent' => $user_agent,
'ignoreCertificateErrors'=> true,
]);
$page = $browser->createPage();

$cookies = $page->getAllCookies();

$uri = 'https://ba-sh.com/us/p/dress-vick-bleunuit-3664784406693.html';
$navigation = $page->navigate($uri);

   // wait for the page to be loaded
   $navigation->waitForNavigation();
   $html = $page->getHtml();

   // evaluate script in the browser
   $pageBody = $page->evaluate('document.body.outerHTML')->getReturnValue();

   $screenshot = $page->screenshot([
    'format'  => 'jpeg',  // default to 'png' - possible values: 'png', 'jpeg',
    'quality' => 80,      // only if format is 'jpeg' - default 100
    ]);
    dd($pageBody); 
   $browser->close();
```

**Comment by enricodias** [comment]
If the content you are fetching is dynamic, it can return different htmls for different requests.

**Comment by devinyasas** [comment]
> If the content you are fetching is dynamic, it can return different htmls for different requests.

I was able to successfully get inner HTML for similar sites. But It somewhat hard for me to understand what's wrong with this website. Do you know any other ways of getting the HTML for [this](https://ba-sh.com/us/p/dress-vick-bleunuit-3664784406693.html) webpage? Thanks!

**Comment by enricodias** [comment]
You'll get the html that the page sends you and there is no guarantee that it would be the same as the previous request.

This page in particular has a script that redirects the browser to another page after a few moments. Your script may get the html from the first or second page depending on the time it takes to execute.

**Comment by devinyasas** [comment]
> You'll get the html that the page sends you and there is no guarantee that it would be the same as the previous request.
> 
> This page in particular has a script that redirects the browser to another page after a few moments. Your script may get the html from the first or second page depending on the time it takes to execute.

Thank you for detailed explanation! I was able to fix but always gets the image from 2nd page! Anyway it works now
