### ISSUE TITLE
Allow psr/log 2 & 3

### ISSUE THREAD

**Issue by sanderdlm** [chrome-php/headless-chromium-php#287]
I noticed that when setting up new PHP8 Symfony projects, this package was the only one holding me back on `psr/log: 1.1`. Could we allow `^1 || ^2 || ^3` in the composer.json to avoid this issue? Or would that conflict with the `"psr/log": "~1.0"` requirement of `apix/log`? Should I make a PR to `apix/log` to try and get a PHP8 compatible version of that package? We could also switch to Monolog, which already has support, or drop the dependency and let the end-user provide the StreamHandler himself.

**Comment by GrahamCampbell** [comment]
Implemented in v1.3.0. :)

**Comment by GrahamCampbell** [comment]
We've done this by swapping over to monolog instead.

**Comment by sanderdlm** [comment]
Good solution, thanks!
