### ISSUE TITLE
Navigate to large pages causes a fatal error due to timeout and does not raise an exception

### ISSUE THREAD

**Issue by jplevene** [chrome-php/headless-chromium-php#288]
**Fatal error**:  Uncaught HeadlessChromium\Exception\OperationTimedOut: Operation timed out (5sec) in .../vendor/chrome-php/chrome/src/Utils.php:71
Stack trace:
  #0 .../vendor/chrome-php/chrome/src/Communication/ResponseReader.php(115): HeadlessChromium\Utils::tryWithTimeout(5000000, Object(Generator))
  #1 .../vendor/chrome-php/chrome/src/PageUtils/AbstractBinaryInput.php(67): HeadlessChromium\Communication\ResponseReader-&gt;waitForResponse(5000)
  #2 ....xxxx.php(181): HeadlessChromium\PageUtils\AbstractBinaryInput-&gt;saveToFile('/var/www/html/m...')
  #3 {main}
  thrown in **.../vendor/chrome-php/chrome/src/Utils.php** on line **71**

For security I had to hide some paths.  The document in question is a 67 page document.

Also I can't find how to extend the 5 second limit.

**Comment by momala454** [comment]
https://github.com/chrome-php/chrome/blob/a564e1e92d414a412c9f1b63957559290bd21fc0/src/PageUtils/AbstractBinaryInput.php#L65

**Comment by jplevene** [comment]
> https://github.com/chrome-php/chrome/blob/a564e1e92d414a412c9f1b63957559290bd21fc0/src/PageUtils/AbstractBinaryInput.php#L65

Thanks, it was there that it was timing out, so I'll try and close the issue.
