### ISSUE TITLE
Crawl Website built with Javascript

### ISSUE THREAD

**Issue by devinyasas** [chrome-php/headless-chromium-php#289]
I'm trying to get product img source from [this](https://www.toryburch.com/en-us/clothing/sweaters/lurex-stripe-cardigan/85850.html?color=001) website. But when I get the [output](https://docs.google.com/document/d/1974_ao7tFKxPrmXmIO_bFGQ8cLAAZaNGHa8kVZLk3rg/edit) it always shows common properties of HTML page. Below is the sample code. It seems like that website has redirect scripts ! How to I get the job done ?

```
$user_agents = [
                'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.1.13) Gecko/20080311 Firefox/2.0.0.13',
                'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36',
                'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0',
                'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36',
                'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36',
                'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.71 Safari/537.36',
                'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11) AppleWebKit/601.1.56 (KHTML, like Gecko) Version/9.0 Safari/601.1.56',
                'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36',
                'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/601.2.7 (KHTML, like Gecko) Version/9.0.1 Safari/601.2.7',
                'Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko',
                'Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; AS; rv:11.0) like Gecko',
                'Mozilla/5.0 (compatible, MSIE 11, Windows NT 6.3; Trident/7.0; rv:11.0) like Gecko',
                'Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; Trident/5.0)',
            ];

   
    $browserFactory = new HeadlessChromium\BrowserFactory('/usr/bin/google-chrome');
    $random_array_key = array_rand($user_agents);
    $user_agent = $user_agents[$random_array_key];
    $browser = $browserFactory->createBrowser([
        'windowSize' => [1920, 780],
        'enableImages' => false,
        'userAgent' => $user_agent,
        'ignoreCertificateErrors'=> true,
        // 'customFlags' => ['--proxy-server=http://50.252.42.253:31820']
    ]);
        $page = $browser->createPage();

        $page->setCookies([
            HeadlessChromium\Cookies\Cookie::create('name', 'value', [
                'domain' => 'matchesfashion.com',
                'expires' => time() + 3600 // expires in 1 day
            ])
        ])->await();

        $cookies = $page->getAllCookies();

        // destination can be specified
        $uri = 'https://www.toryburch.com/en-us/clothing/sweaters/lurex-stripe-cardigan/85850.html?color=001';
        // $page = $browser->createPage($uri);
        $navigation = $page->navigate($uri);

           // wait for the page to be loaded
           $navigation->waitForNavigation();

           // evaluate script in the browser
           // $evaluation = $page->evaluate('document.documentElement.outerHTML');
           $pageBody = $page->evaluate('document.body.innerHTML')->getReturnValue();

           // wait for the value to return and get it
           // $value = $evaluation->getReturnValue();
           $browser->close()
```

[Click here to see](https://docs.google.com/document/d/1974_ao7tFKxPrmXmIO_bFGQ8cLAAZaNGHa8kVZLk3rg/edit)  the full response I got for `$pageBody` / `$value`

**Comment by enricodias** [comment]
This page is built dynamically with js. Getting the raw html will probably not help you. Try to use the new `Dom` class to get what you want without parsing the html directly.

**Comment by devinyasas** [comment]
> This page is built dynamically with js. Getting the raw html will probably not help you. Try to use the new `Dom` class to get what you want without parsing the html directly.

Thanks. I also tried passing html with normal dom xpath queries without headless. It also returned the same .But what you're suggesting is new to me do you have any link to a documentation or could you please show me an example. Thanks in advance

**Comment by enricodias** [comment]
https://github.com/chrome-php/chrome/tree/1.2#interacting-with-dom

**Comment by devinyasas** [comment]
> https://github.com/chrome-php/chrome/tree/1.2#interacting-with-dom

Thanks and I did update branch to 1.2@dev and then tried to get `img src` from this code ,
```
.
.
.
$navigation->waitForNavigation();
   $elem = $page->dom()->search('//img[@src]');
   dd($elem);
```
What I did was search for `src` values in `img` tag .See the attached screenshot of the `dd($elem)`. It showing me that it has two matching nodes and target info and all correctly. But I couldn't find returned values of `src` s. Did I do something wrong ? or Is that  impossible with this web page ?

![Screenshot from 2021-11-13 21-08-41](https://user-images.githubusercontent.com/31001854/141650151-dc0c4377-2892-43c0-a8ac-edf7d51d6a3d.png)

**Comment by enricodias** [comment]
Have you tried searching for an `img` tag inside of a `picture` tag? After giving some time for the page to render completely.

The string `[Product Name]` is not present in the final html (at least for me), just in a json inside the javascript block.
