### ISSUE TITLE
auth

### ISSUE THREAD

**Issue by ph1ex0n** [chrome-php/headless-chromium-php#29]
how to do basic auth with headless chrome?

**Comment by ph1ex0n** [comment]
thanks for answer

**Comment by ph1ex0n** [comment]
can we together find a way to solve this problem?

**Comment by choval** [comment]
@ph1ex0n You could pass it through the URI: 

```
http://user:password@domain/path
```

https://en.wikipedia.org/wiki/Basic_access_authentication#URL_encoding
