### ISSUE TITLE
Call to undefined method HeadlessChromium\Page::dom() 

### ISSUE THREAD

**Issue by devinyasas** [chrome-php/headless-chromium-php#290]
Updated to version 1.1.0 to access new `Dom` but got this error. `Call to undefined method HeadlessChromium\Page::dom() `

```
.
.
$navigation = $page->navigate($uri);   
// wait for the page to be loaded   
$navigation->waitForNavigation();   
$elem = $page->dom()->querySelector('#asset__container-2if');
.
.
```
Did I miss something?

**Comment by GrahamCampbell** [comment]
Yes, that feature is not yet in a stable release. You can use `^1.2@dev` to get it. :)
