### ISSUE TITLE
Cannot make a PDF. Reason : -32000 - Printing is not available

### ISSUE THREAD

**Issue by Speedy059** [chrome-php/headless-chromium-php#302]
Whenever I try to use this, chrome keeps returning this error:
`Cannot make a PDF. Reason : -32000 - Printing is not available`

I'm not sure what to do differently, as I'm not doing anything special. I'm creating an HTML template, saving it to the disk, and then opening it in headless chrome. I've checked the html, it loads fine when I load it in my Chrome and can Save-As PDF when I do it. Using the headless chrome, I get that error. I can't seem to find anything online about it?

How i'm using the package:
`$browserFactory = new BrowserFactory($this->binary);
        $browser = $browserFactory->createBrowser([
            'headless'        => false,          // disable headless mode
            'connectionDelay' => 0.8,            // add 0.8 second of delay between each instruction sent to chrome,
            'debugLogger'     => 'php://stdout', // will enable verbose mode
        ]);
        try {
            $page = $browser->createPage();
            $page->navigate($this->htmlPath)->waitForNavigation();
            if($action === 'pdf') {
                $this->pdf = $page->pdf($options);
                if ($this->pdfPath !== null) {
                    $this->pdf->saveToFile($this->pdfPath);
                }
            }else{
                $this->screenshot = $page->screenshot($options);
                if ($this->imgPath !== null) {
                    $this->screenshot->saveToFile($this->imgPath);
                }
            }
        } finally {
            $browser->close();
        }`

I added some extra params for the createBrowser for troubleshooting reasons. I can't seem to figure out what is causing this? When I dumpt he $this->pdfPath, it's correct.

**Comment by PanuWeb** [comment]
It gives me the same error.

It is not the solution but if you set the 'headless' option to true (just comment/remove the line) it no longer gives that error and you can generate the PDFs

**Comment by JavaScriptDude** [comment]
This one has sent me for a wild goose chase. Came to same conclusion. Definitely a chromium issue. 

Any idea why PDF generation does not work when headless is disabled?

**Comment by JavaScriptDude** [comment]
FYI - Looks like no one raised an issue with Chromium on this so I just opened a new [ticket](https://bugs.chromium.org/p/chromedriver/issues/detail?id=4070).

**Comment by calien666** [comment]
After one week of debugging, I would prefer to add two custom flags while initializing the browser, to get the print working:
```php
'customFlags' => [
    '--disable-dev-shm-usage',
    '--disable-gpu'
],
```
My setup is currently working with chromium browser inside a docker container. Hope this helps

**Comment by Robert-Bartel** [comment]
I have the same issue. The customFlags from @calien666 did not help and chromium is in headless mode.

I can create small pdf files from html that are mostly between 2 and 15 pages. 
But if i want to create a very large pdf file with round about 700 pages, i get the error.

Browser settings:

```
$browserFactory->createBrowser([
        'noSandbox'      => true,
        'startupTimeout' => 600,
        'customFlags'    => ['--disable-dev-shm-usage']
    ]);
```

Timeout on saving pdf:

`$pdf->saveToFile('/some/path/pdf.pdf', 7200000);`

Installed versions:

```
chrome-php/chrome (v1.7.1; via composer)
chromium (102.0.5005.182-r0; via apk)
php:8.1-cli-alpine3.16 (FROM in Dockerfile)
PHP 8.1.11
```

Error message:

```
HeadlessChromium\Exception\PdfFailed: Cannot make a PDF. Reason : -32000 - Printing failed

/srv/clearing/vendor/chrome-php/chrome/src/PageUtils/PagePdf.php:119
/srv/clearing/vendor/chrome-php/chrome/src/PageUtils/AbstractBinaryInput.php:70
...
```

Edit: I don't think, that this issue should be closed since i have the latest versions installed and the customFlags did not work.

**Comment by huelsgp27** [comment]
same issue

**Comment by enricodias** [comment]
The issue is closed because I don't see how we could solve this issue in the lib as it appears to be an issue with chromium itself.
Also, the browser settings from Robert-Bartel didn't add the `--disable-gpu` flag.

**Comment by JavaScriptDude** [comment]
Its true that this issue was a Chromium / Chromedriver issue. It has since been patched in chromedriver however, I'm not sure when we will be able to get this version.
Related info:
- [Chromedriver Issue 3517
](https://bugs.chromium.org/p/chromedriver/issues/detail?id=3517)
- [Chromedriver Issue 4070](https://bugs.chromium.org/p/chromedriver/issues/detail?id=4070)

**Comment by JavaScriptDude** [comment]
Looks like the ChromeDriver [112.0.5615.49](https://chromedriver.storage.googleapis.com/112.0.5615.49/notes.txt) contains the update

**Comment by danilo00010** [comment]
> After one week of debugging, I would prefer to add two custom flags while initializing the browser, to get the print working:
> 
> ```
> 'customFlags' => [
>     '--disable-dev-shm-usage',
>     '--disable-gpu'
> ],
> ```
> 
> My setup is currently working with chromium browser inside a docker container. Hope this helps

It works for me, thanks!

**Comment by blitzarx1** [comment]
If anyone happens to have this problem and nothing above helps try to increase limits for the pod where the chromium is running (https://github.com/lucas-gaitzsch/pdf-turtle/issues/15)
