### ISSUE TITLE
Load only main document (block all external resources)?

### ISSUE THREAD

**Issue by AndriusCTR** [chrome-php/headless-chromium-php#306]
Is it possible to get only the main html document and do not load all external urls (js, css, ajax, images, etc.)? To save cpu/ram and not waste network bandwidth, etc?

**Comment by enricodias** [comment]
Then what's the point of using a full browser for this? You can use a client such as Guzzle to fetch the html and then use [DOMDocument](https://www.php.net/manual/en/class.domdocument.php) to parse it. There are libs to create pdfs from html without using a browser as well.

**Comment by AndriusCTR** [comment]
> Then what's the point of using a full browser for this? You can use a client such as Guzzle to fetch the html and then use [DOMDocument](https://www.php.net/manual/en/class.domdocument.php) to parse it. There are libs to create pdfs from html without using a browser as well.

There is a point. Do you need a use case example in order to add this feature? 

To mimic real browser TLS fingerprint, which you can't (easily do) with Guzzle and other curl clones.

**Comment by enricodias** [comment]
I'm not sure if this is even possible to implement in this lib. As a workaround, you could use a chrome extension that blocks those requests.

**Comment by AndriusCTR** [comment]
> I'm not sure if this is even possible to implement in this lib. As a workaround, you could use a chrome extension that blocks those requests.

With puppeteer you can intercept requests and block them using your own custom hooks:

`await page.setRequestInterception(true);`
`page.on('request', (request) => {`
    `if (request.resourceType() === 'document') {`
        `request.continue();`
    `} else {`
        `request.abort();`
    `}`
`});`

Wonder if chrome headless/dev tool layer has any of such possibilities

**Comment by enricodias** [comment]
[setRequestInterception ](https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-setRequestInterception) exists in the DevTools, but it's experimental and deprecated. The replacement is [Fetch](https://chromedevtools.github.io/devtools-protocol/tot/Fetch/).

To make this possible, the requests that match a predefined pattern would need to be paused using `Fetch.enable`. An `Fetch.requestPaused` event will be triggered for every paused request. For each request, the client must use `Fetch.failRequest` to block it or `Fetch.fulfillRequest` to fulfill it.

Note that `Fetch.fulfillRequest` will require the client to send the actual response for that request. The method `Fetch.continueResponse` that actually just continues the response is marked as experimental.

It doesn't seem so simple to implement.
