### ISSUE TITLE
Cannot get cookie with WS Message

### ISSUE THREAD

**Issue by TheoD02** [chrome-php/headless-chromium-php#307]
Hello !

I'm attempting to get cookies of browser through websocket.

Sending a message to websocket with Message Object and method "Network.getAllCookies" but it return this Reponse and saying method wasn't found : 

```
$cookies = FuviClanBrowser::getBrowser()->getConnection()->sendMessageSync(new Message('Network.getAllCookies'));
```

```
HeadlessChromium\Communication\Response {#1067
  #message: HeadlessChromium\Communication\Message {#1066
    #id: 23
    #method: "Network.getAllCookies"
    #params: []
  }
  #data: array:2 [
    "id" => 23
    "error" => array:2 [
      "code" => -32601
      "message" => "'Network.getAllCookies' wasn't found"
    ]
  ]
}
```

If anyone can help me to get this working.

Thanks ! Happy New Year's Eve :)

**Comment by enricodias** [comment]
Hello. What version of chrome are you using?

Also, there is the method `Page::getCookies()` for that. You don't need to send the message manually.
