### ISSUE TITLE
The following code can work normally under CLI, but cannot obtain HTML data from non CLI, Why? How should I output it?

### ISSUE THREAD

**Issue by quyunet** [chrome-php/headless-chromium-php#308]
The following code can work normally under cli, but cannot obtain HTML data from non cli. Why? How should I output it?

```
<?php
define('USERAGENT', 'Mozilla/5.0 (X11; CentOS; Linux x86_64) Gecko/20100101 Firefox/95.0');

require(__DIR__ . '/vendor/autoload.php');
exec('taskkill /im chrome.exe /f');     //End all chrome tasks under Windows

$options = [
		'userAgent' => USERAGENT,	//Client browser
		'headless' => true,	//Disable headless mode
		'keepAlive' => true,
		'devtools' => false,
		'enableImages' => true,	//Image loading
		'userDataDir' => __DIR__ . '/chrome_data',	//User data directory (default: temporarily generate a new empty directory)
		'startupTimeout' => 60,	//Maximum time (in seconds) to wait for chrome to start
		'noSandbox' => false,
               //'customFlags' => ['--proxy-server=socks5://127.0.0.1:1080','--auto-open-devtools-for-tabs'],	//Use the agent and automatically turn on DevTools
              //'connectionDelay' => 0.8,	//Add a delay of 0.8 seconds between each instruction sent to chrome
              //'debugLogger'     => 'php://stdout'	//Verbose mode is enabled 
    ];

//$factory = new \HeadlessChromium\BrowserFactory('google-chrome-stable');	//Linux
$factory = new \HeadlessChromium\BrowserFactory('C:\\Progra~1\\Google\\Chrome\\Application\\chrome.exe');
$browser = $factory->createBrowser($options);

// do something with the browser
$page = $browser->createPage();
$url = 'https://smarthost.az/az/domains';

//Set browser
$page->setUserAgent(USERAGENT);

$page->navigate($url)->waitForNavigation('networkIdle');

//reference documents：https://developer.mozilla.org/zh-CN/docs/Web/API/Document/querySelector
$evaluation = $page->evaluate(
'(() => {
        document.querySelector("input[name=domain]").value = "crypto";
		document.querySelector(".input_center input[type=submit]").click();
    })()'
);

$evaluation->waitForPageReload('networkIdle');

$html = $page->getHtml();
//$value = $page->evaluate('document.documentElement.innerHTML')->getReturnValue();
print_r($html);
$browser->close();
```

**Comment by enricodias** [comment]
You'll have to debug the code manually to see what part isn't working. Your cli environment is probably different, either with a different `php.ini` or a different php executable. Check the logs, follow the code with xdebug, run chrome without the headless flag to see its behavior and etc.

Note that if you are trying to access the script in the browser, you will need to use another browser to do so since executing `exec('taskkill /im chrome.exe /f');` will kill all chrome instances.

**Comment by quyunet** [comment]
> You'll have to debug the code manually to see what part isn't working. Your cli environment is probably different, either with a different `php.ini` or a different php executable. Check the logs, follow the code with xdebug, run chrome without the headless flag to see its behavior and etc.
> 
> Note that if you are trying to access the script in the browser, you will need to use another browser to do so since executing `exec('taskkill /im chrome.exe /f');` will kill all chrome instances.

you can view the demo Video: [https://drive.google.com/file/d/1tFNMhMvHvZ0Zb4aw9dRdO2HiUWWOfMvp/view?usp=sharing](url)

Is the method of getting browser content from PHP wrong? I have used both of the following 2 methods:
```
$html = $page->getHtml();
//$value = $page->evaluate('document.documentElement.innerHTML')->getReturnValue();
```
But the result was failure.

**Comment by enricodias** [comment]
Oh, I see. I thought your script only works when executing via cli, but it doesn't work at all.

You are clicking on a button that submits a form via ajax. The event `networkIdle` will not be fired in this case and the page will not reload. Instead of using `waitForPageReload`, use `waitForResponse`.

```php
$evaluation->waitForResponse(3000); // 3 seconds timeout
```
