### ISSUE TITLE
Delay Before Screenshot

### ISSUE THREAD

**Issue by Cmaxster** [chrome-php/headless-chromium-php#31]
I need to create a delay before the screenshot is taken..

I want the page to load, and then have headless-chromium-php take a screenshot after 15 seconds (I have an animation running that I want to capture it's end frame).

How do I do this?

**Comment by gsouf** [comment]
If the end of the animation is detectable via javascript, for instance a dom element has been added or removed, then you can loop a javascript function that tests it until it returns true. To evaluate javascript on the page you can do that:

```php
$page->evaluate('document.querySelector("#elementAdded") !== null')->getReturnValue();
```

Or else what's about doing `sleep(15)` before your screenshot to wait for 15 seconds?

**Comment by Cmaxster** [comment]
Ok.. I'll try that... do you know if there's any way to automatically crop the screenshot to only teh content on the page? For example if I had a 300x400 wrapper div, could it somehow crop only that space automatically without me having to set it?

**Comment by gsouf** [comment]
See the doc for a screenshot: https://github.com/chrome-php/headless-chromium-php#make-a-screenshot
you can choose an area with the clip parameter

**Comment by Cmaxster** [comment]
Hi gsouf.. I saw that but what if I don't know the size beforehand? If I'm taking a screenshot of an .html page with a div wrapper that could be anywhere from 300x800 to 600x150, etc.

I was wondering if there was a way to set it to automatically crop to the outer div?

**Comment by choval** [comment]
@Cmaxster I would retrieve the position&offset using javascript and pass those for croping the screenshot.
