### ISSUE TITLE
[BUG] default timeout is too short, can't change it

### ISSUE THREAD

**Issue by AndriusCTR** [chrome-php/headless-chromium-php#311]
Operation timed out (2sec) #0 C:\App\vendor\chrome-php\chrome\src\Communication\ResponseReader.php(115): tryWithTimeout(2000000, Generator)
#1 C:\App\vendor\chrome-php\chrome\src\PageUtils\PageEvaluation.php(77): waitForResponse(2000)
#2 C:\App\vendor\chrome-php\chrome\src\PageUtils\PageEvaluation.php(107): waitForResponse(NULL)
#3 C:\App\vendor\chrome-php\chrome\src\Page.php(817): getReturnValue()

Apparently the timeout param on line 106 for a class ResponseReader.php can't be changed by other calls, so it always uses default value of 2secs which in some cases is too short and returned page is then empty.

**Comment by enricodias** [comment]
It actually can. It's the method `getHtml()` that you are executing in line 817 doesn't use a custom timeout. This method is supposed to be called when you already have a page fully loaded, so I didn't think it was necessary to change the default timeout.

Are you timing out when communicating to the browser itself?

**Comment by AndriusCTR** [comment]
> 

> It actually can. It's the method `getHtml()` that you are executing in line 817 doesn't use a custom timeout. This method is supposed to be called when you already have a page fully loaded, so I didn't think it was necessary to change the default timeout.
> 
> Are you timing out when communicating to the browser itself?

I use the code from the main page to load url and get results. That's it:

`	


	
        $browserFactory->setOptions($options);

        $browser = $browserFactory->createBrowser();

	try {

		$page = $browser->createPage();

		try {
			$page->navigate($url)->waitForNavigation(Page::DOM_CONTENT_LOADED, 30000);
		} catch (OperationTimedOut $e) {
			// too long to load
		} catch (NavigationExpired $e) {
			// Another page was loaded
		}

		$html = $page->getHtml();
	}
	finally {
		$browser->close();
	}

	return $html;`
	
And I get that error, but if I modify source from default 2sec to 12sec then I don't get the error. 

So how should I check 'when I have a page fully loaded then?

**Comment by enricodias** [comment]
Ideally the page should be fully loaded for this, but I think I will add the option to set a custom timeout in this method. There may be other cases where this will require more than 2 seconds.

**Comment by AndriusCTR** [comment]
> Ideally the page should be fully loaded for this, but I think I will add the option to set a custom timeout in this method. There may be other cases where this will require more than 2 seconds.

So why it's timing out at 2sec if I put waitForNavigation 30sec? Seems like it's not using any waiting and just waits 2sec by default. Hence bug

I also use 'startupTimeout'  => 15 option, but that makes no difference

**Comment by enricodias** [comment]
Your 30 seconds timeout is to receive the DOM_CONTENT_LOADED event only. The `getHtml()` itself is using the default of 2 seconds.

**Comment by AndriusCTR** [comment]
> Your 30 seconds timeout is to receive the DOM_CONTENT_LOADED event only. The `getHtml()` itself is using the default of 2 seconds.

Yes. And it's too short, need to be able to adjust it. And it should be dynamic, i.e. return results as soon as they are available, not just wait fixed amount of time and then return.

**Comment by enricodias** [comment]
> And it should be dynamic, i.e. return results as soon as they are available, not just wait fixed amount of time and then return.

The timeouts don't work like that. It's an internal loop that checks the results constantly until it receives something or until it reaches the maximum time.

**Comment by AndriusCTR** [comment]
> > And it should be dynamic, i.e. return results as soon as they are available, not just wait fixed amount of time and then return.
> 
> The timeouts doesn't work like that. It's an internal loop that checks the results constantly until it receives something or until it reaches the maximum time.

You wrote exactly what I had in mind 😕

**Comment by enricodias** [comment]
Implemented in #316
