### ISSUE TITLE
Landscape Orientation On Some Pages Not Working?

### ISSUE THREAD

**Issue by nickabond** [chrome-php/headless-chromium-php#314]
Chrome has implemented a feature: https://caniuse.com/mdn-css_properties_page

It allows you to do this:

```
@page landscapeOrientation{
        size:landscape;
    }

    [data-pagetype="drawing"]{
        page:landscapeOrientation;
    }

}
```

Which is cool because then you can set individual pages in landscape mode without setting the whole thing. I'm trying to figure out why it doesn't work with your library? "Named Pages" work fine for me in Chrome, but I thought it might work since it was sort of using Chrome.

I tried setting the "preferCSSPageSize" option, but it just gives me landscape for every page instead of just the named one that I was setting it too.

Here's info on the CSS Editor's Draft for more info about what I'm talking about:

https://drafts.csswg.org/css-page/#using-named-pages

Hoping you can help,

Nick

**Comment by nickabond** [comment]
Nevermind, this did work. The preview Chrome was showing me looked like portrait, but it was indeed landscape.

**Comment by nickabond** [comment]
Actually this is still somewhat of an issue. 

This is my CSS code which works in Chrome on the Save As PDF feature, but not through this library:

`@page rotated {
        page-orientation: rotate-left;
        margin:10px;
 }`

`
.landscapePage[data-pagetype="drawing"]{
        page:rotated;
        transform-origin: top left;
        transform: translateX(100vw) rotate(90deg);
        width: 98vh;
        height: 100vw;
        margin-left: 400px !important;
        margin-bottom: auto !important;
        page-break-after: always;
}
`
I've attached the behavior that happens correctly in regular Chrome. It is supposed to rotate the page. The second screenshot is what happens with the library. Basically it just needs to rotate it.

Not sure if there is a workaround for this?

Also, here's the Chrome link that they support it now:
https://chromestatus.com/feature/5173237715566592

![correctBehavior](https://user-images.githubusercontent.com/4335602/152243236-f780b539-d245-44c4-a433-2943aa6d8e18.jpg)
![incorrectBehavior](https://user-images.githubusercontent.com/4335602/152243235-43f38083-791b-40c1-888e-f4587766553d.jpg)

**Comment by enricodias** [comment]
Are you using exactly the same chrome executable for both tests? Also, are you using version 1.2 or higher of this lib? There were some changes related to pdf creation on v1.2.

**Comment by nickabond** [comment]
I believe I am using the same Chrome executable. It's just finding it automatically. I'm not setting the path explicitly. Is there a way to check?

Currently I am using v. 1.3 of the lib.

**Comment by nickabond** [comment]
Yep I can confirm it is the same executable because I just used this:

```
$chrome_path = "C:/Program Files (x86)/Google/Chrome/Application/chrome.exe";
$browserFactory = new BrowserFactory($chrome_path);
```

Both are on Chrome 98.

**Comment by nickabond** [comment]
Any updates on this? Were you all able to recreate the issue?
