### ISSUE TITLE
How to make screenshot if page not fully loaded

### ISSUE THREAD

**Issue by Igzak** [chrome-php/headless-chromium-php#315]
Hello, I was trying to test headless chrome with this [tool](https://abrahamjuliot.github.io/creepjs/) and make a screenshot but the page newer loaded fully as I can understand. Waiting Network Idle event timed out or when I was trying to make a screenshot get an error with message `Operation timed out (2sec)`, I was changed this 2sec to 5min in chrome-php\chrome\src\Communication\ResponseReader.php::waitForResponse but that won't help, how can I make a screenshot of this page?

Here was my [test command code](https://pastebin.com/D4TMKSkG), also i can see in MITM proxy that all was loaded
![зображення_2022-01-19_115423](https://user-images.githubusercontent.com/22889464/150107038-0de82c7a-87fe-4f19-87a8-996ac65d3c82.png)

PHP version: 7.4
Chrome version: Google Chrome 95.0.4638.69

**Comment by maximgrynykha** [comment]
This may be related to #311
