### ISSUE TITLE
Code Quality

### ISSUE THREAD

**Issue by simPod** [chrome-php/headless-chromium-php#323]
👋🏾 was considered using phpstan/phpcs in this lib? Is it desirable? It would use a lot of type adds, useless annotations removals etc. Is it desired here?

_Related to https://github.com/chrome-php/chrome/pull/320#discussion_r789879121 since I do not want to touch anything unrelated in the PR._

**Comment by GrahamCampbell** [comment]
phpstan and styleci are both already run on this repo, by CI. I am aware the type coverage is poor - we have inherited this codebase. :P

**Comment by simPod** [comment]
oh did not notice phpstan. ok thanks. asking so I can help
