### ISSUE TITLE
How to: set user agent

### ISSUE THREAD

**Issue by woodsbox** [chrome-php/headless-chromium-php#33]
Hi there,

Would it be possible to let chromium act as different browser by setting the user agent?

**Comment by gsouf** [comment]
It's implemented in version 0.2.2. You can either set it per page: 

```php
$page->setUserAgent('user agent');
```

Or for the whole browser via the factory option ``userAgent``

**Comment by woodsbox** [comment]
Do you mean like this?

$browser = $browserFactory->createBrowser(['userAgent' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1.2 Safari/605.1.15']);
