### ISSUE TITLE
Change type of options by default in method signature

### ISSUE THREAD

**Issue by maximgrynykha** [chrome-php/headless-chromium-php#330]
https://github.com/chrome-php/chrome/blob/a03581b2d99d5e8cad413932d5cb4130717040c2/src/BrowserFactory.php#L65

```php
public function createBrowser(array $options = []): ProcessAwareBrowser 
{
    https://github.com/chrome-php/chrome/blob/1.3/src/BrowserFactory.php#L67
    $options = $options ?: $this->options;
}
```

**Comment by GrahamCampbell** [comment]
The default of null is intentional to allow users to say "give me the default", which is not the same thing as "i want no options, the empty array".

**Comment by maximgrynykha** [comment]
@GrahamCampbell Yap, I understand your point, but my proposal was made to note that `$options` is an array by default (not null). [Short ternary operation](https://stitcher.io/blog/shorthand-comparisons-in-php#shorthand-ternary-operator) checks if `$options` are filled if that is true - use `$options` as method params, but in other cases use the default - in-class `$this->options`.

**Comment by GrahamCampbell** [comment]
I know, I don't want that, for the reasons I explained. It prevents users passing through the empty array, when they really wanted that.

**Comment by maximgrynykha** [comment]
@GrahamCampbell Emm, why will they want to pass an empty array if there is already set one as the default value of param? Referencing your previous words, you have been talking about the default value of null like a standard value for default cases. But in this concrete context, it might be more appropriate to set an empty array as the default value.
