### ISSUE TITLE
Add in-code (PHPDoc) documentation to the methods

### ISSUE THREAD

**Issue by maximgrynykha** [chrome-php/headless-chromium-php#331]
https://github.com/chrome-php/chrome/blob/a03581b2d99d5e8cad413932d5cb4130717040c2/src/BrowserFactory.php#L86

https://github.com/chrome-php/chrome/blob/a03581b2d99d5e8cad413932d5cb4130717040c2/src/BrowserFactory.php#L176

**Comment by GrahamCampbell** [comment]
Those methods linked there don't need phpdoc because the type information is already captured in the code.
