### ISSUE TITLE
Executable not found in Linux

### ISSUE THREAD

**Issue by jakobwildrain-si** [chrome-php/headless-chromium-php#339]
So, if the CHROME_PATH is not set, in AutoDiscover guessChromeBinaryPath() it only checks for MacOS and Windows, and if it's neither, it ends up using a default name of 'chrome', however on all versions of Linux it's 'google-chrome', unless a user has set a global alias.
I would suggest checking if PHP_OS_FAMILY is 'Linux' and setting it to 'google-chrome' and only then defaulting to 'chrome'.
This way we don't have to set CHROME_PATH or pass the executable name to BrowserFactory.

Otherwise, what a great package, thank you so much for creating it, seeing as the original has seized development. Using this package means having to deal with less code (compared to jakub calhoun's package, which was way more verbose) and the code is more clear.
Great job!

**Comment by enricodias** [comment]
I'll leave a comment here to remind me to work on this. Removing the default "chrome" will break backwards compatibility, but I think we can test if the command exists and fallback to "google-chrome" if it doesn't.

**Comment by enricodias** [comment]
Implemented in #410
