### ISSUE TITLE
is possible support firefox

### ISSUE THREAD

**Issue by FelipeAzambuja** [chrome-php/headless-chromium-php#341]
i tried using firefox insted of chrome , but no success.
Is there any way to get this support?

**Comment by GrahamCampbell** [comment]
No, we don't support Firefox, and doing so would be a lot of work. If you'd like to look into what would be required to support Firefox, feel free to, and post your findings here. Alternatively, you can contact me at `hello at gjcampbell.co.uk` for a quote to have this implemented. :)
