### ISSUE TITLE
$page->getCurrentUrl() response is not the actual current URL

### ISSUE THREAD

**Issue by rubobaquero** [chrome-php/headless-chromium-php#343]
Hello,

I am trying to automate login on Google. I need to check whats the current URL for different reasons, so I saw that the page object has a getCurrentUrl() method. For some reason, this method is not returning the actual current URL. It seems that after clicking on a submit button that generates a redirect, the URL is not being updated.

**Comment by GrahamCampbell** [comment]
I don't think this is a bug, more that the method has a confusing name. The URL is intended to be the URL that you browsed to, and not whatever text is currently in the navbar.
