### ISSUE TITLE
Issue with socket timeouting/crashing with some conditions

### ISSUE THREAD

**Issue by momala454** [chrome-php/headless-chromium-php#344]
on certain sites after navigating to it, then trying to navigating to another website crashes with
``Fatal error: Uncaught HeadlessChromium\Exception\CommunicationException: Message could not be sent. Reason: the connection is closed.`` 

We can reproduce the same error with Emulation.setCPUThrottlingRate and any website when doing page.navigate.
It crashes only on PHP 8 but not php 7

```php
$browserFactory = new \HeadlessChromium\BrowserFactory();

// starts headless chrome
$browser = $browserFactory->createBrowser([
  'userAgent'					=>	'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36',
  'headless'          =>  true,
  'debugLogger'     			=> 'php://stdout',
]);

try {
    // creates a new page and navigate to an URL
    $page = $browser->createPage();
    $page->getSession()->sendMessageSync(new \HeadlessChromium\Communication\Message('Emulation.setCPUThrottlingRate', ['rate'	=>	20]));

    $page->navigate('http://example.com/')->waitForNavigation();
} finally {
    // bye
    //sleep(230);
    echo 'close';
    $browser->close();
}
```

I tracked the error to
vendor\chrome-php\wrench\src\Socket\AbstractSocket.php 
method receive :
```php
// fread FALSE means socket has been closed
                if (false === $result) {
```

$result is equals to false there.

If I remove this code, it don't crash anymore 
```php
if ($makeBlockingAfterRead) {
                    \stream_set_blocking($this->socket, true);
                    $makeBlockingAfterRead = false;
                }
```

i'm not sure if we need to set the socket to blocking, but increasing the blocking timeout prevent the crashes
```php
stream_set_timeout($this->socket, 20);
```

actually we can change it there
```php
public const TIMEOUT_SOCKET = 5;
```

strange why on php8 it require an higher timeout

**Comment by momala454** [comment]
when it crashes,
```php
stream_get_meta_data($this->socket)
```
contains "timed_out => 1"
we could detect this and send the appropriate error instead of silently close the connection.

And the default timeout should be increased

**Comment by momala454** [comment]
the crashing example from the top message doesn't crash anymore since https://github.com/chrome-php/wrench/pull/8

**Comment by GrahamCampbell** [comment]
Nice.
