### ISSUE TITLE
Images not loading in headers and footers

### ISSUE THREAD

**Issue by jamesatplebble** [chrome-php/headless-chromium-php#347]
Hi,

I can't get images to load in headers and footers - see screenshot. 
![Screen Shot 2022-02-22 at 12 09 42](https://user-images.githubusercontent.com/33558941/155131099-51f7c53a-cbfa-4e57-913c-8eb3b0f82659.png)

Here's my code for the header:
<div style="font-size:9px; 
width: 100%; 
margin: 0mm 5mm;
font-family: proxima-nova, 'proxima-nova', 'Proxima Nova', 'Proxima Nova', 'Helvetica Neue', Helvetica, Arial, sans-serif;
color: #444444; "><table style="width: 100%;">
<tbody>
<tr>
<td style="width: 50.0000%;">I'm a test Header</td>
<td style="width: 50%; text-align: right;"><img src="https://plainly.com/assets/userfiles/1637260373-hvl.png" alt="" width="32" height="32"></td>
</tr>
</tbody>
</table>
</div>

My options:

`$browser = $browserFactory->createBrowser([
     'windowSize'   => [882, 1248],
     'ignoreCertificateErrors' => true,
     'enableImages' => true,
     'userAgent' => 'PlainlyBot',
]);`

Is this a bug or something I'm doing wrong? (Once I understood that you need to set some inline CSS in a wrapper div for headers and footers, everything else seems to work well.)

Many thanks
James

**Comment by enricodias** [comment]
You mean, during printing to pdf?

**Comment by jamesatplebble** [comment]
Yes! Sorry, I should have said.

**Comment by jamesatplebble** [comment]
Hi Enrico, any further thoughts on this?
Thanks

**Comment by enricodias** [comment]
I didn't have time to test this yet. It's in my to-do list.

**Comment by jamesatplebble** [comment]
This is still an issue as far as I know?

**Comment by enricodias** [comment]
So, there are a lot of sources around saying that both `headerTemplate` and `footerTemplate` can't load external resources, but I couldn't find why. I checked the chromium [source code](https://github.com/chromium/chromium/blob/main/components/printing/resources/print_header_footer_template_page.html) and saw that the header and footer are added using `innerHTML`, just like the content.

I couldn't find any way to load external images. The only thing that worked was injecting the image as base64 directly in the html: `<img src="data:image/png;base64,..."/>`

If anyone finds a better solution, feel free to reopen this issue.

**Comment by Entretoize** [comment]
Same issue, any news ?
