### ISSUE TITLE
Obtain Html content before "operation time out"

### ISSUE THREAD

**Issue by iamAbdullahAbdi** [chrome-php/headless-chromium-php#349]
Hello,
I wonder how to get received Html content before "operation timed out" executed!
I want to save the data **whether page fully loaded or not!**
Could you please help me to do it?
Thanks a lot,

**Comment by enricodias** [comment]
Technically you don't need to wait the load event to take a screenshot. Have you tried taking the screenshot after the exception? It should work as long as the browser is still available.

**Comment by iamAbdullahAbdi** [comment]
> Technically you don't need to wait the load event to take a screenshot. Have you tried taking the screenshot after the exception? It should work as long as the browser is still available.

@enricodias 
The problem is exactly this! 
Please check my code out!

```
require_once 'vendor/autoload.php';
use HeadlessChromium\BrowserFactory;
use HeadlessChromium\Exception\OperationTimedOut;
use HeadlessChromium\Exception\NavigationExpired;
use HeadlessChromium\Page;

$browserFactory = new BrowserFactory();
$browser = $browserFactory->createBrowser();
$page = $browser->createPage();
$navigation = $page->navigate('https://www.digikala.com/product/dkp-6459793/');
//$navigation = $page->navigate('https://www.digikala.com/product/dkp-6459793/')->waitForNavigation(); // default 30 sec on LOAD event!
//usleep(5000000); // I use it to stop 5 sec! (We can't skip it, anyway!)
$content = $page->getHtml();
```

Consider that, my goal website has many many stuff to load, so it may take too long but content (html) is ready to use!
That's all I want! (Just return html content **once they loaded** in chrome, _I mean finally after 5 sec_)

Thank you,

**Comment by iamAbdullahAbdi** [comment]
@enricodias
Sorry to bother you, but **no solution**?!

**Comment by enricodias** [comment]
This worked on my end:
```php
require_once 'vendor/autoload.php';
use HeadlessChromium\BrowserFactory;

$browserFactory = new BrowserFactory();
$browser = $browserFactory->createBrowser();
$page = $browser->createPage();
$navigation = $page->navigate('https://www.digikala.com/product/dkp-6459793/');
usleep(9000000);
echo $page->getHtml();
$browser->close();
```

When using a 5 second delay I get the error `TypeError: Cannot read properties of null (reading 'outerHTML')` because the html didn't exist yet. This particular page is dynamic and changes the html several times during the loading. To overcome this you may try to call `getHtml()` in a loop and in a try catch block to catch this js exception, sleeping 1 second on every iteration until a maximum defined time.
