### ISSUE TITLE
Can I get page information like page size, number of css requests, number of js requests, etc?

### ISSUE THREAD

**Issue by p01ymath** [chrome-php/headless-chromium-php#35]
I have a requirement to get all the information about a specific page. For example, I want to know how many total requests are required to load a page, how many total requests are static files, etc. Is it possible?

**Comment by gsouf** [comment]
HI @p01ymath 

There are no built-in way for now but that's something we can add to the library. I'll keep you updated

**Comment by choval** [comment]
Hi @p01ymath ,

You can get the information from `window.performance.getEntries()`.

```
entryType:
* navigation the page you're navigating
* link (css)
* img
* script
* xmlhttprequest
* fetch

transferSize <- the size of the resource, if it's retrieved from the cache, its 0.

for the time it took to download i use:
responseEnd - fetchStart

for the time it took to load:
duration

for drawing:
duration - (responseEnd - fetchStart)
```

To count the number of css/scripts/imgs you can loop through it and count entryType.

**Comment by Tobias-Keller** [comment]
would be nice if we can get the har file from network section

**Comment by SEOArcade** [comment]
> window.performance.getEntries()

How to use that in PHP?

**Comment by choval** [comment]
@SEOArcade That is JavaScript, in PHP

```php
$entries = $page->evaluate('window.performance.getEntries()')->getReturnValue();
```

**Comment by SEOArcade** [comment]
> @SEOArcade That is JavaScript, in PHP
> 
> ```
> $entries = $page->evaluate('window.performance.getEntries()')->getReturnValue();
> ```

Thanks, that's the problem though. When I run this command, I get empty array. No matter how I run it. I can get all the information using the:

`$pageContent = $page->evaluate('document.documentElement.innerHTML');`

but nothing with

`$entries = $page->evaluate('window.performance.getEntries()')->getReturnValue();`

Is there anything else to it?

**Comment by choval** [comment]
> When I remove:
> `->getReturnValue();`
> I get just a wall of code with no sign of transferSize, or duration.

Can you post a few lines?

**Comment by SEOArcade** [comment]
> > When I remove:
> > `->getReturnValue();`
> > I get just a wall of code with no sign of transferSize, or duration.
> 
> Can you post a few lines?

Sure:

`HeadlessChromium\PageUtils\PageEvaluation Object ( [responseReader:protected] => HeadlessChromium\Communication\SessionResponseReader Object ( [topResponseReader:protected] => HeadlessChromium\Communication\ResponseReader Object ( [message:protected] => HeadlessChromium\Communication\Message Object ( [id:protected] => 22 [method:protected] => Target.sendMessageToTarget [params:protected] => Array ( [message] => {"id":21,"method":"Runtime.evaluate","params":{"awaitPromise":true,"returnByValue":true,"expression":"window.performance.getEntries()","userGesture":true}} [sessionId] => 98D25921796CEE0DD394D60B46471A41 ) ) [connection:protected] => HeadlessChromium\Communication\Connection Object ( [strict:protected] => 1 [delay:protected] => [lastMessageSentTime:HeadlessChromium\Communication\Connection:private] => [wsClient:protected] => HeadlessChromium\Communication\Socket\Wrench Object ( [client:protected] => Wrench\Client Object ( [uri:protected] => ws://127.0.0.1:44629/devtools/browser/68e8b0f8-0641-4d12-95e9-cf7b7d76efd7 [origin:protected] => http://127.0.0.1 [socket:protected] => Wrench\Socket\ClientSocket Object ( [scheme:protected] => tcp [host:protected] => 127.0.0.1 `

**Comment by SEOArcade** [comment]
> > When I remove:
> > `->getReturnValue();`
> > I get just a wall of code with no sign of transferSize, or duration.
> 
> Can you post a few lines?

Could be the issue is caused by me using headless-chrome, rather than chrome?

**Comment by choval** [comment]
@SEOArcade 

Performance is a web api, Chromium should work fine.
Try this:

```
<?php
require('vendor/autoload.php');

// Fake it
$userAgent = 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:40.0) Gecko/20100101 Firefox/40.1';

$bin = '"/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"';
$url = 'https://github.com/';

use \HeadlessChromium\BrowserFactory;
$browserFactory = new BrowserFactory($bin);

$browser = $browserFactory->createBrowser([
//    'debugLogger' => 'php://stdout',
    'userAgent'   => $userAgent,
]);
$page = $browser->createPage();
$page->navigate($url)->waitForNavigation();
$performanceEntriesRaw = $page->evaluate('JSON.stringify( window.performance.getEntries() )')->getReturnValue();
$performanceEntries = json_decode($performanceEntriesRaw, true);
var_dump($performanceEntries);
```

**Comment by SEOArcade** [comment]
> @SEOArcade
> 
> [Performance](https://developer.mozilla.org/en-US/docs/Web/API/Performance/getEntries) is a web api, Chromium should work fine.
> 
> Try this:
> 
> ```
> <?php
> require('vendor/autoload.php');
> 
> // Fake it
> $userAgent = 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:40.0) Gecko/20100101 Firefox/40.1';
> 
> $bin = '"/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"';
> $url = 'https://github.com/';
> 
> use \HeadlessChromium\BrowserFactory;
> $browserFactory = new BrowserFactory($bin);
> 
> $browser = $browserFactory->createBrowser([
> //    'debugLogger' => 'php://stdout',
>     'userAgent'   => $userAgent,
> ]);
> $page = $browser->createPage();
> $page->navigate($url)->waitForNavigation();
> $performanceEntriesRaw = $page->evaluate('JSON.stringify( window.performance.getEntries() )')->getReturnValue();
> $performanceEntries = json_decode($performanceEntriesRaw, true);
> var_dump($performanceEntries);
> ```

Works like a charm! Thank you for this, it was a real headscratcher for me.

In order to get load time/file size/number of the request should I just loop through the results and calculate all, or is there an easier way?
