### ISSUE TITLE
Can't control font-size and font-family

### ISSUE THREAD

**Issue by Artanisky** [chrome-php/headless-chromium-php#354]
For some reason I can not install the font "Times new roman".

html file
![image](https://user-images.githubusercontent.com/32029918/158052655-b6e69be6-0e1a-4381-993e-dd1b2dd49a97.png)
created pdf file
![image](https://user-images.githubusercontent.com/32029918/158052681-583cb204-c566-4e8a-8a95-6626a600d065.png)

And font size big

**Comment by enricodias** [comment]
Does printing manually directly in chrome works as expected?

**Comment by Artanisky** [comment]
@enricodias Yes, it works fine
![image](https://user-images.githubusercontent.com/32029918/158199370-ff75b23c-4d23-4f7f-8b3b-eff711903a8c.png)
