### ISSUE TITLE
Clearing all cookies ?

### ISSUE THREAD

**Issue by Entretoize** [chrome-php/headless-chromium-php#357]
I have some issues with cockies being shared between session, I don't know if a session is supposed to be like a sandbox  but it doesn't seems to be the case, also I'm looking for a method to clear all cookies.
Does it exists ?

Thanks

**Comment by Entretoize** [comment]
Can this work ?

`        $response = $this->getSession()
            ->sendMessage(
                new Message('Network.setCookies', [ 'cookies' => [] ])
            );
`

**Comment by enricodias** [comment]
You are controlling a real browser. The cookies will be stored and shared between every page with an URL that matches the cookie domain path.

There is no method to clear cookies implemented in this lib at this moment, but you can call `Network.clearBrowserCookies` manually.

https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-clearBrowserCookies

**Comment by Entretoize** [comment]
I know I'm controlling a real browser but it could have several browsers eacch one with it's own cookies.
Then what is the goal of sessions ($this->page->GetSession()) if they don't isolate things ? Is there one session per page ?
When I send messages to a session, are they sent globally to the browser or specifically to the page ?

**Comment by enricodias** [comment]
When you use a real browser, the cookies are shared with all windows and persist even after you reopen the browser. They are saved in the current profile and the only way to not share them would be to open the browser again using another profile folder.

**Comment by Entretoize** [comment]
Ok, thank you, is it the userDataDir ?
It seems that the argument for the profile directory is `--profile-directory` but userDataDir  uses --user-data-dir

**Comment by Entretoize** [comment]
I found that I can add custom arguments in the `createBrowser `method then it should be : `'customFlags'=>["--profile-directory=profileName"],`

**Comment by enricodias** [comment]
Yes, you can start a new browser instance with a different profile or try to clear the cookies using `Network.clearBrowserCookies`.

**Comment by Entretoize** [comment]
It seems to work, thank you for your help.

**Comment by divinity76** [comment]
to clear all cookies:
```php
    function clearAllCookies()
    {
        $this->page->getSession()->sendMessageSync(new \HeadlessChromium\Communication\Message(
            'Network.clearBrowserCookies',
            []
        ));
    }
```
