### ISSUE TITLE
Save image

### ISSUE THREAD

**Issue by nano-freelancer** [chrome-php/headless-chromium-php#36]
How to get image from site and save(not screenshot) via headless chromium?

**Comment by gsouf** [comment]
Hi @nano-freelancer 

I guess the easiest way for now is to get image's href and to download it from its url:

```php

$imageHref = $page->evaluate('document.querySelector("#myImage").href')->getReturnValue();

$imageStream =  fopen($imageHref, 'r');

file_put_contents('/path/to/save.jpg', $imageStream);
```

I'll investigate to find more convenient way to proceed.

**Comment by nano-freelancer** [comment]
@gsouf thanks for fast answer, a little class/method would be nice

also it should be mentioned in readme.md **usage** section for new enthusiasts (as part of web scraping)

**Comment by choval** [comment]
I'm doing the following to retrieve the image from the browser instead of a re-download (without headers the browser used for the image).

```
$page = $browser->createPage();
$script = file_get_contents('https://gist.githubusercontent.com/choval/981be741ce8f39d0edd951933e256bf2/raw/f78adb457f7458e9113210e7ed3c33363e4dc379/ImageToDataUrl.js');
$page->addPreScript($script);
$page->navigate('https://google.com/')->waitForNavigation();
$dataUrl = $page->evaluate('document.getElementsByTagName("img")[0].toDataUrl("image/png")')->getReturnValue();
$parts = explode(',',$dataUrl,2);
file_put_contents('image.png', base64_decode(end($parts)));
```

https://gist.github.com/choval/981be741ce8f39d0edd951933e256bf2

**Comment by gsouf** [comment]
@choval That looks good. I'll add this to the doc at some point!

**Comment by olaviinha** [comment]
> ```
> $page = $browser->createPage();
> $script = file_get_contents('https://gist.githubusercontent.com/choval/981be741ce8f39d0edd951933e256bf2/raw/f78adb457f7458e9113210e7ed3c33363e4dc379/ImageToDataUrl.js');
> $page->addPreScript($script);
> $page->navigate('https://google.com/')->waitForNavigation();
> $dataUrl = $page->evaluate('document.getElementsByTagName("img")[0].toDataUrl("image/png")')->getReturnValue();
> $parts = explode(',',$dataUrl,2);
> file_put_contents('image.png', base64_decode(end($parts)));
> ```

Is this supposed to work with a direct image URL? I'm getting errors.

**Comment by olaviinha** [comment]
Ok I seem to have ended up just screenshotting the image (from a direct image URL) with correct clipping.
This example assumes that the URL contains image filename as basename, and only strips possible params after it. You may want to tweak `$filename` by use case, esp. if the URL does not specify an image filename.

```
$imgs_path = '/path/to/save/images/to/';
$image_url = '<DIRECT IMAGE URL>';
$filename = explode('?', basename($image_url))[0]; // You may want to tweak this

use HeadlessChromium\Clip;
$vp = 1200; // Square viewport side
$page->setViewport($vp, $vp)->await();
$page->navigate($image_url);
sleep(2); // You can probably use ->waitForNavigation(); in majority of use cases instead of sleep.
$w = $page->evaluate('document.querySelector("img").width')->getReturnValue();
$h = $page->evaluate('document.querySelector("img").height')->getReturnValue();
$left = floor(($vp/2)-($w/2));
$top = floor(($vp/2)-($h/2));
$page->screenshot(['clip' => new Clip($left, $top, $w, $h)])->saveToFile($imgs_path.$filename);
```

**Comment by realskudd** [comment]
@choval  This works great for still-frame images. However, for any other content like webp or gif, it only renders a single frame. This is true when you specify the `image/gif` content type in the `->evaluate()` statement.

What am I missing?

**Comment by realskudd** [comment]
> [@choval](https://github.com/choval) This works great for still-frame images. However, for any other content like webp or gif, it only renders a single frame. This is true when you specify the `image/gif` content type in the `->evaluate()` statement.
> 
> What am I missing?

Hm, apparently this method only captures one frame and the way we need to handle the gif/webp formats is to capture each frame individually then coalesce.

**Comment by enricodias** [comment]
@realskudd that will be beyond the scope of this project. There are other libs specifically for image manipulation that will allow you to edit and extract specific frames of a gif.
