### ISSUE TITLE
Set & Get Cookies failure with PHP 8.1.3 #2

### ISSUE THREAD

**Issue by JupitorGeorge** [chrome-php/headless-chromium-php#361]
Thanks for the previous update.   We now have just these 2 issues.

Deprecated: Return type of HeadlessChromium\Cookies\CookiesCollection::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/chrome-php/chrome/src/Cookies/CookiesCollection.php on line 47

PHP Deprecated:  Return type of HeadlessChromium\Cookies\CookiesCollection::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/chrome-php/chrome/src/Cookies/CookiesCollection.php on line 55

Thanks for your help

**Comment by GrahamCampbell** [comment]
Oh, I should say, this library is still not compatible with PHP 8.1, by the way, because `chrome-php/wrench` is not yet compatible, and so we don't even test this library on PHP 8.1 yet, which is why we've not fixed any of this stuff yet.
