### ISSUE TITLE
PHP 8.0  querySelector not finding elements within the body

### ISSUE THREAD

**Issue by JupitorGeorge** [chrome-php/headless-chromium-php#362]
In a complex page like Google's front the page request works:  $html = $page->getHtml();

None of the suggested methods, as I understand them, extract an internal element by ID, CSS, or TAG selector.

This command shows no result
$elem = $page->evaluate("document.querySelector('input').innerHTML")->getReturnValue();

This command returns the "HeadlessChromium\Dom\Node Object" without the requested element
$elem = $page->dom()->querySelector('input');

Please let me know if I am using the right approach for complex pages.

**Comment by enricodias** [comment]
There are several input fields in the Google page and you are using the wrong syntax in the `querySelector`, assuming you are trying to fetch all of them. `querySelector` returns only one element and you are not searching for a specific input with a class or id.

Check the `querySelector` docs: https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelector
