### ISSUE TITLE
Setting multiple cookies throwing an error

### ISSUE THREAD

**Issue by JupitorGeorge** [chrome-php/headless-chromium-php#364]
I'm trying to set multiple cookies and am running into an error.  Please let me know if I have interpreted the examples incorrectly.

The example code executes but does not seem to set the cookie
$page->setCookies([
	Cookie::create('cookie_A', '09ACCjH', ['domain' => 'www.domain1.com',  'expires' => '2022-09-20T04:29:38.977Z'])		
])->await();

Using this example with 2 cookies sets the cookies but the expires is wrong
$page->setCookies([
    Cookie::create('cookie_A', '1', ['1648397341']),
    Cookie::create('cookie_B', '09ACCjHP', ['2022-09-20T04:29:38.977Z']),
])->await();

HeadlessChromium\Cookies\CookiesCollection Object
(
    [cookies:protected] => Array
        (
            [0] => HeadlessChromium\Cookies\Cookie Object
                (
                    [data:protected] => Array
                        (
                            [name] => cookie_B
                            [value] => 09ACCjHP
                            [domain] => www.octomize.com
                            [path] => /
                            [expires] => -1
                            [size] => 16
                            [httpOnly] =>
                            [secure] =>
                            [session] => 1
                            [priority] => Medium
                            [sameParty] =>
                            [sourceScheme] => NonSecure
                            [sourcePort] => 80
                        )
                )

            [1] => HeadlessChromium\Cookies\Cookie Object
                (
                    [data:protected] => Array
                        (
                            [name] => cookie_A
                            [value] => 1
                            [domain] => www.octomize.com
                            [path] => /
                            [expires] => -1
                            [size] => 9
                            [httpOnly] =>
                            [secure] =>
                            [session] => 1
                            [priority] => Medium
                            [sameParty] =>
                            [sourceScheme] => NonSecure
                            [sourcePort] => 80
                        )
                )
        )
)

Adding the "expires" and "domain" options throws the following error

$page->setCookies([
    Cookie::create('cookie_A', '1', ['domain' => '.domain1.com', 'expires' => '1648397341']),
    Cookie::create('cookie_2', '09ACCjHPqiwPKJD5o0YMxJzZLH0e3fYwvRxItphbSU2e_9QQv1yYpVi_6ksDEwLwtSaB0qojU0HRF2-or0BWF0YtM', ['domain' => '.domain2.com', 'expires' => '2022-09-20T04:29:38.977Z']),
//

PHP Fatal error:  Uncaught HeadlessChromium\Exception\CommunicationException\ResponseHasError: -32602 - Invalid parameters - Failed to deserialize params.cookies.expires - BINDINGS: double value expected at position 87 in /var/www/html/vendor/chrome-php/chrome/src/PageUtils/ResponseWaiter.php:54
Stack trace:
#0 /var/www/cgi-bin/recall_test2.php(1817): HeadlessChromium\PageUtils\ResponseWaiter->await()
#1 /var/www/cgi-bin/recall_test2.php(310): OctomizeTest()
#2 {main}
  thrown in /var/www/html/vendor/chrome-php/chrome/src/PageUtils/ResponseWaiter.php on line 54

**Comment by enricodias** [comment]
`Cookie::create('cookie_A', '1', ['1648397341']),` wont work, you need to specify the param names, like `Cookie::create('cookie_A', '1', ['domain' => '.domain1.com', 'expires' => 1648397341]),`.

Expires may be a timestamp as int, or any valid string that can be interpreted by [strtotime](https://www.php.net/manual/en/function.strtotime.php). The timestamp 1648397341 is also in the past.
