### ISSUE TITLE
Anyway to generate miniature screenshot?

### ISSUE THREAD

**Issue by imrane555** [chrome-php/headless-chromium-php#365]
Hello and thank you for this great piece of software.

It's working really great.

Only one thing I'm struggling to do. I'm trying to generate thumbnail screenshot. But I found no way to "zoom out" in the browser to generate a thumbnail after shrinking the viewport. I tried the "scale" option the screenshot function but it seems to do nothing.

Here's my code 

![2022-03-29_22-22](https://user-images.githubusercontent.com/25330744/160700455-fc723332-19b6-4877-a4c6-7532f468f7b6.png)

**Comment by enricodias** [comment]
The best way to do this would be to take a normal screenshot and then create a thumbnail of it using any image lib. Several websites change their layout depending on your viewport, so zooming out will not produce the desired result.

**Comment by imrane555** [comment]
Alright I see. Thank you for your answer. I think I'll keep it like this and shrink it with html. 
The idea is to send these via email so they need to be loaded fast so I thought maybe generating a thumbnail directly would generate the image quicker. 

Anyways thank you for this great software bud.
