### ISSUE TITLE
Browser user agent no quotes

### ISSUE THREAD

**Issue by choval** [chrome-php/headless-chromium-php#37]
When setting the browser userAgent, the string is not quoted, thus spaces break the command.

In file src/Browser/BrowserProcess.php at line 322
`
            $args[] = '--user-agent=' . $options['userAgent'];
`

Current workaround: using double quotes on the userAgent option or using page->setUserAgent

**Comment by choval** [comment]
9722546 fixed it.

**Comment by gsouf** [comment]
Sorry, let it openned to answer you and forgot!
