### ISSUE TITLE
Gettin OperationTimedOut exception when trying to open a .pdf URL

### ISSUE THREAD

**Issue by rodrigo1990** [chrome-php/headless-chromium-php#370]
Hello,
I share you my code.`

            $browserService = new BrowserService(new BrowserFactory());
            $browser = $browserService->getBrowser();

            try {
                // creates a new page and navigate to an URL
                $page = $browser->createPage();
                $page->navigate('https://www.bundesgesundheitsministerium.de/fileadmin/Dateien/3_Downloads/C/Coronavirus/Verordnungen/Corona-TestV_mit_Begruendung_080321.pdf')->waitForNavigation();
                // pdf
                $page->pdf(['printBackground' => false])->saveToFile('/');
            } catch(OperationTimedOut  $e) {
                $this->error($e->getMessage());
            } catch (NavigationExpired $e) {
                $this->error($e->getMessage());
            }`

 BrowserService.php

     ` class BrowserService {

    /**
     * @var BrowserFactory
     */
    private BrowserFactory $browserFactory;

    public function __construct(BrowserFactory $browserFactory) {
        $this->browserFactory = $browserFactory;
    }

    public function getBrowser(): ProcessAwareBrowser {
        return $this->browserFactory->createBrowser(['headless' => true, 'noSandbox' => true]);
    }

    }`

Maybe is missing a header ?

**Comment by agustavo87** [comment]
You can increment the timeout option in the `saveToFile('/')` method:
```php
$page->pdf(['printBackground' => false])->saveToFile('/',  10000);
```

**Comment by enricodias** [comment]
Navigating to a pdf file will not trigger the same events as navigating to a normal page would, resulting in a timeout in the `waitForNavigation()` call.

The `saveToFile()` method requires a filename, not just a path. You are trying to print something, not download something.

Chrome's `printToPdf` function apparently doesn't work with a pdf. You'll need to download the file.
