### ISSUE TITLE
How to switch Contexts between Frame and child iFrames?

### ISSUE THREAD

**Issue by earthisflat123** [chrome-php/headless-chromium-php#371]
Hi, 

first of all thanks for this project!

I managed to login to a webapp that was created with primefaces, but unfortunately all widgets in the web app that i'm trying to access via chrome-php are implemented as iFrames.

When I use the keyboard navigation by hammering the tab key to reach the element I want to enter data in and submit a form by doing some more tab keys and pressing Enter key on the "Search" button to submit the search in the iFrame I get different results as when I manually click on the search button.

So now I think that the reason for this is the context because I think when switching with tab keyboard events from main frame to iFrame then the enter keyboard type event does something else than in in the context of the iFrame.

How can I change between frames? 

I saw that with $page->getFrameManager() there are some methods to get the mainFrame and to get a certain frame by ID but I don't know how to determine the ID of the iFrame that I am trying to interact with. 

I hope I described the problem adequately enough and am grateful for any useful feedback.

Thanks in advance :)

**Comment by bob-yangpf** [comment]
I have the same problem, have you solved it?

**Comment by enricodias** [comment]
The keyboard and mouse interface just enter inputs the same way a user would. You can see exactly what's being done if you run without headless mode and add breakpoints in the script to follow step by step.

And by the way, there is a new [Dom](https://github.com/chrome-php/chrome/blob/1.6/src/Dom/Dom.php) class that may be useful here.

**Comment by bob-yangpf** [comment]
You are right. The scenario I am facing is that I want to use the mouse to drag an element in the iframe. If it is in the mianframe, I can use `$page->mouse()->find('#id')->move(x,y)`  But I can't get it position in the iframe, so I can't go on

in phpwebdriver，i can use ` $driver->switchTo()->frame($myFrame);`  and `$driver->switchTo()->defaultContent();` switch Contexts， But in chrome-php, I haven't found a suitable way to complete it yet

**Comment by ethaniel** [comment]
https://github.com/chrome-php/chrome/issues/442 might be related to your case.

**Comment by divinity76** [comment]
Don't think this issue should be closed - I have the same issue ( I need to click on something inside an iframe), and AFAIK chrome-php does not have a solution yet 🤔
