### ISSUE TITLE
Can't click on a drop down list (select)

### ISSUE THREAD

**Issue by Entretoize** [chrome-php/headless-chromium-php#372]
I developed a remote browser interface that use chrome-php, where clicks and key strokes done in the local browser are transmitted to the remote browser.
For example, I can [mousedown+slide+mouseup] to select text, scroll down with the mouse wheel, write text in inputs...
However I can't click inside a drop downdown list, I mean if there's a SELECT with OPTIONS, I can click to open the list but when I click an option the list just close without selecting the option I clicked.

As it's just a click I don't understand what I can do better, but maybe the Input.dispatchMouseEvent send the message to the page but drop down liste are on a higher level, I don't know ??

How can I do ?

The click are done like that:

```
$params = [
	'x' => intval($m[1]),
	'y' => intval($m[2]),
	'type' => 'mousePressed',
	'button' => 'left',
	'clickCount' => 1
];
$message        = new Message('Input.dispatchMouseEvent', $params);
$response       = $hl->page->getSession()->sendMessage($message);

```

Thanks in advance

**Comment by enricodias** [comment]
That's not exactly the answer for your question, but we have a mouse interface. You don't have to send messages by hand like that.
```php
$page->mouse()->move($x, $y)->click();
```
A click action is a `mousePressed` event followed by a `mouseReleased` event.

Also, are you moving the mouse to the correct location to click in the option?

**Comment by Entretoize** [comment]
Yes I know there's a mouse click method but I though it was better to just transmit everything the user do in the local browser, then I transmit when he press and later when he release. The position is correct because it works for everything else...
I find for puppeteer and the same issue exist then I think I have to find an alternative way to do.

**Comment by Entretoize** [comment]
I'm trying to get the select options when a click is done on a select like that:

```
$params = [
	'x' => intval($m[1]),
	'y' => intval($m[2]),
	'type' => 'mouseReleased',
	'button' => 'left',
	'clickCount' => 0
];
$message        = new Message('Input.dispatchMouseEvent', $params);
$response       = $hl->page->getSession()->sendMessage($message);
$send=" up";

//look if a select is below the cursor
$selectoptions=$hl->page->evaluate("	var selectoptions=false;
                                    var elm=document.elementFromPoint(".intval($m[1]).", ".intval($m[2]).");
                                    if (elm && elm.tag=='SELECT')
                                    {
                                              selectoptions=[];
                                              for(var i=0;i<elm.options.length;i++)
                                              selectoptions.push({'text':elm.options[i].text,'value':elm.options[i].value});
                                    }
                                    else
                                    {
                                          if (elm)
                                                selectoptions=elm.tag;
                                          else
                                                selectoptions='no element';
                                    }
	selectoptions")->getReturnValue();

if ($selectoptions)								//a select is below the cursor
	$send=json_encode($selectoptions);			//send back content
```

But for some reasons `selectoptions `is always empty, what's the problem ?

**Comment by Entretoize** [comment]
elm.tag is empty, ti's tagName that's it, sorry...
