### ISSUE TITLE
How to disable load css?

### ISSUE THREAD

**Issue by dregore** [chrome-php/headless-chromium-php#373]
Hello, is it possible to drop connection on css?
I mean, get only html response without css in it? 
I need it to save traffic.

**Comment by enricodias** [comment]
The same as #306, although there is still a reason to use a real browser to parse javascript in that case

**Comment by dregore** [comment]
Sorry, I missed #306.
So. I made it this way. Is it OK to use '**method:Network.requestWillBeSent**'? How do you think?

```
$page->getSession()->on('method:Network.requestWillBeSent', function ($response) use (&$page) {
        if($response['type'] == 'Stylesheet'){
            $page->getSession()->sendMessageSync(new Message('Target.closeTarget', ['requestId' => $response['requestId']]));
            $page->getSession()->sendMessageSync(new Message('Fetch.failRequest', ['requestId' => $response['requestId']]));
        }
    });
    $page->navigate($url)->waitForNavigation(Page::DOM_CONTENT_LOADED, $waitMS);
```

**Comment by enricodias** [comment]
I never used `requestWillBeSent` before, but it may be an alternative. If it works, we could think about adding this feature in the package.
