### ISSUE TITLE
[Bug] Please add php function validation which should be used

### ISSUE THREAD

**Issue by gdplayerto** [chrome-php/headless-chromium-php#374]
Please add php functions validation which should be used. For example chrome-php uses php functions like shell_exec, proc_open, proc_close, proc_get_status, etc. Thanks...

**Comment by enricodias** [comment]
You mean listing every core function used by the package? Why?

**Comment by gdplayerto** [comment]
![image](https://user-images.githubusercontent.com/27673157/166078755-bc4b6785-8fcc-4e7a-8c17-cc79456054a4.png)
During the process of using chrome-php I often experience errors as shown in the picture.

**Comment by enricodias** [comment]
I don't think it's feasible to keep track of every function that can be potentially be disabled for security reasons. It's fairly easy to assume that this package will need to fork processes to work. Disabled functions are usually used in shared hosting, where a package like this will not work.

**Comment by gdplayerto** [comment]
At least add that validation because chrome-php is not possible to use on shared hosting because shared hosting also can't use the terminal to install chrome. In the picture that I sent, the message appears on the server with the Plesk control panel installed with chrome in it.

**Comment by GrahamCampbell** [comment]
If you'd like to contribute this, feel free @adis0308, and I will try to make time to review that PR. Otherwise, I'm going to close this out, since the core team here don't plan to prioritize this any time soon. Thank you for raising this, all the same. :)
