### ISSUE TITLE
RuntimeException: Cannot start browser

### ISSUE THREAD

**Issue by idem84** [chrome-php/headless-chromium-php#375]
I got this error on Ubuntu 18, after update on last chrome-php version i got this error, i start 'google-chrome'

I cannot produce more information.

"chrome-php/chrome": "1.6.0"

On version 1.1.0 same error

**Comment by enricodias** [comment]
Looks like the same problem described in #263.

I looked at this issue before but I couldn't reproduce that behavior.

**Comment by idem84** [comment]
Chrome process stopped before startup completed. Additional info: [8055:8055:0504/185004.260287:ERROR:ozone_platform_x11.cc(247)] Missing X server or $DISPLAY [8055:8055:0504/185004.260352:ERROR:env.cc(225)] The platform failed to initialize. Exiting.
