### ISSUE TITLE
How to connect external headless chrome exposed as http

### ISSUE THREAD

**Issue by yuseferi** [chrome-php/headless-chromium-php#377]
in my container I don't have headless chrome, but it's running in another container.

I have the hostname and port of it which is accessible through HTTP.

I'm wondering how I can connect to it from PHP?

I see the following code in the example:
```
use HeadlessChromium\Communication\Connection;
use HeadlessChromium\Communication\Message;

// chrome devtools URI
$webSocketUri = 'ws://127.0.0.1:9222/devtools/browser/xxx';

// create a connection
$connection = new Connection($webSocketUri);
$connection->connect();
```

could it be just like this? 
```
use HeadlessChromium\Communication\Connection;
use HeadlessChromium\Communication\Message;

// chrome devtools URI
$webSocketUri = 'http://' . $MY_HOST .  ':' . $MY_PORT ;

// create a connection
$connection = new Connection($webSocketUri);
$connection->connect();
```

**Comment by enricodias** [comment]
You can use another ip in the uri, but you'll need to keep the `ws://`. It's a different protocol than http.

**Comment by yuseferi** [comment]
@enricodias  thanks a lot for the quick reply.
the website is hosted on platform.sh and at the end, I wanted to use https://docs.platform.sh/add-services/headless-chrome.html.

any idea how can I use it with the chrome-php package?

**Comment by yuseferi** [comment]
I've got the solution, first I need to curl  `http://IP:port/json/version` and then get `webSocketDebuggerUrl` as to where I want to connect. 

```
curl http://169.254.25.72:9222/json/version
{
   "Browser": "HeadlessChrome/86.0.4240.183",
   "Protocol-Version": "1.3",
   "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/86.0.4240.183 Safari/537.36",
   "V8-Version": "8.6.395.23",
   "WebKit-Version": "537.36 (@0b568b034b8f7994697cb341eeca5979b84151cc)",
   "webSocketDebuggerUrl": "ws://169.254.25.72:9222/devtools/browser/8e5a18b3-c43e-4e08-9f8a-891b4da0cec8"
}

```

**Comment by r4cker** [comment]
You can connect an existing Chrome Headless instance the following. I use it to connect a chrome in docker

```
$browser = BrowserFactory::connectToBrowser("ws://127.0.0.1:3000/",array(
            'windowSize'   => [1920, 1000],
            'headers' => [
                'Authorization' => 'Bearer '.$token,
            ]
        ));
```
