### ISSUE TITLE
Question about page breaks in PDF render

### ISSUE THREAD

**Issue by fluktegrute** [chrome-php/headless-chromium-php#379]
Hi, 
I am using this library to generate PDF files from HTML.
The HTML pages are sometimes longer than a standard PDF page so many pages are created. The issue is that the pages are separated without any control and the text is then sometimes cut (see attachment).
I know I can adjust the page height but it is set for every pages and doesn't totally solve the issue, so I wonder whether there is a way to add some element in the HTML DOM telling the library to add a page break at that place?
Thanks
![2022-05-18 11_26_25-](https://user-images.githubusercontent.com/57525938/169007077-acb1458b-c309-42ac-90b6-08e9d1c1e75f.png)
s

**Comment by derStephan** [comment]
> I wonder whether there is a way to add some element in the HTML DOM telling the library to add a page break at that place?

in fact there is:

``<div style='page-break-after: always;'></div>``

**Comment by d-damien** [comment]
The `page-break-*` properties have been deprecated. I had to use these two :
```
.target-elements {
  break-inside: avoid;
  break-after: auto;
}
```
