### ISSUE TITLE
mouse()->scroll with too high values will cause timeout

### ISSUE THREAD

**Issue by momala454** [chrome-php/headless-chromium-php#387]
This line will wait until the position is current position + wanted scroll : 
https://github.com/chrome-php/chrome/blob/1.6/src/Input/Mouse.php#L205
however, if by example the page only has 10 pixels of scroll possible (if the page is not bigh enough), but we ask for 100, it will wait until the timeout is reached as it's not possible to achieve a scroll of 100

this could be the reason some of the tests are failing with mouse

**Comment by ms-smz** [comment]
chrome-php\chrome\src\Input\Mouse.php
```
    private function scroll(int $distanceY, int $distanceX = 0): self
    {
        $this->page->assertNotClosed();

-->     $scrollableArea = $this->page->getLayoutMetrics()->getCssContentSize();
          $visibleArea = $this->page->getLayoutMetrics()->getCssVisualViewport();

...

        // wait until the scroll is done
        Utils::tryWithTimeout(30000 * 1000, $this->waitForScroll($targetX, $targetY));


```
There is a process that waits for processing after mouse movement, but a timeout occurred in the previous stage getCssContentSize().
I still think it would be better to be able to increase the default timeout value on the ResponseReader.php side.
