### ISSUE TITLE
Ignore certificate issues?

### ISSUE THREAD

**Issue by AngelOfTerror** [chrome-php/headless-chromium-php#39]
So, I've installed "sudo apt-get install chromium-browser".

What I've got working so far, is reading the value from the "Search"-button https://www.google.nl/

```
require_once('vendor/autoload.php');
use HeadlessChromium\BrowserFactory;
// open browser
$factory = new BrowserFactory('chromium-browser');
//$browser = $factory->createBrowser();
$browser = $factory->createBrowser([
      'debugLogger'     => 'php://stdout'
]);

// navigate to a page with a form
$page = $browser->createPage();
$page->navigate('https://www.google.nl/')->waitForNavigation();
// get value in the new page
$value = $page->evaluate('document.querySelector("input[name=\"btnK\"]").value')->getReturnValue();
var_dump($value);
```

The problem I currently have, is with a web-gui from a vendor we have running internally. 
There are multiple servers running the same web-gui, with each a self-signed certificate.
The servers are load-balanced by a virtual-ip. So the certificate is not only self-signed, it also contains the wrong server-name and server-ip address.
Of course, when using Google Chrome on my desktop, I get a certificate error.

How do I ignore the certificate errors with this script?
Because there are some statistics on that web-gui I'd like to grab.

**Comment by choval** [comment]
Try passing ```--ignore-certificate-errors``` with the browser cmd.

You have more switches here: https://peter.sh/experiments/chromium-command-line-switches/

```
$factory = new BrowserFactory('chromium-browser --ignore-certificate-errors');
```

**Comment by AngelOfTerror** [comment]
Thank you very much :=)  Didn't knew that was possible.

**Comment by gsouf** [comment]
@AngelOfTerror thanks for rising the issue.

To provide a little better way to do it I just added an option for it:``ignoreCertificateErrors`` that you can use this way:

```php
$factory = new BrowserFactory('chromium-browser');
$factory->createBrowser([
    'ignoreCertificateErrors' => true
]);
```

Note that I also added an option named ``customFlags`` that would allow to pass any flag you need for chrome as there are a lot of them and it does not make sense to support them all.

```php
$factory = new BrowserFactory('chromium-browser');
$factory->createBrowser([
    'customFlags' => [
        '--someOption',
        '--someOption=foo',
    ]
]);
```
