### ISSUE TITLE
typeRawKey("U+000D") ... typeRawKey("Return") ? 

### ISSUE THREAD

**Issue by johnray** [chrome-php/headless-chromium-php#392]
I'm finding it very difficult to simulate pressing the return key.   Nothing that I've tried or found elsewhere seems to work (https://github.com/ChromeDevTools/devtools-protocol/issues/45).

Is this possible?

**Comment by enricodias** [comment]
Have you tried `Enter`?

Here is a useful tool to check key names and codes: https://unixpapa.com/js/testkey.html

**Comment by johnray** [comment]
I'm afraid I have - I've tried return, newline, enter, the unicode character for a return and a variety of other representations for a return (Control+M), but nothing seems to work.  I've got other characters and key combinations working properly, I just can't trigger a return.

The interface that I'm attempting to script provides no other controls (besides) a return for triggering an action.  Although, duh, I suppose I could trigger whatever script is processing the input - I guess I'll look at that next.  

I feel like I'm missing something obvious, and it's such a silly roadblock when all the other actions I'm using are working just fine.

**Comment by enricodias** [comment]
Using the tool that I sent previously, what name does it show when you press your return key? You need to enable the "DOM" option to see the key code.

**Comment by johnray** [comment]
It does show the key as "Enter" - (13), and I've tried:

`$page->keyboard()->typeRawKey("Enter");`

Repeatedly.  I'm running with headless off, I can see it type into the UI element, then nothing (despite throwing a bunch of those "Enter"s at it).  If I manually click onto the window and press enter on my keyboard it immediately works.

**Comment by enricodias** [comment]
Then the page is probably expecting something else than just the enter key. Is it a public url that I can test?

**Comment by johnray** [comment]
Unfortunately, it's an internal application - but you did inspire me to just test it on the main GitHub "Search GitHub" field and, as you suggested, `$page->keyboard()->typeRawKey("Enter");`, works perfectly fine.  I'm going to go ahead and close this, as it's clear the problem is on my end, not the tool.

**Comment by johnray** [comment]
For what it's worth,

`page.keyboard.press('Enter');`

does work fine in Puppeteer.

**Comment by enricodias** [comment]
Note that the type methods in the packages do a `press` and a `release` in sequence. There are public methods do perform those actions individually and some pages may have different behaviors for those two events.

**Comment by johnray** [comment]
I did try press/release without any luck.  It looks like the implementation in puppeteer is a bit different in the javascript events that it generates. 

(I appreciate all of your assistance - I'm happy to have this working in any form :) )

**Comment by SoyDelgadillo** [comment]
As I am on the same way like you... my work around is to prevent errors at page load: when Page::NETWORK_IDLE I think it is an issue with javascript that I can see on the target website code evaluated when load the page it self...
