### ISSUE TITLE
Error when trying to set a pages html.

### ISSUE THREAD

**Issue by mambans** [chrome-php/headless-chromium-php#393]
When I try and set a pages html ($page->setHtml() i get the following error: "Attempted to call an undefined method named \"setHtml\" of class \"HeadlessChromium\\Page\".\nDid you mean to call \"getHtml\"?".

And I can't find any sethtml method in Page class.

$page = $browser->createPage();
$page->setHtml('<p>asd</p>');

i'm on Mac with PHP 7.4.30.

**Comment by GrahamCampbell** [comment]
I think you're using an out of date version of the package.

**Comment by mambans** [comment]
Ah true, weird it gabbed such an old version. Thanks!
