### ISSUE TITLE
Fatal error: in  vendor\chrome-php\chrome\src\Browser\BrowserProcess.php on line 410

### ISSUE THREAD

**Issue by lutskboy** [chrome-php/headless-chromium-php#402]
I have an error 
Fatal error: in vendor\chrome-php\chrome\src\Browser\BrowserProcess.php on line 410
PHP 7.4 OS windows 8.1

**Comment by enricodias** [comment]
Without the debug logs and the exception thrown, no one will be able to help. There is not enough information to guess what may have happened. You need to give as much details as possible.

**Comment by lutskboy** [comment]
include 'vendor/autoload.php';

use HeadlessChromium\BrowserFactory;

$browserFactory = new BrowserFactory();

// // starts headless chrome
$browser = $browserFactory->createBrowser();

thi is my code

**Comment by GrahamCampbell** [comment]
We need to see the whole stack trace.
