### ISSUE TITLE
Cloudflare and Co bypass

### ISSUE THREAD

**Issue by RestOp** [chrome-php/headless-chromium-php#403]
Hello,

Sorry, not found questions...
So is chrome-php bypass cloudflare? For example will it pass https://nowsecure.nl/ cloud please anyone try it?
Or will it pass Google Recaptcha v3 challenge?

Thanks a lot.

**Comment by enricodias** [comment]
This lib is just an interface to control a chrome browser. Google and others may allow a real browser to pass without any captcha challenge for a few times, especially if they have some other way of verifying the user such as being logged in a google account, but with enough requests they will eventually display captcha challenges.

**Comment by RestOp** [comment]
Thanks, but the problem almost of all controlled browsers is that it detected as bot. Because of it i alk could you please check is chrome-php if it will be also detected as bot or not. Just load the page https://nowsecure.nl/ and say the result.
Thanks a lot.

**Comment by RestOp** [comment]
Or other page with cloudflare challenge...

**Comment by GrahamCampbell** [comment]
Likely you will be detected as a bot, eventually... because you are one. Nothing you can really do about that. A bot is a bot. ;)

**Comment by RestOp** [comment]
Guys, really no possible just to make one check and put here a screenshot? It is mich less time as to write here suggestions. All of you have chrome-php installed and it takes no time to check it. As for me i have to understand how it works, install it, tune and so on. Waste lot of time to find just to make this test ...

Thanks in advance if anyone could do it all the same!

**Comment by GrahamCampbell** [comment]
I'm sorry. Why would you expect us to do that for you?

**Comment by GrahamCampbell** [comment]
I'm happy to do it for you, for a fee. Get in touch at hello at gjcampbell.co.uk.

**Comment by RestOp** [comment]
> I'm sorry. Why would you expect us to do that for you?

Just fetch this https://nowsecure.nl page/ with chrome-php (or any other with cloudflare challenge) wait 10 sec and make a screenshot. So it will be clear if chrome-php will be detected as bot or not (i hope so)

Thanks a lot.
https://nowsecure.nl/

**Comment by foremtehan** [comment]
The site you mentioned enabled the IUAM hence the cloudflare analyze almost all of the requests even if you behind the real browser, I don't think you can bypass this mode by any library

**Comment by RestOp** [comment]
> The site you mentioned enabled the IUAM hence the cloudflare analyze almost all of the requests even if you behind the real browser, I don't think you can bypass this mode by any library

Is is possible, but now i have found only libs on Python, that i can not use because i use PHP

**Comment by foremtehan** [comment]
I know what lib you are talking about, It just cannot pass this mode and stuck on the js challenge, i testes it rn: 
![image](https://user-images.githubusercontent.com/53290883/183289732-bd0473cf-7416-460f-9250-37469c6119e9.png)

**Comment by RestOp** [comment]
> I know what lib you are talking about, It just cannot pass this mode and stuck on the js challenge, i testes it rn: ![image](https://user-images.githubusercontent.com/53290883/183289732-bd0473cf-7416-460f-9250-37469c6119e9.png)

Thanks a lot!!!
Have you made 10 sec delay before screenshot?

**Comment by foremtehan** [comment]
not working:
```python
import undetected_chromedriver as uc
import time

driver = uc.Chrome()
time.sleep(10)
driver.get('https://nowsecure.nl')
```

**Comment by RestOp** [comment]
Interesting, on their github they say it have to work ;-(((

**Comment by RestOp** [comment]
> not working:
> 
> ```python
> import undetected_chromedriver as uc
> import time
> 
> driver = uc.Chrome()
> time.sleep(10)
> driver.get('https://nowsecure.nl')
> ```

I think you have to make a sleep after fetching URL, then is challange takes time.

**Comment by RestOp** [comment]
I have just tried it work for me!

> not working:
> 
> ```python
> import undetected_chromedriver as uc
> import time
> 
> driver = uc.Chrome()
> time.sleep(10)
> driver.get('https://nowsecure.nl')
> ```

I have just tried it work for me! 
Also some other sites with cloudflare challange!

PS
As is mentioned make a sleep after page load...

**Comment by GrahamCampbell** [comment]
Locking as this is not productive. This is an issue tracker for the library, not a support forum. Sorry to be like this, but we can all do without the notifications.
