### ISSUE TITLE
Not working custom headers

### ISSUE THREAD

**Issue by badman666** [chrome-php/headless-chromium-php#404]
```
require_once 'vendor/autoload.php';

use HeadlessChromium\BrowserFactory;

$browserFactory = new BrowserFactory();
$browser = $browserFactory->createBrowser([
    'windowSize' => [1920, 1080],
    'enableImages' => true,
    'headless' => false,
    'headers' => [
        'Accept: */*',
        'sec-fetch-dest: document',
        //'test' => 'document', // or this
    ]
]);
$page = $browser->createPage();
$page->navigate('http://foxtools.ru/Http');
sleep(20);
$browser->close();

exit();
```

**Comment by enricodias** [comment]
The headers must be a key value array, like `['Accept' => */*']`. But I tested this way and the method is really not working.

The browserFactory class tries to set the headers before calling `Network.enable` and the `setExtraHTTPHeaders` in the Page class results in a deserialization error. I don't know what is causing this error. The param seems correct.
