### ISSUE TITLE
Timeout error

### ISSUE THREAD

**Issue by extinqued-resp** [chrome-php/headless-chromium-php#405]
hi, I'm using this product to traverse the pages of some site, it works, but at some point I start getting "Operation timed out" when I try to get to any page. In debugging like this, what's the matter?
![image](https://user-images.githubusercontent.com/106451690/184435441-eeb72dfd-d785-4513-ada6-3006591a497e.png)

**Comment by enricodias** [comment]
The log shows timeouts when trying to create a new tab.  Your chrome just didn't respond in less than 10 seconds. Maybe there are lots of active tabs making it too slow.

**Comment by extinqued-resp** [comment]
I do createPage once and then go to others through navigate, at the moment I solved the problem by reloading the browser on error, but I'm interested in a more adequate solution
tabs can accumulate with this implementation? how to clean them?

**Comment by enricodias** [comment]
Can you paste a sample code here so I can see exactly what you are doing?

**Comment by GrahamCampbell** [comment]
Closing due to no response from the issue author.
