### ISSUE TITLE
any way to capture javascript console logs?

### ISSUE THREAD

**Issue by divinity76** [chrome-php/headless-chromium-php#406]
is there any way to capture javascript console logs? like if i navigate to a page that contains javascript errors, is there any way to capture those javascript errors on the php side?

**Comment by enricodias** [comment]
Register this listener before navigating to a page:
```php
$page->getSession()->on('method:Runtime.consoleAPICalled', function (array $message): void {
    if ($message['type'] === 'log') {
        \var_dump($message);
    }
});
```

The type could be any of the following:
> log, debug, info, error, warning, dir, dirxml, table, trace, clear, startGroup, startGroupCollapsed, endGroup, assert, profile, profileEnd, count, timeEnd

Reference: https://chromedevtools.github.io/devtools-protocol/tot/Runtime/#event-consoleAPICalled

**Comment by divinity76** [comment]
Perfect! thanks
