### ISSUE TITLE
Bookmarks in PDF

### ISSUE THREAD

**Issue by derStephan** [chrome-php/headless-chromium-php#415]
Hi guys,

thank you very much for chrome-php which works like a charme when it comes to creating PDF documents from HTML. As I could not find any documentation or even an issue about it, I think my question is out of scope but I want to try anyway. 

Is there a way to have bookmarks e.g. for header-tags (``<h1>``, ``<h2>``, ...) or any other HTML element? This would be perfect.

Thank you in advance
Stephan

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. You are right that this is out of scope. I'd recommend asking on some forums. :)
