### ISSUE TITLE
Cannot make a PDF. Reason : -32000 - Printing failed

### ISSUE THREAD

**Issue by derStephan** [chrome-php/headless-chromium-php#417]
Hi,

I am printing a large (!) table as PDF and it fails after about 30s with the error ``Cannot make a PDF. Reason : -32000 - Printing failed``.

The table has around 90.000 cells in about 8.000 rows. When I print the same table with only 1.000 rows, it works perfectly. 

I wonder, if there is some timeout I might have missed because it looks like chrome is stopping after 30s. 

My chrome version is 104.0.5112.101 (stable)

Thank you in advance for your help. 
Stephan

PS. This is my code: 

```
$browser = $browserFactory->createBrowser();
$page = $browser->createPage();
$page->setHtml($HTML, 30000); //30s timeout for loading the HTML. Increasing that does not help. 
$options = [
		'landscape'           => false,
		'printBackground'     => true,
		'displayHeaderFooter' => true, 
		'preferCSSPageSize'   => false,
		'marginTop'           => 0.4,
		'marginBottom'        => 0.4, 
		'marginLeft'          => 0.4, 
		'marginRight'         => 0.4,
		'paperWidth'          => 8.2677165354,              // A4
		'paperHeight'         => 11.692913386,              // A4
		'headerTemplate'      => $headerTemplate,
		'footerTemplate'      => $footerTemplate, 
		'scale'               => 1.0, 
	];

$pdf = $page->pdf($options);

set_time_limit(3600); //1h php ecxecution time does not help

$pdf->saveToFile("myPDF",2000000); //2000s timeout. 
```

<details>
  <summary>debug log (stripped from the massive HTML content)</summary>
<pre>[2022-08-26T09:26:25.387187+02:00]
 chrome.DEBUG: process: initializing [] []
[2022-08-26T09:26:25.387570+02:00] chrome.DEBUG: process: using 
directory: /tmp/chromium-php-mYywcO [] []
[2022-08-26T09:26:25.387902+02:00] chrome.DEBUG: process: starting 
process: 'google-chrome' '--remote-debugging-port=0' 
'--disable-background-networking' 
'--disable-background-timer-throttling' 
'--disable-client-side-phishing-detection' '--disable-hang-monitor' 
'--disable-popup-blocking' '--disable-prompt-on-repost' '--disable-sync'
 '--disable-translate' '--disable-features=ChromeWhatsNewUI' 
'--metrics-recording-only' '--no-first-run' 
'--safebrowsing-disable-auto-update' '--enable-automation' 
'--password-store=basic' '--use-mock-keychain' '--headless' 
'--disable-gpu' '--font-render-hinting=none' '--hide-scrollbars' 
'--mute-audio' '--disable-dev-shm-usage' '--disable-gpu' 
'--user-data-dir=/tmp/chromium-php-mYywcO' [] []
[2022-08-26T09:26:25.390952+02:00] chrome.DEBUG: process: waiting for 
120 seconds for startup [] []
[2022-08-26T09:26:25.411473+02:00] chrome.DEBUG: process: chrome 
output:mkdir: cannot create directory '/var/www/.local': Permission 
denied touch: cannot touch 
'/var/www/.local/share/applications/mimeapps.list': No such file or 
directory [] []
[2022-08-26T09:26:25.411542+02:00] chrome.DEBUG: process: ignoring 
output:mkdir: cannot create directory '/var/www/.local': Permission 
denied [] []
[2022-08-26T09:26:25.411564+02:00] chrome.DEBUG: process: ignoring 
output:touch: cannot touch 
'/var/www/.local/share/applications/mimeapps.list': No such file or 
directory [] []
[2022-08-26T09:26:25.523254+02:00] chrome.DEBUG: process: chrome 
output:DevTools listening on 
ws://127.0.0.1:40683/devtools/browser/e77d2f06-3a47-401b-b663-3aed0350d527
 [0826/092625.522128:WARNING:bluez_dbus_manager.cc(247)] Floss manager 
not present, cannot set Floss enable/disable. [] []
[2022-08-26T09:26:25.523323+02:00] chrome.DEBUG: process: ✓ accepted 
output [] []
[2022-08-26T09:26:25.523351+02:00] chrome.DEBUG: process: connecting 
using 
ws://127.0.0.1:40683/devtools/browser/e77d2f06-3a47-401b-b663-3aed0350d527
 [] []
[2022-08-26T09:26:25.529685+02:00] chrome.DEBUG: socket(1): connecting 
[] []
[2022-08-26T09:26:25.542386+02:00] chrome.DEBUG: socket(1): ✓ connected 
[] []
[2022-08-26T09:26:25.542609+02:00] chrome.DEBUG: socket(1): → sending 
data:{"id":1,"method":"Target.setDiscoverTargets","params":{"discover":true}}
 [] []
[2022-08-26T09:26:25.547815+02:00] chrome.DEBUG: socket(1): ← receiving 
data:{"method":"Target.targetCreated","params":{"targetInfo":{"targetId":"3a3ce4c3-420d-48a5-b8a1-c0f8ccbf1c59","type":"browser","title":"","url":"","attached":true,"canAccessOpener":false}}}
 [] []
[2022-08-26T09:26:25.547894+02:00] chrome.DEBUG: connection: ⇶ 
dispatching method:Target.targetCreated [] []
[2022-08-26T09:26:25.548137+02:00] chrome.DEBUG: socket(1): ← receiving 
data:{"method":"Target.targetCreated","params":{"targetInfo":{"targetId":"6309C6AC85457AC996F7FFD531AAC449","type":"page","title":"","url":"about:blank","attached":false,"canAccessOpener":false,"browserContextId":"5952BBAFAC447B8E68FDD1CF57F2B7BF"}}}
 [] []
[2022-08-26T09:26:25.548176+02:00] chrome.DEBUG: connection: ⇶ 
dispatching method:Target.targetCreated [] []
[2022-08-26T09:26:25.548605+02:00] chrome.DEBUG: socket(1): ← receiving 
data:{"method":"Target.targetCreated","params":{"targetInfo":{"targetId":"d0bc892f-22e9-4f20-ba12-17432538e7e3","type":"browser","title":"","url":"","attached":false,"canAccessOpener":false}}}
 [] []
[2022-08-26T09:26:25.548645+02:00] chrome.DEBUG: connection: ⇶ 
dispatching method:Target.targetCreated [] []
[2022-08-26T09:26:25.548827+02:00] chrome.DEBUG: socket(1): ← receiving 
data:{"id":1,"result":{}} [] []
[2022-08-26T09:26:25.549005+02:00] chrome.DEBUG: socket(1): → sending 
data:{"id":2,"method":"Network.setExtraHTTPHeaders","params":{}} [] []
[2022-08-26T09:26:25.549698+02:00] chrome.DEBUG: socket(1): ← receiving 
data:{"id":2,"error":{"code":-32601,"message":"'Network.setExtraHTTPHeaders'
 wasn't found"}} [] []
[2022-08-26T09:26:25.549761+02:00] chrome.DEBUG: socket(1): → sending 
data:{"id":3,"method":"Target.createTarget","params":{"url":"about:blank"}}
 [] []
[2022-08-26T09:26:25.550404+02:00] chrome.DEBUG: socket(1): ← receiving 
data:{"method":"Target.targetCreated","params":{"targetInfo":{"targetId":"58A6FB6375758E408EF1B521B3CFB491","type":"page","title":"","url":"","attached":false,"canAccessOpener":false,"browserContextId":"5952BBAFAC447B8E68FDD1CF57F2B7BF"}}}
 [] []
[2022-08-26T09:26:25.550448+02:00] chrome.DEBUG: connection: ⇶ 
dispatching method:Target.targetCreated [] []
[2022-08-26T09:26:25.554344+02:00] chrome.DEBUG: socket(1): ← receiving 
data:{"id":3,"result":{"targetId":"58A6FB6375758E408EF1B521B3CFB491"}} 
[] []
[2022-08-26T09:26:25.554422+02:00] chrome.DEBUG: socket(1): → sending 
data:{"id":4,"method":"Target.attachToTarget","params":{"targetId":"58A6FB6375758E408EF1B521B3CFB491","flatten":true}}
 [] []
[2022-08-26T09:26:25.557688+02:00] chrome.DEBUG: socket(1): ← receiving 
data:{"method":"Target.targetInfoChanged","params":{"targetInfo":{"targetId":"58A6FB6375758E408EF1B521B3CFB491","type":"page","title":"","url":"about:blank","attached":true,"canAccessOpener":false,"browserContextId":"5952BBAFAC447B8E68FDD1CF57F2B7BF"}}}
 [] []
[2022-08-26T09:26:25.557742+02:00] chrome.DEBUG: connection: ⇶ 
dispatching method:Target.targetInfoChanged [] []
[2022-08-26T09:26:25.558003+02:00] chrome.DEBUG: socket(1): ← receiving 
data:{"method":"Target.attachedToTarget","params":{"sessionId":"8B2EB9C1CBB10FC5DA2ED132EF674C5D","targetInfo":{"targetId":"58A6FB6375758E408EF1B521B3CFB491","type":"page","title":"","url":"about:blank","attached":true,"canAccessOpener":false,"browserContextId":"5952BBAFAC447B8E68FDD1CF57F2B7BF"},"waitingForDebugger":false}}
 [] []
[2022-08-26T09:26:25.558041+02:00] chrome.DEBUG: connection: ⇶ 
dispatching method:Target.attachedToTarget [] []
[2022-08-26T09:26:25.558286+02:00] chrome.DEBUG: socket(1): ← receiving 
data:{"id":4,"result":{"sessionId":"8B2EB9C1CBB10FC5DA2ED132EF674C5D"}} 
[] []
[2022-08-26T09:26:25.558402+02:00] chrome.DEBUG: socket(1): → sending 
data:{"id":5,"method":"Page.getFrameTree","params":{},"sessionId":"8B2EB9C1CBB10FC5DA2ED132EF674C5D"}
 [] []
[2022-08-26T09:26:25.590827+02:00] chrome.DEBUG: socket(1): ← receiving 
data:{"method":"Target.targetInfoChanged","params":{"targetInfo":{"targetId":"6309C6AC85457AC996F7FFD531AAC449","type":"page","title":"about:blank","url":"about:blank","attached":false,"canAccessOpener":false,"browserContextId":"5952BBAFAC447B8E68FDD1CF57F2B7BF"}}}
 [] []
[2022-08-26T09:26:25.590915+02:00] chrome.DEBUG: connection: ⇶ 
dispatching method:Target.targetInfoChanged [] []
[2022-08-26T09:26:25.593580+02:00] chrome.DEBUG: socket(1): ← receiving 
data:{"method":"Target.targetInfoChanged","params":{"targetInfo":{"targetId":"58A6FB6375758E408EF1B521B3CFB491","type":"page","title":"about:blank","url":"about:blank","attached":true,"canAccessOpener":false,"browserContextId":"5952BBAFAC447B8E68FDD1CF57F2B7BF"}}}
 [] []
[2022-08-26T09:26:25.593641+02:00] chrome.DEBUG: connection: ⇶ 
dispatching method:Target.targetInfoChanged [] []
[2022-08-26T09:26:25.597496+02:00] chrome.DEBUG: socket(1): ← receiving 
data:{"id":5,"result":{"frameTree":{"frame":{"id":"58A6FB6375758E408EF1B521B3CFB491","loaderId":"CA4DE20CCC1D1CDA464A16BDAA552485","url":"about:blank","domainAndRegistry":"","securityOrigin":"://","mimeType":"text/html","adFrameStatus":{"adFrameType":"none"},"secureContextType":"InsecureScheme","crossOriginIsolatedContextType":"NotIsolated","gatedAPIFeatures":[]}}},"sessionId":"8B2EB9C1CBB10FC5DA2ED132EF674C5D"}
 [] []
[2022-08-26T09:26:25.597969+02:00] chrome.DEBUG: socket(1): → sending 
data:{"id":6,"method":"Page.enable","params":{},"sessionId":"8B2EB9C1CBB10FC5DA2ED132EF674C5D"}
 [] []
[2022-08-26T09:26:25.599051+02:00] chrome.DEBUG: socket(1): ← receiving 
data:{"id":6,"result":{},"sessionId":"8B2EB9C1CBB10FC5DA2ED132EF674C5D"}
 [] []
[2022-08-26T09:26:25.599119+02:00] chrome.DEBUG: socket(1): → sending 
data:{"id":7,"method":"Network.enable","params":{},"sessionId":"8B2EB9C1CBB10FC5DA2ED132EF674C5D"}
 [] []
[2022-08-26T09:26:25.599981+02:00] chrome.DEBUG: socket(1): ← receiving 
data:{"id":7,"result":{},"sessionId":"8B2EB9C1CBB10FC5DA2ED132EF674C5D"}
 [] []
[2022-08-26T09:26:25.600037+02:00] chrome.DEBUG: socket(1): → sending 
data:{"id":8,"method":"Runtime.enable","params":{},"sessionId":"8B2EB9C1CBB10FC5DA2ED132EF674C5D"}
 [] []
[2022-08-26T09:26:25.609663+02:00] chrome.DEBUG: socket(1): ← receiving 
data:{"method":"Runtime.executionContextCreated","params":{"context":{"id":1,"origin":"://","name":"","uniqueId":"-543665680199210751.2331896562393979101","auxData":{"isDefault":true,"type":"default","frameId":"58A6FB6375758E408EF1B521B3CFB491"}}},"sessionId":"8B2EB9C1CBB10FC5DA2ED132EF674C5D"}
 [] []
[2022-08-26T09:26:25.609730+02:00] chrome.DEBUG: 
session(8B2EB9C1CBB10FC5DA2ED132EF674C5D): ⇶ dispatching 
method:Runtime.executionContextCreated [] []
[2022-08-26T09:26:25.609962+02:00] chrome.DEBUG: socket(1): ← receiving 
data:{"id":8,"result":{},"sessionId":"8B2EB9C1CBB10FC5DA2ED132EF674C5D"}
 [] []
[2022-08-26T09:26:25.610011+02:00] chrome.DEBUG: socket(1): → sending 
data:{"id":9,"method":"Page.setLifecycleEventsEnabled","params":{"enabled":true},"sessionId":"8B2EB9C1CBB10FC5DA2ED132EF674C5D"}
 [] []
[2022-08-26T09:26:25.611189+02:00] chrome.DEBUG: socket(1): ← receiving 
data:{"method":"Page.lifecycleEvent","params":{"frameId":"58A6FB6375758E408EF1B521B3CFB491","loaderId":"CA4DE20CCC1D1CDA464A16BDAA552485","name":"commit","timestamp":4314570.510065},"sessionId":"8B2EB9C1CBB10FC5DA2ED132EF674C5D"}
 [] []
[2022-08-26T09:26:25.611233+02:00] chrome.DEBUG: 
session(8B2EB9C1CBB10FC5DA2ED132EF674C5D): ⇶ dispatching 
method:Page.lifecycleEvent [] []
[2022-08-26T09:26:25.611626+02:00] chrome.DEBUG: socket(1): ← receiving 
data:{"method":"Page.lifecycleEvent","params":{"frameId":"58A6FB6375758E408EF1B521B3CFB491","loaderId":"CA4DE20CCC1D1CDA464A16BDAA552485","name":"DOMContentLoaded","timestamp":4314570.510097},"sessionId":"8B2EB9C1CBB10FC5DA2ED132EF674C5D"}
 [] []
[2022-08-26T09:26:25.611659+02:00] chrome.DEBUG: socket(1): ← receiving 
data:{"method":"Page.lifecycleEvent","params":{"frameId":"58A6FB6375758E408EF1B521B3CFB491","loaderId":"CA4DE20CCC1D1CDA464A16BDAA552485","name":"load","timestamp":4314570.511243},"sessionId":"8B2EB9C1CBB10FC5DA2ED132EF674C5D"}
 [] []
[2022-08-26T09:26:25.611677+02:00] chrome.DEBUG: socket(1): ← receiving 
data:{"method":"Page.lifecycleEvent","params":{"frameId":"58A6FB6375758E408EF1B521B3CFB491","loaderId":"CA4DE20CCC1D1CDA464A16BDAA552485","name":"networkAlmostIdle","timestamp":4314570.511745},"sessionId":"8B2EB9C1CBB10FC5DA2ED132EF674C5D"}
 [] []
[2022-08-26T09:26:25.611692+02:00] chrome.DEBUG: socket(1): ← receiving 
data:{"method":"Page.lifecycleEvent","params":{"frameId":"58A6FB6375758E408EF1B521B3CFB491","loaderId":"CA4DE20CCC1D1CDA464A16BDAA552485","name":"networkIdle","timestamp":4314570.511745},"sessionId":"8B2EB9C1CBB10FC5DA2ED132EF674C5D"}
 [] []
[2022-08-26T09:26:25.611717+02:00] chrome.DEBUG: 
session(8B2EB9C1CBB10FC5DA2ED132EF674C5D): ⇶ dispatching 
method:Page.lifecycleEvent [] []
[2022-08-26T09:26:25.611872+02:00] chrome.DEBUG: 
session(8B2EB9C1CBB10FC5DA2ED132EF674C5D): ⇶ dispatching 
method:Page.lifecycleEvent [] []
[2022-08-26T09:26:25.612059+02:00] chrome.DEBUG: 
session(8B2EB9C1CBB10FC5DA2ED132EF674C5D): ⇶ dispatching 
method:Page.lifecycleEvent [] []
[2022-08-26T09:26:25.612209+02:00] chrome.DEBUG: 
session(8B2EB9C1CBB10FC5DA2ED132EF674C5D): ⇶ dispatching 
method:Page.lifecycleEvent [] []
[2022-08-26T09:26:25.612800+02:00] chrome.DEBUG: socket(1): ← receiving 
data:{"id":9,"result":{},"sessionId":"8B2EB9C1CBB10FC5DA2ED132EF674C5D"}
 [] []
[2022-08-26T09:26:25.621001+02:00] chrome.DEBUG: socket(1): → sending 
data:{"id":10,"method":"Page.setDocumentContent","params":{"frameId":"58A6FB6375758E408EF1B521B3CFB491","html":"2MiB of HTML Table"},"sessionId":"8B2EB9C1CBB10FC5DA2ED132EF674C5D"}
 [] []
[2022-08-26T09:26:25.828577+02:00] chrome.DEBUG: socket(1): ← receiving 
data:{"method":"Page.documentOpened","params":{"frame":{"id":"58A6FB6375758E408EF1B521B3CFB491","loaderId":"CA4DE20CCC1D1CDA464A16BDAA552485","url":"about:blank","domainAndRegistry":"","securityOrigin":"://","mimeType":"text/html","adFrameStatus":{"adFrameType":"none"},"secureContextType":"InsecureScheme","crossOriginIsolatedContextType":"NotIsolated","gatedAPIFeatures":[]}},"sessionId":"8B2EB9C1CBB10FC5DA2ED132EF674C5D"}
 [] []
[2022-08-26T09:26:25.828658+02:00] chrome.DEBUG: 
session(8B2EB9C1CBB10FC5DA2ED132EF674C5D): ⇶ dispatching 
method:Page.documentOpened [] []
[2022-08-26T09:26:25.828925+02:00] chrome.DEBUG: socket(1): ← receiving 
data:{"method":"Page.lifecycleEvent","params":{"frameId":"58A6FB6375758E408EF1B521B3CFB491","loaderId":"CA4DE20CCC1D1CDA464A16BDAA552485","name":"init","timestamp":4314570.743883},"sessionId":"8B2EB9C1CBB10FC5DA2ED132EF674C5D"}
 [] []
[2022-08-26T09:26:25.828989+02:00] chrome.DEBUG: 
session(8B2EB9C1CBB10FC5DA2ED132EF674C5D): ⇶ dispatching 
method:Page.lifecycleEvent [] []
[2022-08-26T09:26:26.559966+02:00] chrome.DEBUG: socket(1): ← receiving 
data:{"method":"Page.domContentEventFired","params":{"timestamp":4314571.475475},"sessionId":"8B2EB9C1CBB10FC5DA2ED132EF674C5D"}
 [] []
[2022-08-26T09:26:26.560041+02:00] chrome.DEBUG: 
session(8B2EB9C1CBB10FC5DA2ED132EF674C5D): ⇶ dispatching 
method:Page.domContentEventFired [] []
[2022-08-26T09:26:26.560248+02:00] chrome.DEBUG: socket(1): ← receiving 
data:{"method":"Page.lifecycleEvent","params":{"frameId":"58A6FB6375758E408EF1B521B3CFB491","loaderId":"CA4DE20CCC1D1CDA464A16BDAA552485","name":"DOMContentLoaded","timestamp":4314571.475475},"sessionId":"8B2EB9C1CBB10FC5DA2ED132EF674C5D"}
 [] []
[2022-08-26T09:26:26.560284+02:00] chrome.DEBUG: 
session(8B2EB9C1CBB10FC5DA2ED132EF674C5D): ⇶ dispatching 
method:Page.lifecycleEvent [] []
[2022-08-26T09:26:26.560715+02:00] chrome.DEBUG: socket(1): ← receiving 
data:{"id":10,"result":{},"sessionId":"8B2EB9C1CBB10FC5DA2ED132EF674C5D"}
 [] []
[2022-08-26T09:26:28.973978+02:00] chrome.DEBUG: socket(1): ← receiving 
data:{"method":"Page.loadEventFired","params":{"timestamp":4314573.889102},"sessionId":"8B2EB9C1CBB10FC5DA2ED132EF674C5D"}
 [] []
[2022-08-26T09:26:28.974052+02:00] chrome.DEBUG: 
session(8B2EB9C1CBB10FC5DA2ED132EF674C5D): ⇶ dispatching 
method:Page.loadEventFired [] []
[2022-08-26T09:26:28.974760+02:00] chrome.DEBUG: socket(1): ← receiving 
data:{"method":"Page.lifecycleEvent","params":{"frameId":"58A6FB6375758E408EF1B521B3CFB491","loaderId":"CA4DE20CCC1D1CDA464A16BDAA552485","name":"load","timestamp":4314573.889102},"sessionId":"8B2EB9C1CBB10FC5DA2ED132EF674C5D"}
 [] []
[2022-08-26T09:26:28.974812+02:00] chrome.DEBUG: 
session(8B2EB9C1CBB10FC5DA2ED132EF674C5D): ⇶ dispatching 
method:Page.lifecycleEvent [] []
[2022-08-26T09:26:29.228360+02:00] chrome.DEBUG: socket(1): ← receiving 
data:{"method":"Page.lifecycleEvent","params":{"frameId":"58A6FB6375758E408EF1B521B3CFB491","loaderId":"CA4DE20CCC1D1CDA464A16BDAA552485","name":"firstPaint","timestamp":4314574.138263},"sessionId":"8B2EB9C1CBB10FC5DA2ED132EF674C5D"}
 [] []
[2022-08-26T09:26:29.228435+02:00] chrome.DEBUG: 
session(8B2EB9C1CBB10FC5DA2ED132EF674C5D): ⇶ dispatching 
method:Page.lifecycleEvent [] []
[2022-08-26T09:26:29.229372+02:00] chrome.DEBUG: socket(1): → sending 
data:{"id":11,"method":"Page.printToPDF","params":{"landscape":true,"printBackground":true,"displayHeaderFooter":true,"preferCSSPageSize":false,"marginTop":0.4,"marginBottom":0.4,"marginLeft":0.4,"marginRight":0.4,"paperWidth":8.2677165354,"paperHeight":11.692913386,"headerTemplate":"&lt;table
 style=\"margin-left: auto; margin-right: auto;width:calc(100% - 
1cm)\"&gt;\n\t\t\t\t\t\t&lt;tr&gt;\n\t\t\t\t\t\t\t&lt;td 
style=\"width:33%;font-size:4pt\"&gt;long table&lt;\/td&gt;\n\t\t\t\t\t\t\t&lt;td 
style=\"width:33%;font-size:4pt;text-align: center\"&gt;report: long table&lt;\/td&gt;\n\t\t\t\t\t\t\t&lt;td 
style=\"font-size:4pt;text-align: right\"&gt;2022-08-26 
09:26&lt;\/td&gt;\n\t\t\t\t\t\t&lt;\/tr&gt;\n\t\t\t\t\t\t&lt;\/table&gt;","footerTemplate":"&lt;table
 style=\"margin-left: auto; margin-right: auto;width:calc(100% - 
1cm)\"&gt;\n\t\t\t\t\t\t&lt;tr&gt;\n\t\t\t\t\t\t\t&lt;td 
style=\"width:33%;font-size:4pt\"&gt;footer left&lt;\/td&gt;\n\t\t\t\t\t\t\t&lt;td 
style=\"width:33%;font-size:4pt;text-align: center\"&gt;footer center &lt;\/td&gt;\n\t\t\t\t\t\t\t&lt;td 
style=\"font-size:4pt;text-align: right\"&gt;page &lt;span 
class=\"pageNumber\"&gt;&lt;\/span&gt; of &lt;span 
class=\"totalPages\"&gt;&lt;\/span&gt;&lt;\/td&gt;\n\t\t\t\t\t\t&lt;\/tr&gt;\n\t\t\t\t\t&lt;\/table&gt;","scale":1},"sessionId":"8B2EB9C1CBB10FC5DA2ED132EF674C5D"}
 [] []
[2022-08-26T09:26:29.229704+02:00] chrome.DEBUG: socket(1): ← receiving 
data:{"method":"Page.lifecycleEvent","params":{"frameId":"58A6FB6375758E408EF1B521B3CFB491","loaderId":"CA4DE20CCC1D1CDA464A16BDAA552485","name":"firstContentfulPaint","timestamp":4314574.138263},"sessionId":"8B2EB9C1CBB10FC5DA2ED132EF674C5D"}
 [] []
[2022-08-26T09:26:29.229736+02:00] chrome.DEBUG: socket(1): ← receiving 
data:{"method":"Page.lifecycleEvent","params":{"frameId":"58A6FB6375758E408EF1B521B3CFB491","loaderId":"CA4DE20CCC1D1CDA464A16BDAA552485","name":"firstMeaningfulPaintCandidate","timestamp":4314574.138263},"sessionId":"8B2EB9C1CBB10FC5DA2ED132EF674C5D"}
 [] []
[2022-08-26T09:26:29.229764+02:00] chrome.DEBUG: 
session(8B2EB9C1CBB10FC5DA2ED132EF674C5D): ⇶ dispatching 
method:Page.lifecycleEvent [] []
[2022-08-26T09:26:29.229914+02:00] chrome.DEBUG: 
session(8B2EB9C1CBB10FC5DA2ED132EF674C5D): ⇶ dispatching 
method:Page.lifecycleEvent [] []
[2022-08-26T09:26:56.316184+02:00] chrome.DEBUG: socket(1): ← receiving 
data:{"id":11,"error":{"code":-32000,"message":"Printing 
failed"},"sessionId":"8B2EB9C1CBB10FC5DA2ED132EF674C5D"} [] []
[2022-08-26T09:26:56.965857+02:00] chrome.DEBUG: process: killing chrome
 [] []
[2022-08-26T09:26:56.966002+02:00] chrome.DEBUG: process: trying to 
close chrome gracefully [] []
[2022-08-26T09:26:56.966350+02:00] chrome.DEBUG: socket(1): → sending 
data:{"id":12,"method":"Browser.close","params":{}} [] []
[2022-08-26T09:26:56.968385+02:00] chrome.DEBUG: socket(1): ← receiving 
data:{"method":"Inspector.targetCrashed","params":{},"sessionId":"8B2EB9C1CBB10FC5DA2ED132EF674C5D"}
 [] []
[2022-08-26T09:26:56.968431+02:00] chrome.DEBUG: socket(1): ← receiving 
data:{"method":"Target.targetCrashed","params":{"targetId":"58A6FB6375758E408EF1B521B3CFB491","status":"crashed","errorCode":132}}
 [] []
[2022-08-26T09:26:56.968468+02:00] chrome.DEBUG: 
session(8B2EB9C1CBB10FC5DA2ED132EF674C5D): ⇶ dispatching 
method:Inspector.targetCrashed [] []
[2022-08-26T09:26:56.968823+02:00] chrome.DEBUG: connection: ⇶ 
dispatching method:Target.targetCrashed [] []
[2022-08-26T09:26:56.969736+02:00] chrome.DEBUG: socket(1): ← receiving 
data:{"id":12,"result":{}} [] []
[2022-08-26T09:26:56.969800+02:00] chrome.DEBUG: socket(1): 
disconnecting [] []
[2022-08-26T09:26:56.970653+02:00] chrome.DEBUG: socket(1): ✓ 
disconnected [] []
[2022-08-26T09:26:56.970684+02:00] chrome.DEBUG: process: waiting for 
process to close [] []
[2022-08-26T09:26:57.045544+02:00] chrome.DEBUG: process: cleaning 
temporary resources:/tmp/chromium-php-mYywcO [] []</pre>

</details>

<details>
  <summary>PHP error</summary>
<pre>
HeadlessChromium\Exception\PdfFailed Object
(
    [message:protected] => Cannot make a PDF. Reason : -32000 - Printing failed
    [string:Exception:private] => 
    [code:protected] => 0
    [file:protected] => /var/www/html/vendor/chrome-php/chrome/src/PageUtils/PagePdf.php
    [line:protected] => 119
    [trace:Exception:private] => Array
        (
            [0] => Array
                (
                    [file] => /var/www/html/vendor/chrome-php/chrome/src/PageUtils/AbstractBinaryInput.php
                    [line] => 70
                    [function] => getException
                    [class] => HeadlessChromium\PageUtils\PagePdf
                    [type] => ->
                )

            [1] => Array
                (
                    [file] => /var/www/html/print.php
                    [line] => 110
                    [function] => saveToFile
                    [class] => HeadlessChromium\PageUtils\AbstractBinaryInput
                    [type] => ->
                )
        )

    [previous:Exception:private] => 
)
</pre>
</details>

**Comment by enricodias** [comment]
Hello.

This is not a timeout exception, it's an error from chrome itself. The message `-32000 - Printing failed` comes directly from chrome. If it was a timeout, you would get a timeout exception.

Does it work if you try to print the same pdf manually with chrome?

**Comment by derStephan** [comment]
Well, it is a bit spooky. 

I tried creating a PDF from the HTML using chrome 32bit on Windows. That failed. 
Then I tried creating the PDF using chrome 64bit on Windows. That worked. Memory consumption was about 7GB. 

But on my headless ubuntu server, memory consumption of chrome does not exceed 4GB. Maybe there is an out-of-memory exception which I can not see. Do you use any switch that limits memory consumption?

**Comment by derStephan** [comment]
Or is there a limit of space in the user-data-dir?

**Comment by enricodias** [comment]
I'm unaware of any way to limit memory consumption using chrome's API. The consumption will vary depending on the distro, extensions and previous opened tabs. Those 7 GB that you mentioned, does it happens consistently exactly when you try to print to pdf? What's the consumption before and after printing?

The user data dir is disk based. Unless your disk is almost full, its size shouldn't interfere with a simple print.

**Comment by derStephan** [comment]
I found the problem. Well, kind of. 

It seems that CSS is the enemy here. If I omit all CSS, then the PDF is created even with twice the row count. But if I add a single style to a single cell, this error occurs. This really smells like out-of-memory errors. 

I would not mind if chrome would eat 32GB of RAM. That is  not the problem. But it simply does not use more than 4GB on ubuntu 22.04. Do you have any clou why?

**Comment by enricodias** [comment]
Maybe your Linux is using swap and you didn't notice?

**Comment by derStephan** [comment]
Thank you for your help. I really appreciate it. It is getting stranger by every test.

I now have a testfile to reproduce the error and there is no CSS involved.

I have attached 2 HTML-files with exactly the same content. The only difference is the HTML-ID of the table. In the file that works, the table has no ID and in the file that fails the table has an ID.

May I ask you to check if you get the same results? I had to rename the files to txt. HTML is not allowed here. 

[works.txt](https://github.com/chrome-php/chrome/files/9469447/works.txt)
[fails.txt](https://github.com/chrome-php/chrome/files/9469448/fails.txt)

**Comment by derStephan** [comment]
Ok, I tried to run my testfiles directly on the command line without PHP. 

I got this error:  ``ERROR:file_io_posix.cc(144)] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq: No such file or directory (2)``

Searching for that, I stumbled upon an old chrome-bug which was fixed but seems to be there again. 
https://bugs.chromium.org/p/chromium/issues/detail?id=1228625

When I deinstall current chrome (104) and install an [old version (93) after the fix ](http://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_93.0.4577.82-1_amd64.deb) then it is working as expected and the PDFs are much (!) smaller. 

So something is severeley broken with the whole PDF stuff in the current version of chrome.

**Comment by enricodias** [comment]
Are you running WSL ubuntu by any chance? Because the WSL kernel can't manage the CPU, it's just a windows process. `scaling_cur_freq` won't work.

**Comment by derStephan** [comment]
>Are you running WSL ubuntu by any chance

no. I am running ubuntu 22.04 LTS server.

**Comment by DrillSergeant** [comment]
Same problem here. Running chromium in a docker container and having the same error message when createing a pdf. I solved it by downgrading to chromium 104.0.5112.79-1~deb11u1

**Comment by DrillSergeant** [comment]
Same here, using chromium 104.0.5112.79-1~deb11u1 in a docker container. Exact same behaviour when generating pdfs. Using the old version (93) as mentioned by @derStephan works.

**Comment by derStephan** [comment]
If you have an account for https://bugs.chromium.org, maybe you can open a new ticket there.

**Comment by enricodias** [comment]
Since it's probably a bug with chromium itself, I suggest reporting it directly with them. If anyone finds a workaround that can be implemented in this lib, feel free to post here.

I'll leave this issue closed for now.
