### ISSUE TITLE
Can't get into https://developer.apple.com with error from the website (The page you're looking for can't be found)

### ISSUE THREAD

**Issue by AmeerDesginer** [chrome-php/headless-chromium-php#423]
![screenshot](https://user-images.githubusercontent.com/25102289/187998933-7e8e8539-4466-4a40-be88-2591e027f2c0.png)

Has been test the code from Mac OS & Linux Server 

My Code is the example from the Github

`
use HeadlessChromium\BrowserFactory;

$browserFactory = new BrowserFactory();

// starts headless chrome
$browser = $browserFactory->createBrowser();

try {
    // creates a new page and navigate to an URL
    $page = $browser->createPage();
    $page->navigate('https://developer.apple.com')->waitForNavigation();

    // screenshot - Say "Cheese"! 😄
    $page->screenshot()->saveToFile('./screenshot.png');
} finally {
    // bye
    $browser->close();
}
`

**Comment by AmeerDesginer** [comment]
Finally after 5 hours from trying everything lol i figure out the issue and it is the "User-Agent" was set by default from PHP script, so we need a real user-agent so I used this user agent and my problem was gone 

`    $page->setExtraHTTPHeaders([
        "User-Agent" => "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36",
    ]);
`
    
Thanks!

**Comment by enricodias** [comment]
Note that there are easier ways to set the user agent. It can be done with the `Page::setUserAgent()` method or in the options when creating the browser with `BrowserFactory::createBrowser()`
