### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by YiwanGi** [chrome-php/headless-chromium-php#426]
I am installing the library through composer, but the composer prompts me:
`
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - chrome-php/chrome[v1.7.0, ..., v1.7.1] require chrome-php/wrench ^1.3 -> found chrome-php/wrench[1.3.x-dev] but it does not match your minimum-stability.
    - Root composer.json requires chrome-php/chrome ^1.7 -> satisfiable by chrome-php/chrome[v1.7.0, v1.7.1].

Installation failed, deleting ./composer.json.
`

**Comment by enricodias** [comment]
I just did an install from scratch here and it went without issues. Can you share your `composer.json` and `composer.lock` file?

**Comment by YiwanGi** [comment]
Thank you for your reply. It's like this. Because I didn't install it successfully, there is no composer in the folder
file
The following is my execution process:

`
[root@VM-0-9-centos php]# mkdir test && cd test
[root@VM-0-9-centos test]# composer require chrome-php/chrome
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Continue as root/super user [yes]? y
Using version ^1.7 for chrome-php/chrome
./composer.json has been created
Running composer update chrome-php/chrome
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - chrome-php/chrome[v1.7.0, ..., v1.7.1] require chrome-php/wrench ^1.3 -> found chrome-php/wrench[1.3.x-dev] but it does not match your minimum-stability.
    - Root composer.json requires chrome-php/chrome ^1.7 -> satisfiable by chrome-php/chrome[v1.7.0, v1.7.1].


Installation failed, deleting ./composer.json.
[root@VM-0-9-centos test]# php -v
PHP 8.0.17 (cli) (built: Apr 23 2022 17:47:33) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.17, Copyright (c) Zend Technologies
[root@VM-0-9-centos test]# 
`

What information can I provide you？

**Comment by enricodias** [comment]
Try running `composer require chrome-php/chrome --no-cache -vvv`

**Comment by YiwanGi** [comment]
thank you！This may be because the mirror site has not synchronized the latest library version `https://mirrors.aliyun.com/composer/p2/chrome-php/wrench.json`
I will close this issue..
`
[root@VM-0-9-centos test]# composer require chrome-php/chrome --no-cache -vvv
Disabling cache usage
Loading config file /root/.config/composer/config.json
Loading config file /root/.config/composer/auth.json
Failed to initialize global composer: Composer could not find the config file: /root/.config/composer/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Running 2.0.14 (2021-05-21 17:03:37) with PHP 8.0.17 on Linux / 3.10.0-1160.45.1.el7.x86_64
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Continue as root/super user [yes]? y
Loading config file /root/.config/composer/config.json
Loading config file /root/.config/composer/auth.json
Failed to initialize global composer: Composer could not find the config file: /root/.config/composer/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Reading ./composer.json (/www/wwwroot/project/php/test/composer.json)
Loading config file /root/.config/composer/config.json
Loading config file /root/.config/composer/auth.json
Loading config file ./composer.json (/www/wwwroot/project/php/test/composer.json)
Checked CA file /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem: valid
Executing command (/www/wwwroot/project/php/test): git branch -a --no-color --no-abbrev -v
Executing command (/www/wwwroot/project/php/test): git describe --exact-match --tags
Executing command (CWD): git --version
Executing command (/www/wwwroot/project/php/test): git log --pretty="%H" -n1 HEAD
Executing command (/www/wwwroot/project/php/test): hg branch
Executing command (/www/wwwroot/project/php/test): fossil branch list
Executing command (/www/wwwroot/project/php/test): fossil tag list
Executing command (/www/wwwroot/project/php/test): svn info --xml
Failed to initialize global composer: Composer could not find the config file: /root/.config/composer/composer.json

Downloading https://mirrors.aliyun.com/composer/packages.json
[200] https://mirrors.aliyun.com/composer/packages.json
Downloading https://mirrors.aliyun.com/composer/p2/chrome-php/chrome.json
[200] https://mirrors.aliyun.com/composer/p2/chrome-php/chrome.json
Using version ^1.7 for chrome-php/chrome
./composer.json has been created
Reading ./composer.json (/www/wwwroot/project/php/test/composer.json)
Loading config file /root/.config/composer/config.json
Loading config file /root/.config/composer/auth.json
Loading config file ./composer.json (/www/wwwroot/project/php/test/composer.json)
Executing command (/www/wwwroot/project/php/test): git branch -a --no-color --no-abbrev -v
Executing command (/www/wwwroot/project/php/test): git describe --exact-match --tags
Executing command (/www/wwwroot/project/php/test): git log --pretty="%H" -n1 HEAD
Executing command (/www/wwwroot/project/php/test): hg branch
Executing command (/www/wwwroot/project/php/test): fossil branch list
Executing command (/www/wwwroot/project/php/test): fossil tag list
Executing command (/www/wwwroot/project/php/test): svn info --xml
Failed to initialize global composer: Composer could not find the config file: /root/.config/composer/composer.json

Running composer update chrome-php/chrome
Loading composer repositories with package information
Downloading https://mirrors.aliyun.com/composer/packages.json
[200] https://mirrors.aliyun.com/composer/packages.json
Downloading https://mirrors.aliyun.com/composer/p2/chrome-php/chrome.json
[200] https://mirrors.aliyun.com/composer/p2/chrome-php/chrome.json
Downloading https://mirrors.aliyun.com/composer/p2/chrome-php/wrench.json
Downloading https://mirrors.aliyun.com/composer/p2/evenement/evenement.json
Downloading https://mirrors.aliyun.com/composer/p2/monolog/monolog.json
Downloading https://mirrors.aliyun.com/composer/p2/psr/log.json
Downloading https://mirrors.aliyun.com/composer/p2/symfony/filesystem.json
Downloading https://mirrors.aliyun.com/composer/p2/symfony/polyfill-mbstring.json
Downloading https://mirrors.aliyun.com/composer/p2/symfony/process.json
[200] https://mirrors.aliyun.com/composer/p2/chrome-php/wrench.json
[200] https://mirrors.aliyun.com/composer/p2/psr/log.json
[200] https://mirrors.aliyun.com/composer/p2/symfony/polyfill-mbstring.json
[200] https://mirrors.aliyun.com/composer/p2/evenement/evenement.json
[200] https://mirrors.aliyun.com/composer/p2/monolog/monolog.json
[200] https://mirrors.aliyun.com/composer/p2/symfony/filesystem.json
[200] https://mirrors.aliyun.com/composer/p2/symfony/process.json
Downloading https://mirrors.aliyun.com/composer/p2/psr/log.json
Downloading https://mirrors.aliyun.com/composer/p2/symfony/polyfill-ctype.json
Downloading https://mirrors.aliyun.com/composer/p2/symfony/polyfill-mbstring.json
Downloading https://mirrors.aliyun.com/composer/p2/symfony/polyfill-php80.json
[200] https://mirrors.aliyun.com/composer/p2/psr/log.json
[200] https://mirrors.aliyun.com/composer/p2/symfony/polyfill-ctype.json
[200] https://mirrors.aliyun.com/composer/p2/symfony/polyfill-mbstring.json
[200] https://mirrors.aliyun.com/composer/p2/symfony/polyfill-php80.json
Updating dependencies
Generating rules
Resolving dependencies through SAT

Dependency resolution completed in 0.001 seconds
Downloading https://mirrors.aliyun.com/composer/p2/chrome-php/wrench.json
[200] https://mirrors.aliyun.com/composer/p2/chrome-php/wrench.json
Downloading https://mirrors.aliyun.com/composer/p2/chrome-php/wrench.json
Downloading https://mirrors.aliyun.com/composer/p2/chrome-php/wrench~dev.json
[200] https://mirrors.aliyun.com/composer/p2/chrome-php/wrench~dev.json
[200] https://mirrors.aliyun.com/composer/p2/chrome-php/wrench.json
Downloading https://mirrors.aliyun.com/composer/p2/chrome-php/wrench.json
Downloading https://mirrors.aliyun.com/composer/p2/chrome-php/wrench~dev.json
[200] https://mirrors.aliyun.com/composer/p2/chrome-php/wrench~dev.json
[200] https://mirrors.aliyun.com/composer/p2/chrome-php/wrench.json
Downloading https://mirrors.aliyun.com/composer/p2/chrome-php/wrench.json
[200] https://mirrors.aliyun.com/composer/p2/chrome-php/wrench.json
Downloading https://mirrors.aliyun.com/composer/p2/chrome-php/wrench.json
Downloading https://mirrors.aliyun.com/composer/p2/chrome-php/wrench~dev.json
[200] https://mirrors.aliyun.com/composer/p2/chrome-php/wrench.json
[200] https://mirrors.aliyun.com/composer/p2/chrome-php/wrench~dev.json
Downloading https://mirrors.aliyun.com/composer/p2/chrome-php/wrench.json
Downloading https://mirrors.aliyun.com/composer/p2/chrome-php/wrench~dev.json
[200] https://mirrors.aliyun.com/composer/p2/chrome-php/wrench.json
[200] https://mirrors.aliyun.com/composer/p2/chrome-php/wrench~dev.json
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - chrome-php/chrome[v1.7.0, v1.7.1] require chrome-php/wrench ^1.3 -> found chrome-php/wrench[1.3.x-dev] but it does not match your minimum-stability.
    - Root composer.json requires chrome-php/chrome ^1.7 -> satisfiable by chrome-php/chrome[v1.7.0, v1.7.1].


Installation failed, deleting ./composer.json.
[root@VM-0-9-centos test]# 
`
