### ISSUE TITLE
Call to undefined method HeadlessChromium\Input\Mouse::find()

### ISSUE THREAD

**Issue by lokutus24** [chrome-php/headless-chromium-php#427]
hello,

how can i use mouse event? whic class need i to use for that?

Thank you.

**Comment by enricodias** [comment]
Hello,

Check the documentation for the mouse API in the readme: https://github.com/chrome-php/chrome#mouse-api

**Comment by lokutus24** [comment]
> Hello,
> 
> Check the documentation for the mouse API in the readme: https://github.com/chrome-php/chrome#mouse-api

Hello enricodias!

i get this error message: 
PHP Fatal error:  Uncaught HeadlessChromium\Exception\OperationTimedOut: Operation timed out (30sec)

How can i solve this Problem?

Regards,
Gabor

**Comment by enricodias** [comment]
> PHP Fatal error: Uncaught HeadlessChromium\Exception\OperationTimedOut: Operation timed out (30sec)

This just means that the browser didn't reply within 30 seconds. There are several reasons for this and lot's of other issues here about timeouts. If none of the previous issues applies to your problem, you'll need to share specific details about it, like the full log, the code you are running and anything else needed to reproduce it.
