### ISSUE TITLE
How to get all Network conditions like DevTools

### ISSUE THREAD

**Issue by iidatomohiko** [chrome-php/headless-chromium-php#434]
Hi.

Can I get all requests conditions like "Network" in Chrome DevTools?
All means actual js or json in script tags, js or json called in js.
 
I'm going to crawl a specific API calling in the pages.

**Comment by enricodias** [comment]
With #430 you'll be able to see all network requests made, regardless of the source.

**Comment by iidatomohiko** [comment]
@enricodias , thanks.

I checked out your developing branch feature/introduce-NetworkResponseEntity in my code, it's done!!
It looks very very good to me.

Again, I have a question.
I guess it depends on the behavior of the page, but sometimes I lose track of some of the requests.

Can I wait until all contents in a page loaded certainly without php "sleep" function by this code?

```
$browserFactory = new BrowserFactory();
$page = $browserFactory->createBrowser()->createPage();
$page->navigate($url)->waitForNavigation(Page::DOM_CONTENT_LOADED, 30000);
```

**Comment by iidatomohiko** [comment]
Sorry.
```
$page->navigate($url)->waitForNavigation(Page::DOM_CONTENT_LOADED, 30000);
```

If I expect the behavior of window load, I have to specify Page::LOAD, i.e. default.
i.e. none.

**Comment by enricodias** [comment]
`Page::DOM_CONTENT_LOADED` and `Page::LOAD` are just some of the possible events. The page content may change indefinitely. You can have javascript updating the dom and making new requests forever after the page was fully loaded. All of those request will be logged.
