### ISSUE TITLE
Custom flag proxy with user pass

### ISSUE THREAD

**Issue by lokutus24** [chrome-php/headless-chromium-php#437]
hello,

i did not found any option how can i set custom flag in chrome php for proxy with user pass.
Can somebody help me Please?

**Comment by enricodias** [comment]
There is no native support for this yet, but you can listen for the auth events and authenticate manually. There's an example in the issue #367

**Comment by alex-bacart** [comment]
Unfortunately #367 issue is deleted now. Code from this answer worked for me https://superuser.com/a/1777046/1465413
