### ISSUE TITLE
Automatically select certificate

### ISSUE THREAD

**Issue by marquesjuniorpalmas** [chrome-php/headless-chromium-php#439]
I need to automatically choose the digital certificate of a page that is authenticated by digital certificate.

It would be possible?

**Comment by enricodias** [comment]
Currently there isn't any way to do this using the current chromium API. You could set a [AutoSelectCertificateForUrls ](https://chromeenterprise.google/policies/?policy=AutoSelectCertificateForUrls) policy in the machine you are using, but it will not work in headless mode.

Maybe we could try to implement that feature directly in this lib, intercepting the requests before sending them to chrome and doing the authentication manually. If I manage to do it, I'll open a PR and link it to this issue.
