### ISSUE TITLE
Page.getLayoutMetrics

### ISSUE THREAD

**Issue by kaero598** [chrome-php/headless-chromium-php#44]
Hi.
I tried to take full-size screenshot of a page with this library. But noticed that the `Page.getLayoutMetrics` feature is not implemented.
So I was hoping a little help would be welcome. #43.

**Comment by gsouf** [comment]
@kaero598  In addition, what's about having an option for automatically take full size screenshots?

**Comment by kaero598** [comment]
@gsouf That would be useful. I was thinking of a new `fullsize` option for `screenshot()` method but I'm not sure how that would behave when `clip` options is also set.

**Comment by gsouf** [comment]
You can upgrade to version ``0.4.0`` and do fullpage screenshot:

```php
$page->screenshot([
         'clip' => $page->getFullPageClip()
     ])
      ->saveToFile('/tmp/image.jpg');
```

**Comment by kaero598** [comment]
Thanks a lot.
