### ISSUE TITLE
Can we catch and record events where JS reloads the page?

### ISSUE THREAD

**Issue by cyberpower678** [chrome-php/headless-chromium-php#444]
Some websites have browser validation JS in place that only serves content when the JS finishes, sets cookies, and subsequently reloads the page, or sends the browser to a new one.

Can we get some means of allowing this to happen, tracking the destination URL, and getting a screenshot/HTTP code of said destination?

On chrome-php, I get:
![testScreenshot](https://user-images.githubusercontent.com/1476075/195471072-139a3136-939c-46f9-b9fb-3763097193a9.png)

On Chrome, I get:
<img width="1624" alt="image" src="https://user-images.githubusercontent.com/1476075/195471079-1ae94f5f-c540-4b74-b596-fa566ec0ce62.png">

**Comment by enricodias** [comment]
You can listen to network events, but you'll have to know how to check if the current rendered page is the final one. This script will fire on every network response received:

```php
$page->getSession()->on('method:Network.responseReceived', function (array $message): void {
     \var_dump($message['response']['url']);
});
```
See #430 

Note that there is nothing preventing those browser validation checks from reloading the same url multiple times, so just listening for a second response with the same url may not work. You'll probably have to dig into the content of every html response with the same url to make sure it contains the final page.

The php will receive the events only when communicating with the browser. After the load event, the navigation is completed and the lib will return the `$page`. Calling `$navigation->waitForNavigation(Page::NETWORK_IDLE);` will return from the navigation only after 500ms of network inactivity, which is probably not enough for the browser check. The final page may also have network activity forever in intervals under 500ms, then the script will run for the entire timeout time and throw a timeout exception.

It would be easier to create a loop in your own code that checks the page's DOM with the `Page::dom()` method every X seconds.

**Comment by cyberpower678** [comment]
> You can listen to network events, but you'll have to know how to check if the current rendered page is the final one. This script will fire on every network response received:
> 
> ```
> $page->getSession()->on('method:Network.responseReceived', function (array $message): void {
>      \var_dump($message['response']['url']);
> });
> ```
> 
> See #430
> 
> Note that there is nothing preventing those browser validation checks from reloading the same url multiple times, so just listening for a second response with the same url may not work. You'll probably have to dig into the content of every html response with the same url to make sure it contains the final page.
> 
> The php will receive the events only when communicating with the browser. After the load event, the navigation is completed and the lib will return the `$page`. Calling `$navigation->waitForNavigation(Page::NETWORK_IDLE);` will return from the navigation only after 500ms of network inactivity, which is probably not enough for the browser check. The final page may also have network activity forever in intervals under 500ms, then the script will run for the entire timeout time and throw a timeout exception.
> 
> It would be easier to create a loop in your own code that checks the page's DOM with the `Page::dom()` method every X seconds.

Doesn't seem to work.  I'm querying https://journals.sagepub.com/doi/abs/10.1177/03058298880170020901 and the regular browser loads correctly with a 200, but chrome-php is still just getting stuck on the former screenshot.
