### ISSUE TITLE
Add --crash-dumps-dir option

### ISSUE THREAD

**Issue by TangLiang** [chrome-php/headless-chromium-php#447]
It's missing the --crash-dumps-dir option to fix this error filesystem_posix.cc(63)] mkdir /tmp/Crashpad/new: Permission denied (13)

$args[] = '--user-data-dir='.$options['userDataDir'];
$args[] = '--crash-dumps-dir='.$options['userCrashDumpsDir'];

this error occur when use B run chrome with headless After user A.

thanks

**Comment by enricodias** [comment]
Implemented in #448
