### ISSUE TITLE
twitter page isnt load

### ISSUE THREAD

**Issue by abdalmonem** [chrome-php/headless-chromium-php#449]
all twitter pages response : 'Hmm...this page doesn’t exist. Try searching for something else.'

`$browserFactory = new BrowserFactory();

// starts headless chrome
        $browser = $browserFactory->createBrowser([
            'windowSize'   => [1920, 1000],
        ]);
        $browserFactory->addOptions(['enableImages' => true]);
        $browserFactory->addOptions(['headless' => false]);
        $browserFactory->addOptions(['keepAlive' => true]);
        $browserFactory->addOptions(['noSandbox' => true]);
        $browserFactory->addOptions(['customFlags' => [
            '--proxy-server=https=proxyip:myproxyport'
        ]]);

        $browserFactory->addHeader('User-Agent', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36',);

        try {
            // creates a new page and navigate to an URL
            $page = $browser->createPage();

            $page->setExtraHTTPHeaders([
                'User-Agent' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36',
            ]);
            $page->setViewport(1920, 1000);
            $page->setUserAgent('Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36');
            $page->navigate('https://twitter.com')->waitForNavigation();
            $browser->createPage();

            // get page title
            $pageTitle = $page->evaluate('document.title')->getReturnValue();
            $content = $page->getHtml();
        } finally {
            // bye
            $browser->close();
        }

        return $content;`

**Comment by enricodias** [comment]
This isn't a problem with the lib. I was able to browse any twitter page using your code without any issue. Twitter is probably restricting your IP (or possible a bot behavior) and you would probably get the same response running chrome without this lib.

Also, the `$browser->createPage();` after the navigation just creates a new empty tab that is never used. Setting the user agent twice is also unnecessary.
