### ISSUE TITLE
add header issue

### ISSUE THREAD

**Issue by lycoch** [chrome-php/headless-chromium-php#451]
hello
how are we supposed to add header
i tried both 
```
            'headers'=>[["task-id:"=> "hello"]],
            'headers'=>["task-id: hello"],
```
with error:

> In Page.php line 211:
>   -32602 - Invalid parameters - Failed to deserialize params.headers - CBOR: map start expected at position 23

```
$browser = $browserFactory->createBrowser([
            'headless' => $headless,
            'headers'=>["task-id: hello"],
            'ignoreCertificateErrors'=>true,
        ]);
```

i also tried
`$browserFactory->addHeader("task-id","1055");`
there is no crash on this one but the header doesn't appear on my target URL

thanks for any help

**Comment by enricodias** [comment]
The correct syntax is `$factory->addHeader('header_name', 'header_value');` and `$factory->addHeaders(['header_name2' => 'header_value2']);`. Both of them work here.

Note that those options must be set before creating a browser.

**Comment by lycoch** [comment]
thanks for the prompt reply

it still doesn't work ( no error this time )


```
public function __construct($binary='chromium-browser',$headless=false){
        $browserFactory = new BrowserFactory($binary);
        $browserFactory->addHeader('header_name', 'header_value');
        //$browserFactory->addHeaders(["task-id"=> "1055"]);
        $browser = $browserFactory->createBrowser([
            'headless' => $headless,
            'connectionDelay' => 0.8,
            'windowSize'   => [1920, 1080],
        ]);
```
the browser open to a phpinfo page, and there is no trace of headers ( i tried both addHeader / addHeaders )

any clue ?

**Comment by enricodias** [comment]
The options given in the `createBrowser()` will override any other option previously set. You may use `addOptions()` instead.

I just tested using httpbin and it works as expected:

```php
$factory->addHeaders(['header_name' => 'header_value']);
$factory->addOptions([
	'headless' => $headless,
	'connectionDelay' => 0.8,
	'windowSize' => [1920, 1080],
]);

$page = $factory->createBrowser()->createPage();

$page->navigate('https://httpbin.org/anything')->waitForNavigation();
```

```
{
  "headers": {
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9", 
    "Accept-Encoding": "gzip, deflate", 
    "Accept-Language": "en-US;q=0.8,en;q=0.7", 
    "Header-Name": "header_value",
    ...
  }
}
```

The phpinfo page also works with the same code:

![image](https://user-images.githubusercontent.com/32619307/202794336-04f9f563-7206-4734-aec1-b32cfe802f4e.png)

**Comment by lycoch** [comment]
now it works great
thanks for your help !
