### ISSUE TITLE
Listen to JavaScript events

### ISSUE THREAD

**Issue by holtkamp** [chrome-php/headless-chromium-php#454]
This might be similar to https://github.com/chrome-php/chrome/issues/444 and https://github.com/chrome-php/chrome/issues/115, but is there (already) a way to listen to JavaScript events? 

For example, I am interested in [the `shown.bs.tab` event, fired by a Bootstrap Tab](https://www.w3schools.com/bootstrap/bootstrap_ref_js_tab.asp) when it has become visible. 

I checked the various domains at https://chromedevtools.github.io/devtools-protocol/ but could not find something that worked...

**Use Case**
1. open page, content of the first Tab is displayed
2. click specific Tab, which changes the DOM: the clicked Tab will get the class "active" assigned
3. select the first heading in the opened Tab, using something like `//li[@class="active]//h1`

**Observations**
Clicking the Tab works: when creating screenshot, the content of the clicked Tab is displayed. 

However, selecting the first heading in the clicked / _active_ tab fails, the heading on the first Tab is displayed...

So I got the feeling that after clicking the Tab, the DOM is not updated properly, or I am trying to select the first heading too quickly... 

Any thoughts / pointers on this?

**Comment by enricodias** [comment]
Have you tried the [DOM.attributeModified](https://chromedevtools.github.io/devtools-protocol/tot/DOM/#event-attributeModified) event?
