### ISSUE TITLE
search() closes browser

### ISSUE THREAD

**Issue by AndiLeni** [chrome-php/headless-chromium-php#457]
Hello,

I am currently struggling with this line of code: ``$page->dom()->querySelectorAll('#filialangebote');``
It somehow forces the browser to close, ends the script and does not return a value before doing so.
The thrown exception is a "Operation timed out after 1000ms." one, however, I certainly know that the required element is there (node based puppeteer finds the element just fine).

``$page->getHtml()`` also throws a "Operation timed out after 2s." exception and all ``evaluete()`` calls time out too.

Any ideas what might cause this behavior?
Thanks in advance

**Comment by AndiLeni** [comment]
Additional information: it is this url which is somehow not working.
Other domains seem to work fine.

``https://www.netto-online.de/ueber-netto/Online-Prospekte.chtm``

Complete debug log: 
[log.txt](https://github.com/chrome-php/chrome/files/10252384/log.txt)

**Comment by momala454** [comment]
It is possible that it's an anti bot detecting querySelector and causing a voluntary crash

**Comment by AndiLeni** [comment]
Thanks for the answer. Puppeteer is working fine without any modifications. What are they doing differently?

All other interactions with the page like scrolling or clicking are also not working.

Can I somehow disable the webdriver detection @momala454 ?

Edit:
Adding
```
 'customFlags' => [
        "--enable-automation=false",
        "--disable-blink-features=AutomationControlled",
    ],
```
did not help on my page. It however passed the bot detection on https://bot.sannysoft.com/.

Any more ideas? :(

**Comment by enricodias** [comment]
Your browser is probably taking too long to do the search. Try increasing the default timeout for sync messages with the `sendSyncDefaultTimeout` option.

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch, and thanks to everyone for the dialogue here. As this does not seem to be a bug in this library, I'm going to close this - this is an issue tracker for bugs in the library. If you need free support, the best place get visibility would be on whatever forum on your choosing. Alternatively, we could engage in some paid support - you can reach me at hello@gjcampbell.co.uk.
