### ISSUE TITLE
Close tab without closing browser

### ISSUE THREAD

**Issue by vcalderonoyarce** [chrome-php/headless-chromium-php#46]
Is there a way to destroy a tab?

`$page = $browser->createPage($uri)  // I need to destroy this tab.`

 Is that possible?

Thanks 👍.

**Comment by vcalderonoyarce** [comment]
Ok thanks!

**Comment by gsouf** [comment]
@vcalderonoyarce I'm closing the issue considering it worked, feel free to re-open if it does not work
