### ISSUE TITLE
Fetch non HTML response

### ISSUE THREAD

**Issue by professional-sourav** [chrome-php/headless-chromium-php#460]
Hi, how can I fetch non-HTML responses?
Let's say I have an URL https://example.com/css/style.css. So, how can I get a response to that?
Also, if there is an image URL, like https://example.com/img/new.png, I can not use `$page->getHtml()`, right? How can I fetch this type of content? Following is my code ...

`
$browser = $browserFactory->createBrowser([
            'windowSize' => [1920, 1080],
            'noSandbox' => true
]);

$page = $browser->createPage();

$page->getSession()->sendMessage(new Message(
          'Network.enable',
));

$page->getSession()->once('method:Network.responseReceived', function (array $params) {
          $this->response = $params['response'];
});

$page->navigate($url)->waitForNavigation();

info("RESPONSE",  [$this->response, $page->getHtml()]);
`

**Comment by enricodias** [comment]
Answered in #368
