### ISSUE TITLE
How to wait a few seconds before taking a screenshot

### ISSUE THREAD

**Issue by sakirsa** [chrome-php/headless-chromium-php#461]
Hi. The area that is needed does not have time to load. Forced somehow can we wait? try to Page::DOM_CONTENT_LOADED, 10000 but not help

**Comment by enricodias** [comment]
The `DOM_CONTENT_LOADED` just mean that the DOM was completely loaded. There's also the `LOAD` and `NETWORK_IDLE` events. If none of those solves your problem, you'll need to check if the page finished loading everything you need manually.

**Comment by sakirsa** [comment]
DOM_CONTENT_LOADED, LOAD, NETWORK_IDLE dont solve problem. is there any way to open a tab and wait 5 seconds before taking a screenshot?

**Comment by sakirsa** [comment]
I checked, the page is loading, just after loading the page, an object appears that needs a shot with a delay of a second or two. something like popup

**Comment by enricodias** [comment]
Then you'll have to wait and check if it's visible manually. A js script can change pretty much anything in the page at any time without triggering those events.

**Comment by iamashishk** [comment]
@sakirsa If you are sure about the delay you need, you can use sleep. Else you can evaluate JS inside a loop to check if element is loaded and then break the loop. Below is one of the technique i used:

$waitingForForm=0;
while($waitingForForm < 60 && $formLoaded===false){//close after waiting for 60 iterations i.e. 2 minutes
    sleep(2);
    $this->source=$page->getHtml();
    if(Str::contains($this->source,"I am your element")){//This is just an example.
        $formLoaded=true;//once this becomes true, loop will break
    }
    $waitingForForm++;
}

**Comment by shawn996** [comment]
src/page.php
```
    public function wait($timeout=0){
        try{
            usleep(100);//短暂等待，收收数据
            $sleep=$timeout;
            $timeout= $timeout>0 ? $timeout : 15000;
            Utils::tryWithTimeout($timeout*1000, $this->waitGenerator($sleep));

        }catch(OperationTimedOut $e) {

        }

    }
    private function waitGenerator($sleep){
        $delay = 1000;
        while(true){
            $bool=$this->getSession()->getConnection()->readallData();
            if($sleep or $bool===true){
                yield $delay;
            }else{
                return true;
            };
        }

    }
```

communication/connection.php

```
        /**
     * Read all data from CRI and store messages
     *
     * @return bool true if data were received
     * @throws CannotReadResponse
     * @throws InvalidResponse
     */
    public function readallData()//多条信息，只要有信息就返回true
    {
        $hasData = false;

        do{
            // if buffer empty, then read from input
            if (empty($this->receivedData)) {
                $this->receiveData();
            }

            // dispatch first line of buffer
            $datum = array_shift($this->receivedData);
            if ($datum) {
                $this->dispatchMessage($datum);
                $hasData=true;
            }
        }while(count($this->receivedData));

        return $hasData;
    }
```
Add the above code，and use $page->wait() function

**Comment by divinity76** [comment]
use the [sleep function](https://www.php.net/manual/en/function.sleep.php) to wait. for example
```php
$page->navigate('https://youtube.com/')->waitForNavigation(\HeadlessChromium\Page::DOM_CONTENT_LOADED);
sleep(5);
$page->screenshot()->saveToFile('/foo/bar.png');
```
waits until DOM_CONTENT_LOADED, then waits 5 seconds, then takes the screenshot.
