### ISSUE TITLE
The loaded page contains auto download files.

### ISSUE THREAD

**Issue by ndrto** [chrome-php/headless-chromium-php#464]
How to handle the page that contains auto download file (file extension is .txt and i want to read this file as result).

**Comment by iamashishk** [comment]
solved?

**Comment by ndrto** [comment]
not yet, still confused 😅

**Comment by iamashishk** [comment]
Can you share some context on what type of file is that, size. If possible provide the URL to check.
I have made that possible by 2 methods. So can help regarding what will work better in your case once i get the context.

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. You've opened an bug on an issue tracker for bugs in this library. As this does not seem to be a bug, I'm going to close this. If you need free support, the best place get visibility would be on whatever forum on your choosing. Alternatively, we could engage in some paid support - you can reach me at hello@gjcampbell.co.uk.
