### ISSUE TITLE
inject jquery

### ISSUE THREAD

**Issue by pashkasan** [chrome-php/headless-chromium-php#47]
hi,
is it possible to inject jquery to get DOM elements values more easy, ie to use jquery selectors?

smth like this
$page->addPreScript(file_get_contents ('jquery-latest.min.js'));
$page->navigate('https://www.somepage.com/feed.html')->waitForNavigation();
$value = $page->evaluate('jQuery("#pagelet_group_mall")')->getReturnValue();

Fatal error: Uncaught HeadlessChromium\Exception\JavascriptException: Error during javascript evaluation: ReferenceError: jQuery is not defined
    at <anonymous>:1:1 in F:\web\chrome\headless-chromium-php\src\PageUtils\PageEvaluation.php:78

**Comment by gsouf** [comment]
Hi @pashkasan 

I made a set of changes in that direction. As of now in master branch you can do:

```php
$page->addScriptTag([
    'content' => file_get_contents ('jquery-latest.min.js')
]);
```

I'll try to figure out how to get it work alongside addPreScript for convenience. 

Stay tuned!

**Comment by gsouf** [comment]
@pashkasan version ``0.5.0`` has all the tools you need for it.

You an either follow the example in my previous message to inject it in a single page or then use ``addPreScript`` with the option ``onLoad``:

``$page->addPreScript(file_get_contents('jquery.js'), ['onLoad' => true]);``
