### ISSUE TITLE
Is there any option for omitBackground ?

### ISSUE THREAD

**Issue by hitinfotech** [chrome-php/headless-chromium-php#470]
Please help with this option "omitBackground"

**Comment by enricodias** [comment]
Where? When printing a page?

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. You've opened an bug on an issue tracker for bugs in this library. As this does not seem to be a bug, I'm going to close this. If you need free support, the best place get visibility would be on whatever forum on your choosing. Alternatively, we could engage in some paid support - you can reach me at hello@gjcampbell.co.uk.
