### ISSUE TITLE
Click on radio button 

### ISSUE THREAD

**Issue by kamurj** [chrome-php/headless-chromium-php#473]
Hello, I have the following html. 
```
<div class="col-xs-12"><fieldset role="radiogroup" aria-labelledby="variantLegend">     <legend id="variantLegend" class="sr-only">
	            						Color
	            					</legend>       <span class="variant-v2 selection-box-v2" tabindex="0">   <label>    <input aria-hidden="true" type="radio" class="hidden" name="productOption00" value="zzz86" automation-id="variationOptions_zzz86">    <span class="selection-item" role="radio" aria-checked="false" automation-id="selectionItem_zzz86">Dark Gray</span>   </label>  </span>   <span class="variant-v2 selection-box-v2" tabindex="0">   <label>    <input aria-hidden="true" type="radio" class="hidden" name="productOption00" value="zzz14" automation-id="variationOptions_zzz14">    <span class="selection-item" role="radio" aria-checked="true" automation-id="selectionItem_zzz14">Bronze</span>   </label>  </span>     </fieldset>   </div>
```
As you can see, the first input/radio button is checked on initial page load. I would like click on the second input, here

`<input aria-hidden="true" type="radio" class="hidden" name="productOption00" value="zzz14" automation-id="variationOptions_zzz14">`

How can I do it? Some page elements are updated via ajax, so I assume there is no need to reload the page.

Thank you very much.

**Comment by kamurj** [comment]
anyone?

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. You've opened an bug on an issue tracker for bugs in this library. As this does not seem to be a bug, I'm going to close this. If you need free support, the best place get visibility would be on whatever forum on your choosing. Alternatively, we could engage in some paid support - you can reach me at hello@gjcampbell.co.uk.
