### ISSUE TITLE
swoole maybe can not use this extension?

### ISSUE THREAD

**Issue by JerryTZF** [chrome-php/headless-chromium-php#476]
I think that under swoole coroutines, the yield keyword of the "waitForNavigation" method will conflict with swoole. It always times out

**Comment by enricodias** [comment]
Do you have a reproductive example where the timeout is not caused by the actual navigation timing out?

**Comment by JerryTZF** [comment]
Sorry, it works under swoole, is my target URL has an anti-crawl mechanism
