### ISSUE TITLE
Error: Response from chrome remote interface is not a valid json response. JSON error: 10

### ISSUE THREAD

**Issue by DenisSokoloff** [chrome-php/headless-chromium-php#477]
I try to get request content and got error:
**Error: Response from chrome remote interface is not a valid json response. JSON error: 10**

Chrome returns back no valid JSON with UNICODE chars
JSON can not be parsed https://jsoneditoronline.org/#left=cloud.87cdf05f474f4db78bee81dc8c6d4531&right=local.huconi
in Connection Class

**Comment by DenisSokoloff** [comment]
I don't realize how I can fix it from client side, but I added fix code to **Connection.dispatchMessage** function:

```
        $message = preg_replace_callback(
            '~(?<!\\\)\\\u[a-f0-9]{4}~iu',
            function($found)
            {
                if(json_decode('"'.$found[0].'"'))
                {
                    return $found[0];
                }
                return "";
            },
            $message
        );
```

**Comment by enricodias** [comment]
Can you provide a reproducible example? I saw the json, but I couldn't reproduce the error here.

**Comment by GrahamCampbell** [comment]
Closing due to no response. Feel free to make a new issue if you can provide us with something we can replicate, or to skip to sending in a PR with tests that fixes the issue.
