### ISSUE TITLE
Permission Error: "not a snap cgroup"

### ISSUE THREAD

**Issue by HayriCan** [chrome-php/headless-chromium-php#479]
I upgraded my Ubuntu to 22.04, but my project began to throw this error after the upgrade. It is about permission, but I couldn't find the solution for giving privileges. Please help!

```
RuntimeException
Chrome process stopped before startup completed. Additional info: cmd_run.go:1046: WARNING: cannot create user data directory: cannot create snap home dir: mkdir /var/www/snap: permission denied /system.slice/php7.4-fpm.service is not a snap cgroup 
```

**Comment by jamesphw** [comment]
I faced a similar issue on Ubuntu 22.04. I don't really have the solution, but my workaround was to use Chrome instead of Chromium. 

Install the latest Chrome with the following:

```
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
apt install ./google-chrome-stable_current_amd64.deb
```

Then when you create the BrowserFactory, point it to the right binary:

```
$browserFactory = new BrowserFactory('google-chrome-stable');
```

**Comment by HayriCan** [comment]
Your solution is working but my project running on server (Laravel Forge) without problem. I thought there is a solution for it. I also read some information like this `Chromium is now a snap, which has access to $HOME, /media/, /mnt/ and a few limited other areas. This is intended for security purposes (it runs in a container that restricts it's access to specified locations).`

**Comment by HayriCan** [comment]
I have solved this problem changing some configurations

/etc/nginx/nginx.conf
```
`user barcin;`
```

/etx/php/7.4/fpm/pool.d/www.conf

```
user = barcin
group = barcin
listen.owner = www-data
listen.group = www-data
listen.mode = 0660
```

and added www-data to barcin group so  www-data has access to files which main user (barcin) has. In this way i can use chromium-browser
