### ISSUE TITLE
How to use with the version of Chromium downloaded by puppeteer

### ISSUE THREAD

**Issue by BrayanCaro** [chrome-php/headless-chromium-php#484]
Puppeteer downloads a specific version of chromium, is there a way of using it?

I've chrome installed locally and it worked out of the box, but if I specify the path of the chromium versions installed by puppeteer:

```php
$browserFactory = new BrowserFactory('/home/someuser/.cache/puppeteer/chrome/linux-1095492/chrome-linux/chrome');
$browser = $browserFactory->createBrowser();
```

It throws:

    [2023-02-28 14:53:16] local.ERROR: No accept header receieved on handshake response {"exception":"[object] (Wrench\\Exception\\HandshakeException(code: 500): No accept header receieved on handshake response at /home/someuser/somefolder/example-app/vendor/chrome-php/wrench/src/Protocol/Protocol.php:469)

Notes:

- I have installed puppeteer as usual

      npm i puppeteer

- Chromium installed by puppeteer exists, and I can launch it.

  ![image](https://user-images.githubusercontent.com/41640423/221892983-3a002638-fa1c-4c1b-8e8b-2c8f9b96ef3f.png)

**Comment by DenisSokoloff** [comment]
Have same error after Chrome updates to last version

**Comment by jarbey** [comment]
If you have _"No accept header receieved on handshake response"_ error with the new version of Chrome (to me was 111.0.5563.65) read below

We can avoid that adding and argument to the chrome command line --remote-allow-origins=*
So in chrome-php it can be done with the "customFlags" option like below


```
$browser = $browserFactory->createBrowser([
    'headless' => false, // disable headless mode
    'customFlags' => ['--remote-allow-origins=*'],
]);
```

**Comment by GrahamCampbell** [comment]
This issue has already been fixed in the latest version of this package. Please upgrade.

**Comment by jarbey** [comment]
Thank you @GrahamCampbell 

See https://github.com/chrome-php/chrome/issues/492
