### ISSUE TITLE
Custom path to chrome.exe

### ISSUE THREAD

**Issue by mare-on** [chrome-php/headless-chromium-php#485]
Hi, is it possible to define custom path to "chrome.exe"?

I tried this definition: $browserFactory = new BrowserFactory('%ProgramFiles%\Google\Chrome\Application\chrome.exe');

But it dosen't work, what I do wrong and how to do it right.
Thanks.

**Comment by enricodias** [comment]
Why it doesn't work? What's the error?

**Comment by mare-on** [comment]
It throws error: "FATAL ERROR ...vendor\chrome-php\chrome\src\Browser\BrowserProcess.php on line 415".

**Comment by mare-on** [comment]
Well but this definition works: 
$browserFactory = new BrowserFactory('../chrome/chrome.exe');

But this needs to copy the app dir with chrome into project.
Another issue is Chromium... I would like to use chromium instead of Chrome but it doesn't work at all...

I tried: $browserFactory = new BrowserFactory('../chromium/chrome.exe');

And error is: 

Fatal error: Uncaught Wrench\Exception\HandshakeException: No accept header receieved on handshake response... HeadlessChromium\BrowserFactory- in ...\vendor\chrome-php\wrench\src\Protocol\Protocol.php on line 469

**Comment by enricodias** [comment]
I can't reproduce this issue here. Custom path is a basic feature that have always worked. Make sure your path is correct and that you can open the browser with it manually.

**Comment by mare-on** [comment]
So I just put chrome as a part of my project and everything is working. ( Valid path: browserFactory = new BrowserFactory('../chrome/chrome.exe'); )

But the issue with Chromium is still active, it's not working.
I'm trying to use the latest version and still getting the same error.

**Comment by DenisSokoloff** [comment]
Got same error after google chrome update at Ubuntu

**Google Chrome 111.0.5563.64**

> Fatal error: Uncaught Wrench\Exception\HandshakeException: No accept header receieved on handshake response in /vendor/chrome-php/wrench/src/Protocol/Protocol.php:469 Stack trace: #0 /vendor/chrome-php/wrench/src/Client.php(243): Wrench\Protocol\Protocol->validateResponseHandshake('HTTP/1.1 403 Fo...', 'BybBKmvy1lqHolj...') #1 /vendor/chrome-php/chrome/src/Communication/Socket/Wrench.php(99): Wrench\Client->connect() #2 /vendor/chrome-php/chrome/src/Communication/Connection.php(186): HeadlessChromium\Communication\Socket\Wrench->connect() #3 /vendor/chrome-php/chrome/src/Browser/BrowserProcess.php(146): HeadlessChromium\Communication\Connection->connect() #4 /vendor/chrome-php/chrome/src/BrowserFactory.php(81): HeadlessChromium in /vendor/chrome-php/wrench/src/Protocol/Protocol.php on line 469

I have updated Chrome for windows (Version 111.0.5563.65 (Official Build) (64-bit)) and got this error too

**Comment by mare-on** [comment]
I'm closing the issue due to the solved in #492
