### ISSUE TITLE
Inability to scroll

### ISSUE THREAD

**Issue by ayd-is** [chrome-php/headless-chromium-php#486]
Hi !
I want to use scroll
not a page, but a separate element on the page
![perviyssss2](https://user-images.githubusercontent.com/48499342/222920001-56180a0a-9709-4f51-b960-fe70a356e818.png)

what happens on the page:
I click on the button and a list box appears in the middle of the screen, but to scroll through it, you need to hold the mouse inside this list (page element)
but all sorts of ways don't work.

my codes:
```
$page->mouse()
->find('._box', 1)
->scrollDown(350);


OR

$page->mouse()
->move(1250, 570, ['steps' => 5])
->find('._box', 1)
->click()
scrollDown(350); 

```

Thank you in advance for your cooperation!

**Comment by enricodias** [comment]
Moving the mouse to the element you want to scroll should work. Are you sure the mouse is above the right element? Did you run it without the headless mode to actually see the mouse there?

**Comment by ayd-is** [comment]
I run it with and without headless,
here are my options:
```
$browser = $browserFactory->createBrowser([
			'windowSize'   => [2560, 1329],
		   	'noSandbox' => 'false',
		   	'userAgent' => $user_agent,
		   	'headless' => 'false',
		   	'sendSyncDefaultTimeout' => '100000', /// msec
		   	'startupTimeout' => '100', //sec
	  	]);
	  	
```

or 

`		   	'headless' => 'true',`

for some reason the mouse is not visible when false and true

**Comment by ayd-is** [comment]
I found a solution !
the scroll method doesn't work for me:

```
$page->mouse()
->move(1250, 570)
->scrollDown(350); 
```

 but it works like this:

```
 $params = [
 'x' => 1250,
 'y' => 570,
 'type' => 'mouseWheel',
 'deltaX' => 0,
 'deltaY' => 350
];
					  
$page->getSession()->sendMessageSync(new HeadlessChromium\Communication\Message('Input.dispatchMouseEvent', $params));

sleep(1);
```

- deltaY (distance a scroll)
