### ISSUE TITLE
Chromium browser is not working

### ISSUE THREAD

**Issue by mare-on** [chrome-php/headless-chromium-php#487]
Custom path to the chromium browser exe is not working.

I tried: $browserFactory = new BrowserFactory('../chromium/chrome.exe');
And the error is:

Fatal error: Uncaught Wrench\Exception\HandshakeException: No accept header receieved on handshake response ...   HeadlessChromium\BrowserFactory-  ... \vendor\chrome-php\wrench\src\Protocol\Protocol.php on line 469

**Comment by enricodias** [comment]
You just created #485 describing the same problem moments ago. Creating multiple issues about the same problem won't help.

**Comment by DenisSokoloff** [comment]
Got same error after google chrome update at Ubuntu

**Google Chrome 111.0.5563.64**

> Fatal error: Uncaught Wrench\Exception\HandshakeException: No accept header receieved on handshake response in /vendor/chrome-php/wrench/src/Protocol/Protocol.php:469 Stack trace: #0 /vendor/chrome-php/wrench/src/Client.php(243): Wrench\Protocol\Protocol->validateResponseHandshake('HTTP/1.1 403 Fo...', 'BybBKmvy1lqHolj...') #1 /vendor/chrome-php/chrome/src/Communication/Socket/Wrench.php(99): Wrench\Client->connect() #2 /vendor/chrome-php/chrome/src/Communication/Connection.php(186): HeadlessChromium\Communication\Socket\Wrench->connect() #3 /vendor/chrome-php/chrome/src/Browser/BrowserProcess.php(146): HeadlessChromium\Communication\Connection->connect() #4 /vendor/chrome-php/chrome/src/BrowserFactory.php(81): HeadlessChromium in /vendor/chrome-php/wrench/src/Protocol/Protocol.php on line 469

I have updated Chrome for windows (Version 111.0.5563.65 (Official Build) (64-bit)) and got this error too
