### ISSUE TITLE
Abrir apenas uma aba do chrome e maximizado

### ISSUE THREAD

**Issue by alexandreChromotech** [chrome-php/headless-chromium-php#488]
Quando uso o  'headless' => false, para ver o navegador fazendo os procedimentos, percebo que ele abre duas abas, como faço para abrir em uma única aba?

Outra pergunta é como deixar o 'windowSize' de forma automática, abrindo maximizado total, sem precisar seta altura e largura?

obrigado.

**Comment by FelipeAzambuja** [comment]
@alexandreChromotech melhor excluir a sua issue e reescrever ela em inglês para que se torne acessivel aos demais devs do projeto

**Comment by GrahamCampbell** [comment]
Apologies, we can only accept issues in English here.

**Comment by alexandreChromotech** [comment]
OK obrigado.
