### ISSUE TITLE
Open only one chrome tab and maximized

### ISSUE THREAD

**Issue by alexandreChromotech** [chrome-php/headless-chromium-php#489]
When I use 'headless' => false, to see the browser doing the procedures, I notice that it opens two tabs, how do I open it in a single tab?

Another question is how to leave the 'windowSize' automatically, opening the total maximized, without having to define height and width?

thanks.

**Comment by enricodias** [comment]
There used to be a specific flag to open chrome maximized, but it was removed a long time ago. There isn't any specific flag to force this, but I just tested using values greater than the current screen resolution in the `--window-size` flag and it opens maximized for me. I tested on Linux only.

Chrome always start with a new tab (on Linux and Windows it can't even remain open without an active tab). The `createPage` method in the `Browser` class creates a new tab. You can try to query the `targetId` for the already opened tab and create a `Page` instance directly to control or close this tab.
