### ISSUE TITLE
Enable JavaScript

### ISSUE THREAD

**Issue by mare-on** [chrome-php/headless-chromium-php#490]
Hi, I would like to get some content from website: https://www.sportli.cz/obchody/, but I can't due to required JavaScript enabled, how I can enable JavaScript by using BrowserFactory?

**Comment by enricodias** [comment]
Javascript is already enabled, you are controlling a real browser with all the features.

**Comment by mare-on** [comment]
Soo, could you tell me why I have error message about enbling JavaScript when I'm trying to parse content from https://www.sportli.cz/obchody/? I just want to understand the issue.

**Comment by buismaarten** [comment]
> Soo, could you tell me why I have error message about enbling JavaScript when I'm trying to parse content from https://www.sportli.cz/obchody/? I just want to understand the issue.


Use something like this (using the `firstImagePaint` event is important):
```
$page->navigate('https://example.com')->waitForNavigation('firstImagePaint');
$page->dom()->getHTML();
```
