### ISSUE TITLE
processes are not closed

### ISSUE THREAD

**Issue by ayd-is** [chrome-php/headless-chromium-php#493]
Hi all!
i have this problems:

when the script and the browser are not running - my ubuntu still has a load and a lot of processes from google (see screenshot).
i run it without "keepAlive".
That is how it should be?
<img width="2560" alt="Снимок экрана 2023-03-08 в 21 56 11" src="https://user-images.githubusercontent.com/48499342/223810041-f12cf0b4-c2d9-43f0-9372-6acb328253d2.png">

is it possible to optimize memory and cpu consumption from google chrome?

thanks for the answer!)

**Comment by enricodias** [comment]
Check if you are not creating several tabs and leaving them opened. Each tab will be a process. Each time you call `createPage`, you are creating a new tab

**Comment by ayd-is** [comment]
> Check if you are not creating several tabs and leaving them opened. Each tab will be a process. Each time you call `createPage`, you are creating a new tab

I'm understood, thank you !
