### ISSUE TITLE
Started having issues

### ISSUE THREAD

**Issue by kamurj** [chrome-php/headless-chromium-php#494]
I have been been using php chrome for months without an issue. But now I started to get this errors.
Any ideas why and how to fix this? Thanks.

`Fatal error: Uncaught Wrench\Exception\HandshakeException: No accept header receieved on handshake response in C:\Users\kamurj\vendor\chrome-php\wrench\src\Protocol\Protocol.php:469 Stack trace: #0 C:\Users\kamurj\vendor\chrome-php\wrench\src\Client.php(243): Wrench\Protocol\Protocol->validateResponseHandshake('HTTP/1.1 403 Fo...', 'SCesESDhu+O5zQ6...') #1 C:\Users\kamurj\vendor\chrome-php\chrome\src\Communication\Socket\Wrench.php(99): Wrench\Client->connect() #2 C:\Users\kamurj\vendor\chrome-php\chrome\src\Communication\Connection.php(186): HeadlessChromium\Communication\Socket\Wrench->connect() #3 C:\Users\kamurj\vendor\chrome-php\chrome\src\Browser\BrowserProcess.php(146): HeadlessChromium\Communication\Connection->connect() #4 C:\Users\kamurj\vendor\chrome-php\chrome\src\BrowserFactory.php(81): HeadlessChromium\Browser\BrowserProcess->start('C:\\Program File...', Array) #5 C:\xampp\htdocs\zmeta.php(266): HeadlessChromium\BrowserFactory->createBrowser(Array) #6 {main} thrown in C:\Users\kamurj\vendor\chrome-php\wrench\src\Protocol\Protocol.php on line 469`

**Comment by enricodias** [comment]
See #492

**Comment by GrahamCampbell** [comment]
This issue has been resolved in v1.8.1.
