### ISSUE TITLE
No accept header receieved on handshake response

### ISSUE THREAD

**Issue by superdeu** [chrome-php/headless-chromium-php#499]
New problem after updete of crhome, my version of chrome 111.0.5563.65 
Everything worked on the previous version, what should I do?

`Fatal error: Uncaught Wrench\Exception\HandshakeException: No accept header receieved on handshake response in D:\OpenServerNew3\OpenServer\domains\chron-new\vendor\wrench\wrench\lib\Wrench\Protocol\Protocol.php:417 Stack trace: #0 D:\OpenServerNew3\OpenServer\domains\chron-new\vendor\wrench\wrench\lib\Wrench\Client.php(244): Wrench\Protocol\Protocol->validateResponseHandshake() #1 D:\OpenServerNew3\OpenServer\domains\chron-new\vendor\chrome-php\chrome\src\Communication\Socket\Wrench.php(99): Wrench\Client->connect() #2 D:\OpenServerNew3\OpenServer\domains\chron-new\vendor\chrome-php\chrome\src\Communication\Connection.php(163): HeadlessChromium\Communication\Socket\Wrench->connect() #3 D:\OpenServerNew3\OpenServer\domains\chron-new\vendor\chrome-php\chrome\src\Browser\BrowserProcess.php(146): HeadlessChromium\Communication\Connection->connect() #4 D:\OpenServerNew3\OpenServer\domains\chron-new\vendor\chrome-php\chrome\src\BrowserFactory.php(67): HeadlessChromium\Browser\BrowserProcess->start() #5 D:\OpenServerNew3\OpenServer\domains\chron-new\test-3.php(30): HeadlessChromium\BrowserFactory->createBrowser() #6 {main} thrown in D:\OpenServerNew3\OpenServer\domains\chron-new\vendor\wrench\wrench\lib\Wrench\Protocol\Protocol.php on line 417`

**Comment by enricodias** [comment]
See #492
