### ISSUE TITLE
High network traffic from google ips, when opening the browser

### ISSUE THREAD

**Issue by santossoares** [chrome-php/headless-chromium-php#502]
Hello!

Recently i found this strange behavior when using this package in one of my scraping projects.
I was monitoring the network usage and found this "bug".

After 30+- secs after opening the browser, it fetches some packets over the opened connections with a 30mb data, everytime, on every website it opens. Even if you don't open a website at all, only by just opening the browser instance, you can see this 30mb network traffic.

This traffic is from google ips, maybe some update? i couldn't figure out whats this.
I tested if this behavior is expected on a normal chrome browser, but this only occurs when using this package to automate it.
Another thing is that this only occurs when headless mode is turned off.

I discovered this bug because I am using proxy in my project and the used bandwidth went skyrocket.
After 10 requests of 30 seconds each, my bandwidth usage is 300mb, and is supposed to be 15 to 20 mb

I used the iftop to monitor the network resources on my pc, and a external proxy service to confirm it.
You need to wait some time for the data to begin to fetch. this is why i used a sleep(30).

this is just a sample working code to demonstrate the bug:

<?php
require_once 'vendor/autoload.php';

use HeadlessChromium\BrowserFactory;

$browserFactory = new BrowserFactory();

$browserFactory->setOptions([
    'headless' => false
]);

$browser = $browserFactory->createBrowser();
$page = $browser->createPage();

$page->navigate('https://www.amazon.com')->waitForNavigation();
sleep(30);

**Comment by enricodias** [comment]
I couldn't reproduce this behavior, but it may be chrome fetching an update, trying to sync data or updating extensions. It makes sense to do those things only in without headless and when idle.

Try to disable automatic updates, remove all extensions and use a new profile. You could also try using chromium directly instead of google chrome.
