### ISSUE TITLE
Uncaught Wrench\Exception\HandshakeException: No accept header receieved on handshake response in

### ISSUE THREAD

**Issue by hourgame01** [chrome-php/headless-chromium-php#505]
After perform a `composer update` it finally works but it's required `>=php8.1.0` which is different from `readme`. Please let me know why does it happen ?

**Comment by GrahamCampbell** [comment]
PHP 8.1 is definitely not required. The only reason you would get a lock file that requires PHP 8.1 would be because you ran composer using PHP 8.1.

**Comment by GrahamCampbell** [comment]
Evidence of this being installed on PHP 7.4: https://github.com/chrome-php/chrome/actions/runs/4393597401/jobs/7694100025.
