### ISSUE TITLE
How to press Enter on Element?

### ISSUE THREAD

**Issue by cobbBR** [chrome-php/headless-chromium-php#524]
In order to submit the form I need to press enter on the same element that text was sent to.  Below is the snippet of code.  Is this possible?

```
$elem = $page->dom()->querySelector('#CallFormPanel_contentSplitter_CallToolPanel_txtLname_I');
$elem->click();
$elem->sendKeys("Smith");
$page->keyboard()->typeRawKey('Enter');  // This sends the enter key to the whole page and does not submit the form.
```

**Comment by codes-begin** [comment]
You can submit form using 2 methods
1. $evaluation = $page->evaluate('(() =>{document.querySelector("#**submit_button_id**").click();})()');
2. $evaluation = $page->evaluate('(() =>{document.querySelector("#**form_id**").submit();})()');

Dont forget to change the button or form id

**Comment by cobbBR** [comment]
I've tried those ways with no success.  I don't think there is a submit button.  And if I submit using the form ID then the page reloads empty.  I have been successful using Python and Selenium by pressing enter in the text field.  I was hoping to be able to do the same thing.  Here's the form I'm working with. http://129.71.117.241/WEBInquiry/Default.aspx

And here's the Python code that worked.

```
last_name = driver.find_element("id", 'CallFormPanel_contentSplitter_CallToolPanel_txtLname_I')
last_name.send_keys("Smith");
last_name.send_keys(Keys.ENTER)
```

**Comment by cobbBR** [comment]
I was able to figure it out.  

`$elem->sendKeys("\r");`
