### ISSUE TITLE
Is it possible to interact with the opened page multiple times?

### ISSUE THREAD

**Issue by codes-begin** [chrome-php/headless-chromium-php#525]
Below are the steps I have to perform to fill multi step form
1. Normal Chrome - Load form and fill 2 fields and submit
2. PHP Chrome - createBrowser() & createPage() gets executed and above 2 fields gets filled and submitted and an OTP is sent
3. Normal Chrome - OTP is entered
4. PHP Chrome - OTP gets filled and form submitted & next step of form is loaded
5. Normal Chrome - Fill the form
6. PHP Chrome - Form gets filled and submitted.

Let me know how can I achieve that, how can I interact with the same opened page again?

**Comment by enricodias** [comment]
You can execute the browser without the headless mode, it will show up for you and the php will still have control over it. You would just have to make the php wait for you to fill the fields somehow.

**Comment by codes-begin** [comment]
I have found a way to do it. Might be helpful to someone else so posting it here.
getting the $targetid=$page->GetSession()->getTargetId(); and then storing it in session

Interacting it with the same page again
$target = $browser->getTarget($target_page);
$frameTreeResponse = $target->getSession()->sendMessageSync(new \HeadlessChromium\Communication\Message('Page.getFrameTree'));
$page = new \HeadlessChromium\Page($target, $frameTreeResponse['result']['frameTree']);

**Comment by enricodias** [comment]
In my last reply I thought you were talking about submitting a form after a user fill the OTP directly in chrome, with the chrome itself running locally in the same machine as the user. If I understand correctly, you were trying to relay information from a remote user using a real chrome to fill the forms. If you need to interact with the same tab across multiple php processes/requests, then yes, you do need to save the target id somewhere and fetch it in subsequent requests.
