### ISSUE TITLE
Waiting for evaluation

### ISSUE THREAD

**Issue by RevolvingDCON** [chrome-php/headless-chromium-php#53]
Hey dude, really cool work!

Is it possible to wait for javascript evaluation (poll for a global variable) rather than navigation such as Page::NETWORK_IDLE?

I'm faced with an interesting issue where I pull a lot of data via ajax, and it takes more than 1000ms to populate the data in the dom (fancy charts etc) therefore Page::NETWORK_IDLE evacuates to true and the image/pdf is captured before the next ajax request fires for the final piece of content.

Thanks!

**Comment by gsouf** [comment]
Hi @RevolvingDCON 

You can do that using a promise in your evaluation. For instance by waiting in the javascript that a given DOM element is populated:

```php
        $evaluation = $page->evaluate('new Promise(resolve => {
            let interval = setInterval(() => {
                if (document.querySelector(".elementToWatch")) {
                    clearInterval(interval);
                    resolve();
                }
            }, 100);
        })');
```

**Comment by RevolvingDCON** [comment]
Holy crap thank you for the swift reply! This is awesome :)

**Comment by dillanjwilding** [comment]
I tried the described solution for waiting but it didn't work for me. The page I am trying to capture an image of makes a large API request and then replaces the loading bar with a graph of the data. I added a custom callback to add a div with ID of "test" to the body but I still end up getting an image of the loading bar. Any advice on how to wait?

```
$connection = new Connection('ws://URL:9222/devtools/browser/HASH');
$connection->connect();
$connection->setConnectionDelay(500);
$browser = new Browser($connection);

try {
	$page = $browser->createPage();
	$page->navigate(URL)->waitForNavigation(Page::NETWORK_IDLE, 100000);
	$evaluation = $page->evaluate('new Promise(resolve => {
		let interval = setInterval(() => {
			if (document.querySelector("#test")) {
				clearInterval(interval);
				resolve();
			}
		}, 100);
	})');

	ob_get_clean();
	header('Content-Description: File Transfer');
	header('Content-Type: application/octet-stream');
	header('Content-Transfer-Encoding: binary');
	header('Expires: 0');
	header('Cache-Control: must-revalidate, post-check=0, pre-check=0');
	header('Pragma: public');
	header('Connection: Keep-Alive');
	header('Content-Disposition: inline; filename="test.png"');
	echo base64_decode($page->screenshot()->getBase64());
} finally {
	$browser->close();
}
```

![test](https://user-images.githubusercontent.com/2286922/126830317-f9956c61-b4b4-48f1-87ed-3e8346e66180.png)
