### ISSUE TITLE
Unable to load some external chain resources(.js and .css, images) after using headless(headless = true).

### ISSUE THREAD

**Issue by quyunet** [chrome-php/headless-chromium-php#537]
I found that when headless=true, some relative path src and href links cannot be loaded, resulting in a second request being unable to reload, the following error occurred during the second request:

Error during javascript evaluation: TypeError: Cannot read properties of null (reading 'innerHTML') at :1:26

At this point, I need to use a replacement method to replace the relative path's src and hrefs with absolute path links in order to display and make secondary requests and reload normally, The example code is as follows:
```php
require(__DIR__ . '/vendor/autoload.php');

$options = [
	'userAgent' => 'Mozilla/5.0 (X11; Debian; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36',
	'headless' => true,
	'keepAlive' => true,
	'enableImages' => true,
	'startupTimeout' => 60,
	'noSandbox' => false,
	'ignoreCertificateErrors' => true,
];
try {
	$factory = new \HeadlessChromium\BrowserFactory('google-chrome-stable'); 
	$browser = $factory->createBrowser($options);
	$page = $browser->createPage();
	$url = 'https://www.srsplus.com/';
	$page->navigate($url)->waitForNavigation();

//replace the relative path's src and href with an absolute path's.
	$html = str_replace('src="../', 'src="https://www.srsplus.com/', $page->getHtml());
	$html = str_replace('href="../', 'href="https://www.srsplus.com/', $html);
	$html = str_replace('src="/', 'src="https://www.srsplus.com/', $html);
	$html = str_replace('href="/', 'href="https://www.srsplus.com/', $html);
	$html = str_replace('src="', 'src="https://www.srsplus.com/', $html);
	$html = str_replace('href="', 'href="https://www.srsplus.com/', $html);
	$page->setHtml($html);
//replace end

	$response = $page->evaluate('document.documentElement.innerHTML')->getReturnValue();
	print_r($response);
}catch (Exception $e) {
	echo ($e->getMessage());
}
```
I want to know, besides targeted replacement methods, are there any other more convenient ways to force browsers to use absolute path links? Is there an option or method to force the global use of absolute path addresses?

**Comment by enricodias** [comment]
The headless flag shouldn't change how chrome resolves paths in any way. I ran your code here and didn't get any exception, even without the replacements. The `getHtml` method will return the same html as running `document.documentElement.innerHTML`, so I don't see a point in doing that.

**Comment by quyunet** [comment]
> The headless flag shouldn't change how chrome resolves paths in any way. I ran your code here and didn't get any exception, even without the replacements. The `getHtml` method will return the same html as running `document.documentElement.innerHTML`, so I don't see a point in doing that.

It has been resolved, thank you!
