### ISSUE TITLE
can I use this package to connect remote webdriver server.

### ISSUE THREAD

**Issue by tintin1926** [chrome-php/headless-chromium-php#552]
I want to use this package to connect a remote server  (selenium/standalone-chrome) running on docker

**Comment by shawn996** [comment]
you can find it in readme.md,example
```
use HeadlessChromium\Communication\Connection;
use HeadlessChromium\Communication\Message;

// Chrome devtools URI
$webSocketUri = 'ws://127.0.0.1:9222/devtools/browser/xxx';

// create a connection
$connection = new Connection($webSocketUri);
$connection->connect();

// send method "Target.activateTarget"
$responseReader = $connection->sendMessage(new Message('Target.activateTarget', ['targetId' => 'xxx']));

// wait up to 1000ms for a response
$response = $responseReader->waitForResponse(1000);
```

**Comment by realG** [comment]
Hi I'd also like to use chrome-php with selenium/standalone-chrome running in a separate docker container.

 @tintin1926 did you ever get this working?

@shawn996 If possible could expand on the example in the readme?

It seems the standard WebDriver connection is just a simple `http://<ip of remote chrome>:4444` as per the example here:
https://github.com/SeleniumHQ/docker-selenium?tab=readme-ov-file#quick-start

If I try setting `$WebSocketUri = http://<ip of remote chrome>:4444` I get a " Unknown socket scheme: http" error.
When I set  `$WebSocketUri = ws://<ip of remote chrome>:4444` I get "Wrench\Exception\HandshakeException, 400 Bad Request"
Same with `ws://<ip of remote chrome>:4444/devtools/browser/xxx`, although I'm not sure what xxx is meant to represent here?

Any help would be much appreciated!

**Comment by shawn996** [comment]
> Hi I'd also like to use chrome-php with selenium/standalone-chrome running in a separate docker container.
> 
> [@tintin1926](https://github.com/tintin1926) did you ever get this working?
> 
> [@shawn996](https://github.com/shawn996) If possible could expand on the example in the readme?
> 
> It seems the standard WebDriver connection is just a simple `http://<ip of remote chrome>:4444` as per the example here: https://github.com/SeleniumHQ/docker-selenium?tab=readme-ov-file#quick-start
> 
> If I try setting `$WebSocketUri = http://<ip of remote chrome>:4444` I get a " Unknown socket scheme: http" error. When I set `$WebSocketUri = ws://<ip of remote chrome>:4444` I get "Wrench\Exception\HandshakeException, 400 Bad Request" Same with `ws://<ip of remote chrome>:4444/devtools/browser/xxx`, although I'm not sure what xxx is meant to represent here?
> 
> Any help would be much appreciated!


It seems that your selenium/standalone-chrome is not working properly or the network is not connected. You can use a tool such as telnet to test whether the port number is connected.

**Comment by realG** [comment]
@shawn996 I am able to use selenium/standalone-chrome with other php libraries like `php-webdriver`, so connectivity should be fine, but `php-webdriver` also uses http and port 4444 for connecting, which works as expected:
https://github.com/php-webdriver/php-webdriver?tab=readme-ov-file#2-create-a-browser-session

Are you saying that to use chrome-php with a remote chrome instance you need to use ws and connect to devtools on port 9222, to a specific browser instance id (assuming that's what you mean by xxx)? If that is the case then I don't think this is actually possible with selenium/standalone-chrome, their container is not listening on that port, and even if it did, it's a transient docker container so the browser ids would be changing all the time anyway?

**Comment by shawn996** [comment]
I always use chrome-php to enable chrome and have never used the remote method.
