### ISSUE TITLE
Keyboard support or event with "istrusted"

### ISSUE THREAD

**Issue by momala454** [chrome-php/headless-chromium-php#56]
Hi
would it be possible to add support to keyboard events or the possibility to trigger events that are "trusted", as keyboards events 'or other kinds of events) triggered by javascript can be detected as "not trusted" and not accepted by the website

**Comment by NabiKAZ** [comment]
+1

**Comment by momala454** [comment]
actually i have found how to do that :
$page->getSession()->sendMessageSync(new HeadlessChromium\Communication\Message('Input.dispatchKeyEvent', [
				//'type'	=>	'event.keyDown',
				'type'	=>	'char',
				'text'	=>	'a'
			]));

for each letter to press
