### ISSUE TITLE
About alert();

### ISSUE THREAD

**Issue by michliu** [chrome-php/headless-chromium-php#577]
How to click alert() ?

**Comment by divinity76** [comment]
that's a good question.. testing shows that you cannot use the `$page->mouse()->move(652, 62)->click();` api even if you somehow can obtain the correct coordinates: the click() does not trigger the checkbox!

However you can hack around it, converting alert() to console.log():
```
$page->addPreScript('window.alert = function(msg) {console.log("ALERT: " + msg);};');
```
just make sure you run it right after `$page = $browser->createPage();`

**Comment by michliu** [comment]
Thank you for your response. The issue has been successfully resolved.

**Comment by michliu** [comment]
Thank you for your response. The issue has been successfully resolved.

**Comment by enricodias** [comment]
Just a bit of context in this one. Both `alert` and `prompt` halt javascript execution, so no javascript code would be able to click in the window itself. The mouse class in this package uses the chrome api directly and doesn't rely on javascript, but I'm not sure if it could work on prompts or if there is anything native in the api to do that.

By using `window.alert = function` you are overwriting the native function and that may have unintended consequences for that page.

**Comment by divinity76** [comment]
Did some digging. The correct way to click an alert() and confirm() box is:
```php
$page->getSession()->sendMessageSync(new \HeadlessChromium\Communication\Message(
    'Page.handleJavaScriptDialog',
    [
        'accept' => true,
    ]
));
```
(and yes, you're supposed to set `accept` even if its an alert box.. not sure why, but the documentation says so: https://chromedevtools.github.io/devtools-protocol/tot/Page/#event-javascriptDialogOpening )

The correct way to handle a prompt() box is:
```php
$page->getSession()->sendMessageSync(new \HeadlessChromium\Communication\Message(
    'Page.handleJavaScriptDialog',
    [
        'accept' => true,
        'promptText' => 'whatever you want to write in the prompt'
    ]
));
```
