### ISSUE TITLE
`headless` set to `false` doesn't show GUI when executing as a service on Windows

### ISSUE THREAD

**Issue by batata004** [chrome-php/headless-chromium-php#582]
Hi,

I am using this wonderful library in my Windows (I know you say in the docs it was mainly developed to linux but is works perfectly on windows!) and I cant see any differenct from using `headless` set to `true` or `false` like:

```
$browser = $browserFactory->createBrowser([

	"headless" => true,
	
]);
```

or

```
$browser = $browserFactory->createBrowser([

	"headless" => false,
	
]);
```

In both cases, a `chrome.exe` process is initiated on Windows Explorer but the Chrome window is invisible (I know I can connect to it using remote debugger). But is there any difference of using false/true?

Thank you!

**Comment by enricodias** [comment]
Hi. With headless set to false the chrome window should be visible. It's been some time since I used it on windows, but I used to set it to false several times when debugging to actually see what's being rendered.

**Comment by batata004** [comment]
@enricodias I also thought that setting `headless` to `false` the window should be shown however that is not what is happening on Windows (latest). Everything works fine, no complains. But the window is not showing up and it would help a lot debugging a few things if the window is shown. For now I am using `remote-debugging-port=2288` to connect to the headless window and debug it, bug it is not as practical and easy as having the window opened!

If you could take a look at this, it would be awesome!

**Comment by divinity76** [comment]
@batata004 Wow, I can reproduce this! I thought it might have been a regression in chrome-php so I tried downgrading to v1.9.1 (a known good version) but even 1.9.1 doesn't honor headless in Windows now! (it used to!)

I guess something changed in Chrome recently, that breaks `headless=false` ?

**Comment by divinity76** [comment]
edit: damn, i accidentally gave headless to BrowserFactory's __construct instead of createBrowser() x.x fixing that, i have confirmed that headless=false works "everywhere" (Windows, WSL Ubuntu, VMWare Ubuntu) for me..

@batata004 just to rule out user error, does this code create a browser window for you? it's the code I used to test Windows+WSL+VMWare
```php
<?php

declare(strict_types=1);
require_once('vendor/autoload.php');
if (PHP_OS_FAMILY === 'Windows') {
    $chromiumPath = 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe';
} elseif (PHP_OS_FAMILY === 'Linux') {
    $chromiumPath = '/snap/bin/chromium';
} else {
    throw new Exception('???');
}
$browserFactory = new \HeadlessChromium\BrowserFactory(
    $chromiumPath
);
$browser = $browserFactory->createBrowser(
    [
        'headless' => false,
    ]
);
$page = $browser->createPage();
$page->navigate('https://example.com')->waitForNavigation();
// image
$page->screenshot()->saveToFile('test.png');
echo "sleeping...";
sleep(9999);
```

**Comment by batata004** [comment]
@divinity76 Thanks my dear friend to take a look at this. I tested your code as you requested (I had just to change the path to `$chromiumPath = 'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe';` and it succesfully created the file `test.png` however the window of Chrome never opened. Then I made a few tests and I discovered one thing!

99% of people run Apache in their Windows machines as a service (you can see it initiated at `services.msc`) and it is what is causing the problem. I then stopped the service and started apache as an application and the Chrome window showed up perfectly.

```
NET STOP "Apache2.4"
start /min "apache title" "Z:\servidor\Apache24\bin\httpd.exe"
```

When I executed Apache with the command line above, the Chrome window showed up as expected. So I am pretty sure this is causing the problem.

Then I went ahead and tried to use my own code that was causing the bug when I reported it here, and now the bug went away (as long Apache is running as an application, not as a service).

```
require "vendor/autoload.php";

use HeadlessChromium\BrowserFactory;
use HeadlessChromium\Page;
use HeadlessChromium\Exception\OperationTimedOut;
use HeadlessChromium\Exception\NavigationExpired;

$browserFactory = new BrowserFactory();

$browser = $browserFactory->createBrowser([

	"headless" => false,
	"userDataDir" => "C:\porra9",
	"windowSize" => [1920,1000],
	"enableImages" => true,
	"sendSyncDefaultTimeout" => 10000,
	//chrome://inspect/#devices -> adicione "127.0.0.1:2255"
	"customFlags" => ["--remote-debugging-port=3311"]
	
]);
```

Hope this helps.

**Comment by enricodias** [comment]
Windows services can't interact with the desktop by default. I remember seeing an option to enable this several years ago, but I can't test it at the moment. I found [this question](https://stackoverflow.com/questions/4237225/allow-windows-service-to-interact-with-desktop) on stackoverflow that may help with it, although I doubt that it would work on windows 10 or 11.

I'll update the issue title to make it easier for people to find it.
