### ISSUE TITLE
[Question] How to close all opened browsers

### ISSUE THREAD

**Issue by batata004** [chrome-php/headless-chromium-php#585]
Hi,

Sometimes I execute `createBrowser` and forget to execute ` $browser->close();`. When I check Task Manager, I see dozens and dozens of Chrome processes opened. I need to killall using command line. So I was wondering: is there a way I can kill all those headless browsers that were opened previously using your library? Or the only way is indeed using command line to kill all chrome processes?

**Comment by enricodias** [comment]
If the php script finishes executing without closing the browser, it looses the reference to the chrome process. You could put your code inside a `try` clause and put the `$browser->close();` code in the `finally` clause to make sure it runs every time. When developing and debugging, using unit tests is easier.

**Comment by batata004** [comment]
Thank you so much!!!!
