### ISSUE TITLE
Support for PHP 8.3

### ISSUE THREAD

**Issue by RpCoding** [chrome-php/headless-chromium-php#605]
Please add support for PHP 8.3

**Comment by GrahamCampbell** [comment]
Blocked by https://github.com/chrome-php/wrench/pull/14.

**Comment by GrahamCampbell** [comment]
@RpCoding feel free to send in a PR to wrench that fixes PHP 8.3. That's the fastest way that's going to happen.

**Comment by GrahamCampbell** [comment]
Will be fixed in today's release.
