### ISSUE TITLE
waitUntilContainsElement with logical operator?

### ISSUE THREAD

**Issue by RenissonSilva** [chrome-php/headless-chromium-php#607]
Is there a way to use "waitUntilContainsElement" with a logical operator where if one of the conditions is true it continues the process?

The problem is that I'm doing a submit, when it works, a div appears with some information, and when it goes wrong, a toast message appears informing the error.

**Comment by divinity76** [comment]
```php
while($page->evaluate("document.querySelectorAll('element1,element2').length")->getReturnValue() < 1){
    sleep(1);
}
```

**Comment by RenissonSilva** [comment]
> ```
> while($page->evaluate("document.querySelectorAll('element1,element2').length")->getReturnValue() < 1){
>     sleep(1);
> }
> ```

Thank you, worked perfectly
