### ISSUE TITLE
PHP is not a snap cgroup (Chromium)

### ISSUE THREAD

**Issue by praemon** [chrome-php/headless-chromium-php#617]
So I'm experiencing the below intermittent startup error using chromium on Ubuntu 22.04.4 LTS:

`Chrome process stopped before startup completed. Additional info: /system.slice/php8.2-fpm.service is not a snap cgroup`

It seems somewhat related to https://github.com/chrome-php/chrome/issues/479, however, that's more inline with file permissions. I don't see any permission issues with the PHP user, and as mentioned this error only happens sometimes.

From what I've read I could try enable "lingering" for the PHP via `loginctl enable-linger php8.2-fpm`, however, I'm not sure of the ramifications of this.

Anyone experience a similar issue and what is the best resolution? Thanks!

**Comment by cavid90** [comment]
I also have similar problem. 
Chrome process stopped before startup completed. Additional info:snap-update-ns failed with code 1

It seems chromium latest version has problems.

**Comment by praemon** [comment]
I think the quick solution is installing without snap or installing Google Chrome. I can't do the latter since I'm on ARM64, so will need to see about installing chromium without snap. Odd thing I noticed is that if I login with any user via SSH it works. As soon as I log out, it fails.

**Comment by cavid90** [comment]
I uninstalled chromium and installed it again and then tried commands here and it worked again:
[chromium fails to start with non-standard home directory](https://bugs.launchpad.net/ubuntu/+source/chromium-browser/+bug/2061981)

**Comment by praemon** [comment]
The solution for me was to enable user-lingering as per https://askubuntu.com/questions/1444787/unable-to-launch-the-chromium-browser-via-puppeteer-on-ubuntu-22-04-after-a-rebo

I was unable to successfully install Chromium on Ubuntu 22.04.4 LTS (arm64) without snap, and re-installing didn't help, so this was the only option.
