### ISSUE TITLE
The background color of thead is overridden by the background color of tbody on the second page.

### ISSUE THREAD

**Issue by smartopworks** [chrome-php/headless-chromium-php#636]
Hi,

We tried to create a table with thead, tbody and tfoot, everything looks fine but the background color of thead on the second page seems to be overridden by the background color of tbody, not sure what we should improve it.

Please find the code as below and what it looks like with it;

`<!DOCTYPE html>
<html lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <style>
        tfoot,
        thead {
            background-color: #2c5e77;
            color: #fff;
        }

        table {
            border-collapse: collapse;
            border: 2px solid rgb(140 140 140);
            font-family: sans-serif;
            font-size: .8rem;
        }

        td,
        th {
            border: 1px solid rgb(160 160 160);
            padding: 8px 10px;
        }

        td {
            text-align: center;
        }
    </style>
</head>

<body>
    <table>
        <thead>
            <tr>
                <th>Item</th>
                <th>Text</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td style="background-color:red">Item 1</td>
                <td>**1. Base Composition (Indentation Number: 001)** The base composition of any paint product serves
                    as its fundamental building block, dictating its performance, durability, and compatibility with
                    various surfaces. Within the indentation numbering system, designated as 001, this specification is
                    meticulously outlined to provide consumers and industry professionals with a comprehensive
                    understanding of the paint's formulation. **1. Base Composition (Indentation Number: 001)** The base
                    composition of any paint product serves as its fundamental building block, dictating its
                    performance, durability, and compatibility with various surfaces. Within the indentation numbering
                    system, designated as 001, this specification is meticulously outlined to provide consumers and
                    industry professionals with a comprehensive understanding of the paint's formulation. At the core of
                    the base composition lies a delicate balance of binders, solvents, and additives, each playing a
                    pivotal role in shaping the paint's characteristics. Binders, often polymers or resins, serve as the
                    adhesive component, binding pigment particles together and adhering them to the painted surface.
                    Solvents, on the other hand, facilitate viscosity adjustments, aiding in application and evaporation
                    to expedite the drying process. Additives encompass a myriad of compounds, ranging from thickeners
                    and stabilizers to anti-fungal agents and UV inhibitors, imparting additional functionalities to the
                    paint formulation. The indentation numbering system elucidates the precise constituents of the base
                    composition, detailing their proportions and interactions. For instance, acrylic-based paints boast
                    superior adhesion and flexibility, making them ideal for exterior applications subjected to
                    temperature fluctuations and weathering. In contrast, oil-based paints offer unparalleled durability
                    and resistance to moisture, rendering them suitable for high-traffic areas such as kitchens and
                    bathrooms. Furthermore, the base composition specification delves into the environmental
                    implications of the paint formulation, addressing concerns regarding volatile organic compound (VOC)
                    emissions and hazardous chemicals. With increasing emphasis on sustainability and eco-friendliness,
                    manufacturers strive to develop low-VOC and zero-VOC formulations, minimizing environmental impact
                    without compromising performance. In essence, the base composition specification under indentation
                    number 001 serves as a cornerstone of paint product characterization, guiding consumers, architects,
                    and contractors in selecting the optimal formulation for their specific needs. By unraveling the
                    intricacies of binders, solvents, and additives within the paint matrix, this specification empowers
                    stakeholders to make informed decisions aligned with performance requirements, aesthetic
                    preferences, and environmental considerations. **2. Color Palette (Indentation Number: 002)** The
                    color palette of a paint product is arguably one of its most visually striking attributes,
                    captivating consumers with a kaleidoscope of hues and shades. Designated as indentation number 002
                    within the comprehensive specification framework, the color palette specification elucidates the
                    myriad colors available within the product range, empowering consumers to unleash their creativity
                    and express their individuality through color selection. Within the indentation numbering system,
                    each color is assigned a unique identifier, facilitating navigation and reference amidst a vast
                    array of options. Whether it's vibrant primary colors, soothing pastels, or sophisticated neutrals,
                    the color palette specification encompasses a diverse spectrum tailored to diverse aesthetic
                    sensibilities and design preferences. Moreover, the color palette specification transcends
                    conventional boundaries, embracing emerging trends and timeless classics alike. From bold,
                    statement-making tones to understated, elegant shades, manufacturers continuously innovate to cater
                    to evolving consumer tastes and design trends. Beyond aesthetics, the color palette specification
                    also addresses practical considerations such as colorfastness, lightfastness, and compatibility with
                    different substrates. Whether it's interior walls, exterior facades, or specialty applications such
                    as automotive refinishing, each color is formulated to withstand the rigors of its intended
                    environment while retaining its vibrancy and luster over time. In addition, the color palette
                    specification serves as a catalyst for creative inspiration, empowering designers, architects, and
                    homeowners to transform spaces with confidence and flair. By providing a curated selection of colors
                    harmonized within the overarching paint product line, this specification fosters coherence and
                    continuity in design schemes, whether it's a single accent wall or a cohesive color scheme spanning
                    an entire property. In essence, the color palette specification under indentation number 002
                    embodies the marriage of aesthetics and functionality, offering consumers a diverse array of colors
                    to elevate their living spaces, evoke emotions, and manifest their design vision. As a cornerstone
                    of the paint product specification, the color palette ignites creativity, fosters self-expression,
                    and transforms mundane surfaces into vibrant canvases of personal style and identity.</td>
            </tr>
            <tr>
                <td style="background-color:red">Item 2</td>
                <td>**1. Base Composition (Indentation Number: 001)** The base composition of any paint product serves
                    as its fundamental building block, dictating its performance, durability, and compatibility with
                    various surfaces. Within the indentation numbering system, designated as 001, this specification is
                    meticulously outlined to provide consumers and industry professionals with a comprehensive
                    understanding of the paint's formulation. **1. Base Composition (Indentation Number: 001)** The base
                    composition of any paint product serves as its fundamental building block, dictating its
                    performance, durability, and compatibility with various surfaces. Within the indentation numbering
                    system, designated as 001, this specification is meticulously outlined to provide consumers and
                    industry professionals with a comprehensive understanding of the paint's formulation. At the core of
                    the base composition lies a delicate balance of binders, solvents, and additives, each playing a
                    pivotal role in shaping the paint's characteristics. Binders, often polymers or resins, serve as the
                    adhesive component, binding pigment particles together and adhering them to the painted surface.
                    Solvents, on the other hand, facilitate viscosity adjustments, aiding in application and evaporation
                    to expedite the drying process. Additives encompass a myriad of compounds, ranging from thickeners
                    and stabilizers to anti-fungal agents and UV inhibitors, imparting additional functionalities to the
                    paint formulation. The indentation numbering system elucidates the precise constituents of the base
                    composition, detailing their proportions and interactions. For instance, acrylic-based paints boast
                    superior adhesion and flexibility, making them ideal for exterior applications subjected to
                    temperature fluctuations and weathering. In contrast, oil-based paints offer unparalleled durability
                    and resistance to moisture, rendering them suitable for high-traffic areas such as kitchens and
                    bathrooms. industry professionals with a comprehensive understanding of the paint's formulation. At
                    the core of the base composition lies a delicate balance of binders, solvents, and additives, each
                    playing a pivotal role in shaping the paint's characteristics. Binders, often polymers or resins,
                    serve as the adhesive component, binding pigment particles together and adhering them to the painted
                    surface. Solvents, on the other hand, facilitate viscosity adjustments, aiding in application and
                    evaporation to expedite the drying process. Additives encompass a myriad of compounds, ranging from
                    thickeners and stabilizers to anti-fungal agents and UV inhibitors, imparting additional
                    functionalities to the paint formulation. The indentation numbering system elucidates the precise
                    constituents of the base composition, detailing their proportions and interactions. For instance,
                    acrylic-based paints boast superior adhesion and flexibility, making them ideal for exterior
                    applications subjected to temperature fluctuations and weathering. In contrast, oil-based paints
                    offer unparalleled durability and resistance to moisture, rendering them suitable for high-traffic
                    areas such as kitchens and bathrooms. industry professionals with a comprehensive understanding of
                    the paint's formulation. At the core of the base composition lies a delicate balance of binders,
                    solvents, and additives, each playing a pivotal role in shaping the paint's characteristics.
                    Binders, often polymers or resins, serve as the adhesive component, binding pigment particles
                    together and adhering them to the painted surface. Solvents, on the other hand, facilitate viscosity
                    adjustments, aiding in application and evaporation to expedite the drying process. Additives
                    encompass a myriad of compounds, ranging from thickeners and stabilizers to anti-fungal agents and
                    UV inhibitors, imparting additional functionalities to the paint formulation. The indentation
                    numbering system elucidates the precise constituents of the base composition, detailing their
                    proportions and interactions. For instance, acrylic-based paints boast superior adhesion and
                    flexibility, making them ideal for exterior applications subjected to temperature fluctuations and
                    weathering. In contrast, oil-based paints offer unparalleled durability and resistance to moisture,
                    rendering them suitable for high-traffic areas such as kitchens and bathrooms. industry
                    professionals with a comprehensive understanding of the paint's formulation. At the core of the base
                    composition lies a delicate balance of binders, solvents, and additives, each playing a pivotal role
                    in shaping the paint's characteristics. Binders, often polymers or resins, serve as the adhesive
                    component, binding pigment particles together and adhering them to the painted surface. Solvents, on
                    the other hand, facilitate viscosity adjustments, aiding in application and evaporation to expedite
                    the drying process. Additives encompass a myriad of compounds, ranging from thickeners and
                    stabilizers to anti-fungal agents and UV inhibitors, imparting additional functionalities to the
                    paint formulation. The indentation numbering system elucidates the precise constituents of the base
                    composition, detailing their proportions and interactions. For instance, acrylic-based paints boast
                    superior adhesion and flexibility, making them ideal for exterior applications subjected to
                    temperature fluctuations and weathering. In contrast, oil-based paints offer unparalleled durability
                    and resistance to moisture, rendering them suitable for high-traffic areas such as kitchens and
                    bathrooms. industry professionals with a comprehensive understanding of the paint's formulation. At
                    the core of the base composition lies a delicate balance of binders, solvents, and additives, each
                    playing a pivotal role in shaping the paint's characteristics. Binders, often polymers or resins,
                    serve as the adhesive component, binding pigment particles together and adhering them to the painted
                    surface. Solvents, on the other hand, facilitate viscosity adjustments, aiding in application and
                    evaporation to expedite the drying process. Additives encompass a myriad of compounds, ranging from
                    thickeners and stabilizers to anti-fungal agents and UV inhibitors, imparting additional
                    functionalities to the paint formulation. The indentation numbering system elucidates the precise
                    constituents of the base composition, detailing their proportions and interactions. For instance,
                    acrylic-based paints boast superior adhesion and flexibility, making them ideal for exterior
                    applications subjected to temperature fluctuations and weathering. In contrast, oil-based paints
                    offer unparalleled durability and resistance to moisture, rendering them suitable for high-traffic
                    areas such as kitchens and bathrooms. industry professionals with a comprehensive understanding of
                    the paint's formulation. At the core of the base composition lies a delicate balance of binders,
                    solvents, and additives, each playing a pivotal role in shaping the paint's characteristics.
                    Binders, often polymers or resins, serve as the adhesive component, binding pigment particles
                    together and adhering them to the painted surface. Solvents, on the other hand, facilitate viscosity
                    adjustments, aiding in application and evaporation to expedite the drying process. Additives
                    encompass a myriad of compounds, ranging from thickeners and stabilizers to anti-fungal agents and
                    UV inhibitors, imparting additional functionalities to the paint formulation. The indentation
                    numbering system elucidates the precise constituents of the base composition, detailing their
                    proportions and interactions. For instance, acrylic-based paints boast superior adhesion and
                    flexibility, making them ideal for exterior applications subjected to temperature fluctuations and
                    weathering. In contrast, oil-based paints offer unparalleled durability and resistance to moisture,
                    rendering them suitable for high-traffic areas such as kitchens and bathrooms. industry
                    professionals with a comprehensive understanding of the paint's formulation. At the core of the base
                    composition lies a delicate balance of binders, solvents, and additives, each playing a pivotal role
                    in shaping the paint's characteristics. Binders, often polymers or resins, serve as the adhesive
                    component, binding pigment particles together and adhering them to the painted surface. Solvents, on
                    the other hand, facilitate viscosity adjustments, aiding in application and evaporation to expedite
                    the drying process. Additives encompass a myriad of compounds, ranging from thickeners and
                    stabilizers to anti-fungal agents and UV inhibitors, imparting additional functionalities to the
                    paint formulation. The indentation numbering system elucidates the precise constituents of the base
                    composition, detailing their proportions and interactions. For instance, acrylic-based paints boast
                    superior adhesion and flexibility, making them ideal for exterior applications subjected to
                    temperature fluctuations and weathering. In contrast, oil-based paints offer unparalleled durability
                    and resistance to moisture, rendering them suitable for high-traffic areas such as kitchens and
                    bathrooms. industry professionals with a comprehensive understanding of the paint's formulation. At
                    the core of the base composition lies a delicate balance of binders, solvents, and additives, each
                    playing a pivotal role in shaping the paint's characteristics. Binders, often polymers or resins,
                    serve as the adhesive component, binding pigment particles together and adhering them to the painted
                    surface. Solvents, on the other hand, facilitate viscosity adjustments, aiding in application and
                    evaporation to expedite the drying process. Additives encompass a myriad of compounds, ranging from
                    thickeners and stabilizers to anti-fungal agents and UV inhibitors, imparting additional
                    functionalities to the paint formulation. The indentation numbering system elucidates the precise
                    constituents of the base composition, detailing their proportions and interactions. For instance,
                    acrylic-based paints boast superior adhesion and flexibility, making them ideal for exterior
                    applications subjected to temperature fluctuations and weathering. In contrast, oil-based paints
                    offer unparalleled durability and resistance to moisture, rendering them suitable for high-traffic
                    areas such as kitchens and bathrooms. industry professionals with a comprehensive understanding of
                    the paint's formulation. At the core of the base composition lies a delicate balance of binders,
                    solvents, and additives, each playing a pivotal role in shaping the paint's characteristics.
                    Binders, often polymers or resins, serve as the adhesive component, binding pigment particles
                    together and adhering them to the painted surface. Solvents, on the other hand, facilitate viscosity
                    adjustments, aiding in application and evaporation to expedite the drying process. Additives
                    encompass a myriad of compounds, ranging from thickeners and stabilizers to anti-fungal agents and
                    UV inhibitors, imparting additional functionalities to the paint formulation. The indentation
                    numbering system elucidates the precise constituents of the base composition, detailing their
                    proportions and interactions. For instance, acrylic-based paints boast superior adhesion and
                    flexibility, making them ideal for exterior applications subjected to temperature fluctuations and
                    weathering. In contrast, oil-based paints offer unparalleled durability and resistance to moisture,
                    rendering them suitable for high-traffic areas such as kitchens and bathrooms. industry
                    professionals with a comprehensive understanding of the paint's formulation. At the core of the base
                    composition lies a delicate balance of binders, solvents, and additives, each playing a pivotal role
                    in shaping the paint's characteristics. Binders, often polymers or resins, serve as the adhesive
                    component, binding pigment particles together and adhering them to the painted surface. Solvents, on
                    the other hand, facilitate viscosity adjustments, aiding in application and evaporation to expedite
                    the drying process. Additives encompass a myriad of compounds, ranging from thickeners and
                    stabilizers to anti-fungal agents and UV inhibitors, imparting additional functionalities to the
                    paint formulation. The indentation numbering system elucidates the precise constituents of the base
                    composition, detailing their proportions and interactions. For instance, acrylic-based paints boast
                    superior adhesion and flexibility, making them ideal for exterior applications subjected to
                    temperature fluctuations and weathering. In contrast, oil-based paints offer unparalleled durability
                    and resistance to moisture, rendering them suitable for high-traffic areas such as kitchens and
                    bathrooms. Furthermore, the base composition specification delves into the environmental
                    implications of the paint formulation, addressing concerns regarding volatile organic compound (VOC)
                    emissions and hazardous chemicals. With increasing emphasis on sustainability and eco-friendliness,
                    manufacturers strive to develop low-VOC and zero-VOC formulations, minimizing environmental impact
                    without compromising performance. In essence, the base composition specification under indentation
                    number 001 serves as a cornerstone of paint product characterization, guiding consumers, architects,
                    and contractors in selecting the optimal formulation for their specific needs. By unraveling the
                    intricacies of binders, solvents, and additives within the paint matrix, this specification empowers
                    stakeholders to make informed decisions aligned with performance requirements, aesthetic
                    preferences, and environmental considerations. **2. Color Palette (Indentation Number: 002)** The
                    color palette of a paint product is arguably one of its most visually striking attributes,
                    captivating consumers with a kaleidoscope of hues and shades. Designated as indentation number 002
                    within the comprehensive specification framework, the color palette specification elucidates the
                    myriad colors available within the product range, empowering consumers to unleash their creativity
                    and express their individuality through color selection. Within the indentation numbering system,
                    each color is assigned a unique identifier, facilitating navigation and reference amidst a vast
                    array of options. Whether it's vibrant primary colors, soothing pastels, or sophisticated neutrals,
                    the color palette specification encompasses a diverse spectrum tailored to diverse aesthetic
                    sensibilities and design preferences. Moreover, the color palette specification transcends
                    conventional boundaries, embracing emerging trends and timeless classics alike. From bold,
                    statement-making tones to understated, elegant shades, manufacturers continuously innovate to cater
                    to evolving consumer tastes and design trends. Beyond aesthetics, the color palette specification
                    also addresses practical considerations such as colorfastness, lightfastness, and compatibility with
                    different substrates. Whether it's interior walls, exterior facades, or specialty applications such
                    as automotive refinishing, each color is formulated to withstand the rigors of its intended
                    environment while retaining its vibrancy and luster over time. In addition, the color palette
                    specification serves as a catalyst for creative inspiration, empowering designers, architects, and
                    homeowners to transform spaces with confidence and flair. By providing a curated selection of colors
                    harmonized within the overarching paint product line, this specification fosters coherence and
                    continuity in design schemes, whether it's a single accent wall or a cohesive color scheme spanning
                    an entire property. In essence, the color palette specification under indentation number 002
                    embodies the marriage of aesthetics and functionality, offering consumers a diverse array of colors
                    to elevate their living spaces, evoke emotions, and manifest their design vision. As a cornerstone
                    of the paint product specification, the color palette ignites creativity, fosters self-expression,
                    and transforms mundane surfaces into vibrant canvases of personal style and identity.</td>
            </tr>
        </tbody>
        <tfoot>
            <tr>
                <td colspan="2">Hello World!</td>
            </tr>
        </tfoot>
</body>

</html>`

![screenshot](https://github.com/user-attachments/assets/d98ea205-cb1b-40ae-b51d-21231bb320bd)

Thanks

**Comment by enricodias** [comment]
This question is not related to this project. This library only controls chrome using php. You will have batter luck submitting it to stackoverflow.
