### ISSUE TITLE
Grabbing whole HTML

### ISSUE THREAD

**Issue by SEOArcade** [chrome-php/headless-chromium-php#64]
Hi there, I am trying to get pages html (whole). Is there an easy way to do this? When I am printing $page, it gives me more than I want.

**Comment by SEOArcade** [comment]
OK, found it. Thanks!

**Comment by eliosh** [comment]
Just to help someone else:

`$html_source = $page->evaluate('document.documentElement.innerHTML')->getReturnValue();`

**Comment by aqib026** [comment]
> Just to help someone else:
> 
> `$html_source = $page->evaluate('document.documentElement.innerHTML')->getReturnValue();`

but it does render the JS or angular stuff , though PDF is rendering stuff fine
