### ISSUE TITLE
Iframe Access

### ISSUE THREAD

**Issue by andreas-globi** [chrome-php/headless-chromium-php#642]
We're using chrome-php for our testing suite.

What we really need is to be able to access iframes for testing Stripe forms. Since it's cross-domain, we cannot use JS for this.

Would any of the contributors here be interested in a paid feature request?

**Comment by jonnywilliamson** [comment]
@andreas-globi Did you ever find out how to access an iframe?

**Comment by andreas-globi** [comment]
No. I tried for many days but could not get it to work. In the end I switched to Facebook\WebDriver\Chrome\ChromeDriver

**Comment by jonnywilliamson** [comment]
I feared as much. Thanks for getting back to me!
