### ISSUE TITLE
adding page to PDF?

### ISSUE THREAD

**Issue by Offbeatmammal** [chrome-php/headless-chromium-php#645]
if I want to loop through a cycle of rendering a 'page', adding to to a PDF then moving to the next page and repeating, is there an optimal way of doing it, or is the best solution to write each page to a temporary PDF and them merge using something like [pdf-merger](https://github.com/clegginabox/pdf-merger)

Is it also possible to include something in the HTML being converted that would indicate a page break in the output PDF?

**Comment by enricodias** [comment]
This lib doesn't create pdf by itself, it just uses the chrome's print feature. Creating several temporary files and merging them with another lib is the best method I can think of.

About the page break, there's a few css properties that may be used to do that. Check [this](https://stackoverflow.com/questions/1664049/can-i-force-a-page-break-in-html-printing) thread.

**Comment by Offbeatmammal** [comment]
thanks, will have a play
