### ISSUE TITLE
Policy to clean temp files

### ISSUE THREAD

**Issue by scorninpc** [chrome-php/headless-chromium-php#647]
My server stopped today due not free space, and analysing i saw that chrome-php are creating a loooot of tmp files

![image](https://github.com/user-attachments/assets/d3e42023-ae77-4cbb-9ef4-a8bde7d56b22)

There is some config or way to configure this kind of temp files?

**Comment by enricodias** [comment]
This lib doesn't intentionally leave any temp files like that, but chrome itself might. What's the content of those temp files you found?

**Comment by scorninpc** [comment]
yeah, I figured it was something related to chrome! But I figured there might be something to configure in the lib

This folders apper to be a user profile of chrome

![image](https://github.com/user-attachments/assets/d114bea2-5b95-4fc5-9a79-8627bd3319cc)

Maybe configure user profile path to use the same always?

**Comment by enricodias** [comment]
You can reuse the same profile using the option [userDataDir](https://github.com/chrome-php/chrome/#available-options) for the browser factory. That should solve your problem.

**Comment by scorninpc** [comment]
This is perfect @enricodias, it works like a charm. My lack of attention
