### ISSUE TITLE
Error While Generate PDF

### ISSUE THREAD

**Issue by Ramdevpatel2426** [chrome-php/headless-chromium-php#650]
<br />
<b>Fatal error</b>:  Uncaught HeadlessChromium\Exception\OperationTimedOut: Operation timed out after 50s. in C:\xampp\htdocs\Export-Document\library\chrome-php-3\chrome-php\chrome\src\Exception\OperationTimedOut.php:18
Stack trace:
#0 C:\xampp\htdocs\Export-Document\library\chrome-php-3\chrome-php\chrome\src\Utils.php(67): HeadlessChromium\Exception\OperationTimedOut::createFromTimeout(50000000)
#1 C:\xampp\htdocs\Export-Document\library\chrome-php-3\chrome-php\chrome\src\Communication\ResponseReader.php(114): HeadlessChromium\Utils::tryWithTimeout(50000000, Object(Generator))
#2 C:\xampp\htdocs\Export-Document\pdf.php(48): HeadlessChromium\Communication\ResponseReader-&gt;waitForResponse(50000)
#3 {main}
  thrown in <b>C:\xampp\htdocs\Export-Document\library\chrome-php-3\chrome-php\chrome\src\Exception\OperationTimedOut.php</b> on line <b>18</b><br />

**Comment by enricodias** [comment]
Check issues #381 and #202.
