### ISSUE TITLE
Why does it generate a large number of chrome processes?

### ISSUE THREAD

**Issue by phpmooc** [chrome-php/headless-chromium-php#654]
VERSION:  1.11.0
---
just one very simple demo code as follow:
```php
<?php

require "vendor/autoload.php";

use HeadlessChromium\BrowserFactory;

$browserFactory = new BrowserFactory();
$browser = $browserFactory->createBrowser();

$page = $browser->createPage();
// navigate
$navigation = $page->navigate('https://example.com');
// wait for the page to be loaded
$navigation->waitForNavigation();
//just for convenience to view TOP chrome process status
sleep(100);
```

it generates a large number of chrome processes after running the demo script,  which seems incredible,  so what am I doing wrong or what happend there?  thanks a lot.

**Comment by enricodias** [comment]
Those are all chorme processes, not related to this lib itself. Chrome does create multiple processes and threads like that during normal usage. If you open the browser manually you'll see the same thing.

**Comment by phpmooc** [comment]
yep，that's indeed created by Chrome self，but I wonder why it produces so many processes for the demo above?  all the code is just the simple demo code self，no other codes at all，what I mean is that should be a normal usage，right? thanks for your help.

**Comment by phpmooc** [comment]
another question，is it possible to disable the option `--remote-debugging-port` ?

**Comment by enricodias** [comment]
My chrome creates more processes than your example, even without navigating to any url. Browsers are more complex than you think.

Without the `--remote-debugging-port` option the lib won't be able to control the browser.

**Comment by phpmooc** [comment]
got it，thanks again.
