### ISSUE TITLE
chrome_crashpad_handler:--database is required  with the latest chromium

### ISSUE THREAD

**Issue by ramyag22** [chrome-php/headless-chromium-php#661]
Latest Chromium gives below error 
Error:
 Cannot start ChromeHeadless
	chrome_crashpad_handler: --database is required

My Dockerfile has below env variables and created the config folder too , but still seeing the error.

ENV CHROME_BIN /usr/bin/chromium
ENV XDG_CONFIG_HOME /tmp/.chromium
ENV XDG_CACHE_HOME /tmp/.chromium

**Comment by enricodias** [comment]
Check #649
