### ISSUE TITLE
Catch XHR  requests?

### ISSUE THREAD

**Issue by BonBonSlick** [chrome-php/headless-chromium-php#73]
There is script which sends  background XHR (can be seen in Network dev tab) request when page loaded, tell me please  can I get it is JSON response?
I know request url.
XHR response stored somewhere in JS variable in some js file.

**Comment by t-geindre** [comment]
You could override XHR prototype to intercept calls and data.

**Comment by BonBonSlick** [comment]
@t-geindre 
any examples or links please?
> override XHR prototype

Something like that
```
(function() {
    var proxied = window.XMLHttpRequest.open;
    window.XMLHttpRequest.open = function() {
        $('.log').html(arguments[0]);
        return proxied.apply(this, arguments);
    };
})();
```

Put in promise? Or how?

php
 ```
   $result = $page->evaluate('new Promise(resolve => {
            let interval = setInterval(() => {
                    clearInterval(interval);
                    resolve();
            }, 20000);
        })'
    );
```

**Comment by t-geindre** [comment]
Here is what I did to get sent headers on a specific API.

First I added the following script to my page:
```php
$page->addPreScript(file_get_contents('path/to/script.js));
```
```javascript
var MyApp = MyApp || {};

(function(window) {
    var
        proxied = {},
        headersLog = false,
        apiUrl = 'https://my.api.com',
        intercepted = false,
        xhrPrototype = window.XMLHttpRequest.prototype
    ;

    ['open', 'setRequestHeader', 'send'].forEach(
        method => proxied[method] = xhrPrototype[method]
    );

    xhrPrototype.open = function(method, url) {
        if (!intercepted && url.substr(0, apiUrl.length) === apiUrl) {
            headersLog = {};
        }

        return proxied.open.apply(this, arguments);
    };

    xhrPrototype.setRequestHeader = function(header, value) {
        if (!intercepted && headersLog) {
            headersLog[header] = value;
        }

        return proxied.setRequestHeader.apply(this, arguments);
    };

    xhrPrototype.send = function() {
        if (!intercepted && headersLog) {
            Object.keys(proxied).forEach(method => xhrPrototype[method] = proxied[method]);
            intercepted = true;
        }

        return proxied.send.apply(this, arguments);
    };

    MyApp.getInterceptedHeaders = () => {
        if (!intercepted) {
            return false;
        }

        return headersLog;
    }
})(window);
```

Then you have to poll for a result:

```php
for(;;) {
    $headers = $this->page->evaluate('MyApp.getInterceptedHeaders()')->getReturnValue();
    if (false === $headers) {
        usleep(100000); // 100ms
       continue;
    }
    break;
}
```

**Comment by BonBonSlick** [comment]
@t-geindre  

```
  $catchXHRScript = \file_get_contents(sprintf('%s/js/InterceptXHR.js', $this->assetsDirPath()));
    $browserFactory = new BrowserFactory('/usr/bin/google-chrome-stable');
    $browser        = $browserFactory->createBrowser();
    $page           = $browser->createPage();
    $page->addPreScript($catchXHRScript);
    $page->navigate('https://site.com')
         ->waitForNavigation();
    usleep(5);

    for(;;) {
      $headers = $page->evaluate('MyApp.getInterceptedHeaders()')->getReturnValue();
      if (false === $headers) {
        \usleep(100000); // 100ms
        continue;
      }
      break;
    }

    $browser->close();
```
 result = endless loop.

InterceptXHR.js
```

'use strict';

var MyApp = MyApp || {};

(function (window) {
    var
        proxied = {},
        headersLog = false,
        apiUrl = 'https://localhost.loc/api/v1/intercept',
        intercepted = false,
        xhrPrototype = window.XMLHttpRequest.prototype
    ;

    ['open', 'setRequestHeader', 'send'].forEach(
        method => proxied[method] = xhrPrototype[method]
    );

    xhrPrototype.open = function (method, url) {
        if (!intercepted && url.substr(0, apiUrl.length) === apiUrl) {
            headersLog = {};
        }

        return proxied.open.apply(this, arguments);
    };

    xhrPrototype.setRequestHeader = function (header, value) {
        if (!intercepted && headersLog) {
            headersLog[header] = value;
        }

        return proxied.setRequestHeader.apply(this, arguments);
    };

    xhrPrototype.send = function () {
        if (!intercepted && headersLog) {
            Object.keys(proxied).forEach(method => xhrPrototype[method] = proxied[method]);
            intercepted = true;
        }

        return proxied.send.apply(this, arguments);
    };

    MyApp.getInterceptedHeaders = () => {
        if (!intercepted) {
            return false;
        }

        return headersLog;
    };
})(window);


```
`https://localhost.loc/api/v1/intercept `is link where we send intercepted results.

**Comment by t-geindre** [comment]
I don't know what is wrong with your code.
I don't really know when preScript are executed, but maybe the request you're trying to intercept is executed before the override occurs. And that's probably why the polling code create an infinite loop.

**Comment by BonBonSlick** [comment]
@t-geindre When I open page in browser, XHR request sent after page fully rendered, it is about after 2 secs.  It is displayed in network tab.

**Comment by BonBonSlick** [comment]
@t-geindre Tell me please how to debug this script? Because running it in console directly on website throws exception and with chromium it is always empty array.
```

Uncaught (in promise) TypeError: Illegal invocation
    at XMLHttpRequest.xhrPrototype.open (<anonymous>:22:29)
    at spread.js:25
    at new Promise (<anonymous>)
    at e.exports (spread.js:25)
    at e.exports (spread.js:25)**
```**

**Comment by BonBonSlick** [comment]
@t-geindre probably xhr sent before we start intercepting it.

```
    $page->navigate($url)
         ->waitForNavigation();
```
It called before page fully loaded and rendered from client js code without user interaction. 
Maybe there is other way to trace all XHRs?

**Comment by albi90** [comment]
Im looking to do something similar but not just with XHR requests, i believe you need to use "setRequestInterceptionEnabled" then "requestIntercepted" you can enable RequestInterception by doing the following `$page->getSession()->sendMessage(new Message('Network.setRequestInterceptionEnabled', ['enabled' => true])));`

but im not sure how to achieve the "requestIntercepted" but this should give you the request type and allow you to continue or block the request.

**Comment by ethaniel** [comment]
> Im looking to do something similar but not just with XHR requests, i believe you need to use "setRequestInterceptionEnabled" then "requestIntercepted" you can enable RequestInterception by doing the following `$page->getSession()->sendMessage(new Message('Network.setRequestInterceptionEnabled', ['enabled' => true])));`
> 
> but im not sure how to achieve the "requestIntercepted" but this should give you the request type and allow you to continue or block the request.

Working on your example, I compiled a full script to intercept (and conditionally block) requests:
```php

// function called on each request. Allow only HTML and Javascript coming from google.com, block everything else (images/stylesheets).
$this->page->getSession()->on('method:Network.requestIntercepted', function (array $params): void {
	if (
		(strstr($params["request"]["url"], "google.com") &&
			(
				$params["resourceType"] == "Document" ||
				$params["resourceType"] == "Script" 
			)
		)
	) {

		echo "OK: " . $params["resourceType"] . " - " . $params["request"]["url"] . PHP_EOL;

		// allow request to go through
		$this->page->getSession()->sendMessage(
			new Message('Network.continueInterceptedRequest', ['interceptionId' => $params["interceptionId"]])
		);
	} else {

		echo "BLOCKED: " . $params["resourceType"] . " - " . $params["request"]["url"] . PHP_EOL;

		// block request
		$this->page->getSession()->sendMessage(
			new Message('Network.continueInterceptedRequest', ['interceptionId' => $params["interceptionId"], 'errorReason' => 'BlockedByClient'])
		);

	}
});

// intercept all requests
$this->page->getSession()->sendMessage(new Message('Network.setRequestInterception', ['patterns' => [['urlPattern' => '*']]]));

```

**Comment by divinity76** [comment]
@ethaniel you should install the listener /before/ sending `Network.setRequestInterception` - otherwise there is a race condition where a request firing after `Network.setRequestInterception` and before the listener gets installed would cause a network request to never receive a `Network.continueInterceptedRequest`

**Comment by ethaniel** [comment]
> @ethaniel you should install the listener /before/ sending `Network.setRequestInterception` - otherwise there is a race condition where a request firing after `Network.setRequestInterception` and before the listener gets installed would cause a network request to never receive a `Network.continueInterceptedRequest`

![682c39bd-81ed-4a50-99c9-e9e8b4685973_text](https://github.com/chrome-php/chrome/assets/941973/a65f6fc1-cd3f-4b69-9041-3f029c6cf45d)

Very good call! Updated!

**Comment by codes-begin** [comment]
Hi @enricodias , thank you for your response. I have already tried before asking the question but it is not working. My code is below, please let me know if I am doing anything wrong.
`$page = $browser->createPage();

$page->getSession()->on('method:Network.requestIntercepted', function (array $params): void {
	if(
		(strstr($params["request"]["url"], "google.com") &&
			(
				$params["resourceType"] == "Document" ||
				$params["resourceType"] == "Script" 
			)
		)
	){
		echo "OK: " . $params["resourceType"] . " - " . $params["request"]["url"] . PHP_EOL;

		// allow request to go through
		$this->getSession()->sendMessage(
			new Message('Network.continueInterceptedRequest', ['interceptionId' => $params["interceptionId"]])
		);
	}else{
		echo "BLOCKED: " . $params["resourceType"] . " - " . $params["request"]["url"] . PHP_EOL;

		// block request
		$this->getSession()->sendMessage(
			new Message('Network.continueInterceptedRequest', ['interceptionId' => $params["interceptionId"], 'errorReason' => 'BlockedByClient'])
		);
	}
});

// intercept all requests
$page->getSession()->sendMessage(new Message('Network.setRequestInterception', ['patterns' => [['urlPattern' => '*']]]));

try{
	$page->navigate('https://www.google.com/')->waitForNavigation();`

**Comment by codes-begin** [comment]
Hi @enricodias , thank you for your response. I have already tried before asking the question but it is not working. My code is below, please let me know if I am doing anything wrong.

```
$page = $browser->createPage();

$page->getSession()->on('method:Network.requestIntercepted', function (array $params): void {
	if(
		(strstr($params["request"]["url"], "google.com") &&
			(
				$params["resourceType"] == "Document" ||
				$params["resourceType"] == "Script" 
			)
		)
	){
		echo "OK: " . $params["resourceType"] . " - " . $params["request"]["url"] . PHP_EOL;

		$this->getSession()->sendMessage(
			new Message('Network.continueInterceptedRequest', ['interceptionId' => $params["interceptionId"]])
		);
	}else{
		echo "BLOCKED: " . $params["resourceType"] . " - " . $params["request"]["url"] . PHP_EOL;

		$this->getSession()->sendMessage(
			new Message('Network.continueInterceptedRequest', ['interceptionId' => $params["interceptionId"], 'errorReason' => 'BlockedByClient'])
		);
	}
});

// intercept all requests
$page->getSession()->sendMessage(new Message('Network.setRequestInterception', ['patterns' => [['urlPattern' => '*']]]));

try{
	$page->navigate('https://www.google.com/')->waitForNavigation();
```

**Comment by enricodias** [comment]
@codes-begin at first glance the code looks fine. If it doesn't work you'll need to debug it and see exactly what's happening. Check if the code in that else block is really being executed and what shows up in the chrome's logs. Also check the response of the `Network.setRequestInterception` message to see if it's not returning any error.

**Comment by codes-begin** [comment]
I am getting "Fatal error: Uncaught Error: Using $this when not in object context" on $this->getSession()->sendMessage(
			new Message('Network.continueInterceptedRequest', ['interceptionId' => $params["interceptionId"]])
		);

**Comment by codes-begin** [comment]
Hello,

Changed the second line to this and it worked.
$page->getSession()->on('method:Network.requestIntercepted', function (array $params) use($page):

Thanks.

**Comment by codes-begin** [comment]
I am able to catch all the requests but some blob requests are missing from it which is showing in the network. It is an audio file which is getting appended by js. 
Is there a way to catch it?
