### ISSUE TITLE
) Fatal error: Uncaught RuntimeException: Chrome process stopped before startup completed. 

### ISSUE THREAD

**Issue by menjilx** [chrome-php/headless-chromium-php#75]
I got this bug when trying to run a basic example code.

![image](https://user-images.githubusercontent.com/14908836/53303453-66fb1100-38a5-11e9-8b61-e3b432e6312d.png)

I'm using my macbook pro.

Code
`<?php

require_once "vendor/autoload.php";

use HeadlessChromium\BrowserFactory;

$browserFactory = new BrowserFactory();

$browser = $browserFactory->createBrowser();

// creates a new page and navigate to an url
$page = $browser->createPage();
$page->navigate('https://openload.co/embed/OzEFf-v-Axs/SampleVideo_1280x720_20mb.mp4')->waitForNavigation();

$page->mouse()->move(100,100)->click();

$page->mouse()->move(100,100)->click();

$src = $page->evaluate("document.getElementsByTagName(\"video\")[0].src")->getReturnValue(4);

$headers=get_headers($src);
var_dump($headers);
var_dump($headers[7]);

$browser->close();`

**Comment by quyunet** [comment]
You need to define the browser's execution file or path, example, if you install a stable version of chrome, please use:
$browserFactory = new BrowserFactory('google-chrome');

**Comment by menjilx** [comment]
> You need to define the browser's execution file or path, example, if you install a stable version of chrome, please use:
> $browserFactory = new BrowserFactory('google-chrome');

I have both Chrome and Chromium on may MAC how to pass the path?

I tried this => $browserFactory = new BrowserFactory('google-chrome');

But still no luck.

Thanks

**Comment by quyunet** [comment]
hello, I passed the test in debian 9, you must first find the installation path for Chrome, and test whether chrome can work properly.

I also encounter a problem of submitting forms that can't be solved. Can I contact you by email? I hope I can make friends with you.

best regards,

**Comment by menjilx** [comment]
> hello, I passed the test in debian 9, you must first find the installation path for Chrome, and test whether chrome can work properly.
> 
> best regards,

I am trying to run this on my MacBookPro and I have chrome and chromium installed as well.

**Comment by shahonseven** [comment]
Hi, please try

```
$browserFactory = new BrowserFactory('/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome');
```

Hope this helps.

**Comment by zerolevelsky** [comment]
> Hi, please try
> 
> ```
> $browserFactory = new BrowserFactory('/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome');
> ```
> Hope this helps.

If it is the same problem under Windows?

**Comment by shahonseven** [comment]
Hi, not on windows but I think its like this:
```
$browserFactory = new BrowserFactory('C:\Program Files (x86)\Google\Chrome\Application\chrome.exe');
```

**Comment by zerolevelsky** [comment]
> Hi, not on windows but I think its like this:
> 
> ```
> $browserFactory = new BrowserFactory('C:\Program Files (x86)\Google\Chrome\Application\chrome.exe');
> ```

No, is someone running on windows? Can you give an example?

**Comment by AveRomain** [comment]
On Windows you need double backslash like this:
$browserFactory = new BrowserFactory("\\EasyPHP-Devserver-17\\eds-www\\vendor\\chrome-win\\chrome.exe");

**Comment by menjilx** [comment]
Thank you, everyone, for the help, I already figure this out and decided to use "Puppeteer & NodeJS" for now. :)

**Comment by menjilx** [comment]
> Hi, please try
> 
> ```
> $browserFactory = new BrowserFactory('/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome');
> ```
> Hope this helps.

Thank you!

**Comment by yevheniy2407** [comment]
> Hi, not on windows but I think its like this:
> 
> ```
> $browserFactory = new BrowserFactory('C:\Program Files (x86)\Google\Chrome\Application\chrome.exe');
> ```

This works for me. Thx!

**Comment by zzarbi** [comment]
This works for me: 
```
$browserFactory = new BrowserFactory('/Applications/Google Chrome.app/Contents/MacOS/Google Chrome');
```
No need to add the backslash for the empty space

**Comment by MatrixOfDeath** [comment]
Hey i'm having the issue on my local environment :
```
RuntimeException: Chrome process stopped before startup completed. Additional info: sh: 1: exec: /usr/bin/google-chrome: not found in HeadlessChromium\Browser\BrowserProcess->HeadlessChromium\Browser\{closure}() (line 390 of /var/www/html/vendor/chrome-php/chrome/src/Browser/BrowserProcess.php).
HeadlessChromium\Utils::tryWithTimeout(30000000, Object) (Line: 425)
HeadlessChromium\Browser\BrowserProcess->waitForStartup(Object, 30000000) (Line: 137)
HeadlessChromium\Browser\BrowserProcess->start('/usr/bin/google-chrome', Array) (Line: 73)
HeadlessChromium\BrowserFactory->createBrowser() (Line: 56)
```

I do have my browser google chrome installed in this path '/usr/bin/google-chrome' what am i missing ?

**Comment by RTIREMONEY** [comment]
Fatal error: Uncaught Error: Call to undefined method HeadlessChromium\Page::getTargetId() in C:\x\htdocs\chrome.php:25 Stack trace: #0 {main} thrown in C:\x\htdocs\chrome.php on line 25
