### ISSUE TITLE
Is it possible to inject raw html?

### ISSUE THREAD

**Issue by moometric** [chrome-php/headless-chromium-php#77]
Ideally to create screenshots on the fly when there are dynamic variables on the page.

**Comment by svbackend** [comment]
You can evaluate js code which will add raw html to the page and then you can make screenshot. Could you explain more detailed what you want to do and where did you stuck?

**Comment by moometric** [comment]
Just a basic example. I want to render a page with the follow HTML. Right now i'm pulling from a local template.html file, but want to eliminate that and simply inject that code and render the page.

`<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Hello World</title>
    <link href="https://fonts.googleapis.com/css?family=Rubik:500,700,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Raleway:400,500,700,800,900" rel="stylesheet">
  </head>`

**Comment by svbackend** [comment]
Use evaluate method, you can change html code of the page as you want, just replace 'Hello World!' by your html:

    $browserFactory = new BrowserFactory();
    $browser = $browserFactory->createBrowser();
    $page = $browser->createPage();
    $page->navigate('https://google.com')->waitForNavigation();
    $page->evaluate("document.getElementsByTagName('html')[0].innerHTML = 'Hello world!';");
    // Make screenshot

**Comment by sergiosusa** [comment]
i have a similar issue, i've generated a html using twig engine then i want to transform that html to a pdf file, but i can't inject it correctly using the solution before. 

I got a page without styles.

**Comment by moometric** [comment]
@sergiosusa - this is what works for me. My current template also uses external style sheets.

`
$rawHTML =<h1>Hello World</h1>;
$browser = $browserFactory->createBrowser(
    	['windowSize' => [600, 600],
        'enableImages' => true]);
$page = $browser->createPage();
$page->evaluate("document.getElementsByTagName('html')[0].innerHTML = '{$rawHTML}';");
$screenshot = $page->screenshot([
        'format'  => 'jpeg',  // default to 'png' - possible values: 'png', 'jpeg',
        'quality' => 100       // only if format is 'jpeg' - default 100 
    ]);
`

I haven't tried with PDF, but maybe test with a simple screenshot to see if you're at least getting the correct styles.

**Comment by moometric** [comment]
@sergiosusa - Thought I had it working, but faced a similar issue. First I had to effectively minify the HTML (no new lines, line breaks, etc). Then I could pass the variable to add the new HTML on the page. MOST important, once the html has been added, I added sleep(5) to give the page time to re-render before taking a screenshot 
`$browserFactory = new BrowserFactory('chromium-browser');`
`$browser = $browserFactory->createBrowser();`
`$page = $browser->createPage();`    
`$uri = file_get_contents('file://'.dirname(__FILE__).'/template.html');`
`$uri = preg_replace(array('/ {2,}/','/<!--.*?-->|\t|(?:\r?\n[ \t]*)+/s'), array(' ', ''), $uri);`
`$uri = addslashes($uri);`
`$navigation = $page->navigate("about:blank")->waitForNavigation();`
`$page->evaluate("document.getElementsByTagName('html')[0].innerHTML = '{$uri}';");`
`sleep(5);`

`$screenshot = $page->screenshot(['format'  => 'jpeg', 'quality' => 100 ]);`

**Comment by sergiosusa** [comment]
@moometric thanks for your answer, i've found a simple but not so elegant solution.

I've created a temporary file with the final html and use navigate function with `file://` protocol.

`$page->navigate('file://'.$htmlFilePath)->waitForNavigation();`

and it works.

what do you think?

**Comment by moometric** [comment]
@sergiosusa - I was going to do the exact same, but personally it seemed clunky to keep (re)writing temp files. Maybe there will be an easier hook that can be added to do this.

**Comment by attisan** [comment]
I'm using data uri to pass along html (See https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs) payload encoded as base64. works (for the time being; but I have the feeling this could easily break for large contents as it is passed through the url?) great for my use case.

**Comment by GrahamCampbell** [comment]
Can't you just write a file to disk, then load it in the browser?

**Comment by attisan** [comment]
> Can't you just write a file to disk, then load it in the browser?

I could, but using the data uri method spares me from handling temp files (creation, deletion ... ) 🤷‍♂️

**Comment by GrahamCampbell** [comment]
Data URIs are limited in length, so that won't work, in general.

**Comment by attisan** [comment]
> Data URIs are limited in length, so that won't work, in general.

totally - I think it is somewhere around 32k - so it will (as mentioned) depend on the use-case. Having small html payloads and looking for as little boilerplate as possible it does the job for me - but as you and I pointed out; it isn't going to work for all situations.
