### ISSUE TITLE
Save image but cannot show the unicode string

### ISSUE THREAD

**Issue by henrysun123** [chrome-php/headless-chromium-php#78]
Hey guys, I just write the code same as the document which makes a screenshot for a web page. Successfully I saved the jpg/png file, but the unicode strings like chinese cannot be seen on the pic. How can I fixed it? 
ps: the web page showing is normal when opened by chrome.

**Comment by svbackend** [comment]
I think your problem with fonts, try to add them directly to the page

**Comment by henrysun123** [comment]
> I think your problem with fonts, try to add them directly to the page

sorry, I didn't find any entry options like font or something else to change the page's font. Besides, this is a public web page, I don't know whether it is the chromium-browser behavior.
Could you give some examples please?

**Comment by svbackend** [comment]
Can you share the link? Because I dont have any problems with chinese letters, page with 你好 - successfully opened by headless chrome and screenshot contain and display these letters correctly

**Comment by svbackend** [comment]
And yes - there's no options in this library to add custom font into page, you can use js for this:

```php
$addFontScript = <<<JS
document.getElementsByTagName('head')[0].innerHTML += "<style>@import url('https://fonts.googleapis.com/css?family=ZCOOL+XiaoWei'); html, body { font-family: 'ZCOOL XiaoWei', serif; }</style>";
JS;

$page->navigate('URL_OF_PAGE_WITH_CHINESE_LETTERS')->waitForNavigation();
$page->evaluate($addFontScript);
sleep(3); // to load font and re-render page (if no changes try to increase it up to 10 secs)
$page->screenshot()->saveToFile('test.png');
```

**Comment by henrysun123** [comment]
> And yes - there's no options in this library to add custom font into page, you can use js for this:
> 
> ```
> $addFontScript = <<<JS
> document.getElementsByTagName('head')[0].innerHTML += "<style>@import url('https://fonts.googleapis.com/css?family=ZCOOL+XiaoWei'); html, body { font-family: 'ZCOOL XiaoWei', serif; }</style>";
> JS;
> 
> $page->navigate('URL_OF_PAGE_WITH_CHINESE_LETTERS')->waitForNavigation();
> $page->evaluate($addFontScript);
> sleep(3); // to load font and re-render page (if no changes try to increase it up to 10 secs)
> $page->screenshot()->saveToFile('test.png');
> ```

Gratefully thanks, it works anyway. But it seems to have other problems. I have tried couple of font-families but only one font-family works and just few letters shows right. It's wired.
Testing page is "https://www.baidu.com" and my enviroment is centos7 + chromium-browser + composer + php7.1. You can try it.

**Comment by henrysun123** [comment]
Ok, I tried on my new virtual machine running **unbuntu 16.4**, but still **not work** well. Here is the code with laravel console command:
```php
<?php

namespace Console\Commands;

use HeadlessChromium\BrowserFactory;
use HeadlessChromium\Clip;
use Illuminate\Console\Command;

class ChromeScreenshot extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'screenshot {--U|url= : url} {--F|font= : font}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Command description';

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {
        $url = $this->option('url');
        $browserFactory = new BrowserFactory('chromium-browser --no-sandbox');
        // starts headless chrome
        $browser = $browserFactory->createBrowser();

        // creates a new page and navigate to an url
        $page = $browser->createPage();
         $navigation = $page->navigate('https://www.baidu.com');
         if ($url) {
            $navigation = $page->navigate($url);
         }
        // wait for the page to be loaded
        $navigation->waitForNavigation();
        $jsScript = <<<JS
document.getElementsByTagName('head')[0].innerHTML += "<style>@import url('https://fonts.googleapis.com/css?family=ZCOOL+XiaoWei'); html, body { font-family: 'ZCOOL XiaoWei', serif; }</style>";
JS;
        $page->evaluate($jsScript);
        $this->info('sleeping');
        sleep(8);
        $this->info('unsleep');

        // take the screenshot (in memory binaries)
        $screenshot = $page->screenshot();

        // save the screenshot
        $screenshot->saveToFile('/img/test.jpg');
    }
}


```
and it **shows like** that:
[https://prnt.sc/n10ve9](https://prnt.sc/n10ve9)

and my chromium-browser version is 
`Chromium 73.0.3683.75 Built on Ubuntu , running on Ubuntu 16.04`

I don't know what else wrong.

**Comment by svbackend** [comment]
Sorry, I have no idea then, try to install chinese fonts support directly to your OS

**Comment by henrysun123** [comment]
It has been **solved**.
It happens when OS like centOS or unbuntu **does not have chinese fonts ('.ttf' prefixed files)** by default. 
If you pull a centos/ubuntu image by docker, it usually has no chinese fonts library. 
Therefore, the best solution is **adding at least one kind of chinese fonts (".ttf" file) to `/usr/share/fonts/chinese`**. Here is my [notes](https://segmentfault.com/a/1190000018687409). Check it out.

**Comment by svbackend** [comment]
Great job! Im happy to know that you managed to solve it :)

**Comment by BadLeo** [comment]
try
`sudo apt-get install fonts-noto`
