### ISSUE TITLE
Chrome Path in Windows

### ISSUE THREAD

**Issue by vzhilov** [chrome-php/headless-chromium-php#82]
I gave up...

`Fatal error: Uncaught Symfony\Component\Process\Exception\ProcessTimedOutException: The process ""C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --version" exceeded the timeout of 60 seconds.`

**Comment by quyunet** [comment]
please try:
C:\\Progra~1\\Google\\Chrome\\Application\\chrome.exe

**Comment by BadLeo** [comment]
This helped me
`		$browser = $browserFactory->createBrowser([
			  //'debugLogger' => 'php://stdout',
			  'sendSyncDefaultTimeout' => 60000,
		]);
`

**Comment by Servietteski** [comment]
Fuck you, not sorking on windows and you close all issues get ebola
