### ISSUE TITLE
Scrolling

### ISSUE THREAD

**Issue by jamielsharief** [chrome-php/headless-chromium-php#83]
What is the best method to scroll a page with the library? I have tried addPreScript and addScriptTag to try and inject javascript and then run it, but without success.

**Comment by s-fraser2007** [comment]
Im also attempting this! Have you had any luck? Ive tried injecting js functions with promises and Im getting the full page scrolled just no images in my returned screenshots :/

**Comment by alex-rsk** [comment]
Add to Input/Mouse.php
` public function scrollY(int $distance, array $options = null)
    {
        $this->page->assertNotClosed();

        // get origin of the move
        $originX = $this->x;
        $originY = $this->y;

        // set new position after move
        $this->y = $this->y+$distance;

        // scroll
        $this->page->getSession()->sendMessageSync(new Message('Input.dispatchMouseEvent', [
            'type'              => 'mouseWheel',
            'x'                 => $originX,
            'y'                 => $originY,
            'deltaX'            => 0,
            'deltaY'            => $distance
            ]
        ));               
        return $this;
    }`
