### ISSUE TITLE
Error: Render header on pages

### ISSUE THREAD

**Issue by pawelruminkiewicz** [chrome-php/headless-chromium-php#84]
When we set `displayHeaderFooter` on true, header will not render. It works only when we set margin to `@page` in CSS, but then page height is increased by margin value and page content is rendered outside of the page. Is there a solution for the headline to appear on every page without bugs ?

**Comment by gsouf** [comment]
Hi @pawelruminkiewicz option `headerTemplate` has been added and should do the trick for you!
