### ISSUE TITLE
Can I capture response of ajax requests as in Puppeteer?

### ISSUE THREAD

**Issue by fima228** [chrome-php/headless-chromium-php#87]
Hi! 
I need to capture responce from ajax requests. 
How  Can I make listener,  something like this in puppeteer:
```
page.on('request', request => {
  if (request.resourceType === 'XHR')
    // do something
});
```

Or the only way is  overriding XHR prototype to intercept calls and data?

**Comment by quyunet** [comment]
I also want to know the answer. Have you solved it?

**Comment by ReutAlexey** [comment]
> Hi!
> I need to capture responce from ajax requests.
> How Can I make listener, something like this in puppeteer:
> 
> ```
> page.on('request', request => {
>   if (request.resourceType === 'XHR')
>     // do something
> });
> ```
> 
> Or the only way is overriding XHR prototype to intercept calls and data?

did you find the answer?
