### ISSUE TITLE
Can I disable CSS and image files?

### ISSUE THREAD

**Issue by vcalderonoyarce** [chrome-php/headless-chromium-php#89]
I'm working on a web scraping service but it takes too long to make a process, so I want to try to disable some useless files to speed up things...

Is there a way to prevent loading CSS and image files?

Any speed up trick to prevent high CPU usage or any resources?

Thanks in advance!

**Comment by svbackend** [comment]
Why you are using chrome if you want to simply grab the content of the page? You can use Symfony DOM crawler instead and it will be a way more faster

**Comment by vcalderonoyarce** [comment]
Because I need to scrape JS rendered website, I already have a method to scrape static DOM content.

**Comment by svbackend** [comment]
add
`--blink-settings=imagesEnabled=false`
to options

**Comment by svbackend** [comment]
![photo5314718890464488177](https://user-images.githubusercontent.com/19356345/56296999-cd770f80-612f-11e9-9337-37d04457fafe.jpg)

I literally just googled it for you :)
