### ISSUE TITLE
Video causes timeout.

### ISSUE THREAD

**Issue by SEOArcade** [chrome-php/headless-chromium-php#90]
I have noticed that on certain pages with video in header Chromium will run until timeout (sometimes for minutes). Is there any way to timeout Chromium here without an error? Like timeout after 30 seconds while keeping data that have already loaded - all my tries to timeout while keeping the data already loaded were unsuccessful... I tried to use native timeouts, but that results in an error.

**Comment by crislin2046** [comment]
@SEOArcade you might want to check out this project: [control Headless Chrome from Node.JS and use it like a regular browser](https://github.com/dosycorp/BrowserView)

**Comment by TimIgoe** [comment]
We went down the route of blocking videos for that reason - they were taking too long to download before returning.
