### ISSUE TITLE
Chrome not found

### ISSUE THREAD

**Issue by jrean** [chrome-php/headless-chromium-php#91]
Hi,
I already searched as much as I could but I'm still stuck.
The package is installed, my code is ready to run...

`Chrome process stopped before startup completed. Additional info: sh: chrome: command not found`.

MacOs 10.12
Brew up and running

Can you please tell me which version of chrome should I install to make this nice package works? Sharing the brew command would be nice :-)

Thank you.

**Comment by robotkos** [comment]
Hi, @jrean 
I use ubuntu 18 and installed chromium-browser but at "BrowserFactory" class 
 $chromeBinaries = 'chrome';
it's mean that script will tried run command "chrome --version" instead "chromium-browser --version"
As a hot fix I changed it to and now lib works:
 $chromeBinaries = 'google-chrome';

user@user:/alpine-chrome$ chrome --version
Command 'chrome' not found, did you mean:...
BUT:
user@user:/alpine-chrome$ chromium-browser --version
Chromium 76.0.3809.100 Built on Ubuntu , running on Ubuntu 18.04

**Comment by hyunbinseo** [comment]
For the `chrome` command to point at the actual `Chrome.app`, you have to set alias(es) in the shell configuration.

```zsh
# /Users/username/.zshrc
alias chrome="/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome"
alias chrome-canary="/Applications/Google\ Chrome\ Canary.app/Contents/MacOS/Google\ Chrome\ Canary"
alias chromium="/Applications/Chromium.app/Contents/MacOS/Chromium"
```

Source: [Chrome for Developers](https://developer.chrome.com/blog/headless-chrome/#starting_headless_cli)

**Comment by Wonz5130** [comment]
> For the `chrome` command to point at the actual `Chrome.app`, you have to set alias(es) in the shell configuration.要让 `chrome` 命令指向实际的 `Chrome.app` ，你需要在 shell 配置中设置别名。
> 
> # /Users/username/.zshrc
> alias chrome="/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome"
> alias chrome-canary="/Applications/Google\ Chrome\ Canary.app/Contents/MacOS/Google\ Chrome\ Canary"
> alias chromium="/Applications/Chromium.app/Contents/MacOS/Chromium"
> Source: [Chrome for Developers](https://developer.chrome.com/blog/headless-chrome/#starting_headless_cli)来源：Chrome 开发者

It works. Thanks!!!
