### ISSUE TITLE
Browser icon

### ISSUE THREAD

**Issue by jgmdev** [chrome-php/headless-chromium-php#96]
Haven't tested this project so far but looks really interesting, I don't know if by headless it also means that the browser interface is kept hidden but in case of the contrary can the icon displayed on the taskbar be changed?

I ask because I have been experimenting with using PHP built-in webserver and a web browser to develop desktop applications. I developed recently [BlueControl](https://github.com/jgmdev/bluecontrol), which is a small application for Linux to automatically handle blue light at nights by changing the color temperature, much like redshift and f.lux but developed with PHP using the Built-in Server/Browser strategy mentioned above. Currently the application is launch to the user like in this [code example](https://github.com/jgmdev/bluecontrol/blob/master/run.php#L300) which works pretty well but it keeps the default chromium icon even If I write a custom .desktop file for my launcher script. I also developed this other application which I named [InFocus](https://github.com/jgmdev/infocus) (that needs some fixes) which is an automatic time tracker that uses wmctrl and other command line tools to automatically keep track of all the windows you are working on and for how much time. Both of them use the chromium --app flag, which makes it feel like a "normal" desktop app.

It would be nice if something like electron could be developed for PHP and these project seems like the thing most near to that. So I would like to know if what this project does is launch a visible instance of chromium and if you can change the icon used by the web browser, and thanks for this great project!

**Comment by gsouf** [comment]
@jgmdev 
Headless just means that it launches chrome without any graphics. For the rest it's just normal chrome. 
The library just helps to automate various tasks to control chrome. I'm not sure it can help with your problem you faced. With that said good luck with your apps!
